{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha22.jar",
          "url": "viewmodel-1.0.0-alpha22.jar",
          "size": 15848,
          "sha512": "f847694ff31dd787e8ef9339335e9fdb23d9cf93f800aa460789c325bfb6fb2fdd2b9f73d2bc1794389109d8393baefc49c403b0a3173562f9e961091726ac37",
          "sha256": "e7575206c0909b35c23709e82caffd5c6d2f2bf7f91f2693fbf2f3219e86057f",
          "sha1": "28321668d5c8157dcc58456ccae760b014899836",
          "md5": "f99d85b2a610fcd1361bf4e61e7dabe2"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha22/viewmodel-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha22/viewmodel-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha22/viewmodel-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha22/viewmodel-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha22"
      }
    }
  ]
}
