{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.15/contract-0.0.15.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gqpemdskoneufiyethujbxdcv4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.15.jar",
          "url": "contract-jvm-0.0.15.jar",
          "size": 15041,
          "sha512": "0c5e53206ab66142308d73d4d6c8a5ebd71d7a87ad1b030ac3597b8af7559c22a81f1b35241071e3da1977fe639a996f72c3cafc303695aa3f00d555986067a0",
          "sha256": "efba2ff0b39eee5dff2f27a6d631b009320b8e34440d5da848873c239c1706ea",
          "sha1": "1851cbfa19cdc9c39c9e041ae63edc29731cf404",
          "md5": "b0a743658a165e5554db2935804818ac"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.15.jar",
          "url": "contract-jvm-0.0.15.jar",
          "size": 15041,
          "sha512": "0c5e53206ab66142308d73d4d6c8a5ebd71d7a87ad1b030ac3597b8af7559c22a81f1b35241071e3da1977fe639a996f72c3cafc303695aa3f00d555986067a0",
          "sha256": "efba2ff0b39eee5dff2f27a6d631b009320b8e34440d5da848873c239c1706ea",
          "sha1": "1851cbfa19cdc9c39c9e041ae63edc29731cf404",
          "md5": "b0a743658a165e5554db2935804818ac"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.15/contract-metadata-0.0.15.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.15"
      }
    }
  ]
}
