{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.43/contract-0.0.43.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "umuh4wxdqfdghocu4tjfq6qmxe"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.43.jar",
          "url": "contract-jvm-0.0.43.jar",
          "size": 20690,
          "sha512": "616465447f169f744e5055235be247f23ab7a4af86c38dc7776a71c9ea121b6b8ef2af7f02d5837a15cfa321e8155bfcaaffed13b21bc7f7f0b7e1176ce33712",
          "sha256": "7861337221c6d96d7def24f820b9595dafa3d4eb52636788cac6f69c7368a168",
          "sha1": "0c57da3dfa7255634291f9c3a30b0c58b2163bef",
          "md5": "522adebc004994480b3e3804e035f2d9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.43.jar",
          "url": "contract-jvm-0.0.43.jar",
          "size": 20690,
          "sha512": "616465447f169f744e5055235be247f23ab7a4af86c38dc7776a71c9ea121b6b8ef2af7f02d5837a15cfa321e8155bfcaaffed13b21bc7f7f0b7e1176ce33712",
          "sha256": "7861337221c6d96d7def24f820b9595dafa3d4eb52636788cac6f69c7368a168",
          "sha1": "0c57da3dfa7255634291f9c3a30b0c58b2163bef",
          "md5": "522adebc004994480b3e3804e035f2d9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.43/contract-metadata-0.0.43.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.43"
      }
    }
  ]
}
