{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.10/core-0.0.10.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.10.jar",
          "url": "core-metadata-0.0.10.jar",
          "size": 4883,
          "sha512": "53a953e8c9c724fe08a90296e6eae9ddfc6676be81f91fdfb22a7e7c6bfe1b2b8de3f57e93a3d5627a6137c0349b6263aa2d5be226777cdcc2872376bf21322e",
          "sha256": "5d675cf7d22d44be5339ba3ef2dc37a9abb9b2ca56a1863ac3136c8583a8200a",
          "sha1": "6bbb06cf7a38875942e796fc6c05a8a205ee1fba",
          "md5": "adff04456e1b90ab62adc7faa1822ad4"
        }
      ]
    }
  ]
}
