{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.18/core-0.0.18.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2mo2nnyckfb5ncqso4y6gwemnm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.18.jar",
          "url": "core-metadata-0.0.18.jar",
          "size": 5327,
          "sha512": "fa546ef5bf537bb290b9dcdedf11dabf00d40dc8d8e36c00b261ad69ff47f0569067baf05547ca2ac478ed8d208fa1844f0ffcd72cd346158d5e9257270ab3bb",
          "sha256": "9389dd85c60e957fc1b7e78283bbd50f00d25ca7bd358b4636e53be7ba6731e7",
          "sha1": "28a93519c7b89e0ffe311c03e24f2f0c228bad46",
          "md5": "fb09dab8926c3a5b9c353b0703be3d2b"
        }
      ]
    }
  ]
}
