{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha13.jar",
          "url": "generator-1.0.0-alpha13.jar",
          "size": 187688,
          "sha512": "ef82d2b46bf8a4655f28e25a0d8997b244d800f97e8b245c2ef67fd840eeb8b728232b502b879306fc38cc4078fd7cfed361f426f86e907a7e27b723193bbfe6",
          "sha256": "1f1d64af1ff838a07fbc6164a6d6420848311087055f9a8bf55c37c4da2650f0",
          "sha1": "8e468b45343f74c61e2d88c5177ccca3e5d3aa50",
          "md5": "cd3838925e3f03e93ed04cf674990353"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha13.jar",
          "url": "generator-1.0.0-alpha13.jar",
          "size": 187688,
          "sha512": "ef82d2b46bf8a4655f28e25a0d8997b244d800f97e8b245c2ef67fd840eeb8b728232b502b879306fc38cc4078fd7cfed361f426f86e907a7e27b723193bbfe6",
          "sha256": "1f1d64af1ff838a07fbc6164a6d6420848311087055f9a8bf55c37c4da2650f0",
          "sha1": "8e468b45343f74c61e2d88c5177ccca3e5d3aa50",
          "md5": "cd3838925e3f03e93ed04cf674990353"
        }
      ]
    }
  ]
}
