{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.14/contract-0.0.14.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3dorn7aqgzbq3owi6pxgrw7ncy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.14.jar",
          "url": "contract-jvm-0.0.14.jar",
          "size": 15041,
          "sha512": "47f0a352bd117bec59ba1bd601468df0fe63a2c074c7817f3223ed06d157fde287ee26851be035803634102aab9cdaa4913e9ddf102944f828d6ef1a101ebdfc",
          "sha256": "caba3e7b1ed9edcbf314cc97fdc53df63ac3112609267704d0bde235eace873b",
          "sha1": "3803609b3fcd65f768ba3a4f5f1565a007cfa72d",
          "md5": "b359d9abce50278dfd8bc5e74fb032af"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.14.jar",
          "url": "contract-jvm-0.0.14.jar",
          "size": 15041,
          "sha512": "47f0a352bd117bec59ba1bd601468df0fe63a2c074c7817f3223ed06d157fde287ee26851be035803634102aab9cdaa4913e9ddf102944f828d6ef1a101ebdfc",
          "sha256": "caba3e7b1ed9edcbf314cc97fdc53df63ac3112609267704d0bde235eace873b",
          "sha1": "3803609b3fcd65f768ba3a4f5f1565a007cfa72d",
          "md5": "b359d9abce50278dfd8bc5e74fb032af"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.14/contract-metadata-0.0.14.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.14"
      }
    }
  ]
}
