{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.14/contract-0.0.14.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.14.jar",
          "url": "contract-jvm-0.0.14.jar",
          "size": 15041,
          "sha512": "fa2288e9f5a2b849823dbefbee3e0d2ccdd0e2ef8382bf333ed1fa8259ed330b3b4a17492f2604934e9368ada61ae07c81e8c8906512ebb046325b849631f692",
          "sha256": "08dba2464cdbeaa78f31f47192094a9bf34c70458bd3dfdd1df1d88542c5667a",
          "sha1": "dfb5dbcda89d9046965b17c669bc696aacf7c1b3",
          "md5": "a9e04fed1f34b157e86b1f8cc5bd2234"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.14.jar",
          "url": "contract-jvm-0.0.14.jar",
          "size": 15041,
          "sha512": "fa2288e9f5a2b849823dbefbee3e0d2ccdd0e2ef8382bf333ed1fa8259ed330b3b4a17492f2604934e9368ada61ae07c81e8c8906512ebb046325b849631f692",
          "sha256": "08dba2464cdbeaa78f31f47192094a9bf34c70458bd3dfdd1df1d88542c5667a",
          "sha1": "dfb5dbcda89d9046965b17c669bc696aacf7c1b3",
          "md5": "a9e04fed1f34b157e86b1f8cc5bd2234"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.14/contract-metadata-0.0.14.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.14"
      }
    }
  ]
}
