{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha16"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha16"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha16"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha16.jar",
          "url": "viewmodel-1.0.0-alpha16.jar",
          "size": 15176,
          "sha512": "ee016aad5284564f324ad7f031227a1b83f2c327dd9b3bb53e627e376faa886ab0453f170b8df8c8451d0d5d8fc7960541bd31b3bde26c197a8524a326c4793c",
          "sha256": "2c7639566a3948363e8d4226d2be8078b9fa5d77c8215c4088bdbf2c8f5674b8",
          "sha1": "e3770618a039ab9691e48eddc4afab9603dd2609",
          "md5": "39c4e0bb13e715a08638211b6aaab752"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha16/viewmodel-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha16/viewmodel-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha16/viewmodel-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha16/viewmodel-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha16"
      }
    }
  ]
}
