{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel-metadata",
    "version": "0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "adu4mcp7tnfvfaxt3d3ep6dpwa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.48.jar",
          "url": "viewmodel-metadata-0.0.48.jar",
          "size": 7429,
          "sha512": "ec58569216683ac17d9fd8cf9b646c76e4d57aba106ada1b3ec4a02e430de4b774426077c3840afd9b0929970f4c9450336e1576d82f36b9acf72bec26acc642",
          "sha256": "b528185408bade719fd6bf39f389e68dd567c181776a245fc01fc0603ae3dba0",
          "sha1": "223209b316fc07dd27d15256c469a41b4da0a599",
          "md5": "705983f3614d7f9aa66470a152ebb7ca"
        }
      ]
    }
  ]
}
