{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.3/contract-0.0.3.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "su2tjwkhbbbjndaqanwwqcxe24"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.3.jar",
          "url": "contract-jvm-0.0.3.jar",
          "size": 14537,
          "sha512": "5a410ad86c65c047ec24a890f71412b72a2acf6f0edf589bb5b3a541a79fccd612adf8663001cd5b1a7b3c52e73a7303170c8711a72e5da06802e91edda9a823",
          "sha256": "5c3b1368185abfc00ccfcaec90df30fbd46328231f114b7ad5b2021760ee07ab",
          "sha1": "f7803d6ba251be17b61e46f7719a067030d45525",
          "md5": "16e4c8bf545d09afc89b75d0cc989885"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.3.jar",
          "url": "contract-jvm-0.0.3.jar",
          "size": 14537,
          "sha512": "5a410ad86c65c047ec24a890f71412b72a2acf6f0edf589bb5b3a541a79fccd612adf8663001cd5b1a7b3c52e73a7303170c8711a72e5da06802e91edda9a823",
          "sha256": "5c3b1368185abfc00ccfcaec90df30fbd46328231f114b7ad5b2021760ee07ab",
          "sha1": "f7803d6ba251be17b61e46f7719a067030d45525",
          "md5": "16e4c8bf545d09afc89b75d0cc989885"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.3/contract-metadata-0.0.3.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.3"
      }
    }
  ]
}
