{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "outl7uxctrgmfpv6znqczvsuxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.24.jar",
          "url": "generator-0.0.24.jar",
          "size": 92834,
          "sha512": "0972de010083f15cc8c97494693ad96aade25573087ada7136ae2e1f702b808a2a3393097d595acc7a6a385b5fbd7d2760c78d6562fcb2f37ab5a97dd33b6e7e",
          "sha256": "f2a41297fc7f1952be112ed28db88002eecd7e9d10f8e0dadf25760f9ef960d6",
          "sha1": "5f00c24206f2d866121f52e439b6738377da9cf0",
          "md5": "d90df0bc3453f4e57bbf18d86db4def6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.24.jar",
          "url": "generator-0.0.24.jar",
          "size": 92834,
          "sha512": "0972de010083f15cc8c97494693ad96aade25573087ada7136ae2e1f702b808a2a3393097d595acc7a6a385b5fbd7d2760c78d6562fcb2f37ab5a97dd33b6e7e",
          "sha256": "f2a41297fc7f1952be112ed28db88002eecd7e9d10f8e0dadf25760f9ef960d6",
          "sha1": "5f00c24206f2d866121f52e439b6738377da9cf0",
          "md5": "d90df0bc3453f4e57bbf18d86db4def6"
        }
      ]
    }
  ]
}
