{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.13/viewmodel-0.0.13.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "kwtsmjyvlzbw3aguhyqjzuuf5m"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.13-debug.aar",
          "size": 51661,
          "sha512": "c01ae79e46292d8a7bdb5c52332444ef6dc6090b3b378f3571cd8e8af6714a60be698866d69894a1b2db31b11675b9366243b28e7c0a8150c1f7be5eee21cc17",
          "sha256": "fb80450d04f46212e71238c1ee88aefec28865d320cb52609e1ea83d11e4d236",
          "sha1": "f170a62ced5ce7cd9a2eba9baeab85bff70249b7",
          "md5": "1227d1f55d90102d8ca5d06bb4563dde"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.13-debug.aar",
          "size": 51661,
          "sha512": "c01ae79e46292d8a7bdb5c52332444ef6dc6090b3b378f3571cd8e8af6714a60be698866d69894a1b2db31b11675b9366243b28e7c0a8150c1f7be5eee21cc17",
          "sha256": "fb80450d04f46212e71238c1ee88aefec28865d320cb52609e1ea83d11e4d236",
          "sha1": "f170a62ced5ce7cd9a2eba9baeab85bff70249b7",
          "md5": "1227d1f55d90102d8ca5d06bb4563dde"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.13.aar",
          "size": 50060,
          "sha512": "c56f6cc0a489e8da1a13633a53087ec1c8033680924c71ce4f4557955f9103e0eed63468a537093e5995a0ca1ab5f099ed81d9a1b0cffed34e02ccdaf64b1059",
          "sha256": "bbd8bf9309d08ebc31ef5828c9d82b31a5d903800f416a7fc1295367ee9bcc19",
          "sha1": "244e3c5b930c08f17bd563d9cfad9d806a807dd4",
          "md5": "c3ae91a489365e9ff4a6d269a1fea178"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.13.aar",
          "size": 50060,
          "sha512": "c56f6cc0a489e8da1a13633a53087ec1c8033680924c71ce4f4557955f9103e0eed63468a537093e5995a0ca1ab5f099ed81d9a1b0cffed34e02ccdaf64b1059",
          "sha256": "bbd8bf9309d08ebc31ef5828c9d82b31a5d903800f416a7fc1295367ee9bcc19",
          "sha1": "244e3c5b930c08f17bd563d9cfad9d806a807dd4",
          "md5": "c3ae91a489365e9ff4a6d269a1fea178"
        }
      ]
    }
  ]
}
