{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.51/core-0.0.51.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rcsqc6iufne5ve6vpfzg2hyyae"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.51.jar",
          "url": "core-jvm-0.0.51.jar",
          "size": 17732,
          "sha512": "787da54b85da3f90a50aebef4bdea388af6077209044f91f04c2da00083829e85116d658b8a70d2e1de5a0ea35cb7295413ea7e2f69b7b22293c3860177e1145",
          "sha256": "fb7d6b2636d3a689777a143c33cd14b17c2a36585d5185350d98de3080673f0e",
          "sha1": "3dcc3aa5e24efe1602463eeeaa94ce0fb6fbff6a",
          "md5": "3826cceabc100bd9ef0109d8174ff23b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.51.jar",
          "url": "core-jvm-0.0.51.jar",
          "size": 17732,
          "sha512": "787da54b85da3f90a50aebef4bdea388af6077209044f91f04c2da00083829e85116d658b8a70d2e1de5a0ea35cb7295413ea7e2f69b7b22293c3860177e1145",
          "sha256": "fb7d6b2636d3a689777a143c33cd14b17c2a36585d5185350d98de3080673f0e",
          "sha1": "3dcc3aa5e24efe1602463eeeaa94ce0fb6fbff6a",
          "md5": "3826cceabc100bd9ef0109d8174ff23b"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/0.0.51/core-metadata-0.0.51.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "0.0.51"
      }
    }
  ]
}
