{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5f2uil5yr5anjo2xrdrfwpkzma"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.5.jar",
          "url": "generator-0.0.5.jar",
          "size": 91298,
          "sha512": "e2404d517b44e129f4c1b551cc8f705573382118c8b117d4a14e7f061a7f3d7c5c44803b730f6f1d7102cc2e8694a579ee42d8a4a43f427060dc903d7f5ab988",
          "sha256": "afe012711f4acb9c70f5452b67e76b88e33cdd2bf88e20a4d25628b8ae0cce0e",
          "sha1": "e22579e65bcc3f2134f412d3275914721a8a353f",
          "md5": "a344a71aa4848e1a21c49cd5cdc64460"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.5.jar",
          "url": "generator-0.0.5.jar",
          "size": 91298,
          "sha512": "e2404d517b44e129f4c1b551cc8f705573382118c8b117d4a14e7f061a7f3d7c5c44803b730f6f1d7102cc2e8694a579ee42d8a4a43f427060dc903d7f5ab988",
          "sha256": "afe012711f4acb9c70f5452b67e76b88e33cdd2bf88e20a4d25628b8ae0cce0e",
          "sha1": "e22579e65bcc3f2134f412d3275914721a8a353f",
          "md5": "a344a71aa4848e1a21c49cd5cdc64460"
        }
      ]
    }
  ]
}
