{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h626lwyzk5cqpjrywyt6pslmqm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.23.jar",
          "url": "generator-0.0.23.jar",
          "size": 92834,
          "sha512": "639466885dc94159e62cfcfc19403dd49f5f3c97d2352f8e75736c8b1faf1e776545d812440712e27aef6d18b5f8dde9a20992f05ce1402cf294fd51f73dbb5b",
          "sha256": "14eecf07d4966f5721dd40128306becdc27a60df1f15aebd28bde3f7ab7e0eca",
          "sha1": "a3646e39c380902b282ec87c3c81e8508ee25e0b",
          "md5": "def0e634d9bd114b03774d743ae7e1a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.23.jar",
          "url": "generator-0.0.23.jar",
          "size": 92834,
          "sha512": "639466885dc94159e62cfcfc19403dd49f5f3c97d2352f8e75736c8b1faf1e776545d812440712e27aef6d18b5f8dde9a20992f05ce1402cf294fd51f73dbb5b",
          "sha256": "14eecf07d4966f5721dd40128306becdc27a60df1f15aebd28bde3f7ab7e0eca",
          "sha1": "a3646e39c380902b282ec87c3c81e8508ee25e0b",
          "md5": "def0e634d9bd114b03774d743ae7e1a1"
        }
      ]
    }
  ]
}
