{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.6/core-0.0.6.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3w2f7l7ypffvjgcalkwzywgyy4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.6.jar",
          "url": "core-metadata-0.0.6.jar",
          "size": 4883,
          "sha512": "f3e04da2c1b68ae9ac32b8e85d0afd6304df87319406f086604055700331e95d0efda3769c74e24a93de07c7ac3b97cf378cf0d70b3bec203bd307d79cdc3d23",
          "sha256": "beca7325e874c063b2fb214f5d075103ae265a838a3d73ad607b5cac6f602bb2",
          "sha1": "9613438079c5f35fe592a8b33c2c15e68519d3e5",
          "md5": "3f0660bd5a04887fe965c21b546e9b70"
        }
      ]
    }
  ]
}
