{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha17/viewcontract-1.0.0-alpha17.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha17.jar",
          "url": "viewcontract-jvm-1.0.0-alpha17.jar",
          "size": 54321,
          "sha512": "e30d451dc2719b9016367f08e9e2b9de9d8305ed2657f0df3ec9dd2416f5a1e562ce2507fe69ff0ef83f8d037bba96f7c45ca51cee3dbf94aafa49a4961c5ce6",
          "sha256": "4bf140f89ca853f0245a5dada713f3e2846ce9f9b209bbc24495862efaa3fa1e",
          "sha1": "12c6fc0e374fcb9a8c86324d047f36fbcc2d00ef",
          "md5": "8aafeafd25324b777942bfe8ce8ea041"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha17.jar",
          "url": "viewcontract-jvm-1.0.0-alpha17.jar",
          "size": 54321,
          "sha512": "e30d451dc2719b9016367f08e9e2b9de9d8305ed2657f0df3ec9dd2416f5a1e562ce2507fe69ff0ef83f8d037bba96f7c45ca51cee3dbf94aafa49a4961c5ce6",
          "sha256": "4bf140f89ca853f0245a5dada713f3e2846ce9f9b209bbc24495862efaa3fa1e",
          "sha1": "12c6fc0e374fcb9a8c86324d047f36fbcc2d00ef",
          "md5": "8aafeafd25324b777942bfe8ce8ea041"
        }
      ]
    }
  ]
}
