{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.22/model-0.0.22.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "mvvg2c2cg5ck5ely2nphe5geda"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.22.jar",
          "url": "model-metadata-0.0.22.jar",
          "size": 13118,
          "sha512": "e6ef021b41f84897ef3215b4b91f50d691753af85d27c586fd77db84d10100ab443181b4e7bfcc5ed224f7e63597c581aaa12bf9b87ddfd3423bfbf3dedc0a65",
          "sha256": "53f2dc04f7d5d1e22da33de72cb26cc0738f3c63eb43c98148b771887c3e886c",
          "sha1": "8493f1a9193ccf976b1202b688bc86d64d71d08f",
          "md5": "7bca776b67623ab54e948d2c59308914"
        }
      ]
    }
  ]
}
