{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha19.jar",
          "url": "androidTests-1.0.0-alpha19.jar",
          "size": 261,
          "sha512": "66a2f8116b3fc6c81804550f7a640d3d93227d984f10925620aae86855c477b08ea59418d2c1fb65438c38a36238e80eccc9484da57aba77b7cc5e7e1e71ae23",
          "sha256": "a282a5acb14323f72bfe49666cea5382aadc3aa0e21f4384a7be76d642fe932f",
          "sha1": "e0676024d8405c8ad95ef1e488a0dd8378c0758e",
          "md5": "6782e1de3e39fa260e3a47adf16f7a1b"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha19/androidTests-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha19/androidTests-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha19/androidTests-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha19/androidTests-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha19"
      }
    }
  ]
}
