{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.16/core-0.0.16.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "xduo2x3rkbaepe3emobddesovq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.16.jar",
          "url": "core-metadata-0.0.16.jar",
          "size": 5327,
          "sha512": "2d27f483a7594d9b5a4021fd774eec2c7b3a46fdb33b382ccc1a53c05d207a82d3fb0330d9d1db07ca10f14f85b7c479ff340974878a6e29d2818380a8c3ee81",
          "sha256": "ef6f0d009f035440da442baf9ec8ce9f0715f0d13a2d21bc1203931e95cc1884",
          "sha1": "e444747abda2c715e44aa14d6bd91afba3b80d2e",
          "md5": "60805a50fa65ca80dc774b0454e4ce7c"
        }
      ]
    }
  ]
}
