{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha9/modelcontract-1.0.0-alpha9.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h2ihyef5ird4dpcb6ziswov2gq"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosx64-1.0.0-alpha9.klib",
          "size": 15232,
          "sha512": "614e70201f4ccd6bacb48a344ddb3737890c1a5c0e29e0f194460154a2769b51aefa113c3dd96c0865c41a3fdfe80f482beccc09f845ad460ac93bb56a83a17e",
          "sha256": "e3edecf80f5f7b9a5bf8898703610c95bfa6502f633fdcd07552e054980c7157",
          "sha1": "c0fffc2b7ab9a56a5aa59b67d36e972737e8beca",
          "md5": "c2232967f276c4221975b8d632f6a24d"
        }
      ]
    }
  ]
}
