{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha22.jar",
          "url": "core-1.0.0-alpha22.jar",
          "size": 7761,
          "sha512": "85f21d117197c41470956ed57ae922bb3c82f7036e669de0589f260274a11dcc41769d0a42aa14bf2de676f29f6ea3acd8804138ceda069fa3e3fcb159ae0c9a",
          "sha256": "fa366556f706faef41113b3a7afdd246888fdea078102a9fd671f32591b394a2",
          "sha1": "b33c160b3d4dbc469a627d21b743c0f9d601f7d7",
          "md5": "cf0f504c9faae60c781b5324b12a4fd8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha22/core-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha22/core-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha22/core-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha22/core-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha22/core-iosarm64-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha22/core-iosx64-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha22"
      }
    }
  ]
}
