{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.52/contract-0.0.52.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "jc6y725iebc23nmj56aixso43i"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.52.jar",
          "url": "contract-jvm-0.0.52.jar",
          "size": 20789,
          "sha512": "18a4696d1c5774cc29d1afb9e7e82e20e02dbe7c2f62545ff0fcc97422327f68a78192633fc9c3ebf657a33f2b71a114148a47483bf00b06ebf1a8c236e5b1f4",
          "sha256": "a217922b6101b2bd0590efd5a0b6a6894d3a060c9437f4b12bd3578918652cbd",
          "sha1": "d0b5b6421c82acbd13fece269ecc437034e4aa51",
          "md5": "9c58ee0093ccb72959f8afa73a762b54"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.52.jar",
          "url": "contract-jvm-0.0.52.jar",
          "size": 20789,
          "sha512": "18a4696d1c5774cc29d1afb9e7e82e20e02dbe7c2f62545ff0fcc97422327f68a78192633fc9c3ebf657a33f2b71a114148a47483bf00b06ebf1a8c236e5b1f4",
          "sha256": "a217922b6101b2bd0590efd5a0b6a6894d3a060c9437f4b12bd3578918652cbd",
          "sha1": "d0b5b6421c82acbd13fece269ecc437034e4aa51",
          "md5": "9c58ee0093ccb72959f8afa73a762b54"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.52/contract-metadata-0.0.52.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.52"
      }
    }
  ]
}
