{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha17.jar",
          "url": "plugin-1.0.0-alpha17.jar",
          "size": 207990,
          "sha512": "515868ed4a90ea06ac8efb0fc64cabf8e5192211bebed392800dff9e6e01d175c2e10985326255276a1ca9439ff6e52a67495651b100092f2c55ad37c63ad792",
          "sha256": "a8993b86806b26274ac20a3415799d6502882419984d702032be12d14bb9e316",
          "sha1": "158496eb864aa2ec9a9e6725b619bfe82b852fda",
          "md5": "67143932080276b64417a68f25c2ca0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha17.jar",
          "url": "plugin-1.0.0-alpha17.jar",
          "size": 207990,
          "sha512": "515868ed4a90ea06ac8efb0fc64cabf8e5192211bebed392800dff9e6e01d175c2e10985326255276a1ca9439ff6e52a67495651b100092f2c55ad37c63ad792",
          "sha256": "a8993b86806b26274ac20a3415799d6502882419984d702032be12d14bb9e316",
          "sha1": "158496eb864aa2ec9a9e6725b619bfe82b852fda",
          "md5": "67143932080276b64417a68f25c2ca0b"
        }
      ]
    }
  ]
}
