{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha62/viewcontract-1.0.0-alpha62.module",
    "group": "com.github.skot-framework.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha62.klib",
          "size": 46669,
          "sha512": "6443834048ab9bcb8de8e79eba9be80131b807c47f4ca1ce1e49984eaaa54ace8e1da21bd16c052f5dd547e5992571ef63dab568e35f8a0e4fa71784381742ad",
          "sha256": "065144056e7038a04e83191c2c0fe2f2097368028b3d80bfad096279785be44e",
          "sha1": "7aced69968e5911b1a39f3f0b3b0344c7fda23fc",
          "md5": "83793f9dc9c0a7cc0a87c4ff274990b1"
        }
      ]
    }
  ]
}
