{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewlegacy/1.0.0-alpha14/viewlegacy-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "viewlegacy",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r323g3eu6re6rhuxjhc3etletm"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-1.0.0-alpha14-debug.aar",
          "size": 299940,
          "sha512": "cef34cee57c2037c69bbd01ec893cf8cf7a8788281ea4eec5a3db7e6b9991cbbcd8cf4ed2cbc4df4c3c363eeb2c0ee9a099e1dac6e75a2e63c159e6db5f8ad1f",
          "sha256": "25904148b22418d05dff629b48806bbef72398619f4e556e142781e50916c64c",
          "sha1": "37739d78c58f77ab74b8257a064a55bf37a57663",
          "md5": "aa2c8595adf94acbafd54f86acc2da0b"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-1.0.0-alpha14-debug.aar",
          "size": 299940,
          "sha512": "cef34cee57c2037c69bbd01ec893cf8cf7a8788281ea4eec5a3db7e6b9991cbbcd8cf4ed2cbc4df4c3c363eeb2c0ee9a099e1dac6e75a2e63c159e6db5f8ad1f",
          "sha256": "25904148b22418d05dff629b48806bbef72398619f4e556e142781e50916c64c",
          "sha1": "37739d78c58f77ab74b8257a064a55bf37a57663",
          "md5": "aa2c8595adf94acbafd54f86acc2da0b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-1.0.0-alpha14.aar",
          "size": 287448,
          "sha512": "d804685095cd756669bbc5cad8aa61c898cb618690fec4c2cae8868a7e5a31cd70ee2b13cfaf104bee582b166e3dd5f3e82df351d3ca7eab2a6fb398167d3441",
          "sha256": "9c0acc510cfd638fbce435e93e64d09f574bdc149c3d65a06d53519895c43c3a",
          "sha1": "dc56949b1c980f5836851ae5de2ffcce5caf1bc2",
          "md5": "8b27dc78df442a6b4465f2311d54b64f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-1.0.0-alpha14.aar",
          "size": 287448,
          "sha512": "d804685095cd756669bbc5cad8aa61c898cb618690fec4c2cae8868a7e5a31cd70ee2b13cfaf104bee582b166e3dd5f3e82df351d3ca7eab2a6fb398167d3441",
          "sha256": "9c0acc510cfd638fbce435e93e64d09f574bdc149c3d65a06d53519895c43c3a",
          "sha1": "dc56949b1c980f5836851ae5de2ffcce5caf1bc2",
          "md5": "8b27dc78df442a6b4465f2311d54b64f"
        }
      ]
    }
  ]
}
