{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3w2f7l7ypffvjgcalkwzywgyy4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.6.jar",
          "url": "generator-0.0.6.jar",
          "size": 92038,
          "sha512": "8eac3e2e9c6009faa2d55ceb9d96cc37b0a1d1768ae2728cd469442b9672c4f2667672c14dab54f8a3aba0cf56015bc4ad2a1f59692843edb028c5127222a424",
          "sha256": "fa111178227eb356eff9ddc9a24f60b652e2a4dc9af2e128402d86a1f2750345",
          "sha1": "e32c09460e0de5914a5534c8cbf07e06b4d49e4a",
          "md5": "fe887b71802969409daf9a36c3bd88a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.6.jar",
          "url": "generator-0.0.6.jar",
          "size": 92038,
          "sha512": "8eac3e2e9c6009faa2d55ceb9d96cc37b0a1d1768ae2728cd469442b9672c4f2667672c14dab54f8a3aba0cf56015bc4ad2a1f59692843edb028c5127222a424",
          "sha256": "fa111178227eb356eff9ddc9a24f60b652e2a4dc9af2e128402d86a1f2750345",
          "sha1": "e32c09460e0de5914a5534c8cbf07e06b4d49e4a",
          "md5": "fe887b71802969409daf9a36c3bd88a8"
        }
      ]
    }
  ]
}
