{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.25/view-0.0.25.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.25.jar",
          "url": "view-metadata-0.0.25.jar",
          "size": 6291,
          "sha512": "81d0932d88b219d62eb499431b4b348fbcadbd63c33f87e26d80610f4fba9a9ef27ac1df9dedb1b576497a0749fc4e0dd7298526fcc1c0c2530f0e5e15dc2fa4",
          "sha256": "bd3a5b4ab411191904d9de6dcbaca075d21953b558a1f099c398b832f44025ec",
          "sha1": "1baa55019f8f9450ec69fc1ebaca5cfd6823c98c",
          "md5": "7f1a5963abf594a89ec28626339c6fe8"
        }
      ]
    }
  ]
}
