{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "viewlegacy",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-metadata-1.0.0-alpha62.jar",
          "url": "viewlegacy-1.0.0-alpha62.jar",
          "size": 261,
          "sha512": "4f21547d9ab4abb551af8a7246b6814b7404e5c6c4cec78a50c924c1ec03d35a68d7a30305496943177ae184269587486a3a7b0fd36dee0d8433b64e77a140f5",
          "sha256": "a5d573c357e29a48f4c552f17b71757e0ea85b9897fcbf10a60bb3e15538ba9a",
          "sha1": "86cfd66fec3a14ca181347f86ee1793dced515c1",
          "md5": "fca8d0b7930d9607af350b14240ad37a"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha62/viewlegacy-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha62/viewlegacy-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha62/viewlegacy-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha62/viewlegacy-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha62"
      }
    }
  ]
}
