{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha9/viewmodel-1.0.0-alpha9.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h2ihyef5ird4dpcb6ziswov2gq"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha9-debug.aar",
          "size": 48594,
          "sha512": "6eb638eb6f5a143400af185fbbba3aa472ec6a63ea4364f5e2196d491493caee23f60e342f66729ca08ecd3febfef5958b7a5047de57c52ad994ca92eea8f553",
          "sha256": "75d98dea6e9b7bbb3344899cc448a2f2eac8dc947cdf8469158ea59ad0653e97",
          "sha1": "fc72786a4ca5f9fc1cf5b53e58ce3b07b93100db",
          "md5": "cfba74cecb7699d63cef6df10c4e5768"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha9-debug.aar",
          "size": 48594,
          "sha512": "6eb638eb6f5a143400af185fbbba3aa472ec6a63ea4364f5e2196d491493caee23f60e342f66729ca08ecd3febfef5958b7a5047de57c52ad994ca92eea8f553",
          "sha256": "75d98dea6e9b7bbb3344899cc448a2f2eac8dc947cdf8469158ea59ad0653e97",
          "sha1": "fc72786a4ca5f9fc1cf5b53e58ce3b07b93100db",
          "md5": "cfba74cecb7699d63cef6df10c4e5768"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha9.aar",
          "size": 46155,
          "sha512": "518d9c678dad5b4745cbd046c62026a49e48e2e562fb281907001647160acde36e06836a06f5445312246762628d4002e5a31807421849dd324042e1d2115f6a",
          "sha256": "9afebdb63918be078a44bcf6a3dbe6fd4e40511132d6334287c77fcf894a33f6",
          "sha1": "ce6fc90dfd56fa40341a143f52f33513b1690bf1",
          "md5": "cee0485171944fe498d3b41bae904f1b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha9.aar",
          "size": 46155,
          "sha512": "518d9c678dad5b4745cbd046c62026a49e48e2e562fb281907001647160acde36e06836a06f5445312246762628d4002e5a31807421849dd324042e1d2115f6a",
          "sha256": "9afebdb63918be078a44bcf6a3dbe6fd4e40511132d6334287c77fcf894a33f6",
          "sha1": "ce6fc90dfd56fa40341a143f52f33513b1690bf1",
          "md5": "cee0485171944fe498d3b41bae904f1b"
        }
      ]
    }
  ]
}
