{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "7g7z7ezk5vaxvor6gqfcljloxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha11.jar",
          "url": "plugin-1.0.0-alpha11.jar",
          "size": 182140,
          "sha512": "a0d5a5f5fb6e5deaab962a2d00339f0f799e69b03896c29ab5fe7dd58ab02b18cfe67178da712458535e425076b10dbe6ca5c191e352e945d4d5c4525d2702aa",
          "sha256": "0e89b83b2ba33e1bf003a65661e29d99f4c491138ac92ec324594131d266f582",
          "sha1": "1ee6736400f389f3fe37aa46f5c037b83abe3067",
          "md5": "f058c9a3dbc997def3b3ff9c60c8148e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha11.jar",
          "url": "plugin-1.0.0-alpha11.jar",
          "size": 182140,
          "sha512": "a0d5a5f5fb6e5deaab962a2d00339f0f799e69b03896c29ab5fe7dd58ab02b18cfe67178da712458535e425076b10dbe6ca5c191e352e945d4d5c4525d2702aa",
          "sha256": "0e89b83b2ba33e1bf003a65661e29d99f4c491138ac92ec324594131d266f582",
          "sha1": "1ee6736400f389f3fe37aa46f5c037b83abe3067",
          "md5": "f058c9a3dbc997def3b3ff9c60c8148e"
        }
      ]
    }
  ]
}
