{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha16/viewcontract-1.0.0-alpha16.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha16.jar",
          "url": "viewcontract-jvm-1.0.0-alpha16.jar",
          "size": 54321,
          "sha512": "fb3efeaaf906fa4fcf7a6c431f460f6842b441628f4a9c67d4caa7dfaad38ec33f1773b06dc7b9da2ba3f9d1d09b2fbc90c861b22405de95d9ac77a944ee93b7",
          "sha256": "7e5599b4d78324dee1cdee44dc0cfcf42ec247381a9e985b8d97c7a3c97d77a5",
          "sha1": "e378f16bea359b754fa4e6ce84f881fdec8c0746",
          "md5": "c8045a38876204957e527b480d1a3ca1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha16.jar",
          "url": "viewcontract-jvm-1.0.0-alpha16.jar",
          "size": 54321,
          "sha512": "fb3efeaaf906fa4fcf7a6c431f460f6842b441628f4a9c67d4caa7dfaad38ec33f1773b06dc7b9da2ba3f9d1d09b2fbc90c861b22405de95d9ac77a944ee93b7",
          "sha256": "7e5599b4d78324dee1cdee44dc0cfcf42ec247381a9e985b8d97c7a3c97d77a5",
          "sha1": "e378f16bea359b754fa4e6ce84f881fdec8c0746",
          "md5": "c8045a38876204957e527b480d1a3ca1"
        }
      ]
    }
  ]
}
