{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.10/androidTests-0.0.10.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.10.jar",
          "url": "androidTests-metadata-0.0.10.jar",
          "size": 261,
          "sha512": "9f9bf78c330387893a0dcee9c8a74481cc3e8b7c5f7dd7fa511f61bf715cb2a7fdf306c07716c4dd40efce6855f420bf16651bc1fe5ce2aad128d66d2a8847e1",
          "sha256": "446fb6149b4932d8b1f329ae224ad91ed7ae75637b0e9e3e292d1c8d53a3200d",
          "sha1": "42797e10f1c76f462f5a0e62c80ea8f265ad6051",
          "md5": "e07bfdccd936c28c768462c6ba1201e4"
        }
      ]
    }
  ]
}
