{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rcsqc6iufne5ve6vpfzg2hyyae"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.51"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.51.jar",
          "url": "view-0.0.51.jar",
          "size": 6296,
          "sha512": "18d040ec6d050f3f6a16788d3a6f484fa5209756b4da3002e4d0dc61c1697974bf46d30e6ce35b39951b9b1c6be350616e8b9a9fa8a329d8789a0b0f6ad428b8",
          "sha256": "dee25f5ed0c61a4487ed464a12eebe79416ca6b1bfac92433f13076939d679a3",
          "sha1": "c1aff0b3259430ec5b44975dc99711e9b668f76a",
          "md5": "c517a938bd6fde9908d40a0eb83ff9a9"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.51/view-android-0.0.51.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.51/view-android-0.0.51.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.51/view-android-0.0.51.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.51/view-android-0.0.51.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.51"
      }
    }
  ]
}
