{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.24/contract-0.0.24.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "outl7uxctrgmfpv6znqczvsuxy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.24.jar",
          "url": "contract-metadata-0.0.24.jar",
          "size": 7497,
          "sha512": "02040e1ae53098ef7db95585f220413b65044a8722220ef5fe1e5db6a7d5d6c6d0b789aef28929f6fdeac9ce03faf0162daff41f04b7831fd0a8c962eb945e24",
          "sha256": "9200a4ffb64919339ed87c3c001e8dc22527badeada3c93d0fa71d9d8941bd3f",
          "sha1": "6ff5799d5459ff300d6acf949601540bcdd99707",
          "md5": "9edb01d2529956c7a04b08396253a734"
        }
      ]
    }
  ]
}
