{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../contract-jvm/0.0.25/contract-jvm-0.0.25.module",
        "group": "tech.skot",
        "module": "contract-jvm",
        "version": "0.0.25"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../contract-jvm/0.0.25/contract-jvm-0.0.25.module",
        "group": "tech.skot",
        "module": "contract-jvm",
        "version": "0.0.25"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.25/contract-metadata-0.0.25.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.25"
      }
    }
  ]
}
