{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.41/core-0.0.41.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mg55xkylpzdfpow33thce6zcgu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.41.jar",
          "url": "core-metadata-0.0.41.jar",
          "size": 5341,
          "sha512": "33476237cb18e5580e39b755a111ca698b087074b106cfbc8b2a2670a5f0ae0e3a2acb3b2d852f9ce2c5f8b8dcad4ff84605a62aaf6ad91d6d7ff33e331f572a",
          "sha256": "a91acadd8fe56492f3fea151b9f10a247a0a0114ee754ea6d836602b76f3e553",
          "sha1": "082bcb5022a12ce69d8bf6ca643ecfc313ac9478",
          "md5": "924d134465b3d4075f89408e91206134"
        }
      ]
    }
  ]
}
