{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.31/contract-0.0.31.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "4g4dsdf7yvgxndmmqjq6s6i2gm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.31.jar",
          "url": "contract-metadata-0.0.31.jar",
          "size": 7614,
          "sha512": "5208e4128932c0cd5efce06f00f1a443ffa55a2faecdceef80737b83df41640d75e3b87e9c1095bb51911ffdfb80495785968a2d4aef145142f6c51212a66848",
          "sha256": "3277c26e8c05fed455fabd0b77ccbdd3c1ef60ca415b32e43d05a87f2991a0c3",
          "sha1": "71df4b084a4e7530d3d60bbf8c8bb2f20a2d6733",
          "md5": "60ff93ae78469940051afa1ba994755a"
        }
      ]
    }
  ]
}
