{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.19/viewmodel-0.0.19.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "julmyh4b25dnnegsjouy3lg5q4"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.19-debug.aar",
          "size": 52009,
          "sha512": "fd199dfe89d42bee5c0cbe6fabbec316c76fb49608e13ea300088f44a94b8bf9e8fd6ce732b9d23bfdd9e9c4d29a447c6c2422b55820db304ad501f5821693e0",
          "sha256": "edfc30b212302670b3508f7ce67b200c2718026c30009b44f17d67ee319e6ace",
          "sha1": "83bb0bbc9db5ec7f60b6669e8cc940e6bed01d7d",
          "md5": "3322e9a77d09eef98ed7608d50048879"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.19-debug.aar",
          "size": 52009,
          "sha512": "fd199dfe89d42bee5c0cbe6fabbec316c76fb49608e13ea300088f44a94b8bf9e8fd6ce732b9d23bfdd9e9c4d29a447c6c2422b55820db304ad501f5821693e0",
          "sha256": "edfc30b212302670b3508f7ce67b200c2718026c30009b44f17d67ee319e6ace",
          "sha1": "83bb0bbc9db5ec7f60b6669e8cc940e6bed01d7d",
          "md5": "3322e9a77d09eef98ed7608d50048879"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.19.aar",
          "size": 50362,
          "sha512": "5e7576095b898a543301cc0c4e8803b5f42019db01571072b9407752fe4422ef65bd9845d65abc38a662e82a531d5d4f070b2d0952b5854cdddeae1af9228278",
          "sha256": "45304d72a6f2df3ef12ee2be238bea93f6d9af55e45b1ca295664121d9cf72f4",
          "sha1": "b72281bb0623910fba80ad02e839ca427d6b8bf9",
          "md5": "872968904bde790e598c6a7f0e7bf5cc"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.19.aar",
          "size": 50362,
          "sha512": "5e7576095b898a543301cc0c4e8803b5f42019db01571072b9407752fe4422ef65bd9845d65abc38a662e82a531d5d4f070b2d0952b5854cdddeae1af9228278",
          "sha256": "45304d72a6f2df3ef12ee2be238bea93f6d9af55e45b1ca295664121d9cf72f4",
          "sha1": "b72281bb0623910fba80ad02e839ca427d6b8bf9",
          "md5": "872968904bde790e598c6a7f0e7bf5cc"
        }
      ]
    }
  ]
}
