{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.46/contract-0.0.46.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "2op6vpqzbfeszkvmuhojwr2oxe"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract.klib",
          "url": "contract-iosarm64-0.0.46.klib",
          "size": 19094,
          "sha512": "42a60819812eb41595d35bdd0e5728d0ebd6ace69ca189aaa2125d7ebb8453bf87bf32f809e4c83e71b97e39c339d1f0682c5e5df005e33fc6a664937e204942",
          "sha256": "926a1470cd140020375c377cab703ff95a5901e919299fd0e98d48b10a2a5e4a",
          "sha1": "a15d6e5e5f53e69b3c3e4fd45e9026a3790cea2d",
          "md5": "01b3d187af7b3cbac77504c928895871"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.46/contract-metadata-0.0.46.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.46"
      }
    }
  ]
}
