{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha13/viewcontract-1.0.0-alpha13.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha13.jar",
          "url": "viewcontract-jvm-1.0.0-alpha13.jar",
          "size": 51334,
          "sha512": "dd9de950962c69189912e7f168756413514271e6f8f282e390625e17956c8591dd121e808283df2e018b5d882a081250e7a5249973189c0fd652331b1a094f53",
          "sha256": "7f750b064b3ce09f91ea84bbc315ceb721b8db25a1af66a526e74351b0350880",
          "sha1": "aa32339fb47269e8e72a7717e07d01fbb06dbdc1",
          "md5": "ac55f80996e93ecbbfcde8b6fd266af8"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha13.jar",
          "url": "viewcontract-jvm-1.0.0-alpha13.jar",
          "size": 51334,
          "sha512": "dd9de950962c69189912e7f168756413514271e6f8f282e390625e17956c8591dd121e808283df2e018b5d882a081250e7a5249973189c0fd652331b1a094f53",
          "sha256": "7f750b064b3ce09f91ea84bbc315ceb721b8db25a1af66a526e74351b0350880",
          "sha1": "aa32339fb47269e8e72a7717e07d01fbb06dbdc1",
          "md5": "ac55f80996e93ecbbfcde8b6fd266af8"
        }
      ]
    }
  ]
}
