{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.21/viewmodel-0.0.21.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yshs27cbmzfrdgxafso6bc577q"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.21-debug.aar",
          "size": 52067,
          "sha512": "4ded9484248d2627460290d20873628698692ee77775e11d091b515aa9fd2b6d1bdbe14cb97d1d77adf30cc5b15e7da5e699b8a4fb1e4ec2f91652b2255e9b4f",
          "sha256": "b36ba30b13d21af3cba2db2a7aafaf9c47a7b9d42e7ffbb7889d84dbdd49b152",
          "sha1": "07f0104d28e08b054f012832f363528f392e333f",
          "md5": "2fcd2ad29f10eb07a53924e72157dbb9"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.21-debug.aar",
          "size": 52067,
          "sha512": "4ded9484248d2627460290d20873628698692ee77775e11d091b515aa9fd2b6d1bdbe14cb97d1d77adf30cc5b15e7da5e699b8a4fb1e4ec2f91652b2255e9b4f",
          "sha256": "b36ba30b13d21af3cba2db2a7aafaf9c47a7b9d42e7ffbb7889d84dbdd49b152",
          "sha1": "07f0104d28e08b054f012832f363528f392e333f",
          "md5": "2fcd2ad29f10eb07a53924e72157dbb9"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.21.aar",
          "size": 50411,
          "sha512": "277abc4815ce9b0d38142d477e7bcbb6c8c929025686855deef3e7a7469b0c083ee1f088dd1817141c45835ce99adefa8f58caafcd1c1670440d4387bcaf9272",
          "sha256": "2b86f3a6f68db852953c05c68cdef748848f69cda5f3bd87789d53c63b979c6d",
          "sha1": "37f96efef9171b005809cb0a446396733bcf37eb",
          "md5": "59ed5866bebd9d0cf80f5f5e997f6588"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.21.aar",
          "size": 50411,
          "sha512": "277abc4815ce9b0d38142d477e7bcbb6c8c929025686855deef3e7a7469b0c083ee1f088dd1817141c45835ce99adefa8f58caafcd1c1670440d4387bcaf9272",
          "sha256": "2b86f3a6f68db852953c05c68cdef748848f69cda5f3bd87789d53c63b979c6d",
          "sha1": "37f96efef9171b005809cb0a446396733bcf37eb",
          "md5": "59ed5866bebd9d0cf80f5f5e997f6588"
        }
      ]
    }
  ]
}
