{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.47.jar",
          "url": "plugin-0.0.47.jar",
          "size": 56869,
          "sha512": "c084c11fd4303dcd553ba224a8ddc97be29efa26e928707d0ae247827a6dda8d8b8e14a593476b645aa76fe4da85e2760b16960b95bdcc619bcb486399507b89",
          "sha256": "be1dd2c04f47a25ad9cb6b84d581f07f391fce531caa42e62a252bacb9e8a386",
          "sha1": "25b03e84f19e2a8b0c17e8397acc5ebad3ae49a6",
          "md5": "32f2cb3f74f04486e970262f358b46d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.47.jar",
          "url": "plugin-0.0.47.jar",
          "size": 56869,
          "sha512": "c084c11fd4303dcd553ba224a8ddc97be29efa26e928707d0ae247827a6dda8d8b8e14a593476b645aa76fe4da85e2760b16960b95bdcc619bcb486399507b89",
          "sha256": "be1dd2c04f47a25ad9cb6b84d581f07f391fce531caa42e62a252bacb9e8a386",
          "sha1": "25b03e84f19e2a8b0c17e8397acc5ebad3ae49a6",
          "md5": "32f2cb3f74f04486e970262f358b46d6"
        }
      ]
    }
  ]
}
