{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-1.0.0-alpha20.jar",
          "url": "model-1.0.0-alpha20.jar",
          "size": 13583,
          "sha512": "61c6de97b8fc00e51d2c5aafe0b57f606c87371765a44cf79e9ff5e14568f3d64dfec25336ae84393edd827196d35259fe9154ac55284ea58d6db617d0038f8f",
          "sha256": "d91114d329ca1e815a5d092d6023f2fb8c39f109714ecef62c0145ad49793280",
          "sha1": "113ef40f5d6c54c51e752e691d63b6123dbb1e3f",
          "md5": "d2a1d8d1e4e55dc21e6fc26d00ef6c22"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha20/model-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha20/model-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha20/model-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha20/model-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosarm64/1.0.0-alpha20/model-iosarm64-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "model-iosarm64",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosx64/1.0.0-alpha20/model-iosx64-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "model-iosx64",
        "version": "1.0.0-alpha20"
      }
    }
  ]
}
