{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha6/viewcontract-1.0.0-alpha6.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha6.klib",
          "size": 26578,
          "sha512": "292e3481feb6a45edec71aab2ef555cbb11b8bc73d8edc5027cdee728e204bddd414db3764b4771785b82e5180a611ecae360b2d16d07fb111f7d58030e0b95f",
          "sha256": "ae17f041755198095d90a9da5c8d692f8837368c25570da7555c748ecac20ea2",
          "sha1": "cbed7d44d9823e724c15eacc42799c3b0d02af22",
          "md5": "25ed5eb78f6264a55ab8dca30d2f53b5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../viewcontract-metadata/1.0.0-alpha6/viewcontract-metadata-1.0.0-alpha6.module",
        "group": "tech.skot",
        "module": "viewcontract-metadata",
        "version": "1.0.0-alpha6"
      }
    }
  ]
}
