{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha11/viewmodel-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "7g7z7ezk5vaxvor6gqfcljloxy"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha11-debug.aar",
          "size": 48594,
          "sha512": "3784574f2c22eace68d761cfdcaead02ef5d886f2e05fe2d68db4dfd255a1a1f15dfc55f5776593a6852bb696729f0e213ef5c2994aff967dcd13befda1e8ad0",
          "sha256": "a0145b1ae2d78f455f3b4e5fbe7b35505125161b3182cc0e5df5018c72facb6d",
          "sha1": "1f8fdc4a8364fb5d7553e45d3e28444993c2e92b",
          "md5": "6c44b96919ca3b3e5491b4703c4f45c6"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha11-debug.aar",
          "size": 48594,
          "sha512": "3784574f2c22eace68d761cfdcaead02ef5d886f2e05fe2d68db4dfd255a1a1f15dfc55f5776593a6852bb696729f0e213ef5c2994aff967dcd13befda1e8ad0",
          "sha256": "a0145b1ae2d78f455f3b4e5fbe7b35505125161b3182cc0e5df5018c72facb6d",
          "sha1": "1f8fdc4a8364fb5d7553e45d3e28444993c2e92b",
          "md5": "6c44b96919ca3b3e5491b4703c4f45c6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha11.aar",
          "size": 46155,
          "sha512": "6b4c4589ba525dcbb605fb8dc0aedc769f044c57246ce6e762e569c3690bf0a2bf9278e5c088b079470d99577da5195daf8da99f59bf10791ca86b94cdd06c9b",
          "sha256": "7c5b2e1705140ca29c1d1a35bb637a8eb8f79923f24c0231ebb866c424ef8070",
          "sha1": "d2b53914001c8ce1e20a5f41ffaeba9a82c1d7b7",
          "md5": "5dce6b5e87097908097b07e7ac6fbe43"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha11.aar",
          "size": 46155,
          "sha512": "6b4c4589ba525dcbb605fb8dc0aedc769f044c57246ce6e762e569c3690bf0a2bf9278e5c088b079470d99577da5195daf8da99f59bf10791ca86b94cdd06c9b",
          "sha256": "7c5b2e1705140ca29c1d1a35bb637a8eb8f79923f24c0231ebb866c424ef8070",
          "sha1": "d2b53914001c8ce1e20a5f41ffaeba9a82c1d7b7",
          "md5": "5dce6b5e87097908097b07e7ac6fbe43"
        }
      ]
    }
  ]
}
