{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha26.jar",
          "url": "plugin-1.0.0-alpha26.jar",
          "size": 221811,
          "sha512": "375e2ab56ab2d57e2342f82885825d998d35b683bfdb02a494edd083224d86bd53139d464143cf4149e2a9cb522b0d1a4c0d17814d5036021937b7d205e190ae",
          "sha256": "915fd9c3983655b2deee8ec7ffe93b153fb9498226773ed5602f80873344805d",
          "sha1": "cabb64c961e8fc0d8854565db40b41f74d957dec",
          "md5": "0cc5322f2c44790c6fef9c19c54ad353"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha26.jar",
          "url": "plugin-1.0.0-alpha26.jar",
          "size": 221811,
          "sha512": "375e2ab56ab2d57e2342f82885825d998d35b683bfdb02a494edd083224d86bd53139d464143cf4149e2a9cb522b0d1a4c0d17814d5036021937b7d205e190ae",
          "sha256": "915fd9c3983655b2deee8ec7ffe93b153fb9498226773ed5602f80873344805d",
          "sha1": "cabb64c961e8fc0d8854565db40b41f74d957dec",
          "md5": "0cc5322f2c44790c6fef9c19c54ad353"
        }
      ]
    }
  ]
}
