{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.sk-tabbar",
    "module": "viewmodel",
    "version": "0.0.2_1.0.0-alpha59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.2_1.0.0-alpha59"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.2_1.0.0-alpha59.jar",
          "url": "viewmodel-0.0.2_1.0.0-alpha59.jar",
          "size": 4152,
          "sha512": "14044708032ffe8246459ed160499e78caa4301f5ba2de28d0cb713233152d93d609a5bbb364b973c67fd83a3bea4115da2624c356f6abc75de6ebee73302bb2",
          "sha256": "cb4cd32fc9e17bfb2d7d52e95b63d29f101d2ed27526079591f71218f243c793",
          "sha1": "4e4983b4d98bda79e77019452c82dfe908307744",
          "md5": "a30ccd3e04132fce430c35c71de5cc14"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha59/viewmodel-android-0.0.2_1.0.0-alpha59.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha59"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha59/viewmodel-android-0.0.2_1.0.0-alpha59.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha59"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha59/viewmodel-android-0.0.2_1.0.0-alpha59.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha59"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha59/viewmodel-android-0.0.2_1.0.0-alpha59.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha59"
      }
    }
  ]
}
