{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.44/core-0.0.44.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i7olmwxatfdhths5wu7quwrrny"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.44.jar",
          "url": "core-metadata-0.0.44.jar",
          "size": 5341,
          "sha512": "5c22f660eb9f75cb69614df665b5d44cf62cca0aee852c0873ae9f930a719a65adfc5e0d3752b80317a5bc27b0070914da9e10980b8384c41fb1574cb67aff8b",
          "sha256": "3289a1de91104a76586c796701b1d2fccf867678f4649f5b9e62683c87a11ac1",
          "sha1": "892516c51693620e09940d1d2b8bd00b174c1c35",
          "md5": "325383beb42d63a26922fcdd715ad455"
        }
      ]
    }
  ]
}
