{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xtqqandxyva3tauucku2734sky"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.9.jar",
          "url": "generator-0.0.9.jar",
          "size": 92123,
          "sha512": "2cb104ecb727647084630231a9ca56c38236812e03e4f02019fe92fc5513297c7e7342d02ce91dbcb259116e2e81c68e1c7e374d80448384749bd16b347922bc",
          "sha256": "d0e6bb2ec35165689cf590ab5ac29e71d6941b769fda7a8fb914060ffcd4f673",
          "sha1": "791a742fcc20ec0bc9e2d546b56480af478bbbaa",
          "md5": "6b2353e8594a2496e241007cd51b095b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.9.jar",
          "url": "generator-0.0.9.jar",
          "size": 92123,
          "sha512": "2cb104ecb727647084630231a9ca56c38236812e03e4f02019fe92fc5513297c7e7342d02ce91dbcb259116e2e81c68e1c7e374d80448384749bd16b347922bc",
          "sha256": "d0e6bb2ec35165689cf590ab5ac29e71d6941b769fda7a8fb914060ffcd4f673",
          "sha1": "791a742fcc20ec0bc9e2d546b56480af478bbbaa",
          "md5": "6b2353e8594a2496e241007cd51b095b"
        }
      ]
    }
  ]
}
