{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "xduo2x3rkbaepe3emobddesovq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.16.jar",
          "url": "generator-0.0.16.jar",
          "size": 92130,
          "sha512": "ff6a74f8d1ff69eed1ed4268307699158149941d7409a902a7af247618edbead45afbb440be22dfeedea0b68fd2c77915e47bf363b13100c82aa0f499576464b",
          "sha256": "ba2a69c9cc231a819a12244446db7a96c132e23a304833f3ec54bc83068fb0e3",
          "sha1": "15f2c3fa5d378bed1db610b3a11c7b7b13c514ee",
          "md5": "94116f7bfb3f3ce591d54a216c40a229"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.16"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.16.jar",
          "url": "generator-0.0.16.jar",
          "size": 92130,
          "sha512": "ff6a74f8d1ff69eed1ed4268307699158149941d7409a902a7af247618edbead45afbb440be22dfeedea0b68fd2c77915e47bf363b13100c82aa0f499576464b",
          "sha256": "ba2a69c9cc231a819a12244446db7a96c132e23a304833f3ec54bc83068fb0e3",
          "sha1": "15f2c3fa5d378bed1db610b3a11c7b7b13c514ee",
          "md5": "94116f7bfb3f3ce591d54a216c40a229"
        }
      ]
    }
  ]
}
