{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "core",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha62.jar",
          "url": "core-1.0.0-alpha62.jar",
          "size": 7807,
          "sha512": "0331be801390523136fffd91aace344b2309ea9b664638acb5bd4f5da7bc26b6e055a6148791067a6814ee522d068ad1785b1a8339be98bf0e95f110830388c4",
          "sha256": "1a29e0f88298f32ccd14d34105f58412d5ceeb1d2de6e54355f8beca3baeca6a",
          "sha1": "8061b670a98ceedaea193c616cbf752666d1d6db",
          "md5": "ec976335926f3241e766f3240786e9ca"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha62/core-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "core-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha62/core-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "core-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha62/core-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "core-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha62/core-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "core-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha62/core-iosarm64-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha62/core-iosx64-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha62"
      }
    }
  ]
}
