{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "542d3vhgfrhaxgd5li4auko6d4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha14.jar",
          "url": "core-1.0.0-alpha14.jar",
          "size": 7358,
          "sha512": "e17b443ff93ced7d5b10b8318e67fdc25c9ec8d79612765d404ad0c899e00af2b2267975433253beb44e2678ac93f87f76c8bde422599562c0d37db354ba5f93",
          "sha256": "c7a0748c5496d1a33793ae1db1613a5036ddf2d2848314317c6862634ed2c693",
          "sha1": "6fff166b68318483b620cd594d6f6633872c4875",
          "md5": "87a98969a0f5ae7af33fd2afdecf383a"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha14/core-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha14/core-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha14/core-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha14/core-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha14/core-iosarm64-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha14/core-iosx64-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha14"
      }
    }
  ]
}
