{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.17/core-0.0.17.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "43amt7eqbfabtkb5q6646kb3hm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.17.jar",
          "url": "core-metadata-0.0.17.jar",
          "size": 5327,
          "sha512": "2516c2ecd7cd28110dcc5d8c9b056f546038556160d0d8811a1ba83e20ef184f4ea22ca41772c0a845fe216609acaa2ee380ba9acd1309c7f05102224067ea11",
          "sha256": "d8eb73e66c75eebeaaa41634efa0c74d0d6a4373a38a92c607a836a56ae0425a",
          "sha1": "b59034ac52912991da888136430eb619f271b194",
          "md5": "adb6a55af7444dba23e9c89f21fb5321"
        }
      ]
    }
  ]
}
