{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "adu4mcp7tnfvfaxt3d3ep6dpwa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.48.jar",
          "url": "generator-0.0.48.jar",
          "size": 94622,
          "sha512": "fee89be286bf9e2553d564d4454e559e0a99459f942cc90610bf3d78efbd6463ae9f615fd295e88575ba2993bb4990c3340fabe81e664594fe09c41bff678cad",
          "sha256": "d3c5b6fe6c851a45aa8a2278ec221c6f2e6debaa1fa3419d9551d18e3532aab6",
          "sha1": "4c302d3e51a261869c908ac6e44db6c8fb66041e",
          "md5": "f76e84d3be8a78b6e256b1920c37858e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.48.jar",
          "url": "generator-0.0.48.jar",
          "size": 94622,
          "sha512": "fee89be286bf9e2553d564d4454e559e0a99459f942cc90610bf3d78efbd6463ae9f615fd295e88575ba2993bb4990c3340fabe81e664594fe09c41bff678cad",
          "sha256": "d3c5b6fe6c851a45aa8a2278ec221c6f2e6debaa1fa3419d9551d18e3532aab6",
          "sha1": "4c302d3e51a261869c908ac6e44db6c8fb66041e",
          "md5": "f76e84d3be8a78b6e256b1920c37858e"
        }
      ]
    }
  ]
}
