{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.14/model-0.0.14.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3dorn7aqgzbq3owi6pxgrw7ncy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.14.jar",
          "url": "model-metadata-0.0.14.jar",
          "size": 13100,
          "sha512": "102a8d20d8d00460e16eae55da9b545fe1e6c927fb82628f514948e7d56137f5647af102a48be0c4cb2e21658ca759afdc3c608cbef8d67151388a5962a91dd1",
          "sha256": "62da42a7e3b6c08db936d853fca785bd9934263ec66894882b9bf398a31312ba",
          "sha1": "aba729eaea4fe64ed5f0f9e02cd6b5d6c8b3e182",
          "md5": "319eb1e7bb7e50e801cf65d62594a658"
        }
      ]
    }
  ]
}
