{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.14/model-0.0.14.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.14.jar",
          "url": "model-metadata-0.0.14.jar",
          "size": 13100,
          "sha512": "99bfedae03308ffe2dd1425b5c347b81a27ec643efef2ecd28a48e893e24a66492b145b2d97ac65355d1d6ba571762d56a82c354b3f70bf6541da22fa0d779b4",
          "sha256": "a932eab28a3022c151dfd0cb45a365ea090605fdaff02a02a5e518d5ef6b043a",
          "sha1": "1be05cb28793641519651bab89189a5c06346b69",
          "md5": "9f246b816e25fe1f0100e7b6bf2b740c"
        }
      ]
    }
  ]
}
