{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.28/model-0.0.28.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.28-debug.aar",
          "size": 93348,
          "sha512": "6ab777e6bd6d436802416a6a55f7587dec748be8219df189bc6629bf4982ad70a6bc34896ac518c83b09b87a430cfc9bf9f135cebba6063e3a848b2664ce38d7",
          "sha256": "9f4118729bec7771c2a501c8ffbac0c02cad91341a7651fbf26fc0f7b43ff08c",
          "sha1": "6d034f64400629b53c4d9a605ef655eb7490c290",
          "md5": "03ef5890c18559b75679d6bc6db9a7bb"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.28-debug.aar",
          "size": 93348,
          "sha512": "6ab777e6bd6d436802416a6a55f7587dec748be8219df189bc6629bf4982ad70a6bc34896ac518c83b09b87a430cfc9bf9f135cebba6063e3a848b2664ce38d7",
          "sha256": "9f4118729bec7771c2a501c8ffbac0c02cad91341a7651fbf26fc0f7b43ff08c",
          "sha1": "6d034f64400629b53c4d9a605ef655eb7490c290",
          "md5": "03ef5890c18559b75679d6bc6db9a7bb"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.28.aar",
          "size": 89549,
          "sha512": "3baf94ab8034287c0406028b2834f20a93ec8f71cc49ea57192c724566114f6d6746b95a6efedaa1761aaf6092933fab26da896ea75a2f5171ee3e8cbba4cf1f",
          "sha256": "b63571ac18b224657a4c924fc3b4c8e853660c834e48f52f027da7d42c6af10c",
          "sha1": "f35cbf92d1b90045c707cbc235defb49724fda42",
          "md5": "63009a170775b63e6addd55142fdefb5"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.28.aar",
          "size": 89549,
          "sha512": "3baf94ab8034287c0406028b2834f20a93ec8f71cc49ea57192c724566114f6d6746b95a6efedaa1761aaf6092933fab26da896ea75a2f5171ee3e8cbba4cf1f",
          "sha256": "b63571ac18b224657a4c924fc3b4c8e853660c834e48f52f027da7d42c6af10c",
          "sha1": "f35cbf92d1b90045c707cbc235defb49724fda42",
          "md5": "63009a170775b63e6addd55142fdefb5"
        }
      ]
    }
  ]
}
