{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.28/model-0.0.28.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "t2w34ohvabccfdd6l3g4neepp4"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.28-debug.aar",
          "size": 93393,
          "sha512": "b81fe10f1d8c5306d432034d0b25a96821aecfda7191ecab182e9a986bcf941a1dca9f084ece906437aedb0d8a1796ff315f180004af77bd8a3edf2396c21881",
          "sha256": "83366d8cff632866abe20b19f7911404e47e5c03afd72e5d0a2a385142cb9718",
          "sha1": "2371359dba74a41957a0e3b3679e04f5de0f2107",
          "md5": "36135de5891aca73fa01406ddcdcc3b4"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.28-debug.aar",
          "size": 93393,
          "sha512": "b81fe10f1d8c5306d432034d0b25a96821aecfda7191ecab182e9a986bcf941a1dca9f084ece906437aedb0d8a1796ff315f180004af77bd8a3edf2396c21881",
          "sha256": "83366d8cff632866abe20b19f7911404e47e5c03afd72e5d0a2a385142cb9718",
          "sha1": "2371359dba74a41957a0e3b3679e04f5de0f2107",
          "md5": "36135de5891aca73fa01406ddcdcc3b4"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.28.aar",
          "size": 89590,
          "sha512": "3d52109ff2caafc0fd6be4dd4364953890d0c0ecb90d5e6e7ddb55540f6b366972029b8229f482dc5cf5943d4037371e3f2f7f5060abd33a8c16efc866fe7f24",
          "sha256": "5e3a7b621b70c0165c6ee68e04552dd332e2d7176ba7be42018c76c305181eb2",
          "sha1": "ac8d6e70d9aa5508f92a136b0d76eb9650330c2b",
          "md5": "e3d21ae3655f57287910ffe39007a8a7"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.28.aar",
          "size": 89590,
          "sha512": "3d52109ff2caafc0fd6be4dd4364953890d0c0ecb90d5e6e7ddb55540f6b366972029b8229f482dc5cf5943d4037371e3f2f7f5060abd33a8c16efc866fe7f24",
          "sha256": "5e3a7b621b70c0165c6ee68e04552dd332e2d7176ba7be42018c76c305181eb2",
          "sha1": "ac8d6e70d9aa5508f92a136b0d76eb9650330c2b",
          "md5": "e3d21ae3655f57287910ffe39007a8a7"
        }
      ]
    }
  ]
}
