{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.28/viewmodel-0.0.28.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.28-debug.aar",
          "size": 52235,
          "sha512": "cae7388dd3f6e6b9505e514201f9ec2279965d2773b11a465beaed8937cc23026ace8169e7967ac125d95dd2b619b9ce1314cf6d86e8d6cfde4c55add0b9a9b8",
          "sha256": "2f6efb3d3a2f7510e161bcd9aaee55ca5b2fee5d46aed766f4d4663cc8c76101",
          "sha1": "924682263a0a374ca5bf44667322747faa69570f",
          "md5": "1a8cf798b698e54704c15002ec162b44"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.28-debug.aar",
          "size": 52235,
          "sha512": "cae7388dd3f6e6b9505e514201f9ec2279965d2773b11a465beaed8937cc23026ace8169e7967ac125d95dd2b619b9ce1314cf6d86e8d6cfde4c55add0b9a9b8",
          "sha256": "2f6efb3d3a2f7510e161bcd9aaee55ca5b2fee5d46aed766f4d4663cc8c76101",
          "sha1": "924682263a0a374ca5bf44667322747faa69570f",
          "md5": "1a8cf798b698e54704c15002ec162b44"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.28.aar",
          "size": 50583,
          "sha512": "3f4a8ce0e3fad2a4dd80ec224d5e7f4e3f99ecf8fd2297ec9040e3b16a396cb4195056c0232af893f2bc6aa455d1b87c929e61335aa6a1fa7fecdaed211aa3f3",
          "sha256": "e570b6acd82fee45069a751522cc9cdc2f28e9fe73b3c32f38dc761bb35c69c8",
          "sha1": "65c2fd0407ac7f7882de7cee436de24a89eb4c0f",
          "md5": "abf83ff5edf4f462f06e91c844b4da1d"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.28.aar",
          "size": 50583,
          "sha512": "3f4a8ce0e3fad2a4dd80ec224d5e7f4e3f99ecf8fd2297ec9040e3b16a396cb4195056c0232af893f2bc6aa455d1b87c929e61335aa6a1fa7fecdaed211aa3f3",
          "sha256": "e570b6acd82fee45069a751522cc9cdc2f28e9fe73b3c32f38dc761bb35c69c8",
          "sha1": "65c2fd0407ac7f7882de7cee436de24a89eb4c0f",
          "md5": "abf83ff5edf4f462f06e91c844b4da1d"
        }
      ]
    }
  ]
}
