{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.30/contract-0.0.30.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "45vyvjpy25d6rogm6vet7cshky"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.30.jar",
          "url": "contract-jvm-0.0.30.jar",
          "size": 17931,
          "sha512": "b23c92d03578afe57a838cbfdc5fde0457334a7371194781134c7977414fe2bb1599e1e0e35a248dbd3297114213a9caefe3941a1e005c173c62c667d58c7fde",
          "sha256": "7dd340e48148efa508ffd5a424f1eb54686aae3b3452e1f5a7970e2f454f4f76",
          "sha1": "e805c58a9c744d071b656db0465bd4e337dfb9ab",
          "md5": "51693128c5b776850269c94677118a80"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.30.jar",
          "url": "contract-jvm-0.0.30.jar",
          "size": 17931,
          "sha512": "b23c92d03578afe57a838cbfdc5fde0457334a7371194781134c7977414fe2bb1599e1e0e35a248dbd3297114213a9caefe3941a1e005c173c62c667d58c7fde",
          "sha256": "7dd340e48148efa508ffd5a424f1eb54686aae3b3452e1f5a7970e2f454f4f76",
          "sha1": "e805c58a9c744d071b656db0465bd4e337dfb9ab",
          "md5": "51693128c5b776850269c94677118a80"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.30/contract-metadata-0.0.30.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.30"
      }
    }
  ]
}
