{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.21/viewmodel-0.0.21.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yshs27cbmzfrdgxafso6bc577q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.21.jar",
          "url": "viewmodel-metadata-0.0.21.jar",
          "size": 6984,
          "sha512": "bce696ca311f26d20600415a9d21fe3b84ab098945e2c65f3f8e383cb4a1d2d03867a62a295b5fc943723a014abc7a9a1937d36a83a80fc73a9cd45bd6da02e6",
          "sha256": "d86e333bd54046e7192636eff3174ca2a6e8fadb64549cdc0189dea110e722b6",
          "sha1": "c8a4d6860f4a38d10025c3fb7c9f6334afa67ce9",
          "md5": "20fe6d1bd8b89d9757aa43943983ed38"
        }
      ]
    }
  ]
}
