{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha17.jar",
          "url": "core-1.0.0-alpha17.jar",
          "size": 7358,
          "sha512": "f12327439bd7df06f315d6f4f3b4636b82b55862394a856f321cf01d0e4ddf1630fa54fa42ab32f77e9cef1f268b646a26aca7e99e5a898ee789eb49b0d7bd61",
          "sha256": "98708aafce37b58eacc7cab1b3846e6e6625160827a1680aefc10ab53526a29a",
          "sha1": "6754387757fa8a4a894989c56cd27b62e1deb2af",
          "md5": "9517ff98bf74206e89dbffd075b392ed"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha17/core-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha17/core-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha17/core-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha17/core-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha17/core-iosarm64-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha17/core-iosx64-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha17"
      }
    }
  ]
}
