{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.7/androidTests-0.0.7.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "igasumkhiveslbdlejoqxrssj4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.7.jar",
          "url": "androidTests-metadata-0.0.7.jar",
          "size": 261,
          "sha512": "9ae0706db2203828a911e407b140880db184284b062901d286e109441e30a112c63ae7eddfc1de00b1872e60bedd9b1466b2be79f4e86b704e75799a52ede071",
          "sha256": "fed22fe6de838e1c228d8a5d63107e7df2dd98bc96703b1407a4b77e9518892c",
          "sha1": "494c0806fce8c178a34289f3c50120e84617b637",
          "md5": "a0a91c58b81504e21c4943efef254eac"
        }
      ]
    }
  ]
}
