{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.45/contract-0.0.45.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract.klib",
          "url": "contract-iosx64-0.0.45.klib",
          "size": 19078,
          "sha512": "bfe94e4c69ea0f22f61412a491bbdc133e98e08eb6b24561cc4e655f017bdaa2351aa368c5294fe532a29af67a442f8682508008e4899cb65641288e817303c5",
          "sha256": "f05ca53b051fe000e1b81bd90d4e909f935d5d1abdcfc177f2baa08172a30159",
          "sha1": "83a36d790a216c1df13acd5e7eeda8901e6e2acf",
          "md5": "fdc5a8fe5b24e78688a895e60c0f123f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.45/contract-metadata-0.0.45.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.45"
      }
    }
  ]
}
