{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.sk-video",
    "module": "viewmodel",
    "version": "0.0.2_1.0.0-alpha61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-video",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.2_1.0.0-alpha61"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.2_1.0.0-alpha61.jar",
          "url": "viewmodel-0.0.2_1.0.0-alpha61.jar",
          "size": 2284,
          "sha512": "d794ee9584cf1385f04cb113537a78861497d7d13f7922fbbba414a4fb19c7c53445e2c924620014a2012cd714fbf9c38238c56d2d592547a613efd9836e1142",
          "sha256": "41bb5cd7d1ad81c8d68820111cab641f1b905dc9c588ccf2c3b25a133521be4d",
          "sha1": "db653d0f8708da2ddbdf7974bb2ae29a3e9525e0",
          "md5": "8410ab893e738584cd54326f5e81a783"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    }
  ]
}
