{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "jc6y725iebc23nmj56aixso43i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.52.jar",
          "url": "androidTests-0.0.52.jar",
          "size": 261,
          "sha512": "81e1c755fdb81cbb3ef598a8f2141ccedab1b3cd604449587b7e45d10522dcd3e0d899a9a0ffbe36b9d1d21fd37b2cf25eb5f9808df247acc8708f7bf7adca70",
          "sha256": "cd22db740b83adfa2c847c45f3ae3f2c72129c3080734bc5d1a4b093fa7d3222",
          "sha1": "685a696b28b4b810f9a0dcb6954039348507a9ef",
          "md5": "b6eb8aab373f40e96859b8a6e8648af8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.52/androidTests-android-0.0.52.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.52"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.52/androidTests-android-0.0.52.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.52"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.52/androidTests-android-0.0.52.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.52"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.52/androidTests-android-0.0.52.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.52"
      }
    }
  ]
}
