{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.28/androidTests-0.0.28.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.28.jar",
          "url": "androidTests-metadata-0.0.28.jar",
          "size": 261,
          "sha512": "821e09c348c1242c2619fb3d74745376779e6b32cea65463354f4486afbb3b3ca1b8da5ab7587fdb5d2a422ccf2bfaaaec0aa14def3ca84403e1f7a077120bca",
          "sha256": "44098c46c520582c06be41b6542d51cc897fdf14fcd2832e32c8474f27a6a717",
          "sha1": "cc7016d510765d7daf4097a4aaf44adac09fb6e1",
          "md5": "97ef1894fba37ac705154cbf3b0f88af"
        }
      ]
    }
  ]
}
