{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.28/androidTests-0.0.28.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "t2w34ohvabccfdd6l3g4neepp4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.28.jar",
          "url": "androidTests-metadata-0.0.28.jar",
          "size": 261,
          "sha512": "416c3261fea1e9036ac16204d32960c80f320739133165c3047892dd9444dfc3ce5631541c7651d0b78d86260ab60ebb4cdca6e0e69dfa79c5a2079da5bdc79e",
          "sha256": "9f976e8adc9f59408b769305b46b36c236fe40cc9e59d23a94f809f6bc96aa0b",
          "sha1": "90df81017c2c777ca8a746d7879d4a5f2b67907d",
          "md5": "72eebe51a4982d57bf4f20cbbf35463a"
        }
      ]
    }
  ]
}
