{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.sk-tabbar",
    "module": "viewmodel",
    "version": "0.0.1_1.0.0-alpha57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1_1.0.0-alpha57"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.1_1.0.0-alpha57.jar",
          "url": "viewmodel-0.0.1_1.0.0-alpha57.jar",
          "size": 4152,
          "sha512": "265458e0110ec686a42d45fa79d42c4f29434b7d219b9b3e1536b6f28bf065cd246a7798fdc13737ddfb580ff44af613a30803629a5628df648f012fd7287572",
          "sha256": "ee261f0015dd18414f7e51df21ca930aa14457c62e934a2ab5006fc3d8d0da6f",
          "sha1": "582e809a737478c1f3180beac3fee1d02d8ce826",
          "md5": "d7ba7d46f6bdd805bc8a0a415559d8cc"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    }
  ]
}
