{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha7/viewcontract-1.0.0-alpha7.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "vuponvlkt5blhpe5a4symex76e"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha7.klib",
          "size": 26831,
          "sha512": "687bc546d6e0dcc4b879b94216183a78a3d4a6b3f1e9262cb240293e12ae43220be0268b12a0ed4330fb5b68e8216cd5d10bc5df2b7ef034e81afca90c8af2d7",
          "sha256": "ad848aaf9f670a1fcde15c63bdda2e095ed8aa9bfcea793139f4e8fe3e4c467f",
          "sha1": "c7ae11db572a3406bff317fb727dc64dc696462e",
          "md5": "8e927541661f4a77e266f28f5743bd8c"
        }
      ]
    }
  ]
}
