{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.8/viewmodel-0.0.8.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5vu6ywwiijbhlbbtlao5nfwm2q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.8.jar",
          "url": "viewmodel-metadata-0.0.8.jar",
          "size": 5530,
          "sha512": "6634bf02040b3c36e3423491a30adf57c228665b4a4510a61291765704e782a79f6c2eb59ff4cb42fa5d03fceb0fa97f195aec13a413097d8f6e9808ad4ac9c0",
          "sha256": "d20de8e40cbe59dca6c5fe1ad4e509d14a2df76e2929d279510cf3505fcba1df",
          "sha1": "ee74045bcd9df1d4bc5f9fc95482be3fee7445d7",
          "md5": "745eee013933da12e86aeb9c71de6b87"
        }
      ]
    }
  ]
}
