{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.45.jar",
          "url": "generator-0.0.45.jar",
          "size": 94622,
          "sha512": "3941867e8d8e263aaa2791604ce396541c263a091a811965b59e27a441d3e698e890d0666ff28fd3e3de4682427b9f4f1704a5eb04fc90e6156733061e8e30ad",
          "sha256": "d12a5fb3420ca0ecd3e282ef201e98ad1c7df02faed40c8dd370918fe8a6678b",
          "sha1": "e7086a1dffc673a5b509480c8fa57cea746cf39b",
          "md5": "0ec6c37747e16df6d50154937bea27a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.45"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.45.jar",
          "url": "generator-0.0.45.jar",
          "size": 94622,
          "sha512": "3941867e8d8e263aaa2791604ce396541c263a091a811965b59e27a441d3e698e890d0666ff28fd3e3de4682427b9f4f1704a5eb04fc90e6156733061e8e30ad",
          "sha256": "d12a5fb3420ca0ecd3e282ef201e98ad1c7df02faed40c8dd370918fe8a6678b",
          "sha1": "e7086a1dffc673a5b509480c8fa57cea746cf39b",
          "md5": "0ec6c37747e16df6d50154937bea27a6"
        }
      ]
    }
  ]
}
