{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.33/viewmodel-0.0.33.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "dpaczj3htbf6dbuy2gp2yf4ski"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.33"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.33.jar",
          "url": "viewmodel-metadata-0.0.33.jar",
          "size": 7418,
          "sha512": "2d6c403846727fcf3e8523a3c2648cf5ab0bded97078ab01d9ec8559795952668e8cc911986c774a73d9e5e0b7e769250859ed0a7ab48b5621070ba9b3349ae9",
          "sha256": "9b1665271f29eaaff312ad1c3dccbe63a220b9e8b27693793e657d8afa1c5adb",
          "sha1": "0c6ad0bcbebf1358df91fec7a90bd9d04cc14b0c",
          "md5": "61326ce6833ff046b2124b4f309d446c"
        }
      ]
    }
  ]
}
