{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.39/viewmodel-0.0.39.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "wulvo6iqbzfl3evraorhz65oge"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.39"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.39-debug.aar",
          "size": 52425,
          "sha512": "830d56d8cb9a5f2cf0923607ac907ebbbcbd40246a926a689e30c43f0f281a4e6e682b4a3aa9eda3821161d5f78983aeb26e2033f403c18e5f70513648bf5894",
          "sha256": "c5d612efa7881af944be4a19fb74b6e0969b8b39a0476767c3b419069901da53",
          "sha1": "bacdc580d3e1eff9db3407b27c44fb540c112061",
          "md5": "1dc28d7a07bf57b2ca1f8c4f45b5f623"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.39"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.39"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.39-debug.aar",
          "size": 52425,
          "sha512": "830d56d8cb9a5f2cf0923607ac907ebbbcbd40246a926a689e30c43f0f281a4e6e682b4a3aa9eda3821161d5f78983aeb26e2033f403c18e5f70513648bf5894",
          "sha256": "c5d612efa7881af944be4a19fb74b6e0969b8b39a0476767c3b419069901da53",
          "sha1": "bacdc580d3e1eff9db3407b27c44fb540c112061",
          "md5": "1dc28d7a07bf57b2ca1f8c4f45b5f623"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.39"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.39.aar",
          "size": 50806,
          "sha512": "72cb29b9e592c887705af75977ed6fcc56fae2f4fbe46d6c73d39ad0994ba7bb82e27d73545acb08e2229366a72628130e1da7f6f034e038aa39a387db70d009",
          "sha256": "f369baddddbb5f589013bac9131f34e6da3eb4281463bd60a3bc16654ced1238",
          "sha1": "0d65184384d242879364cdc4712e8d0937f59c43",
          "md5": "5f93c57d68eb32605917da511ba97079"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.39"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.39"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.39.aar",
          "size": 50806,
          "sha512": "72cb29b9e592c887705af75977ed6fcc56fae2f4fbe46d6c73d39ad0994ba7bb82e27d73545acb08e2229366a72628130e1da7f6f034e038aa39a387db70d009",
          "sha256": "f369baddddbb5f589013bac9131f34e6da3eb4281463bd60a3bc16654ced1238",
          "sha1": "0d65184384d242879364cdc4712e8d0937f59c43",
          "md5": "5f93c57d68eb32605917da511ba97079"
        }
      ]
    }
  ]
}
