{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.29.jar",
          "url": "generator-0.0.29.jar",
          "size": 93268,
          "sha512": "7fb8369d582b9b54e3c75415d1244676f9f1db6fe8a405974b07e63108c12d48133f03d055bb0b7fe726faf6c065439da5aa7d182cd4eb930f3c5d2f723a1315",
          "sha256": "bafd577966930dc4b099761a87b58f37cb69c8477ae083e5c922a99e234bc6c3",
          "sha1": "0e8308dbe432d7e67dd4c04e3d3d570cbc61bdfc",
          "md5": "d53813d95689c056291c4049a8e147ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.29.jar",
          "url": "generator-0.0.29.jar",
          "size": 93268,
          "sha512": "7fb8369d582b9b54e3c75415d1244676f9f1db6fe8a405974b07e63108c12d48133f03d055bb0b7fe726faf6c065439da5aa7d182cd4eb930f3c5d2f723a1315",
          "sha256": "bafd577966930dc4b099761a87b58f37cb69c8477ae083e5c922a99e234bc6c3",
          "sha1": "0e8308dbe432d7e67dd4c04e3d3d570cbc61bdfc",
          "md5": "d53813d95689c056291c4049a8e147ad"
        }
      ]
    }
  ]
}
