{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.10/core-0.0.10.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-0.0.10-debug.aar",
          "size": 14399,
          "sha512": "c27146c58a9e021c6b8e700ebee2e4661a9d61dfbad77699bb41ef6772b5c1b9b0f8e067f5765af3bef8493796bbb07e5fa8b55c7f0416660e2d7cb5c7a3f55c",
          "sha256": "93abaf4d2ac48440b5250fb6614b7d44c00df12888099d2e9b184021a67c98a6",
          "sha1": "8cd9f5ba3e643a5dae08844de5e046c101118ace",
          "md5": "31900101385861a017594c874f78bd15"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-0.0.10-debug.aar",
          "size": 14399,
          "sha512": "c27146c58a9e021c6b8e700ebee2e4661a9d61dfbad77699bb41ef6772b5c1b9b0f8e067f5765af3bef8493796bbb07e5fa8b55c7f0416660e2d7cb5c7a3f55c",
          "sha256": "93abaf4d2ac48440b5250fb6614b7d44c00df12888099d2e9b184021a67c98a6",
          "sha1": "8cd9f5ba3e643a5dae08844de5e046c101118ace",
          "md5": "31900101385861a017594c874f78bd15"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.0.10.aar",
          "size": 14010,
          "sha512": "5f7f47c144a35eaccb7b723ae7e728f269923b3fe3483612c22434c2a966105ad12214ca39ddef8b8ace1fce2d810f9d65994bfbc14d2647b661e9eb4243a0dc",
          "sha256": "4446108b33618a6ed7489bde52ef6c5742e42d5a17efff76ca4725d072960e05",
          "sha1": "3350423a1fd7b5b9022e725427eae29e492b156d",
          "md5": "2bc9aa350f366bf401f115663cfcba56"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.0.10.aar",
          "size": 14010,
          "sha512": "5f7f47c144a35eaccb7b723ae7e728f269923b3fe3483612c22434c2a966105ad12214ca39ddef8b8ace1fce2d810f9d65994bfbc14d2647b661e9eb4243a0dc",
          "sha256": "4446108b33618a6ed7489bde52ef6c5742e42d5a17efff76ca4725d072960e05",
          "sha1": "3350423a1fd7b5b9022e725427eae29e492b156d",
          "md5": "2bc9aa350f366bf401f115663cfcba56"
        }
      ]
    }
  ]
}
