{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "view-metadata",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.47"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.47.jar",
          "url": "view-metadata-0.0.47.jar",
          "size": 6294,
          "sha512": "98f49dbf6494f1e3918076e5c45138f54e374b607d8d960b7d0db0bbb775fab3404cedc854ad9ec0e59e2d53c2d1e0707ca5c75af3982b6d24ac857e07771043",
          "sha256": "44dda905d7fa68e633dd845123ed0bcd0fe97a4239d3b2355149b59b45d13420",
          "sha1": "8f618ebb99c48f58b82767190d921207b571ec6d",
          "md5": "47d2c12ad72117f04d00332618c9b18c"
        }
      ]
    }
  ]
}
