{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.25/contract-0.0.25.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.25.jar",
          "url": "contract-metadata-0.0.25.jar",
          "size": 7497,
          "sha512": "6e43856901515dccfabba48f8f4e47270003f7e4c6f0294a5936fc5df2f612cad4d2245ddf8609247eb0858f948f23ae9ba9d3a2d8d15338fce58727e6ac264d",
          "sha256": "7521341d037a7a9fa2f05bf0cc6fb74a576ede1cae94d57b3640a52133d2818f",
          "sha1": "2b7cf51d4216444d958ea2822466f9d7e40127ac",
          "md5": "d1618fd82731cf3b97cdd15fce6ea2d6"
        }
      ]
    }
  ]
}
