{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.37/core-0.0.37.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6ad6ifprjjfd5g5alw3qha32pu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.37.jar",
          "url": "core-metadata-0.0.37.jar",
          "size": 5329,
          "sha512": "6fd75fd2887f05cdad39696550f43d5040568b810eaef6730220c0e5939a4fe9068e538212d386402fc4f38250453ec7bff8b83903e03e264d84e56b8743b45f",
          "sha256": "3da10c65b40d64068a2afb61cf5ad164140775bc6dab0c1fdda00430bb424ff0",
          "sha1": "98a8e9d0bda70b5f03cb5d5d52ad5a905410db3f",
          "md5": "acb1fd000d04dee6df4a8626d02f3c34"
        }
      ]
    }
  ]
}
