{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha5/modelcontract-1.0.0-alpha5.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosx64-1.0.0-alpha5.klib",
          "size": 14885,
          "sha512": "5b26369720bdaeeb0e3ffb7c52246c601f95446af2df08ecb75ca1ff0d87a6eecc273416c07f8375c1fc4ed5dacd798a221dc88ae281e31c553f45dc5fadcc95",
          "sha256": "4fd9cedee206952d0ec2c52857afc867da9cae4ca1c37a349f66d392ac585d0a",
          "sha1": "9c97c7d6547210945ff8753fc51c49e7841373cc",
          "md5": "99e052934df5855ec594a2e9c01125d3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../modelcontract-metadata/1.0.0-alpha5/modelcontract-metadata-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "modelcontract-metadata",
        "version": "1.0.0-alpha5"
      }
    }
  ]
}
