{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha4/viewmodel-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha4-debug.aar",
          "size": 40457,
          "sha512": "196ffffbaab8c47d302740b21d56aa8efd297abd3f93dbe71b429357445774fb984bf0e82acc8b7d343f2528c2040b13a4368d67ee2cee771b34f8ea53f9558e",
          "sha256": "f92006f7e55aec4c3946d29f476e188a7f3c2b9282fc835de571de1032780575",
          "sha1": "52c3f4c10f534de4e0c2203084e1930da4beeebb",
          "md5": "feb755fdba181ee4a120677c61548f3b"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha4-debug.aar",
          "size": 40457,
          "sha512": "196ffffbaab8c47d302740b21d56aa8efd297abd3f93dbe71b429357445774fb984bf0e82acc8b7d343f2528c2040b13a4368d67ee2cee771b34f8ea53f9558e",
          "sha256": "f92006f7e55aec4c3946d29f476e188a7f3c2b9282fc835de571de1032780575",
          "sha1": "52c3f4c10f534de4e0c2203084e1930da4beeebb",
          "md5": "feb755fdba181ee4a120677c61548f3b"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha4.aar",
          "size": 38709,
          "sha512": "05d6165320a5250ed5ca12e32d3f4cae13fc2f8403c90c6f6a6e6b3accdce6f04c4db7b89e6c81a31235f9155f75d1c5a4b9d79d9c88b59afd1b05452b036801",
          "sha256": "cb030f41a6599f868a1c7402c4f6d7a1aa3b15a3f00813f15a9948079077216c",
          "sha1": "af726633016e12cc8ebeb1d4691b9c929cbb93c6",
          "md5": "83061c6b0b2bd60a0026afc5dd97087b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha4.aar",
          "size": 38709,
          "sha512": "05d6165320a5250ed5ca12e32d3f4cae13fc2f8403c90c6f6a6e6b3accdce6f04c4db7b89e6c81a31235f9155f75d1c5a4b9d79d9c88b59afd1b05452b036801",
          "sha256": "cb030f41a6599f868a1c7402c4f6d7a1aa3b15a3f00813f15a9948079077216c",
          "sha1": "af726633016e12cc8ebeb1d4691b9c929cbb93c6",
          "md5": "83061c6b0b2bd60a0026afc5dd97087b"
        }
      ]
    }
  ]
}
