{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.36/view-0.0.36.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yghnb2gewvenvmp42l64g7zv3y"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.36.jar",
          "url": "view-metadata-0.0.36.jar",
          "size": 6294,
          "sha512": "b7a260fd9183ebe97c4c71fbeb3c40493e3015de2daad5ef67b6bd19297242cec6497bb75d379934f212617d769650cd1e4cde1a79b98c11253ac897b7a12aa8",
          "sha256": "ac9906be3d4af2342743bf1dba1857feb06d518430643f880a7db1c03d03513e",
          "sha1": "89ce39331c4c17c8f68247e81bc93282e80caf9f",
          "md5": "bbb9d4e24cb359718bdccd4b8e8a7f5f"
        }
      ]
    }
  ]
}
