{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.45.jar",
          "url": "androidTests-0.0.45.jar",
          "size": 261,
          "sha512": "2786b08e1887abe39355c3247d91c794075974015b7a093f130a9f0655c0504af0526e99d6a138ca76d474d292520c3e348dba09220bad3982218f0527704338",
          "sha256": "19387c678f6f8afe30b52823e6e060a517fecef94be455e7213d56a739f6c6a3",
          "sha1": "b4f6d3b1212fda9052715c09ef3f738dd7c12adc",
          "md5": "9dadab31ab0bdffe61f100aaf0b64844"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.45/androidTests-android-0.0.45.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.45"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.45/androidTests-android-0.0.45.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.45"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.45/androidTests-android-0.0.45.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.45"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.45/androidTests-android-0.0.45.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.45"
      }
    }
  ]
}
