{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "umuh4wxdqfdghocu4tjfq6qmxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.43.jar",
          "url": "generator-0.0.43.jar",
          "size": 94663,
          "sha512": "1ada5e681e53fb0f612e3a2d24875b3ea07e473fa27b5e383e300f68197c641e3ca1096d3321e19e6e4f86462449b2a05c79b1e673ef3fa2199dccd2dcb15597",
          "sha256": "9befd552945378a88966e8d2886e4f59bc819cd06db270524184d04c0a3412c0",
          "sha1": "fe513673ff677ba8499924d60ed180368d37ce70",
          "md5": "c803672166e517784b4aeffeba7229f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.43.jar",
          "url": "generator-0.0.43.jar",
          "size": 94663,
          "sha512": "1ada5e681e53fb0f612e3a2d24875b3ea07e473fa27b5e383e300f68197c641e3ca1096d3321e19e6e4f86462449b2a05c79b1e673ef3fa2199dccd2dcb15597",
          "sha256": "9befd552945378a88966e8d2886e4f59bc819cd06db270524184d04c0a3412c0",
          "sha1": "fe513673ff677ba8499924d60ed180368d37ce70",
          "md5": "c803672166e517784b4aeffeba7229f7"
        }
      ]
    }
  ]
}
