{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha20/viewmodel-1.0.0-alpha20.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha20-debug.aar",
          "size": 85048,
          "sha512": "e5f613f600d43ce6808001acb37840eb0dd4caceda454578b3f32cfed0d7b3be537943d05369630a7e0b401ed9fd037a5dcf522619385982f844fb72e4343af0",
          "sha256": "3f28daf4bc2670050e65c454a3651c59ed6f417c13eaaa5a635858ed30406aa5",
          "sha1": "a72c135ac7e4d457ef458f9b15ec1b4f7365383a",
          "md5": "25866d6d5fb3c3e70dcd93394db84abb"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha20-debug.aar",
          "size": 85048,
          "sha512": "e5f613f600d43ce6808001acb37840eb0dd4caceda454578b3f32cfed0d7b3be537943d05369630a7e0b401ed9fd037a5dcf522619385982f844fb72e4343af0",
          "sha256": "3f28daf4bc2670050e65c454a3651c59ed6f417c13eaaa5a635858ed30406aa5",
          "sha1": "a72c135ac7e4d457ef458f9b15ec1b4f7365383a",
          "md5": "25866d6d5fb3c3e70dcd93394db84abb"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha20.aar",
          "size": 81125,
          "sha512": "a169687c7e0849e5d94a331cb37d86d4366e333c11d3988ce019a096bcbb0301ee23a25331414fb54d525ee301c2c94284fb260c4c45fe5ffcc7937b602e39e8",
          "sha256": "16f680343581218ce9074da4c1b5b34ae55ae529c447fd4bc8368519d17bbeaf",
          "sha1": "c7ecd003f4969689642bc8a30182e056ff56e8e3",
          "md5": "b9a2eb100b02de9db1bd091c3791f532"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha20.aar",
          "size": 81125,
          "sha512": "a169687c7e0849e5d94a331cb37d86d4366e333c11d3988ce019a096bcbb0301ee23a25331414fb54d525ee301c2c94284fb260c4c45fe5ffcc7937b602e39e8",
          "sha256": "16f680343581218ce9074da4c1b5b34ae55ae529c447fd4bc8368519d17bbeaf",
          "sha1": "c7ecd003f4969689642bc8a30182e056ff56e8e3",
          "md5": "b9a2eb100b02de9db1bd091c3791f532"
        }
      ]
    }
  ]
}
