{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha26/modelcontract-1.0.0-alpha26.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha26.jar",
          "url": "modelcontract-jvm-1.0.0-alpha26.jar",
          "size": 79809,
          "sha512": "3e0148e52437fa08799e2336045fd92d1d6889100be692d50aac4dbf273418fa1b9a215b12ffd60c0fdaaada9b45c58961b3bd64efcebef925c1a7d7b2d57549",
          "sha256": "ae8549769fc2b6ffe10196e4304d15d59178f700bdd26bc2f6ad0d8e639e5fbc",
          "sha1": "44e0a7e46a458d874e1ace3c8ff28363e240fa51",
          "md5": "26bbd61ff91831818ea998197b661a96"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha26.jar",
          "url": "modelcontract-jvm-1.0.0-alpha26.jar",
          "size": 79809,
          "sha512": "3e0148e52437fa08799e2336045fd92d1d6889100be692d50aac4dbf273418fa1b9a215b12ffd60c0fdaaada9b45c58961b3bd64efcebef925c1a7d7b2d57549",
          "sha256": "ae8549769fc2b6ffe10196e4304d15d59178f700bdd26bc2f6ad0d8e639e5fbc",
          "sha1": "44e0a7e46a458d874e1ace3c8ff28363e240fa51",
          "md5": "26bbd61ff91831818ea998197b661a96"
        }
      ]
    }
  ]
}
