{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha20/modelcontract-1.0.0-alpha20.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha20.jar",
          "url": "modelcontract-jvm-1.0.0-alpha20.jar",
          "size": 57610,
          "sha512": "6d44d6a3fc9bac9b4949a30a1257d258cf09a0f225e120cc0aaa31117c8d6afb4e62a22ab21c01eccb86d856b0193d9356c78351a86a504d584a5b903fd05c9e",
          "sha256": "ac378232ead445436cd9ed20b5f57bfbc5da6c2afdbcf720f68fcd873d76a035",
          "sha1": "b19a6e97f013c31b0c7f31038a593865c4f75015",
          "md5": "964cbfe4c7699d470f4e5db8b2d4767c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha20.jar",
          "url": "modelcontract-jvm-1.0.0-alpha20.jar",
          "size": 57610,
          "sha512": "6d44d6a3fc9bac9b4949a30a1257d258cf09a0f225e120cc0aaa31117c8d6afb4e62a22ab21c01eccb86d856b0193d9356c78351a86a504d584a5b903fd05c9e",
          "sha256": "ac378232ead445436cd9ed20b5f57bfbc5da6c2afdbcf720f68fcd873d76a035",
          "sha1": "b19a6e97f013c31b0c7f31038a593865c4f75015",
          "md5": "964cbfe4c7699d470f4e5db8b2d4767c"
        }
      ]
    }
  ]
}
