{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "r76z3av2pjgf5gaz7k45ehatda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.2.jar",
          "url": "generator-0.0.2.jar",
          "size": 81067,
          "sha512": "d03ff53f9f1f782d36d62c548e6fa007a1f1662ebe56a42c729192afb1e170b2f4c8be13192abcfee36c7b29d996a6f28c5d6e40a09bd47114aed78afb518678",
          "sha256": "e20fdda3fb85599a4542ff88581c636d14f41ea3d0b9f600ff203dd67be5d6a8",
          "sha1": "2c514972994a2cc3773523eab974562fc0962b5c",
          "md5": "5afbc40ae669c1d9eeababb7ab27a5d3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.2.jar",
          "url": "generator-0.0.2.jar",
          "size": 81067,
          "sha512": "d03ff53f9f1f782d36d62c548e6fa007a1f1662ebe56a42c729192afb1e170b2f4c8be13192abcfee36c7b29d996a6f28c5d6e40a09bd47114aed78afb518678",
          "sha256": "e20fdda3fb85599a4542ff88581c636d14f41ea3d0b9f600ff203dd67be5d6a8",
          "sha1": "2c514972994a2cc3773523eab974562fc0962b5c",
          "md5": "5afbc40ae669c1d9eeababb7ab27a5d3"
        }
      ]
    }
  ]
}
