{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.16/model-0.0.16.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "xduo2x3rkbaepe3emobddesovq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.16"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.16.jar",
          "url": "model-metadata-0.0.16.jar",
          "size": 13100,
          "sha512": "26622788829694a37d6e592102e9770ba83e36128fcd28dc9fb4079b27dcea0bf1df29bb7669a9508970d68082e20876245b7bccc3f77dd6061589f2c8deafa4",
          "sha256": "23fdfa37484e79ff6be7873aedf5cde25c395557e8fa2fd34003afe88d396ef2",
          "sha1": "9e9834bcce184db3ea3438277c04cec6d019c93a",
          "md5": "7277a8dd884d2b2bdbe855dc129ab857"
        }
      ]
    }
  ]
}
