{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "4g4dsdf7yvgxndmmqjq6s6i2gm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.31.jar",
          "url": "generator-0.0.31.jar",
          "size": 93268,
          "sha512": "bbc3c2c1196e425c9a91086501ab09f484270a1622ae896c73730f39c474b9e642e121742b761d61c58d5b99bd1482bc3091703406c5135661f5c8e44ebfd28d",
          "sha256": "486e03835bf402b24ffd33481af5437364743cdb07d95c3f6725d9de12349929",
          "sha1": "c2a2ef4307ed481c917816dcc78c8442373aad65",
          "md5": "c76c142243bb34c1a72440399ae1d902"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.31"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.31.jar",
          "url": "generator-0.0.31.jar",
          "size": 93268,
          "sha512": "bbc3c2c1196e425c9a91086501ab09f484270a1622ae896c73730f39c474b9e642e121742b761d61c58d5b99bd1482bc3091703406c5135661f5c8e44ebfd28d",
          "sha256": "486e03835bf402b24ffd33481af5437364743cdb07d95c3f6725d9de12349929",
          "sha1": "c2a2ef4307ed481c917816dcc78c8442373aad65",
          "md5": "c76c142243bb34c1a72440399ae1d902"
        }
      ]
    }
  ]
}
