{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.43/viewmodel-0.0.43.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "umuh4wxdqfdghocu4tjfq6qmxe"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.43-debug.aar",
          "size": 52703,
          "sha512": "d67b2398da086c8874eee233f571661fa288c4935cfb617d2603d4252b720a6d97b5c12a754f6c6a923ba441c34c740c8af993439302da4f59b8382f8406ab39",
          "sha256": "ab9aa6ed1754c9832ede2bee85db6b0a21acc1c003e68f0cc531a9a09aaee158",
          "sha1": "7b315fef1d9ce2158ad12c8c4d94277656cba44c",
          "md5": "56dfbe04b049fda3dfa37a27845b6087"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.43-debug.aar",
          "size": 52703,
          "sha512": "d67b2398da086c8874eee233f571661fa288c4935cfb617d2603d4252b720a6d97b5c12a754f6c6a923ba441c34c740c8af993439302da4f59b8382f8406ab39",
          "sha256": "ab9aa6ed1754c9832ede2bee85db6b0a21acc1c003e68f0cc531a9a09aaee158",
          "sha1": "7b315fef1d9ce2158ad12c8c4d94277656cba44c",
          "md5": "56dfbe04b049fda3dfa37a27845b6087"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.43.aar",
          "size": 51076,
          "sha512": "28a324b0489c7a662783fa7e5552ebbe39f5bf1580986bc7828bf9dfd0a7525e5508d8bdfd918a6f8c57b3fe9a49f5c8e919e2361648cf152bc2287739ccb950",
          "sha256": "18f1807dde7b91e52e911ac5e5f6af08b311f2abdb22ce2c163f8ed9696e2c00",
          "sha1": "304899aba70cc0b8b8be3c0ef8b810485e871147",
          "md5": "f724786b3431613d370a52bc801646c6"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.43.aar",
          "size": 51076,
          "sha512": "28a324b0489c7a662783fa7e5552ebbe39f5bf1580986bc7828bf9dfd0a7525e5508d8bdfd918a6f8c57b3fe9a49f5c8e919e2361648cf152bc2287739ccb950",
          "sha256": "18f1807dde7b91e52e911ac5e5f6af08b311f2abdb22ce2c163f8ed9696e2c00",
          "sha1": "304899aba70cc0b8b8be3c0ef8b810485e871147",
          "md5": "f724786b3431613d370a52bc801646c6"
        }
      ]
    }
  ]
}
