{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.52/core-0.0.52.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "jc6y725iebc23nmj56aixso43i"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.52.jar",
          "url": "core-jvm-0.0.52.jar",
          "size": 17732,
          "sha512": "a0896cd9c6da295ce070f2e0f3e1261c01b223c01456dc926b61f9369dbe506b17c19c4b9eb44d78e1703f59f15999c89bf65464f823f31e5827e93bc1c2a2ad",
          "sha256": "577cd6c37464fe3e22c958b9519bf94b5ebdf2b3f6e4074b59cd0fb9e3014a28",
          "sha1": "dc054283353d39e6b7a249375361a59723b05d4b",
          "md5": "d4ac391102e3706d4bd7c6c9826752ad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.52.jar",
          "url": "core-jvm-0.0.52.jar",
          "size": 17732,
          "sha512": "a0896cd9c6da295ce070f2e0f3e1261c01b223c01456dc926b61f9369dbe506b17c19c4b9eb44d78e1703f59f15999c89bf65464f823f31e5827e93bc1c2a2ad",
          "sha256": "577cd6c37464fe3e22c958b9519bf94b5ebdf2b3f6e4074b59cd0fb9e3014a28",
          "sha1": "dc054283353d39e6b7a249375361a59723b05d4b",
          "md5": "d4ac391102e3706d4bd7c6c9826752ad"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/0.0.52/core-metadata-0.0.52.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "0.0.52"
      }
    }
  ]
}
