{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.44/model-0.0.44.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i7olmwxatfdhths5wu7quwrrny"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.44.jar",
          "url": "model-metadata-0.0.44.jar",
          "size": 13116,
          "sha512": "474f903794e217139009675645797e2992784f27536f140cd9fdbdeebd884316ed10dd4031c43c16502cf358dc188d9d83edcc0bc9e0dd2c242716eed8901d98",
          "sha256": "a406328449a843641cc8e240619c803bfa41be59c6ae86c75172296d9643b75a",
          "sha1": "1242b4f8555ed1bc448e34213b9fcd83f59a858a",
          "md5": "1cd56259155898ef5322074c3de3f317"
        }
      ]
    }
  ]
}
