{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.7/contract-0.0.7.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "igasumkhiveslbdlejoqxrssj4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.7.jar",
          "url": "contract-jvm-0.0.7.jar",
          "size": 15654,
          "sha512": "dc2b433854289354ecae445f28d296fea3069db2ad37181f3f88ab07900a11883e70612f69139d10c7570e520a7c06966c94ed073f8d598d0c4dc81a10dd697d",
          "sha256": "139ec8d74ffcb3956b7ee5ded2b2848b9c874f91c29639fa0d8beb25b591c8c6",
          "sha1": "89f117ddab715129453f0d54ea54a332072fc925",
          "md5": "c0e25f917b1658bbf3c71e95eb2a4e41"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.7.jar",
          "url": "contract-jvm-0.0.7.jar",
          "size": 15654,
          "sha512": "dc2b433854289354ecae445f28d296fea3069db2ad37181f3f88ab07900a11883e70612f69139d10c7570e520a7c06966c94ed073f8d598d0c4dc81a10dd697d",
          "sha256": "139ec8d74ffcb3956b7ee5ded2b2848b9c874f91c29639fa0d8beb25b591c8c6",
          "sha1": "89f117ddab715129453f0d54ea54a332072fc925",
          "md5": "c0e25f917b1658bbf3c71e95eb2a4e41"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.7/contract-metadata-0.0.7.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.7"
      }
    }
  ]
}
