{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "43amt7eqbfabtkb5q6646kb3hm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.17.jar",
          "url": "generator-0.0.17.jar",
          "size": 92130,
          "sha512": "5f8e9c9d3b848997c659c57a954bc877424ee399bd415d70a74cb1de9243be2c67f543938944dfa4adf3a814d31f4917ddc8b82191778f55cf6402bcd52ab9b0",
          "sha256": "3ee888b37640c0a17cba33b6b8826145d0c7e38860a2e55b0b68ec9efab3b0c7",
          "sha1": "b1a5da8d880ac284a1c8af5582c2e33298b183d1",
          "md5": "b8d4a63abaebb33ff8826be5171e506b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.17"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.17.jar",
          "url": "generator-0.0.17.jar",
          "size": 92130,
          "sha512": "5f8e9c9d3b848997c659c57a954bc877424ee399bd415d70a74cb1de9243be2c67f543938944dfa4adf3a814d31f4917ddc8b82191778f55cf6402bcd52ab9b0",
          "sha256": "3ee888b37640c0a17cba33b6b8826145d0c7e38860a2e55b0b68ec9efab3b0c7",
          "sha1": "b1a5da8d880ac284a1c8af5582c2e33298b183d1",
          "md5": "b8d4a63abaebb33ff8826be5171e506b"
        }
      ]
    }
  ]
}
