{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.40/model-0.0.40.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "vudukgf34fdc3murg37da3g47e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.40"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.40.jar",
          "url": "model-metadata-0.0.40.jar",
          "size": 13166,
          "sha512": "ef933c97bc1c9cb8888a605dd7acd94bd0f4e567b01d9fb6f40fe9c31b32a1d45fcc0fbb7ec9d01a957b27cff6547f8c1a473e9702bdd68d660ff141f159790c",
          "sha256": "e60d90eeec6ce32c5c2493c78ecd23f28a6390134f9fc5e13238d8e4e0504e28",
          "sha1": "e48b58c18db0429a37009a35896273aa0338ef58",
          "md5": "b12f3bd9f555057627772e1f69420a1a"
        }
      ]
    }
  ]
}
