{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha23/modelcontract-1.0.0-alpha23.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha23.jar",
          "url": "modelcontract-jvm-1.0.0-alpha23.jar",
          "size": 79211,
          "sha512": "da2fe81ec3a05e0e81051cdc82bca08fe85af6cc192429d34cab91bd4ed397ec65b01da8e2fd0df246de5029deef6f24a715840fc7e11a18eacf2dc33f6e1428",
          "sha256": "30b9a820a1ebff9fca93ea09b556d2cdd2d149ac947bdde11321d0c8a418b3c6",
          "sha1": "ec1170c597d88dc45a7f6299daf608307d36b693",
          "md5": "d3f8673ed5c01236be5447651936dd2d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha23.jar",
          "url": "modelcontract-jvm-1.0.0-alpha23.jar",
          "size": 79211,
          "sha512": "da2fe81ec3a05e0e81051cdc82bca08fe85af6cc192429d34cab91bd4ed397ec65b01da8e2fd0df246de5029deef6f24a715840fc7e11a18eacf2dc33f6e1428",
          "sha256": "30b9a820a1ebff9fca93ea09b556d2cdd2d149ac947bdde11321d0c8a418b3c6",
          "sha1": "ec1170c597d88dc45a7f6299daf608307d36b693",
          "md5": "d3f8673ed5c01236be5447651936dd2d"
        }
      ]
    }
  ]
}
