{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.1/view-0.0.1.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zk7tjfukpff7tmn3tiqtxdfuzy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.1.jar",
          "url": "view-metadata-0.0.1.jar",
          "size": 5556,
          "sha512": "a34f5c122928f61dd75cb168ed3544b163e67d2b9b044a46adbb428793c2ccbd2ede0cc30f713883fd5a3a1790f31ead4193aa4ce185ae7c34e03c78f5306b7c",
          "sha256": "1dd04a6fc73af07318aa9bbe34ac7d191248978207a34e2df7fea3d8624863a5",
          "sha1": "76c46f17cfb7b0e062563fb670bf6b550e6ce915",
          "md5": "4099a3c616c2fa86ab0797dd615ac075"
        }
      ]
    }
  ]
}
