{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.sk-video",
    "module": "viewmodel",
    "version": "0.0.1_1.0.0-alpha57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-video",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1_1.0.0-alpha57"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.1_1.0.0-alpha57.jar",
          "url": "viewmodel-0.0.1_1.0.0-alpha57.jar",
          "size": 2284,
          "sha512": "835cf7367564d6e4535c2c4353f3d7bb427df67e68d320ba1c6ae6e74c40b68808be8c07d03e39c0cb5bd4b15eec2e84fb39cb675c91188490aed654a65c7c24",
          "sha256": "d99abe596e50a6f71f0b91277fa25b2759e16893b13b6dce74a947d29e0afecc",
          "sha1": "7a859a0f4c5924f6a23bfe15532fb9d6ab7b9e3c",
          "md5": "88597147df687b9ce1c05005818dc794"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.1_1.0.0-alpha57/viewmodel-android-0.0.1_1.0.0-alpha57.module",
        "group": "com.github.skot-framework.sk-video",
        "module": "viewmodel-android",
        "version": "0.0.1_1.0.0-alpha57"
      }
    }
  ]
}
