{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha15/modelcontract-1.0.0-alpha15.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha15.jar",
          "url": "modelcontract-jvm-1.0.0-alpha15.jar",
          "size": 57086,
          "sha512": "e78ca6fa43b7ac0b400c742e1972d08242f64e2533548a10103be6821282a9ee7c68cb0deaa479a6467af3c3c853d0617c6da25bca441dc6bd6331fd60250b70",
          "sha256": "e7e50c10df42be9ae81dc6f68a8c51775c250f299d6161db216b875792070327",
          "sha1": "213d98483dde345ee4489cd901839123e9dcc5a1",
          "md5": "654826813433ed45a9370d4c2d033c7c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha15.jar",
          "url": "modelcontract-jvm-1.0.0-alpha15.jar",
          "size": 57086,
          "sha512": "e78ca6fa43b7ac0b400c742e1972d08242f64e2533548a10103be6821282a9ee7c68cb0deaa479a6467af3c3c853d0617c6da25bca441dc6bd6331fd60250b70",
          "sha256": "e7e50c10df42be9ae81dc6f68a8c51775c250f299d6161db216b875792070327",
          "sha1": "213d98483dde345ee4489cd901839123e9dcc5a1",
          "md5": "654826813433ed45a9370d4c2d033c7c"
        }
      ]
    }
  ]
}
