{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.26.jar",
          "url": "generator-0.0.26.jar",
          "size": 92834,
          "sha512": "ab47710a41391b452741d91dc0b0710c731a9be2f66f5fce9cdef87395a0da3bb28a711f958880e6f842e39da5eef1a94fb281218081eb877be5472a9e51a8ef",
          "sha256": "c1f4aaad3b945b6e61e380abb84d7953438b8599a29dec7001d4d7e0888b15ab",
          "sha1": "97410a80305540d0e94f20c0d199a9eec188c550",
          "md5": "7938e4ba3fce6d9804b8f5f826471099"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.26.jar",
          "url": "generator-0.0.26.jar",
          "size": 92834,
          "sha512": "ab47710a41391b452741d91dc0b0710c731a9be2f66f5fce9cdef87395a0da3bb28a711f958880e6f842e39da5eef1a94fb281218081eb877be5472a9e51a8ef",
          "sha256": "c1f4aaad3b945b6e61e380abb84d7953438b8599a29dec7001d4d7e0888b15ab",
          "sha1": "97410a80305540d0e94f20c0d199a9eec188c550",
          "md5": "7938e4ba3fce6d9804b8f5f826471099"
        }
      ]
    }
  ]
}
