{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.50/contract-0.0.50.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h2qswlibvbgzncub57ri5633aa"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract.klib",
          "url": "contract-iosx64-0.0.50.klib",
          "size": 15677,
          "sha512": "e5db84e84a120e92ea4eafcb39500c62a2afdb5ada7c78b87735b7122f7d343cc05f2712563cfa67cb847620a689ec4aa0d01d4cf735cf27addf01b2ac91133e",
          "sha256": "40a5bc0f8114d546b8bc046d73cacafd2728d0145d469a491598c78a8ce1f1bb",
          "sha1": "022b7169f87fc297407c213fb0f1b26c72133b49",
          "md5": "ab82639fe610e5e43140ab5f360e9a9f"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.50/contract-metadata-0.0.50.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.50"
      }
    }
  ]
}
