{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.43/core-0.0.43.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "umuh4wxdqfdghocu4tjfq6qmxe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.43.jar",
          "url": "core-metadata-0.0.43.jar",
          "size": 5341,
          "sha512": "ca4428607ea474f2e5ff40a2d94e076aa6dbd0fed5c854becbc62882eae503346952e369cae454f16c73a968c0150451565d91b067e51b06ce27d8ca335ef04c",
          "sha256": "97d1672b8c3b9b35b10ae74fcdbf359abb25d9128275b55923c7711d3c93d20a",
          "sha1": "b2110d9f3ceb8840d8a9ad51609e43e6facd80d0",
          "md5": "af5e1a9c4e7e38ade5acd1f49ae6680c"
        }
      ]
    }
  ]
}
