{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha6/viewmodel-1.0.0-alpha6.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha6-debug.aar",
          "size": 43987,
          "sha512": "484fe3dbd761e89ddcf85ef523b220b589979d424311cbf0483e6fe09a306ec8ef32de3fc862dd1063b410f8c55f1b54f413351fb53ad6faca09bd9276d2c844",
          "sha256": "867eb43b4df7d62adbb9384841e960093dfa3fefe79baa3b61a3cb85e982f0f6",
          "sha1": "31cb1c29ac59d22fb3b7b15a877838e8f14bf24b",
          "md5": "78fbb2caa0709f793961ba636b1921e8"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha6-debug.aar",
          "size": 43987,
          "sha512": "484fe3dbd761e89ddcf85ef523b220b589979d424311cbf0483e6fe09a306ec8ef32de3fc862dd1063b410f8c55f1b54f413351fb53ad6faca09bd9276d2c844",
          "sha256": "867eb43b4df7d62adbb9384841e960093dfa3fefe79baa3b61a3cb85e982f0f6",
          "sha1": "31cb1c29ac59d22fb3b7b15a877838e8f14bf24b",
          "md5": "78fbb2caa0709f793961ba636b1921e8"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha6.aar",
          "size": 42036,
          "sha512": "92b1394b83c65e6ca15bb4efa480d923c9d63afee3502e919f4464f4a4bf99c810f2d4031b3b7ce1598c8f4833738003f95bb6ea389e92c1351c757051664574",
          "sha256": "e87686ca30b3da590d20e475a0892dbbcbc76c97c35b07eeb405eddbeff41332",
          "sha1": "5da9fbc8039fc3b8f22ba0b2813da2fdc6387bf6",
          "md5": "0b680e629c899f41c6dae85c11a796a5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha6.aar",
          "size": 42036,
          "sha512": "92b1394b83c65e6ca15bb4efa480d923c9d63afee3502e919f4464f4a4bf99c810f2d4031b3b7ce1598c8f4833738003f95bb6ea389e92c1351c757051664574",
          "sha256": "e87686ca30b3da590d20e475a0892dbbcbc76c97c35b07eeb405eddbeff41332",
          "sha1": "5da9fbc8039fc3b8f22ba0b2813da2fdc6387bf6",
          "md5": "0b680e629c899f41c6dae85c11a796a5"
        }
      ]
    }
  ]
}
