{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.32/model-0.0.32.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6qssia3r7rbwpb5cs5jxxg4cpy"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.32-debug.aar",
          "size": 94323,
          "sha512": "0a67bc4b6b588affac82cd11be4e8848ac78d4de3e31d26c4c7519417a76c30fc5819c1a9b93a567e646b4b8a84f35114632cfe60709b3d93bf1525164fe3126",
          "sha256": "1b2f482691be50dc05ecd8ce5eadf2e76185b376a24eb932303947d6bf8bb229",
          "sha1": "3ede26a41fd1dc0c6071e7e38343d53dd021486f",
          "md5": "4c9a3759f9ef2aea7672956561bacee8"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.32-debug.aar",
          "size": 94323,
          "sha512": "0a67bc4b6b588affac82cd11be4e8848ac78d4de3e31d26c4c7519417a76c30fc5819c1a9b93a567e646b4b8a84f35114632cfe60709b3d93bf1525164fe3126",
          "sha256": "1b2f482691be50dc05ecd8ce5eadf2e76185b376a24eb932303947d6bf8bb229",
          "sha1": "3ede26a41fd1dc0c6071e7e38343d53dd021486f",
          "md5": "4c9a3759f9ef2aea7672956561bacee8"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.32.aar",
          "size": 90424,
          "sha512": "d71d439c5f0415db7354ce176d815f2d885bab7dee7fcc672d66746902e5c92d6f360aa29e7de75d1c4f4f1e43da6b6be52ab0b81062747541322dbed0a2cd4f",
          "sha256": "2aa93ebe825a700b98df4267a0f418862b6e33f38d52d764b523f9c1e3c1f015",
          "sha1": "a63eabd26aaf5fba0b7ea8d74652d3c96fa586d1",
          "md5": "27866173fddd5e37574ca87eadf9969b"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.32"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.32.aar",
          "size": 90424,
          "sha512": "d71d439c5f0415db7354ce176d815f2d885bab7dee7fcc672d66746902e5c92d6f360aa29e7de75d1c4f4f1e43da6b6be52ab0b81062747541322dbed0a2cd4f",
          "sha256": "2aa93ebe825a700b98df4267a0f418862b6e33f38d52d764b523f9c1e3c1f015",
          "sha1": "a63eabd26aaf5fba0b7ea8d74652d3c96fa586d1",
          "md5": "27866173fddd5e37574ca87eadf9969b"
        }
      ]
    }
  ]
}
