{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.26/androidTests-0.0.26.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.26.jar",
          "url": "androidTests-metadata-0.0.26.jar",
          "size": 261,
          "sha512": "b8cbdcb6fd4e09986ad8b6d4d9ce226b1f44816eb0833bf573f1d84954da4cbf1e111bea0684ca4007b7811601ee0b9511b55c5d8b4585ef4f3135374f8fd9a3",
          "sha256": "44d663f07f0ad5a1d00ee6e123ab5e54def5cfb50c08ac6a3467296f153bcc54",
          "sha1": "f807bb48af017512e4efb0a6e18eaf3ce5cfc163",
          "md5": "3b3fbd5619e3096ba4a235fa412b7348"
        }
      ]
    }
  ]
}
