{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.35/contract-0.0.35.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "giu2xg36zfb4vbk5yuetpxzity"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.35.jar",
          "url": "contract-metadata-0.0.35.jar",
          "size": 8039,
          "sha512": "dbc995b2dc8c4b4470f33bef332fbe28bcf56f2f13ae4fff692c8484887fc0bbf53f8148dda04c5ccc34a2978abe8de16da9f200cd54b7aca4c02ae1b0990a73",
          "sha256": "bb59f9726ee6bc63283e26314b054bc616073231f587ebf25b18852d5c52af5d",
          "sha1": "22b13efc6cc8367404edf9c276380ef8fc6998c2",
          "md5": "f9a5b6138359f1ae168dae19975461ba"
        }
      ]
    }
  ]
}
