{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.11/view-0.0.11.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.11"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.11.jar",
          "url": "view-metadata-0.0.11.jar",
          "size": 5556,
          "sha512": "387e24fb879986641d48b30ac5a898696e485c7e7e2fd956388a8a90937f10b2883383e2378d993c6d4b27c35e4c00fc5d9ed155e769fd9f368ca0256bdcdfe3",
          "sha256": "b6b7bbfba20c58308f1f4a4e82193f898d8dedaceac7f7f220c6b59265145670",
          "sha1": "40c376ec5de9a3d7ffa7cfc0455f2d41d4c3174d",
          "md5": "03979072d043fa893e990cc22a14026c"
        }
      ]
    }
  ]
}
