{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "7g7z7ezk5vaxvor6gqfcljloxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha11.jar",
          "url": "generator-1.0.0-alpha11.jar",
          "size": 118366,
          "sha512": "bf4a39726c8d7f3eaa665a0b65eae22cfb2f1b08352b88893260d495ebfe3df5d23eda907fa2e6218e435b6ec69e1dac1593efcef20472b88042d1f3c90eca5c",
          "sha256": "4c2e1112e9d6dedb291bd48b31449de5abad4988b83e431bf9cac2efb3a0f9eb",
          "sha1": "46499904bca1e4d10a5d4d7d73a0f3f028c1fe0d",
          "md5": "13291851fc2d589f03a8b6b7ad33d890"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha11.jar",
          "url": "generator-1.0.0-alpha11.jar",
          "size": 118366,
          "sha512": "bf4a39726c8d7f3eaa665a0b65eae22cfb2f1b08352b88893260d495ebfe3df5d23eda907fa2e6218e435b6ec69e1dac1593efcef20472b88042d1f3c90eca5c",
          "sha256": "4c2e1112e9d6dedb291bd48b31449de5abad4988b83e431bf9cac2efb3a0f9eb",
          "sha1": "46499904bca1e4d10a5d4d7d73a0f3f028c1fe0d",
          "md5": "13291851fc2d589f03a8b6b7ad33d890"
        }
      ]
    }
  ]
}
