{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha11.jar",
          "url": "generator-1.0.0-alpha11.jar",
          "size": 118366,
          "sha512": "c2a12e5c8dde774f5560ed23bd3d7ef11f8b6e2561a6178a1c285c006c8c959c6fd9fcebc6b6f6c834507ef76814e2a2ce1aeab2795e5da59b87225a733f3e7d",
          "sha256": "86022eda09292474ffdbad1488b20859333679ba1b8910410267661b6c4614ac",
          "sha1": "1f04d2da51d9bc088517ecaeccf2574912f9e009",
          "md5": "e3a6c90fc277d7224fd9e349dab99e5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha11.jar",
          "url": "generator-1.0.0-alpha11.jar",
          "size": 118366,
          "sha512": "c2a12e5c8dde774f5560ed23bd3d7ef11f8b6e2561a6178a1c285c006c8c959c6fd9fcebc6b6f6c834507ef76814e2a2ce1aeab2795e5da59b87225a733f3e7d",
          "sha256": "86022eda09292474ffdbad1488b20859333679ba1b8910410267661b6c4614ac",
          "sha1": "1f04d2da51d9bc088517ecaeccf2574912f9e009",
          "md5": "e3a6c90fc277d7224fd9e349dab99e5b"
        }
      ]
    }
  ]
}
