{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.13/contract-0.0.13.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "kwtsmjyvlzbw3aguhyqjzuuf5m"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.13.jar",
          "url": "contract-metadata-0.0.13.jar",
          "size": 7170,
          "sha512": "238f931b8d14f69de019e81ea7bccbb505828a8ad865169f4d5b821062cd00307b7adb48ce6d02e1c44752bb0a6cbfe3dba7567efba03d0a6a228367dc0cf0bb",
          "sha256": "576f8389c008d760d0c025063082608b1360c164a61f3c51288284bdc5f80d0b",
          "sha1": "3a5c98f652414dd00ff9b9706a26a11d449f98d7",
          "md5": "e1a1f8403ac481bc940a0ba3b9b090ba"
        }
      ]
    }
  ]
}
