{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "vuponvlkt5blhpe5a4symex76e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha7"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha7"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha7"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha7.jar",
          "url": "viewmodel-1.0.0-alpha7.jar",
          "size": 8275,
          "sha512": "73c7053d4c1fbef03fac8b3e6848aded736565784d5c97d58d5003888d95474c194c65f59b5a6915f8607432ef70f0b2ca17063aa5e47c6db0e48382534183c2",
          "sha256": "ad98096fdee19a3b33a89652675c7835c49e3658591c7ae068068292cf4a0dee",
          "sha1": "087309ffa804c73bde9b59c50c631b238c326a5a",
          "md5": "8602087592a3a8566304e4cc26bb6364"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha7/viewmodel-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha7/viewmodel-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha7/viewmodel-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha7/viewmodel-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha7"
      }
    }
  ]
}
