{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha18/modelcontract-1.0.0-alpha18.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha18.jar",
          "url": "modelcontract-jvm-1.0.0-alpha18.jar",
          "size": 57610,
          "sha512": "f1d99308ee07f78819a4355d1fbc5323ced91ba982ba88dfaff7ae3b454be8be07d581281f70cade3042c2d75991fd7098eb08605d6155f6ca411940e61c59f9",
          "sha256": "a809232f63d378dc6115b4fe25a3750718754580d99b7275d75304c189fe7eb2",
          "sha1": "34d967892dae2ae5f11d3866ddcc46381efbc34e",
          "md5": "38ab8de391b7aeb605d22f5fe1f76d78"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha18.jar",
          "url": "modelcontract-jvm-1.0.0-alpha18.jar",
          "size": 57610,
          "sha512": "f1d99308ee07f78819a4355d1fbc5323ced91ba982ba88dfaff7ae3b454be8be07d581281f70cade3042c2d75991fd7098eb08605d6155f6ca411940e61c59f9",
          "sha256": "a809232f63d378dc6115b4fe25a3750718754580d99b7275d75304c189fe7eb2",
          "sha1": "34d967892dae2ae5f11d3866ddcc46381efbc34e",
          "md5": "38ab8de391b7aeb605d22f5fe1f76d78"
        }
      ]
    }
  ]
}
