{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xev66rvdfzgj5boulrz2n5qhre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.1.jar",
          "url": "generator-0.0.1.jar",
          "size": 81067,
          "sha512": "89c207ebb5f4cfbdf25bb602bab9cf2ffbe5f8a87c28a5f0d01cd655bb51845becd3f091e45b2013daf96d71f9b5c9939a6882edf6c5f077744e78522b87ce58",
          "sha256": "4d4ca47bdedf32f4e29e45e9c057ba80451891c6bdd8b7c7bda3faff18959d9",
          "sha1": "a0ac0ff244d82c5702c9947d0005842b79376a8b",
          "md5": "838218f8c24c7785a75c9aad30162ff9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.1.jar",
          "url": "generator-0.0.1.jar",
          "size": 81067,
          "sha512": "89c207ebb5f4cfbdf25bb602bab9cf2ffbe5f8a87c28a5f0d01cd655bb51845becd3f091e45b2013daf96d71f9b5c9939a6882edf6c5f077744e78522b87ce58",
          "sha256": "4d4ca47bdedf32f4e29e45e9c057ba80451891c6bdd8b7c7bda3faff18959d9",
          "sha1": "a0ac0ff244d82c5702c9947d0005842b79376a8b",
          "md5": "838218f8c24c7785a75c9aad30162ff9"
        }
      ]
    }
  ]
}
