{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.47.jar",
          "url": "viewmodel-0.0.47.jar",
          "size": 7429,
          "sha512": "e68516b5ea907b3e9eab9d77baa07cf8b0e3462cb99904c9a7a4821869bb1ac5e23cc8dc3831b4e1c20d145343256028d46694c8375fb88e8035a4c79288704b",
          "sha256": "53d07e78ab08b4eac87d111f26a3c34baf7a3dc52b718d6aeab64d21e9796db0",
          "sha1": "e0320546111c219c3f2a7bbc20ad314299aa70ce",
          "md5": "2d9e8d04a538799f49a588c1500c7eea"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.47/viewmodel-android-0.0.47.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.47"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.47/viewmodel-android-0.0.47.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.47"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.47/viewmodel-android-0.0.47.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.47"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.47/viewmodel-android-0.0.47.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.47"
      }
    }
  ]
}
