{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.23/view-0.0.23.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h626lwyzk5cqpjrywyt6pslmqm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.23"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.23.jar",
          "url": "view-metadata-0.0.23.jar",
          "size": 6291,
          "sha512": "e0873bb807b7a2473a6f5a0685982721fcb7a953481c25f31770c071a635b5af4092827154859fda643f59a739cd05c7f2f31a7eb3fd2ba917967c3f999bd68e",
          "sha256": "8324f8274fd62509cc92c67337a25a813507e02beb95259b21e38dfbbff490d6",
          "sha1": "5f5ef4188014e8d0d9616ca02d29d87764f9a69c",
          "md5": "dbf551553773961c9091d2b272d573b2"
        }
      ]
    }
  ]
}
