{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.24/model-0.0.24.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "outl7uxctrgmfpv6znqczvsuxy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.24.jar",
          "url": "model-metadata-0.0.24.jar",
          "size": 13118,
          "sha512": "9ba54eed0dd18288ca41aeb39f389aa9d5f395c3c5e372947c43c3b0414af2c42665b2ed34fe6b9ef1be6ffba40b6fc99efae11e0a0d161dbb646b6fb0158464",
          "sha256": "e72417000dbcef27d0c13c3a9c0928d5c2ab409d356d7e2d2911421674b5d158",
          "sha1": "ec08c5e6aeb5529476f97d5ec7dfcf1661bc5887",
          "md5": "0b473ee730b1d3b22ade14f0ea829279"
        }
      ]
    }
  ]
}
