{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "wulvo6iqbzfl3evraorhz65oge"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.39.jar",
          "url": "generator-0.0.39.jar",
          "size": 94663,
          "sha512": "b59a55d164feb5033fe8daebd28fe646387f2c8c8883f70bcb0ac21a8095bad2d9785e942fb2b637ae7928f4607793a988b9d88a06eb4ffc28e04bdf6203b120",
          "sha256": "6a1f2a6ea02ae49f3f9c13ac3caedb594b44b7a9f8197e2b08806055b0c54047",
          "sha1": "250aa085a2d9350c783f4c2a4356fa7341570103",
          "md5": "f23514047109ce6879f5960d0757fe48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.39"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.39.jar",
          "url": "generator-0.0.39.jar",
          "size": 94663,
          "sha512": "b59a55d164feb5033fe8daebd28fe646387f2c8c8883f70bcb0ac21a8095bad2d9785e942fb2b637ae7928f4607793a988b9d88a06eb4ffc28e04bdf6203b120",
          "sha256": "6a1f2a6ea02ae49f3f9c13ac3caedb594b44b7a9f8197e2b08806055b0c54047",
          "sha1": "250aa085a2d9350c783f4c2a4356fa7341570103",
          "md5": "f23514047109ce6879f5960d0757fe48"
        }
      ]
    }
  ]
}
