{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.20/model-0.0.20.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2r2ojxqr5ffvpf4fmosdnmnn7i"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.20.jar",
          "url": "model-metadata-0.0.20.jar",
          "size": 13100,
          "sha512": "3a75d7a86e28fe748b919458455d92543a7cd3dd1d3957908d986d5cb9ce71c0574f032e0d68085268a9d4e39fb6b604e85e9ba82a3bf9050bccab3809de62e5",
          "sha256": "c92988bf6983138e96c31d90c77471503f73f569a19008496e35d40d2c8a7254",
          "sha1": "975e432ef435ac31c83a05e5af928fade5eab2de",
          "md5": "13134de9406d135cc24c319a3d6bf79f"
        }
      ]
    }
  ]
}
