{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.40/androidTests-0.0.40.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "vudukgf34fdc3murg37da3g47e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.40.jar",
          "url": "androidTests-metadata-0.0.40.jar",
          "size": 261,
          "sha512": "c0d281c7bf85937d3bba5250b74ef778b4fa74266d6407dd7b2b329b41047fca7b90afd4af01b46fc794edb77598fc2e449921760e0761e986660f516afcbff4",
          "sha256": "fcbe7fe234f9e1906f6e45c3f9035595e14d720519363ba130d196a8c215b3f6",
          "sha1": "b5f6ede548fb644664c83242a451399c81f73dc1",
          "md5": "d43f2cdde4ddcb202b79639ea588c66a"
        }
      ]
    }
  ]
}
