{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.18/view-0.0.18.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "nrva6vite5hrni2xsf6nk6q4ge"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.18"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.18.jar",
          "url": "view-metadata-0.0.18.jar",
          "size": 6033,
          "sha512": "b22db7dada6f316ca210d47d6aa0ae240a7754fa9e78c17ec68e6474fd8ce8b9cd6ea83f5a00eca687fe4c975f261a49ef3cc6c4445a1742416db20f1454b667",
          "sha256": "4ed7ba392a6770ba77228456d45a42271f142d83f68602271882861e1bdb59ec",
          "sha1": "52bdc1042448dd6c00648cc7df489edcdc42334e",
          "md5": "dc0fe307628240f2d83e46a8e5b3e58a"
        }
      ]
    }
  ]
}
