{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rcsqc6iufne5ve6vpfzg2hyyae"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.51.jar",
          "url": "viewmodel-0.0.51.jar",
          "size": 7431,
          "sha512": "85b9d27d8e2dcb14122ef205bd9fd36d0e7472155444b5cb1cde5b411936981a16a4b9029d1700773c16245b137606545a5c85b1332f67abf45f14bcae6652d1",
          "sha256": "8dd395115350abe55090aca504ee9855df4cdc59f574a503e8851483fba22b52",
          "sha1": "15a474999e38c67b7bc7da932772ca06310bc872",
          "md5": "08805dae6d74c3d4e847f730089b94b8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.51/viewmodel-android-0.0.51.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.51/viewmodel-android-0.0.51.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.51/viewmodel-android-0.0.51.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.51/viewmodel-android-0.0.51.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.51"
      }
    }
  ]
}
