{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-jvm/0.0.48/core-jvm-0.0.48.module",
    "group": "tech.skot",
    "module": "core-jvm",
    "version": "0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "adu4mcp7tnfvfaxt3d3ep6dpwa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.48.jar",
          "url": "core-metadata-0.0.48.jar",
          "size": 5341,
          "sha512": "499495184ad37b2429dd11064ddd97819897fa4d9c7499b52a2eea0d9e19e1410b43c233d21a481d188bb21dbe78c47e87643849d6e549565af1dc71fedcd5c2",
          "sha256": "91c79885e13f8f5b7e344c85d37a2001ad50d955684267e4a6a96ea4e89913d0",
          "sha1": "fc8ccf2b1913bb9382dcabf2f28e9dc1174d568d",
          "md5": "abcc62e8f3c4fb463d61abdbda072822"
        }
      ]
    }
  ]
}
