{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-metadata-1.0.0-alpha25.jar",
          "url": "modelcontract-1.0.0-alpha25.jar",
          "size": 6228,
          "sha512": "5b984fe155cd85a125f21fab87ab7f5cd8792f91ac25f73bc4136a4118c4c7541af9c08b86d7b45c7dcd021f8cc02ebd7d9aee9976f407ccfd7616e4e50abd20",
          "sha256": "0c0016965e0a434b604918c3906efd716500c0474d15f3aa91c9506079313449",
          "sha1": "e0f3e98ce0b37063eb0cd3b08af4029c52429d43",
          "md5": "db918bf8704c950d2730d2f21c05b3c8"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosarm64/1.0.0-alpha25/modelcontract-iosarm64-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "modelcontract-iosarm64",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosx64/1.0.0-alpha25/modelcontract-iosx64-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "modelcontract-iosx64",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha25/modelcontract-jvm-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha25/modelcontract-jvm-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha25"
      }
    }
  ]
}
