{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha19.jar",
          "url": "core-1.0.0-alpha19.jar",
          "size": 7321,
          "sha512": "b6b17942f798fa4a4fe3c8a4900543ea91c3a9cd8564d0782c9774bac5520f12b9c3cbe5e609f4f601bf1a39f0b0a7e7395679458d3bb4d26254c1ea6910d146",
          "sha256": "513e0400c2ce3e05e8ad783644841cecc2dafbb46a5df978baff61433ba19ad8",
          "sha1": "656215496abbdfdf153a5ba62c284d63e0e3d1a4",
          "md5": "cf9fa936e97100a4d596c402112847cd"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha19/core-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha19/core-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha19/core-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha19/core-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha19/core-iosarm64-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha19/core-iosx64-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha19"
      }
    }
  ]
}
