{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha5/viewmodel-1.0.0-alpha5.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha5-debug.aar",
          "size": 43768,
          "sha512": "d48cd3f0f1b7a795ebc03c09176133fc4515e6a5924756a8e519278c55f3fffee3533230ccdf03ffc5f72d8afdf6ea52b948926f207814b891b0c7f3c1a888cd",
          "sha256": "f5a006a01d54e5c8a251e77c43f845b323c2a295f26bce0f8a223a2a92c8d39b",
          "sha1": "573bf38079cc611d11ad5b3a599b7bca87f4b1c6",
          "md5": "73ea3df9c1be68fa8bbff67a236cb2b4"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha5-debug.aar",
          "size": 43768,
          "sha512": "d48cd3f0f1b7a795ebc03c09176133fc4515e6a5924756a8e519278c55f3fffee3533230ccdf03ffc5f72d8afdf6ea52b948926f207814b891b0c7f3c1a888cd",
          "sha256": "f5a006a01d54e5c8a251e77c43f845b323c2a295f26bce0f8a223a2a92c8d39b",
          "sha1": "573bf38079cc611d11ad5b3a599b7bca87f4b1c6",
          "md5": "73ea3df9c1be68fa8bbff67a236cb2b4"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha5.aar",
          "size": 41849,
          "sha512": "b622e65d718bc5ab679f675b99be4127866d0d6d83a81f0fa3c1d26127290f3b4d93691bb577d560a4c9fc3a7ce62871ccc6402369555a9a9553b5771fe4784e",
          "sha256": "d7b677acf2bcf252f09013abf6c773cccd56f8cd0fe8c6051b555d1eba784c56",
          "sha1": "36228a457b9cf79eedbae2d6c4b43eae95a42ca4",
          "md5": "116a1f8dad2dc2e89587e453ca07a997"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha5.aar",
          "size": 41849,
          "sha512": "b622e65d718bc5ab679f675b99be4127866d0d6d83a81f0fa3c1d26127290f3b4d93691bb577d560a4c9fc3a7ce62871ccc6402369555a9a9553b5771fe4784e",
          "sha256": "d7b677acf2bcf252f09013abf6c773cccd56f8cd0fe8c6051b555d1eba784c56",
          "sha1": "36228a457b9cf79eedbae2d6c4b43eae95a42ca4",
          "md5": "116a1f8dad2dc2e89587e453ca07a997"
        }
      ]
    }
  ]
}
