{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha25/viewcontract-1.0.0-alpha25.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha25.jar",
          "url": "viewcontract-jvm-1.0.0-alpha25.jar",
          "size": 55450,
          "sha512": "b3eeaba169aeda9435cc26079ca1349e56c92620d97f2d1c6436ee36058cd64873f0f1502fc78f9ea66b52200886e597dd46ca19f18e211bbaa6c7f903171652",
          "sha256": "c1b37cac5700c8d9c966e5f3107cba3d1e86c4b208f1ee965ad34f1ee554e8f6",
          "sha1": "774c297c03e73c454626f1008f72b3229cc46a37",
          "md5": "1a2bc9a968303b1f97228e307d296bbb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha25.jar",
          "url": "viewcontract-jvm-1.0.0-alpha25.jar",
          "size": 55450,
          "sha512": "b3eeaba169aeda9435cc26079ca1349e56c92620d97f2d1c6436ee36058cd64873f0f1502fc78f9ea66b52200886e597dd46ca19f18e211bbaa6c7f903171652",
          "sha256": "c1b37cac5700c8d9c966e5f3107cba3d1e86c4b208f1ee965ad34f1ee554e8f6",
          "sha1": "774c297c03e73c454626f1008f72b3229cc46a37",
          "md5": "1a2bc9a968303b1f97228e307d296bbb"
        }
      ]
    }
  ]
}
