{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha11/core-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0-RC-native-mt",
            "requires": "1.5.0-RC-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-1.0.0-alpha11.klib",
          "size": 20706,
          "sha512": "aaa45e77f508023b8083c00c0cc67c293437af992ef392ba23506310ffc90d415b1dc2a3a9f80e258341e28db75eb279f59f489232565677c7ffc5b20597ba08",
          "sha256": "809809478d80c139fae4104a340c0d0e902467df7cd6b042dad321333bb56746",
          "sha1": "cd51f77788d9040d5f685ce6e7ed3f013ee86ab3",
          "md5": "d27ae6959a1c95b61c4996703e1a2346"
        }
      ]
    }
  ]
}
