{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.12/model-0.0.12.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tgichq4ydfcfnbmsheeguc344q"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.12-debug.aar",
          "size": 84165,
          "sha512": "6c97f32724cd181507fc3bbe0cfb420c24b7ccca929afd7d405e2d6434d9c6af8b16144bf97d21604454e6b6f9ff962ebfe91f23e1d2df2fb66eaa185fdaec02",
          "sha256": "91c8e4fafa1f2ce311ae0080d6f99df9a0420f9297ef2520ddb77451e450779c",
          "sha1": "ac81bd19ee4bc3a127354103595d27f59d858b6d",
          "md5": "b4e54e1cf211e8bcb3c1a0457569c41f"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.12-debug.aar",
          "size": 84165,
          "sha512": "6c97f32724cd181507fc3bbe0cfb420c24b7ccca929afd7d405e2d6434d9c6af8b16144bf97d21604454e6b6f9ff962ebfe91f23e1d2df2fb66eaa185fdaec02",
          "sha256": "91c8e4fafa1f2ce311ae0080d6f99df9a0420f9297ef2520ddb77451e450779c",
          "sha1": "ac81bd19ee4bc3a127354103595d27f59d858b6d",
          "md5": "b4e54e1cf211e8bcb3c1a0457569c41f"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.12.aar",
          "size": 80826,
          "sha512": "bf0df129e4eb9a204c8ea01a25ce1df67e5c65b34620db07015a861834b33d18f4cf04edd900a22080276e7d29044e3b2db860835e9fc38d8cc1f9ceee55409f",
          "sha256": "811c61cd2522b124c8864216ccc4d97ffcc9db36e1e9cf59706b03159e57088d",
          "sha1": "ae97032e71457606cd223af8de21444da78016ad",
          "md5": "c6bd1c42dc58011bab63c3e0d6cb6ba5"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.12.aar",
          "size": 80826,
          "sha512": "bf0df129e4eb9a204c8ea01a25ce1df67e5c65b34620db07015a861834b33d18f4cf04edd900a22080276e7d29044e3b2db860835e9fc38d8cc1f9ceee55409f",
          "sha256": "811c61cd2522b124c8864216ccc4d97ffcc9db36e1e9cf59706b03159e57088d",
          "sha1": "ae97032e71457606cd223af8de21444da78016ad",
          "md5": "c6bd1c42dc58011bab63c3e0d6cb6ba5"
        }
      ]
    }
  ]
}
