{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha12/viewmodel-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha12-debug.aar",
          "size": 72863,
          "sha512": "5e60d34b7754b7c2593a3b695e71ca2c5f4f7d4338a7772f2c560d9429f482ceb969f4507047f5ae7a16b4a943237b12124a24275b5bdb13ada78977c371c7f5",
          "sha256": "919cb1504dda54bdeebde314f87b4ce0d949be0063aa2a355525cf0e642fd190",
          "sha1": "a9d52fe330fe2f3b09bfd736f989bd4e878d28de",
          "md5": "c5f0dbab4e5d008932865bef2e281ea7"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha12-debug.aar",
          "size": 72863,
          "sha512": "5e60d34b7754b7c2593a3b695e71ca2c5f4f7d4338a7772f2c560d9429f482ceb969f4507047f5ae7a16b4a943237b12124a24275b5bdb13ada78977c371c7f5",
          "sha256": "919cb1504dda54bdeebde314f87b4ce0d949be0063aa2a355525cf0e642fd190",
          "sha1": "a9d52fe330fe2f3b09bfd736f989bd4e878d28de",
          "md5": "c5f0dbab4e5d008932865bef2e281ea7"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha12.aar",
          "size": 69447,
          "sha512": "20d6581a1e350b42bad2c441b40114d5819bd738ee72d44bb572467a872a5ab86338309fbefc4df15281c27e74681d4ec38d2b493d8394c6b327f987b8685358",
          "sha256": "f288ac7dfa45b7fd00f71c0f2f84e2406bffa5b73d8e33eb95f80f9bec072223",
          "sha1": "c152d64b258341e3d37b8f9810cce96cbd4b4d7c",
          "md5": "6d7c23b79f629dcde229b3fdd471ed69"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha12.aar",
          "size": 69447,
          "sha512": "20d6581a1e350b42bad2c441b40114d5819bd738ee72d44bb572467a872a5ab86338309fbefc4df15281c27e74681d4ec38d2b493d8394c6b327f987b8685358",
          "sha256": "f288ac7dfa45b7fd00f71c0f2f84e2406bffa5b73d8e33eb95f80f9bec072223",
          "sha1": "c152d64b258341e3d37b8f9810cce96cbd4b4d7c",
          "md5": "6d7c23b79f629dcde229b3fdd471ed69"
        }
      ]
    }
  ]
}
