{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.27/contract-0.0.27.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "eivbo7yrmzcdnc7ypzmvwqtxd4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.27.jar",
          "url": "contract-jvm-0.0.27.jar",
          "size": 17931,
          "sha512": "bdf87b8a9a80bca26d86f4e48b5c585e02602a145f28a5e81989a29dcee0909322dcdbe67151e585ab8904129092c8bf35d7e6eef14784064cbe82529d716ddf",
          "sha256": "cc4736e8cbc0e0af0a8e2814566d7fe87d8fd2ded060679b0aa380f7fc4b080e",
          "sha1": "e93a375d96997642eb901e21316b62e62afd7d83",
          "md5": "4fecdfd202c9316b2c5a050e3e7ea8db"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.27.jar",
          "url": "contract-jvm-0.0.27.jar",
          "size": 17931,
          "sha512": "bdf87b8a9a80bca26d86f4e48b5c585e02602a145f28a5e81989a29dcee0909322dcdbe67151e585ab8904129092c8bf35d7e6eef14784064cbe82529d716ddf",
          "sha256": "cc4736e8cbc0e0af0a8e2814566d7fe87d8fd2ded060679b0aa380f7fc4b080e",
          "sha1": "e93a375d96997642eb901e21316b62e62afd7d83",
          "md5": "4fecdfd202c9316b2c5a050e3e7ea8db"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.27/contract-metadata-0.0.27.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.27"
      }
    }
  ]
}
