{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha14/core-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "biqopuycmjhqla5bue3ohogk3m"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0",
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-1.0.0-alpha14.klib",
          "size": 22506,
          "sha512": "cf9d93c8d9dce6656bb254c56cbcac328a0f65a4c784322dbced1499313780fbce4857635190d45acc25841cee51d3fb9b96b1a6d10feab51087cc4bc2e16971",
          "sha256": "c495c3371f1ef9439d752c23c05d0478fb4a2a47952d884e8bc4bbfad2635d1a",
          "sha1": "f734f04a9bb08bd3d7b4fd7802a5f60b4137720d",
          "md5": "d9f927ad6f57b6f7894bc7c5d5f75f50"
        }
      ]
    }
  ]
}
