{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.13/androidTests-0.0.13.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "kwtsmjyvlzbw3aguhyqjzuuf5m"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.13.jar",
          "url": "androidTests-metadata-0.0.13.jar",
          "size": 261,
          "sha512": "a904cd017280056d3096a164f56abcc2e2aef5abc62f378c08cc3201588649774e4874a46e34ad09c348dbfc8bd002cce11d902cd9561594501510495b42ca1e",
          "sha256": "5bdf34269fb8ab251778abe544a1b927038669600425cae96277d1ea0f0b30f5",
          "sha1": "626d80eead559114fd030f7b49e17df1fc664949",
          "md5": "727e7173ac5785149521c0adef384114"
        }
      ]
    }
  ]
}
