{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.44/view-0.0.44.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i7olmwxatfdhths5wu7quwrrny"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.44"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.44.jar",
          "url": "view-metadata-0.0.44.jar",
          "size": 6294,
          "sha512": "b1bd7d81d487b904529a2ea71b09811c801cf12505cc9d286f6f8f74c7c35f2de415592b5b3870a418b59cd085acad811d1e634e0bf0d5669638b64456caf40e",
          "sha256": "59174869106d2a7fd4033b12df46e6730bd94149f680cb205dce4ac23315d049",
          "sha1": "d88f2628f8b1e3979bba194a2165b89040827367",
          "md5": "5a0c913f49ba1cb2cc2dcd767686b070"
        }
      ]
    }
  ]
}
