{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha16.jar",
          "url": "generator-1.0.0-alpha16.jar",
          "size": 192942,
          "sha512": "b382fe4ce8801a7ecfcd1d2e0d95dd80b2570206b8c3ac9b85403fc9535b10b4bbde6b0562c6becd602a59c2ee33458042596e2f267d62276fbb41b728a721c8",
          "sha256": "49241dfd6db19a1fcee5bcba91a3441294e293a9e9e65a6b77ffb3dea0e1fbef",
          "sha1": "52af3426e34454321ac36b094caa46f1bf987d29",
          "md5": "45ccfbd967e817d358f29f729eee8cd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha16"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha16.jar",
          "url": "generator-1.0.0-alpha16.jar",
          "size": 192942,
          "sha512": "b382fe4ce8801a7ecfcd1d2e0d95dd80b2570206b8c3ac9b85403fc9535b10b4bbde6b0562c6becd602a59c2ee33458042596e2f267d62276fbb41b728a721c8",
          "sha256": "49241dfd6db19a1fcee5bcba91a3441294e293a9e9e65a6b77ffb3dea0e1fbef",
          "sha1": "52af3426e34454321ac36b094caa46f1bf987d29",
          "md5": "45ccfbd967e817d358f29f729eee8cd5"
        }
      ]
    }
  ]
}
