{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha16/core-1.0.0-alpha16.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-1.0.0-alpha16.klib",
          "size": 22504,
          "sha512": "8a102a59524be110097b85b1af6f5cb1f8be8517481f279e16d670af63018e1c68968e65957851c9af87fa6ea4def7b28f36ab5134b1e581b3f9565a90a79b56",
          "sha256": "94568fd11cbc3fb1bac9597bdf856497acdcd8fd6cc046b1cf984f97cbde6da6",
          "sha1": "67fc3f2aaea8865a94f686b26a6a94b07c42bc50",
          "md5": "59380c5b7466f1061bdf29a518fc4d82"
        }
      ]
    }
  ]
}
