{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha17.jar",
          "url": "viewmodel-1.0.0-alpha17.jar",
          "size": 15230,
          "sha512": "1bd77d65021013cbc20b9c14bf08910ede98705d8837ec31351d8ce8ef09bbdd6a761047000a797d349ae464d69304526ec3306e162f20601fcf59956125cdad",
          "sha256": "77d2be45e81a2dff8a2464fb4227fb90344b3223b4fa13d20fb66fbe52c6acfd",
          "sha1": "e931c9b9a39127dfa0c6ed869af71259e9e387c0",
          "md5": "44150c464a765ff658638868d6061475"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha17/viewmodel-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha17/viewmodel-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha17/viewmodel-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha17/viewmodel-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha17"
      }
    }
  ]
}
