{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.24/contract-0.0.24.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "outl7uxctrgmfpv6znqczvsuxy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.24.jar",
          "url": "contract-jvm-0.0.24.jar",
          "size": 15726,
          "sha512": "e962f0fe34a72f79c75530aa57b6fd9a8e016b95ee3c830dbe8df4eec977c5661224dd50379e355930de480d0a647fcb031e0b479ffbf64468034792e1f0aa2c",
          "sha256": "91c4f7d3036ac4087a5b959b1a1ca7bb4ef2a750847a3458e23c270f4bd8073b",
          "sha1": "7509cdb362fe0ff322a02140c014a16d7973144a",
          "md5": "1b9104e3acb3817d0cf08fc121f82987"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.24.jar",
          "url": "contract-jvm-0.0.24.jar",
          "size": 15726,
          "sha512": "e962f0fe34a72f79c75530aa57b6fd9a8e016b95ee3c830dbe8df4eec977c5661224dd50379e355930de480d0a647fcb031e0b479ffbf64468034792e1f0aa2c",
          "sha256": "91c4f7d3036ac4087a5b959b1a1ca7bb4ef2a750847a3458e23c270f4bd8073b",
          "sha1": "7509cdb362fe0ff322a02140c014a16d7973144a",
          "md5": "1b9104e3acb3817d0cf08fc121f82987"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.24/contract-metadata-0.0.24.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.24"
      }
    }
  ]
}
