{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/1.0.0-alpha14/androidTests-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "biqopuycmjhqla5bue3ohogk3m"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-debug.aar",
          "url": "androidTests-android-1.0.0-alpha14-debug.aar",
          "size": 56051,
          "sha512": "785307dec8eb0cee43cb6395738801f9bc3fb89afbcc0c53d97c3a8f0b4825ead1d256c836172c1d3715d64c4faf9d5a9bf98189dd8821fbc60c0f40b55b8355",
          "sha256": "6a33c225d4aa8661249eb3d7259378859a614f56ce19ec80ba079aa99a955d7e",
          "sha1": "2239d298730e3029bb466e66734310bd543774bb",
          "md5": "9b822dab33abd257f71f5735a7678783"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-debug.aar",
          "url": "androidTests-android-1.0.0-alpha14-debug.aar",
          "size": 56051,
          "sha512": "785307dec8eb0cee43cb6395738801f9bc3fb89afbcc0c53d97c3a8f0b4825ead1d256c836172c1d3715d64c4faf9d5a9bf98189dd8821fbc60c0f40b55b8355",
          "sha256": "6a33c225d4aa8661249eb3d7259378859a614f56ce19ec80ba079aa99a955d7e",
          "sha1": "2239d298730e3029bb466e66734310bd543774bb",
          "md5": "9b822dab33abd257f71f5735a7678783"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-release.aar",
          "url": "androidTests-android-1.0.0-alpha14.aar",
          "size": 54451,
          "sha512": "590fe7e79ca74650609ecb0b705956e4d0171bd581c2d5906734ea83c2b8b4644ac397f49efe6d9c945dffb19b8958f686714a5d00b324c53b9118fdcafac610",
          "sha256": "5f7f114c6cd74b22e8bf384b831402d0c6a8634d6cfa7d485a3bcd9fdcb9eeba",
          "sha1": "7b9fbc10255591b7d9fcb687a0b03e48c1f6a95a",
          "md5": "b796c3af67315b6db33475b230890efa"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-release.aar",
          "url": "androidTests-android-1.0.0-alpha14.aar",
          "size": 54451,
          "sha512": "590fe7e79ca74650609ecb0b705956e4d0171bd581c2d5906734ea83c2b8b4644ac397f49efe6d9c945dffb19b8958f686714a5d00b324c53b9118fdcafac610",
          "sha256": "5f7f114c6cd74b22e8bf384b831402d0c6a8634d6cfa7d485a3bcd9fdcb9eeba",
          "sha1": "7b9fbc10255591b7d9fcb687a0b03e48c1f6a95a",
          "md5": "b796c3af67315b6db33475b230890efa"
        }
      ]
    }
  ]
}
