{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.41/view-0.0.41.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mg55xkylpzdfpow33thce6zcgu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.41"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.41.jar",
          "url": "view-metadata-0.0.41.jar",
          "size": 6294,
          "sha512": "d7ef91c28a8c6f6a83c2ad0537e26b1c8d4eba64a70a8967c228dd46c1523fa9b21e9bc4d67beb0b4cedbe91ef636d90698b4b559bea56113a1a263542258332",
          "sha256": "42f7e76bdc9396c3c8b6b3bdab21efda3fee224233c3abd6f772b30815e226e2",
          "sha1": "b0d66db49dc9af4c06218e83eb516dfe906546cf",
          "md5": "6dc8d372d3b549ae276f370271d4ace4"
        }
      ]
    }
  ]
}
