{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.48/viewmodel-0.0.48.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "adu4mcp7tnfvfaxt3d3ep6dpwa"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.48-debug.aar",
          "size": 52497,
          "sha512": "db7fd65bb826d5b46a81631f7a2801a55daebb27546637d529fc2b884ec2199387391f16e6ee490aa505158ee8f560cdf36c432f68f8c72c5e766be258cb06f9",
          "sha256": "1e2c59d6b22c2a4ff1e585ccc8a72ba116a2da3e2caac2ff8680f73ab0b90a55",
          "sha1": "d4e0b5e54ce14895ec9648e1510dedea41bcaa44",
          "md5": "42b2e4feed2b89f2e4b2e9bb31f4219e"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.48-debug.aar",
          "size": 52497,
          "sha512": "db7fd65bb826d5b46a81631f7a2801a55daebb27546637d529fc2b884ec2199387391f16e6ee490aa505158ee8f560cdf36c432f68f8c72c5e766be258cb06f9",
          "sha256": "1e2c59d6b22c2a4ff1e585ccc8a72ba116a2da3e2caac2ff8680f73ab0b90a55",
          "sha1": "d4e0b5e54ce14895ec9648e1510dedea41bcaa44",
          "md5": "42b2e4feed2b89f2e4b2e9bb31f4219e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.48.aar",
          "size": 50866,
          "sha512": "bdd03e84c93e139f37d17970efb1783338cfaccfafc86804d567b200c236b933fd9631dad2da643700ca1e62bfd76407fc46507cfacdc0b1b289423c57cbff7a",
          "sha256": "b308339ef6bf0b01cfaee86c0a21dfd81329d185a51bed7ad528766dc5bf6a44",
          "sha1": "74aeba0d1c4a29aecc5c412c9a782d1870664ce7",
          "md5": "c8cb9fd098ef2bbbf1807591d385ea7d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.48.aar",
          "size": 50866,
          "sha512": "bdd03e84c93e139f37d17970efb1783338cfaccfafc86804d567b200c236b933fd9631dad2da643700ca1e62bfd76407fc46507cfacdc0b1b289423c57cbff7a",
          "sha256": "b308339ef6bf0b01cfaee86c0a21dfd81329d185a51bed7ad528766dc5bf6a44",
          "sha1": "74aeba0d1c4a29aecc5c412c9a782d1870664ce7",
          "md5": "c8cb9fd098ef2bbbf1807591d385ea7d"
        }
      ]
    }
  ]
}
