{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.25/view-0.0.25.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.25-debug.aar",
          "size": 143350,
          "sha512": "ad22907ea3bde5f109e89d7046a063f053de3633815860afc218ec82f6410a4d8269b936fe53546d3c4e1516772a950d923da2f2b14c82f1337eaee9713cbc2b",
          "sha256": "6fb5393a37ee0d82e100e8bfafb29c8a5487d7f45d66aafb747737712b539db2",
          "sha1": "0b6bc15db7698901585fd6ae5d7866fa7a791a18",
          "md5": "48ecaf252af5d1473082fd51724091e2"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.25-debug.aar",
          "size": 143350,
          "sha512": "ad22907ea3bde5f109e89d7046a063f053de3633815860afc218ec82f6410a4d8269b936fe53546d3c4e1516772a950d923da2f2b14c82f1337eaee9713cbc2b",
          "sha256": "6fb5393a37ee0d82e100e8bfafb29c8a5487d7f45d66aafb747737712b539db2",
          "sha1": "0b6bc15db7698901585fd6ae5d7866fa7a791a18",
          "md5": "48ecaf252af5d1473082fd51724091e2"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.25.aar",
          "size": 138929,
          "sha512": "3e9f9861ec2f47570ee3cd66998d077cc42dff9581862c44925b05e968fa0656f3895929cbb7da5c29476e6a3f970ec9ead0f430a82c63dc5949340155c781c8",
          "sha256": "010fc9a7ad2a5c2981a368565e47311f60bc9b5e51716256023139264c482dad",
          "sha1": "48aba30433db0b3c9ebf45007f8b454320b11487",
          "md5": "2a499adc9c4ab2786db147d503787f06"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.25.aar",
          "size": 138929,
          "sha512": "3e9f9861ec2f47570ee3cd66998d077cc42dff9581862c44925b05e968fa0656f3895929cbb7da5c29476e6a3f970ec9ead0f430a82c63dc5949340155c781c8",
          "sha256": "010fc9a7ad2a5c2981a368565e47311f60bc9b5e51716256023139264c482dad",
          "sha1": "48aba30433db0b3c9ebf45007f8b454320b11487",
          "md5": "2a499adc9c4ab2786db147d503787f06"
        }
      ]
    }
  ]
}
