{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "viewmodel",
    "version": "1.0.0-iosalpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-iosalpha62.jar",
          "url": "viewmodel-1.0.0-iosalpha62.jar",
          "size": 16492,
          "sha512": "17c88ac980117346f4f157e1cf3db5a478c7bc87c58a58f6704fca7ce0d4837689451575d2b2ecb8703e1080195e94fef1ce027fae29a48a472e89b869d36953",
          "sha256": "7d51357cb63e3c78ab9abe234dd91d68fd2a723388d037ed8b1d93484cd760f5",
          "sha1": "a5f1b3f597bd25c0e3fd0911677fa0ca4574917e",
          "md5": "6a42294bab535f39d5924225d851b428"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-iosalpha62/viewmodel-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-iosalpha62/viewmodel-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-iosalpha62/viewmodel-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-iosalpha62/viewmodel-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewmodel-iosarm64/1.0.0-iosalpha62/viewmodel-iosarm64-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-iosarm64",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewmodel-iosx64/1.0.0-iosalpha62/viewmodel-iosx64-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-iosx64",
        "version": "1.0.0-iosalpha62"
      }
    }
  ]
}
