{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model-metadata",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.49.jar",
          "url": "model-metadata-0.0.49.jar",
          "size": 13116,
          "sha512": "ceb9889f40a48606e922bd9be7242403522a6de8eb577c79c271b3b1da5efa950d9a4c8b899636c050197f10ee892b89f542f15ae0f7e39ae41f640afaa4a28c",
          "sha256": "60fc264c5a09998c09790744c7e6f0b41b0103e5fd643670aa73c9a946258aec",
          "sha1": "4343a8d4f5c10be6e033fcdd6551d7a810147e50",
          "md5": "208353d744ffd32fdd78977c18d763c4"
        }
      ]
    }
  ]
}
