{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.5/core-0.0.5.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "nju6gt2f4nfplmunyax325fmbu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.5.jar",
          "url": "core-metadata-0.0.5.jar",
          "size": 4883,
          "sha512": "65c2219c17cd455b48b1bba58d21e3f2bf6de3a6227781143b50b04af93f931e4c4df00434d7cfe34885b2da6fc4cb6340e9c48a7e3f672e6c5997a03814327",
          "sha256": "6c3154f255e70ce7100717389152f24da71671a8fec2bb5e36a4a8ce27f77e8a",
          "sha1": "36d052b77cee2b0107d8c3e2b0416e6aca9eb26d",
          "md5": "a3c2d9048797256ff1d9d6602f285a35"
        }
      ]
    }
  ]
}
