{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha17/core-1.0.0-alpha17.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-1.0.0-alpha17.klib",
          "size": 22488,
          "sha512": "21a0cd1409422c219fcdbe7d405051804c3e1d8fa021fe7dd6742b5853c132792016d5cb4dbdcd34feb809849870f70a710e583fc299fe8e58e6104bf1a59587",
          "sha256": "65965036ec54d53c6c208066a447bf720bbd10ce1a37c94c7e6e618aa5a943b8",
          "sha1": "043dd04247f2967aec256dd3cbc5f10076b2dbb9",
          "md5": "a35c36fb8f88c947c189c9dc071a15a7"
        }
      ]
    }
  ]
}
