{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha12/modelcontract-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha12.klib",
          "size": 23424,
          "sha512": "588320924e4b800dba0e4cf5d802840d410030e95f90d4f6f49549f9cf8341913824a3a4600fe663fcc408ecdd144c3fd4a22afddf042d38b38e3e996afddf71",
          "sha256": "a3991d648eee7a6b84d980cb5ac04f3c82cc4ac6857291ed9c7207c1edcf292a",
          "sha1": "31fdd8664d937d4a9b36b98d1b13add38883e1de",
          "md5": "c9794edf7e04083b52f5782b5dc0d8d1"
        }
      ]
    }
  ]
}
