{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha6/core-1.0.0-alpha6.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3",
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-1.0.0-alpha6.klib",
          "size": 20657,
          "sha512": "2eb7b7537c8994c130135c0f30194ec17bceddeb94bb0ced874e51a6062d1af92ad2aec5e3dff9278b7a1ad8bbfc3cfffcace64a5b2545b76cc43108b3955803",
          "sha256": "668e50d99208758fd2d4c54d731f1441e7e3644271b71dc5a9fb5eecf8e71728",
          "sha1": "67a416941e3f1d198d98ce18886a1815129e4802",
          "md5": "2bbf9cb917c14a41e2591a8110af6c63"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/1.0.0-alpha6/core-metadata-1.0.0-alpha6.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "1.0.0-alpha6"
      }
    }
  ]
}
