{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.49/core-0.0.49.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.49.jar",
          "url": "core-jvm-0.0.49.jar",
          "size": 17701,
          "sha512": "b525096fbf585911dec7aea1fe4908f45b373fa85d3fc19cde53299dcdd2377e7315d81ff1877cc695994ff48036c092deb37cdfad77d64d8aed6005d802a683",
          "sha256": "4f928a5d389527d3d5b71ff64a02e905f093630c744de64b1209dd141fa242e5",
          "sha1": "2a19f85133e5e065d146a613b63fa2eab88acb90",
          "md5": "f595bbb28c9f0569e5bbe22e2f62912e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.49.jar",
          "url": "core-jvm-0.0.49.jar",
          "size": 17701,
          "sha512": "b525096fbf585911dec7aea1fe4908f45b373fa85d3fc19cde53299dcdd2377e7315d81ff1877cc695994ff48036c092deb37cdfad77d64d8aed6005d802a683",
          "sha256": "4f928a5d389527d3d5b71ff64a02e905f093630c744de64b1209dd141fa242e5",
          "sha1": "2a19f85133e5e065d146a613b63fa2eab88acb90",
          "md5": "f595bbb28c9f0569e5bbe22e2f62912e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/0.0.49/core-metadata-0.0.49.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "0.0.49"
      }
    }
  ]
}
