{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.22/contract-0.0.22.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6uskpwxm4nhbnbsedqteegk7ke"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.22.jar",
          "url": "contract-metadata-0.0.22.jar",
          "size": 7501,
          "sha512": "dc3bee6213aa7b01c64b65034e6ccc26ada22ba4d9548c59dcb74fb43f4064467388f1856983ca35b974814776158996dbb56e7f55b8e951c6447cdf7a87f4f9",
          "sha256": "6fa9c1dc66e1c23a8753a5f8c37f2ed523e40832ac0b299f5401344e2048bd29",
          "sha1": "f5e5ebb328ec8ce9429c9e86d186adf18a5cfcfc",
          "md5": "2acb02dcc71316e428ece1e099be4c7b"
        }
      ]
    }
  ]
}
