{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "jc6y725iebc23nmj56aixso43i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.52.jar",
          "url": "generator-0.0.52.jar",
          "size": 94157,
          "sha512": "5a39934fac0910f02e551d589d2b9a4a38feb9090516ac48958f54845162d02ce13e4515c68694d5976dc098b3db4e67934244b8d114ce5ff126ac13ccdba170",
          "sha256": "1b07c471345d9d8515ba0fff1320a152fe9c1a8a53e339f698cee265c7b24151",
          "sha1": "c3932a506846aa024bd49bb821bc6535575d6758",
          "md5": "5f451bee44ee8566662818f6d75d9af4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.52"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.52.jar",
          "url": "generator-0.0.52.jar",
          "size": 94157,
          "sha512": "5a39934fac0910f02e551d589d2b9a4a38feb9090516ac48958f54845162d02ce13e4515c68694d5976dc098b3db4e67934244b8d114ce5ff126ac13ccdba170",
          "sha256": "1b07c471345d9d8515ba0fff1320a152fe9c1a8a53e339f698cee265c7b24151",
          "sha1": "c3932a506846aa024bd49bb821bc6535575d6758",
          "md5": "5f451bee44ee8566662818f6d75d9af4"
        }
      ]
    }
  ]
}
