{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.34/model-0.0.34.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sdiuqgpfpvgqbhgb64jk7k3g3u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.34.jar",
          "url": "model-metadata-0.0.34.jar",
          "size": 13166,
          "sha512": "423ea8376097b6d570f119ba9f4f4fb8de1f52da11fbd16f5f6e83ad15e6c86e6e757ec29957b1a002011d3f9a34b98c85840578ed2926d50376bc924e81f25d",
          "sha256": "bce68ec096da732e61096bc87958bc12b0b453a8d29b1700a12be16389f03668",
          "sha1": "94ce576c355f2b9fbe7fe14449271316a4851350",
          "md5": "27bb90115e7ff1541a1746f0406788d9"
        }
      ]
    }
  ]
}
