{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha8/core-1.0.0-alpha8.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5q5bv5aktfh2fdqq25rjsv33bm"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0-RC-native-mt",
            "requires": "1.5.0-RC-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-1.0.0-alpha8.klib",
          "size": 20931,
          "sha512": "b0662575911b8bc7d7e6e77f55c201214a46049a8bf5c94fc4d919cb95f2775c2b23c7a31d7f20db7b42b8dd116928bcf794ef5565750c8777b4c34f33481e44",
          "sha256": "5eb344ee59c040d639a7d046a984c1a61092642a381102289e4371dd1a9e42d1",
          "sha1": "0c44c048fd7d9b5e169644eda61718302fbe5909",
          "md5": "f8108da67862b41db205a23ab5e04904"
        }
      ]
    }
  ]
}
