{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "vuponvlkt5blhpe5a4symex76e"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha7"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha7"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-1.0.0-alpha7.jar",
          "url": "model-1.0.0-alpha7.jar",
          "size": 12965,
          "sha512": "063bff6bef23039fcbd81fa8a79274c2907b4d05f8f828a9c16eb9863bf254ebabbf2163558af6be6f7edaaecf21ce9d178cf8790cabc3b71780108de692bb58",
          "sha256": "75d2b09d9faba5a60aba549f85ba8b43a0dd3a9260a80bc14a9ab9447c77723c",
          "sha1": "e0e51a0a627f0d3bb0c351e3fe15ceee99ca7dc7",
          "md5": "7fc119fb2f798501fa64a5bd5a05300c"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha7/model-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha7/model-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha7/model-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha7/model-android-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosarm64/1.0.0-alpha7/model-iosarm64-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "model-iosarm64",
        "version": "1.0.0-alpha7"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosx64/1.0.0-alpha7/model-iosx64-1.0.0-alpha7.module",
        "group": "tech.skot",
        "module": "model-iosx64",
        "version": "1.0.0-alpha7"
      }
    }
  ]
}
