{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.13/contract-0.0.13.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "kwtsmjyvlzbw3aguhyqjzuuf5m"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.13.jar",
          "url": "contract-jvm-0.0.13.jar",
          "size": 15041,
          "sha512": "fb0831465df5b296946f1799ff793532f22e2dde9cab0d0a4fb710e6b710769b209c5ef6fb20de10a3fe0ff7596253f15f4f46deaaad5a1d8d6df453d57dbace",
          "sha256": "8dfee5b2714f57b6a43d853bfe38b582645676f303b3e30332e4ea2b43dfedeb",
          "sha1": "047ea1906fef1eb87dc8aaa570dcec5a04533c73",
          "md5": "61850cadba884396ee155a1d1b2b266c"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.13.jar",
          "url": "contract-jvm-0.0.13.jar",
          "size": 15041,
          "sha512": "fb0831465df5b296946f1799ff793532f22e2dde9cab0d0a4fb710e6b710769b209c5ef6fb20de10a3fe0ff7596253f15f4f46deaaad5a1d8d6df453d57dbace",
          "sha256": "8dfee5b2714f57b6a43d853bfe38b582645676f303b3e30332e4ea2b43dfedeb",
          "sha1": "047ea1906fef1eb87dc8aaa570dcec5a04533c73",
          "md5": "61850cadba884396ee155a1d1b2b266c"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.13/contract-metadata-0.0.13.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.13"
      }
    }
  ]
}
