{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2r2ojxqr5ffvpf4fmosdnmnn7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.20.jar",
          "url": "generator-0.0.20.jar",
          "size": 92131,
          "sha512": "8129d608ab1f1722639424618619dbd7c7b4f3e68c919685700064079d6a2dfa5cdf35d79b7a7d056c4ef005ca1c7b5e646816bf83848d03b0be6d5ca7bbcfcc",
          "sha256": "1ed404c543cce42303e3a83a7d7724c6bcd5809d92ea7df3f6443d5d33cb9e58",
          "sha1": "64e48744069dda90cb66f018081c65c8666a6cbd",
          "md5": "6c474deb8e5cb2bd6a499cd0582c7028"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.20.jar",
          "url": "generator-0.0.20.jar",
          "size": 92131,
          "sha512": "8129d608ab1f1722639424618619dbd7c7b4f3e68c919685700064079d6a2dfa5cdf35d79b7a7d056c4ef005ca1c7b5e646816bf83848d03b0be6d5ca7bbcfcc",
          "sha256": "1ed404c543cce42303e3a83a7d7724c6bcd5809d92ea7df3f6443d5d33cb9e58",
          "sha1": "64e48744069dda90cb66f018081c65c8666a6cbd",
          "md5": "6c474deb8e5cb2bd6a499cd0582c7028"
        }
      ]
    }
  ]
}
