{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha10/viewcontract-1.0.0-alpha10.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "vrvei6o5trhotpxc7jm4yf4dri"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha10.jar",
          "url": "viewcontract-jvm-1.0.0-alpha10.jar",
          "size": 33799,
          "sha512": "dd212b457754cdc02f648d05927e705d5ebd4dfed4f7296c703879586c5a606096c81b62078d29e832a5dc1c6e17c0f01a2b9783f3de44533957432a7ebf9ac2",
          "sha256": "1484bb9cb242874525f66e8aa3b9c205123f4d09b29833f1e79e90436dc64db1",
          "sha1": "13555366e7b840758f592fde42f9e21f1148a6fa",
          "md5": "c0cb1e45bac73eb7581b0d199912eaa9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha10.jar",
          "url": "viewcontract-jvm-1.0.0-alpha10.jar",
          "size": 33799,
          "sha512": "dd212b457754cdc02f648d05927e705d5ebd4dfed4f7296c703879586c5a606096c81b62078d29e832a5dc1c6e17c0f01a2b9783f3de44533957432a7ebf9ac2",
          "sha256": "1484bb9cb242874525f66e8aa3b9c205123f4d09b29833f1e79e90436dc64db1",
          "sha1": "13555366e7b840758f592fde42f9e21f1148a6fa",
          "md5": "c0cb1e45bac73eb7581b0d199912eaa9"
        }
      ]
    }
  ]
}
