{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.29/viewmodel-0.0.29.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.29-debug.aar",
          "size": 52210,
          "sha512": "150bfe759eb4737c8fe1d794a9198620287d2f2aa7142c66bb8f94ad870045e6f3c208702c578de27c37618e48d0ef8f5c9dc0dd26e68e2ff96ef9e899cce99f",
          "sha256": "06aa4e92333a9af9bb9e275f73bece374da545510b39d94c0ac86552e7d55480",
          "sha1": "87e7f71c76ecfb2c27d1386871121bb7f4e96cb4",
          "md5": "6596802ed67a16ee3f14b1e16d7f4a6a"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.29-debug.aar",
          "size": 52210,
          "sha512": "150bfe759eb4737c8fe1d794a9198620287d2f2aa7142c66bb8f94ad870045e6f3c208702c578de27c37618e48d0ef8f5c9dc0dd26e68e2ff96ef9e899cce99f",
          "sha256": "06aa4e92333a9af9bb9e275f73bece374da545510b39d94c0ac86552e7d55480",
          "sha1": "87e7f71c76ecfb2c27d1386871121bb7f4e96cb4",
          "md5": "6596802ed67a16ee3f14b1e16d7f4a6a"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.29.aar",
          "size": 50558,
          "sha512": "b28e3fc640d34af5ff7f99faa718aeb67aa8ab93cb0252966a08552507c0a48a3987744a048310bf2a5940cc972d7d78b8e3b7a6e11962f4d2691afb067ee2dc",
          "sha256": "a3a36bea866149ca58fb4b483a7fd0182b84d6235c90ad5a66d46df85fbedd2d",
          "sha1": "0d3434b722f649f82113b06d18748992e9e0df23",
          "md5": "95bebf96adf35c821f37cd690cd74b5b"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.29.aar",
          "size": 50558,
          "sha512": "b28e3fc640d34af5ff7f99faa718aeb67aa8ab93cb0252966a08552507c0a48a3987744a048310bf2a5940cc972d7d78b8e3b7a6e11962f4d2691afb067ee2dc",
          "sha256": "a3a36bea866149ca58fb4b483a7fd0182b84d6235c90ad5a66d46df85fbedd2d",
          "sha1": "0d3434b722f649f82113b06d18748992e9e0df23",
          "md5": "95bebf96adf35c821f37cd690cd74b5b"
        }
      ]
    }
  ]
}
