{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.14/view-0.0.14.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.14-debug.aar",
          "size": 128833,
          "sha512": "c301d0a3cbd800f0eee9ff61c64e66885351e01635a37f9b5a502933c2e3f9d00261d2d6c7b3fed0cfe40ff7183d0a915bbd18092ab70251a4620b8647d7e1fe",
          "sha256": "8f761a4cc2c4a4abbbd44a6335ee24f7c9620b9fbdde7783a073c926f1b71e4e",
          "sha1": "fa1717a5e433b74dbd567de46a2d29c2b22a6782",
          "md5": "7a33aa3aa692e3ddee85e650cdf00f43"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.14-debug.aar",
          "size": 128833,
          "sha512": "c301d0a3cbd800f0eee9ff61c64e66885351e01635a37f9b5a502933c2e3f9d00261d2d6c7b3fed0cfe40ff7183d0a915bbd18092ab70251a4620b8647d7e1fe",
          "sha256": "8f761a4cc2c4a4abbbd44a6335ee24f7c9620b9fbdde7783a073c926f1b71e4e",
          "sha1": "fa1717a5e433b74dbd567de46a2d29c2b22a6782",
          "md5": "7a33aa3aa692e3ddee85e650cdf00f43"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.14.aar",
          "size": 124554,
          "sha512": "e444ee51f0fdcef7ae73a4ddfc524a6a726dfedda91852dea0b7fe3eb32c1a81a556fe1fe2bbce0d4d97e621ebec6f71d363065b9abe474d8853d921d7ce519a",
          "sha256": "e79dacb00dd7155c8df0b3bd7d3266be95fe0341de335dada061aa1003d33b27",
          "sha1": "5281028644232349fc5fddab02296cb2f9280414",
          "md5": "6bcff60c49731b40fc804872e6ba2144"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.14.aar",
          "size": 124554,
          "sha512": "e444ee51f0fdcef7ae73a4ddfc524a6a726dfedda91852dea0b7fe3eb32c1a81a556fe1fe2bbce0d4d97e621ebec6f71d363065b9abe474d8853d921d7ce519a",
          "sha256": "e79dacb00dd7155c8df0b3bd7d3266be95fe0341de335dada061aa1003d33b27",
          "sha1": "5281028644232349fc5fddab02296cb2f9280414",
          "md5": "6bcff60c49731b40fc804872e6ba2144"
        }
      ]
    }
  ]
}
