{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.45/core-0.0.45.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-0.0.45-debug.aar",
          "size": 17387,
          "sha512": "781838746e72231d27ee80e3b28193197fbaf537a84f7de8692fdafefcbe2d465d28c32dd75548b9c57012fb55ba2f472b1ea454107549c91b6ff9255e827a29",
          "sha256": "8eaa64979d8ebf5253ba38d3159fa1f1369dee41c2f9d43f41af7559e11c02ec",
          "sha1": "9f6f570fca446c2ff69e02c0acb23058aa781236",
          "md5": "b8f7b7d9f759fc1336ae3e26549d4bb9"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-0.0.45-debug.aar",
          "size": 17387,
          "sha512": "781838746e72231d27ee80e3b28193197fbaf537a84f7de8692fdafefcbe2d465d28c32dd75548b9c57012fb55ba2f472b1ea454107549c91b6ff9255e827a29",
          "sha256": "8eaa64979d8ebf5253ba38d3159fa1f1369dee41c2f9d43f41af7559e11c02ec",
          "sha1": "9f6f570fca446c2ff69e02c0acb23058aa781236",
          "md5": "b8f7b7d9f759fc1336ae3e26549d4bb9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.0.45.aar",
          "size": 16893,
          "sha512": "da0139d81e7f8ba8bde0aa0389802e6726aeafa2a73c42c470cce9813bfe1fec647fe642e664236b94cf321912ca3891b0a71ebcbd4f6dd1ea4325a658508460",
          "sha256": "7ca8149c3164bdfa10abfc18def23f8efda4885925f85599d76d7f13d098848f",
          "sha1": "7860a735da5fdb6c15b6e367597bb51239debf76",
          "md5": "4cc9d782e99210e037bf179d151949f0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.0.45.aar",
          "size": 16893,
          "sha512": "da0139d81e7f8ba8bde0aa0389802e6726aeafa2a73c42c470cce9813bfe1fec647fe642e664236b94cf321912ca3891b0a71ebcbd4f6dd1ea4325a658508460",
          "sha256": "7ca8149c3164bdfa10abfc18def23f8efda4885925f85599d76d7f13d098848f",
          "sha1": "7860a735da5fdb6c15b6e367597bb51239debf76",
          "md5": "4cc9d782e99210e037bf179d151949f0"
        }
      ]
    }
  ]
}
