{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.12/androidTests-0.0.12.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tgichq4ydfcfnbmsheeguc344q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.12.jar",
          "url": "androidTests-metadata-0.0.12.jar",
          "size": 261,
          "sha512": "8ec434add3c92243bda007c3f1e8ab629ee311d592abd9c8b72fe4ea5c52e3952330af9f6d70b1f58745b0f560957c32415214a881289a0afe2b7658b9f5b5d5",
          "sha256": "60cb3f7d65daab0592bd2dd23a1e2563fb1212007492979608444c4338f1e2e6",
          "sha1": "5a66750e4ac09f4fe2bad8710a2470d257cd2027",
          "md5": "a5ecd4c59e253c927d05fa635f6fc6bf"
        }
      ]
    }
  ]
}
