{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.30/view-0.0.30.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "45vyvjpy25d6rogm6vet7cshky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.30"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.30.jar",
          "url": "view-metadata-0.0.30.jar",
          "size": 6291,
          "sha512": "2a2489f38e2d1ef1c0e13dc6ff8c6eb76994c52d935751a28fe8e6fb5c9f8e41e5997d1ef1a119c4f472ba76c5bd0fb8b62d792bfc33bae950315e23aaa5266a",
          "sha256": "15250ddb202cc3f5b6a89069a78d76b031f58d8e9d5e62ca8a7606acae1a1f4d",
          "sha1": "0aaf34b2384182d4a3bbe5e83761033c9b4cb7f8",
          "md5": "523b184dc749d54501ab08deab902261"
        }
      ]
    }
  ]
}
