{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract-jvm/1.0.0-alpha5/modelcontract-jvm-1.0.0-alpha5.module",
    "group": "tech.skot",
    "module": "modelcontract-jvm",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-metadata-1.0.0-alpha5.jar",
          "url": "modelcontract-metadata-1.0.0-alpha5.jar",
          "size": 2406,
          "sha512": "809bc5e6d52cf0b16403b24f7500bbb6d2a9f2c17c989d6564309e7f9ed468f004084c57033b233cd177493ed185f9b9da5ba9a2804813f42cd9cfb902578117",
          "sha256": "ab66576d34604241af7be37e3eef244964ddd66322425f24699674766918bbcf",
          "sha1": "b520eb1c6c0eba97b382a7ee4b118bddca9526b1",
          "md5": "f5976e1cc441dc2a45bbed13a38f83d8"
        }
      ]
    }
  ]
}
