{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.18/viewmodel-0.0.18.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "nrva6vite5hrni2xsf6nk6q4ge"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.18"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.18.jar",
          "url": "viewmodel-metadata-0.0.18.jar",
          "size": 6939,
          "sha512": "bf3d46c5e34a9f67f46fdd7f834a8a890fcbadbf7e555e3fe298808294f7f54aa3f977189a40dc85acd9c72847bb731b1b12d4a32f79fdbb0e209a130dc98831",
          "sha256": "de33b1d13d3aa753091de69455155859ff2a22ce22421e1d9d726b01fc05d5bc",
          "sha1": "9ffb89f5033950b6f800ca2d5e32334bd9c25b1d",
          "md5": "73052382f4d12ea8c48f7271d964075e"
        }
      ]
    }
  ]
}
