{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "eivbo7yrmzcdnc7ypzmvwqtxd4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.27.jar",
          "url": "generator-0.0.27.jar",
          "size": 93268,
          "sha512": "149da5458252d573c7f1f28d27ada8837fb32a4e664254af69a8824f88b2a3170ac3d925a462af412676e3f029504f75581c613dc2eec2877d6c2025586c0248",
          "sha256": "1e269f3bfd3d0a808ab0b152aaa46e6b7620026ab887332ead59a008d1b7b094",
          "sha1": "83474c632dad51b75f27e053532586299ab4208f",
          "md5": "1a3b513fc5b3f5e61aacd6d54d220bd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.27.jar",
          "url": "generator-0.0.27.jar",
          "size": 93268,
          "sha512": "149da5458252d573c7f1f28d27ada8837fb32a4e664254af69a8824f88b2a3170ac3d925a462af412676e3f029504f75581c613dc2eec2877d6c2025586c0248",
          "sha256": "1e269f3bfd3d0a808ab0b152aaa46e6b7620026ab887332ead59a008d1b7b094",
          "sha1": "83474c632dad51b75f27e053532586299ab4208f",
          "md5": "1a3b513fc5b3f5e61aacd6d54d220bd1"
        }
      ]
    }
  ]
}
