{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.6/view-0.0.6.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3w2f7l7ypffvjgcalkwzywgyy4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.6.jar",
          "url": "view-metadata-0.0.6.jar",
          "size": 5556,
          "sha512": "100beda7488c43b9c5854ba308f17e561ae1b2a010502dd82bde0bc934b264fe394f90ffba977cc792bd3243565bc96270117afb7e6c8914630270fae78c8421",
          "sha256": "911a6746a194a73138f7283e128d0ad1b833446c5c1c0fe06db077a8d808c706",
          "sha1": "ad828e9d0395fd27bdae56fc582ac735c5c6f811",
          "md5": "ae2b3d4c563afbb9222e8a2e1e839599"
        }
      ]
    }
  ]
}
