{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.51/model-0.0.51.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rcsqc6iufne5ve6vpfzg2hyyae"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.51-debug.aar",
          "size": 92962,
          "sha512": "e28b599ad6cea15a118d1bcc095a59ddc06ca313d170621bad3bcd22593d0ddc44548f91447a2ceafd0ebcfc16f31c76ca36f71d35817eb9865b4d40111fe45d",
          "sha256": "52b6bbf35e1c731be1dfc324fc4b6962b0d7bbd1116c86417a1de5e7ab992189",
          "sha1": "932048abbffa59725f6ed2afd5496cd62281fe77",
          "md5": "4d5d1dc8bd4802dc7e9571f47ed69fb7"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.51-debug.aar",
          "size": 92962,
          "sha512": "e28b599ad6cea15a118d1bcc095a59ddc06ca313d170621bad3bcd22593d0ddc44548f91447a2ceafd0ebcfc16f31c76ca36f71d35817eb9865b4d40111fe45d",
          "sha256": "52b6bbf35e1c731be1dfc324fc4b6962b0d7bbd1116c86417a1de5e7ab992189",
          "sha1": "932048abbffa59725f6ed2afd5496cd62281fe77",
          "md5": "4d5d1dc8bd4802dc7e9571f47ed69fb7"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.51.aar",
          "size": 89264,
          "sha512": "9c9248808960e82f095ac48a18b0faf6bd0c9b7eee97afa1c699f8ede5b3da24fe0c0bd81ae3f422de976b6d4f41b92dff418f710f032d6fa53877fdf8eb2fce",
          "sha256": "9cc48dab2b62be197541804f88f4d4083ac506626a55eff5b432a5b6b871458b",
          "sha1": "bb0aca65f2f7a1eeb77f822c6e3ed5d2f259610f",
          "md5": "172a46712d01054298046faf39cad18e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.51.aar",
          "size": 89264,
          "sha512": "9c9248808960e82f095ac48a18b0faf6bd0c9b7eee97afa1c699f8ede5b3da24fe0c0bd81ae3f422de976b6d4f41b92dff418f710f032d6fa53877fdf8eb2fce",
          "sha256": "9cc48dab2b62be197541804f88f4d4083ac506626a55eff5b432a5b6b871458b",
          "sha1": "bb0aca65f2f7a1eeb77f822c6e3ed5d2f259610f",
          "md5": "172a46712d01054298046faf39cad18e"
        }
      ]
    }
  ]
}
