{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.23/contract-0.0.23.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h626lwyzk5cqpjrywyt6pslmqm"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.23.jar",
          "url": "contract-jvm-0.0.23.jar",
          "size": 15726,
          "sha512": "3f794cdaeb982a553b0b826fc0652b715c8ff88f64cba564cf5c5cdadc26375832d38367628aac1c6c365dc2d6946264937179ea28ef5a5e91cc12bfb628aab2",
          "sha256": "0fded91d9d1aaa79cc6dd0a17b3cd9691386f93d440d94a8c8bd08871ee38175",
          "sha1": "2fd36d6f7fbc9e3a0806649f2f2947f2c55b51ce",
          "md5": "442eee81fcdba9fac576ed25bb62aa1d"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.23.jar",
          "url": "contract-jvm-0.0.23.jar",
          "size": 15726,
          "sha512": "3f794cdaeb982a553b0b826fc0652b715c8ff88f64cba564cf5c5cdadc26375832d38367628aac1c6c365dc2d6946264937179ea28ef5a5e91cc12bfb628aab2",
          "sha256": "0fded91d9d1aaa79cc6dd0a17b3cd9691386f93d440d94a8c8bd08871ee38175",
          "sha1": "2fd36d6f7fbc9e3a0806649f2f2947f2c55b51ce",
          "md5": "442eee81fcdba9fac576ed25bb62aa1d"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.23/contract-metadata-0.0.23.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.23"
      }
    }
  ]
}
