{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.12/model-0.0.12.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tgichq4ydfcfnbmsheeguc344q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.12.jar",
          "url": "model-metadata-0.0.12.jar",
          "size": 12012,
          "sha512": "df27e03b59cd164afa2f6176b77ec9345b8dfbc53bcf2adcd625e40e680d7f7819775667587ade8bec707ed8860a33f6a5de883f87c03b2b9a3df1c269c563d9",
          "sha256": "b3d4a2ef3debb665e91d789fcfe2da2f175316dd0581019dba932e86f1d44482",
          "sha1": "b5adb923effc62b7bcd26a2ca477c4c8be0a6244",
          "md5": "10b83d1a2496f85798a5f7fe785f569a"
        }
      ]
    }
  ]
}
