{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.25/viewmodel-0.0.25.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.25-debug.aar",
          "size": 52166,
          "sha512": "8defea9ae362e5edcca528aa4a03af073a3bf15fd804a26bf0061eb2ce9732d24f586ec59bb8f3c4051990c6c4de9a3b16f09d497da810072245320e6a3ef1f1",
          "sha256": "06fa1534a47f0b065d56198e2336bd198c1156d89f9991c40fc302240fc9ca73",
          "sha1": "5721c2e6a5401e1033e6f50c26b4485b791827e3",
          "md5": "2e85fa94dda868cc04575f880495fe79"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.25-debug.aar",
          "size": 52166,
          "sha512": "8defea9ae362e5edcca528aa4a03af073a3bf15fd804a26bf0061eb2ce9732d24f586ec59bb8f3c4051990c6c4de9a3b16f09d497da810072245320e6a3ef1f1",
          "sha256": "06fa1534a47f0b065d56198e2336bd198c1156d89f9991c40fc302240fc9ca73",
          "sha1": "5721c2e6a5401e1033e6f50c26b4485b791827e3",
          "md5": "2e85fa94dda868cc04575f880495fe79"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.25.aar",
          "size": 50503,
          "sha512": "ad17e496a5eee2ab388209e53acb9f1cd48759c46ef8f49639df24d0683dec9eb4e680fdc162fec208c24c7304eb494ca433d9e594a0b66433c4d6b8d11e9b08",
          "sha256": "f8924556b8ffa5cadd7f4b3d2af61d916c138f5c3b9d912cfa1a0ccdbc1dbfcb",
          "sha1": "44bba9241997009bdc50808a078043684565ffde",
          "md5": "4779de0cca763c78e2c2afd9ebdb804f"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.25.aar",
          "size": 50503,
          "sha512": "ad17e496a5eee2ab388209e53acb9f1cd48759c46ef8f49639df24d0683dec9eb4e680fdc162fec208c24c7304eb494ca433d9e594a0b66433c4d6b8d11e9b08",
          "sha256": "f8924556b8ffa5cadd7f4b3d2af61d916c138f5c3b9d912cfa1a0ccdbc1dbfcb",
          "sha1": "44bba9241997009bdc50808a078043684565ffde",
          "md5": "4779de0cca763c78e2c2afd9ebdb804f"
        }
      ]
    }
  ]
}
