{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i7olmwxatfdhths5wu7quwrrny"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.44.jar",
          "url": "generator-0.0.44.jar",
          "size": 94663,
          "sha512": "de4eb84713a6ac638748beee44b1ddeee5d6a36d00a0a9ee3db0c05c910245d00e288ec876979daeaf616c574d1e3c170e07facbf7831bc3e19a30af158ba2e1",
          "sha256": "87b6e50625384cd4bac6e240b391c5c2bc2e6742196370879eaf2e2e82e792a5",
          "sha1": "e252db09a5416b943c2ba10fd8eb9c19cccedf8e",
          "md5": "f2501ccdacf633dbe0bea131a6f77acd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.44.jar",
          "url": "generator-0.0.44.jar",
          "size": 94663,
          "sha512": "de4eb84713a6ac638748beee44b1ddeee5d6a36d00a0a9ee3db0c05c910245d00e288ec876979daeaf616c574d1e3c170e07facbf7831bc3e19a30af158ba2e1",
          "sha256": "87b6e50625384cd4bac6e240b391c5c2bc2e6742196370879eaf2e2e82e792a5",
          "sha1": "e252db09a5416b943c2ba10fd8eb9c19cccedf8e",
          "md5": "f2501ccdacf633dbe0bea131a6f77acd"
        }
      ]
    }
  ]
}
