{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.5/contract-0.0.5.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "nju6gt2f4nfplmunyax325fmbu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.5.jar",
          "url": "contract-jvm-0.0.5.jar",
          "size": 15071,
          "sha512": "67a293e86ddbea281c510771002456208870d07cf2b1fdaaec0cb3b3df53b5381b8810cd15829c51f393abf1189a5e9c1966f384c102cee17ae33d26d38c05f0",
          "sha256": "f3179f28b26daf6efede67563c3944751cd030184346fae6e165e8e34491127d",
          "sha1": "79c5800288ecaa13f52cfbcc30f47d44b9631e3f",
          "md5": "830b1bcfc169b26c944595e0f21d1289"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.5.jar",
          "url": "contract-jvm-0.0.5.jar",
          "size": 15071,
          "sha512": "67a293e86ddbea281c510771002456208870d07cf2b1fdaaec0cb3b3df53b5381b8810cd15829c51f393abf1189a5e9c1966f384c102cee17ae33d26d38c05f0",
          "sha256": "f3179f28b26daf6efede67563c3944751cd030184346fae6e165e8e34491127d",
          "sha1": "79c5800288ecaa13f52cfbcc30f47d44b9631e3f",
          "md5": "830b1bcfc169b26c944595e0f21d1289"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.5/contract-metadata-0.0.5.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.5"
      }
    }
  ]
}
