{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha23.jar",
          "url": "plugin-1.0.0-alpha23.jar",
          "size": 221289,
          "sha512": "faf36fe238d4cead7c4573c0e9e4cef61c60fd98bddb9c4e7f51cd39d71e7acc4c7f85ec114876de40441704503909dda8caa0e208efe445dc9e2ba1316d0f7b",
          "sha256": "796df120c53b3540c2ddd1851392721478194c5969e829781f1e4850eba8cf8f",
          "sha1": "49457c0ce7e4dc9ed88cc23ca9430e3bcaf6f990",
          "md5": "a488f1925e61ddbe597d15e1985e0912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha23.jar",
          "url": "plugin-1.0.0-alpha23.jar",
          "size": 221289,
          "sha512": "faf36fe238d4cead7c4573c0e9e4cef61c60fd98bddb9c4e7f51cd39d71e7acc4c7f85ec114876de40441704503909dda8caa0e208efe445dc9e2ba1316d0f7b",
          "sha256": "796df120c53b3540c2ddd1851392721478194c5969e829781f1e4850eba8cf8f",
          "sha1": "49457c0ce7e4dc9ed88cc23ca9430e3bcaf6f990",
          "md5": "a488f1925e61ddbe597d15e1985e0912"
        }
      ]
    }
  ]
}
