{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha11/viewcontract-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha11.jar",
          "url": "viewcontract-jvm-1.0.0-alpha11.jar",
          "size": 33799,
          "sha512": "25a61cd89adf938894b6034c06c4cfd0c064b3199aa0fd75acf014629b3c96386f0f70f5d1618c77f819d221080f739b6a4bec77d524b27aa4a64f7d4254298b",
          "sha256": "98c1cf2aad8ca2f4015302803f9a3a4b3d2df8c0e140eab669a32c508ece5068",
          "sha1": "ad1e986cc0b22e228e9870117b41cd5f17468446",
          "md5": "a333a8fb158d5a25762e862949a7f4f0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha11.jar",
          "url": "viewcontract-jvm-1.0.0-alpha11.jar",
          "size": 33799,
          "sha512": "25a61cd89adf938894b6034c06c4cfd0c064b3199aa0fd75acf014629b3c96386f0f70f5d1618c77f819d221080f739b6a4bec77d524b27aa4a64f7d4254298b",
          "sha256": "98c1cf2aad8ca2f4015302803f9a3a4b3d2df8c0e140eab669a32c508ece5068",
          "sha1": "ad1e986cc0b22e228e9870117b41cd5f17468446",
          "md5": "a333a8fb158d5a25762e862949a7f4f0"
        }
      ]
    }
  ]
}
