{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.17/contract-0.0.17.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "43amt7eqbfabtkb5q6646kb3hm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.17.jar",
          "url": "contract-metadata-0.0.17.jar",
          "size": 7199,
          "sha512": "b107988bdcf300c324d9f2ac91f16ebfc527a611e36d743de4d09b84c91aaf78c968e54ef52488bf3d688077037d7a5e6e68c72eb48ad79217f949ba886fb4ee",
          "sha256": "b6f4c65b2d9316f92e87bbda59f89b1bc7c647335f30bdee037384edcb61c890",
          "sha1": "8d31adbc13c6cf602fe916c266569bf653c47332",
          "md5": "77a97ca81313803fbe86be1cf35283b0"
        }
      ]
    }
  ]
}
