{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.22/core-0.0.22.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6uskpwxm4nhbnbsedqteegk7ke"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.22.jar",
          "url": "core-metadata-0.0.22.jar",
          "size": 5327,
          "sha512": "0f501e244989b1fab8b6e8b9e8729f67433d1b8069d7825bc11198470d26c3e668204ddfc02b88c59b6ab4f5c70df0f0968ea8ce3e0fdbb8a4fb7784ade3e168",
          "sha256": "c51bb72a7cdec6fa49c9b5c0074def33a8e834852102901e6d3c2943e580e45c",
          "sha1": "1846c848ac7fcab9606472bc4dc5af91e59c3951",
          "md5": "b48c1d1ff7919206759487a878f4462c"
        }
      ]
    }
  ]
}
