{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "igasumkhiveslbdlejoqxrssj4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.7.jar",
          "url": "generator-0.0.7.jar",
          "size": 92120,
          "sha512": "9c368e40ed256446d54f03195181ba4942c6c858ba8e9c567d180afc03a246f1b660a9c83e0fff38d1f641ffc023ddde6d623f24297fee94f737303a935372cc",
          "sha256": "e0e15e88285632359f5e314ba1785c16ec4c194ab9eefacad9293c6d0f1e6b73",
          "sha1": "e6471b6d9ca4fadfc786945278d526209e13176a",
          "md5": "89fabcf479a104210a06dff1b4915a74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.7.jar",
          "url": "generator-0.0.7.jar",
          "size": 92120,
          "sha512": "9c368e40ed256446d54f03195181ba4942c6c858ba8e9c567d180afc03a246f1b660a9c83e0fff38d1f641ffc023ddde6d623f24297fee94f737303a935372cc",
          "sha256": "e0e15e88285632359f5e314ba1785c16ec4c194ab9eefacad9293c6d0f1e6b73",
          "sha1": "e6471b6d9ca4fadfc786945278d526209e13176a",
          "md5": "89fabcf479a104210a06dff1b4915a74"
        }
      ]
    }
  ]
}
