{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.2/contract-0.0.2.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "r76z3av2pjgf5gaz7k45ehatda"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.2.jar",
          "url": "contract-jvm-0.0.2.jar",
          "size": 14537,
          "sha512": "b096071043cecf6c3aea10488c5583a6816e926800c07473eee27205549e037b17163bba8cbf0237718a2a46eb797436e6793b509571a7911258f6e819595630",
          "sha256": "94b6605b0e7aadda414abe0f7bc8ad44fb093b8fa1a3fe6f27ac12076aad0d8a",
          "sha1": "f69c2b9c55aee7d00a10fb9bcd626881469c8bab",
          "md5": "202fa23f9d0a50cb4ab85f2756ecb528"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.2.jar",
          "url": "contract-jvm-0.0.2.jar",
          "size": 14537,
          "sha512": "b096071043cecf6c3aea10488c5583a6816e926800c07473eee27205549e037b17163bba8cbf0237718a2a46eb797436e6793b509571a7911258f6e819595630",
          "sha256": "94b6605b0e7aadda414abe0f7bc8ad44fb093b8fa1a3fe6f27ac12076aad0d8a",
          "sha1": "f69c2b9c55aee7d00a10fb9bcd626881469c8bab",
          "md5": "202fa23f9d0a50cb4ab85f2756ecb528"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.2/contract-metadata-0.0.2.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.2"
      }
    }
  ]
}
