{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.23/contract-0.0.23.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h626lwyzk5cqpjrywyt6pslmqm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.23.jar",
          "url": "contract-metadata-0.0.23.jar",
          "size": 7497,
          "sha512": "f44da9da5b83bccd48ae05152d4f569e54397a7ba72868dc10c50653f60d83aac557f3403bc4e58df229b793384f0c9cabcfe3dbd6c6403cc772943283af467f",
          "sha256": "b2c83a36179901d060acc733cbf06ceb0632a3891d096df80b5a74d4d2b7553a",
          "sha1": "1e088159e1c29ccb01e1acace9e04b987397ad6c",
          "md5": "a8ca63b9beda3eec944a5155c1cca96a"
        }
      ]
    }
  ]
}
