{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha5.jar",
          "url": "viewmodel-1.0.0-alpha5.jar",
          "size": 8112,
          "sha512": "ce3a298464684b2a7f46f6e2506d1f312c2c39d7200dffdb7e6c77d4a34a407cd7e2a37057d8e67e984b6a4078ab0e01e5eab525843f33f2e06eea28985c76f6",
          "sha256": "4268660d083210e747aa493a3cd1d8b62f393826816773035d1012b3b850564d",
          "sha1": "02e9013419b19bc162d4d95c4160aac6adc14aba",
          "md5": "9ddbd869e9fb1e39e02f4988e4aad346"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha5/viewmodel-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha5/viewmodel-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha5/viewmodel-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha5/viewmodel-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha5"
      }
    }
  ]
}
