{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha17.jar",
          "url": "generator-1.0.0-alpha17.jar",
          "size": 193576,
          "sha512": "6f380bb4752c0a380e9926f195acc33e44fcd75e1b0b317a31554ddffc7023ea44cc7ab25c5d25d8a2641960cc3fd42a404d4490f33d3448ef8f627dc8ce18f9",
          "sha256": "97c8df9b3b3c0534de77b171cc29851d75e94de26a9d07263adb7748b9aa7fa3",
          "sha1": "66a87bbde6a97d07c47320d69be4ed31aff97388",
          "md5": "217823fd3a27464e2966463933af9c36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha17.jar",
          "url": "generator-1.0.0-alpha17.jar",
          "size": 193576,
          "sha512": "6f380bb4752c0a380e9926f195acc33e44fcd75e1b0b317a31554ddffc7023ea44cc7ab25c5d25d8a2641960cc3fd42a404d4490f33d3448ef8f627dc8ce18f9",
          "sha256": "97c8df9b3b3c0534de77b171cc29851d75e94de26a9d07263adb7748b9aa7fa3",
          "sha1": "66a87bbde6a97d07c47320d69be4ed31aff97388",
          "md5": "217823fd3a27464e2966463933af9c36"
        }
      ]
    }
  ]
}
