{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-metadata-1.0.0-alpha15.jar",
          "url": "viewcontract-1.0.0-alpha15.jar",
          "size": 17644,
          "sha512": "e8fee91f1b4800319a4a63b2b8ed97f1c4523fbd6487d79813aefe47553d9f38ca277c4a19f096e5d0231b3a333470098a909672911a9aaec8c68b2200551fae",
          "sha256": "791db0c96ea4b75456eed022d427b99c58b769911197f858b3b6e4d45b55bf04",
          "sha1": "ed1e677996d94356ec457b5bdc89a2cce53aa419",
          "md5": "118fccbacbadc1e0000985329bc958f0"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosarm64/1.0.0-alpha15/viewcontract-iosarm64-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewcontract-iosarm64",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosx64/1.0.0-alpha15/viewcontract-iosx64-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewcontract-iosx64",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha15/viewcontract-jvm-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha15/viewcontract-jvm-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha15"
      }
    }
  ]
}
