{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.13/core-0.0.13.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "kwtsmjyvlzbw3aguhyqjzuuf5m"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.13.jar",
          "url": "core-metadata-0.0.13.jar",
          "size": 4883,
          "sha512": "c1097a6da7869afa65b3b03660ed143ee8ba4e8fbae93088aa96b2016c88b3d5ad7d24a7269988cc26dee4c491014598a78db379053737ee533cd41f1ce5e0e2",
          "sha256": "1a7113ef6d5df207a97b23c0297ff88c7ba02525454723b6bfd6f52e3d16df56",
          "sha1": "618ad3681c1167d6aed8ebcc4768bba0c6a4ebfd",
          "md5": "f2a5c33e246de66322f9cf9a51d55daa"
        }
      ]
    }
  ]
}
