{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.50/contract-0.0.50.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h2qswlibvbgzncub57ri5633aa"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract.klib",
          "url": "contract-iosarm64-0.0.50.klib",
          "size": 15693,
          "sha512": "f2a7e06e8aa0935756e72e85dd42e68049bbb6354774192cfea324a306df5886d6122a082655727a5d8fcb0a865259537f17d0826eda6b2f383d70d9c11f0c8c",
          "sha256": "4d4cfde764f2f2100d815dcccb6dfe02d1834b3f4f9e0c020a0314edeb4aff11",
          "sha1": "e24d384203d0e80c7eabb643f18c9df2baa3fbd9",
          "md5": "a537ce5ae4f494dbf8cf55c979ab1b14"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.50/contract-metadata-0.0.50.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.50"
      }
    }
  ]
}
