{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha11/viewcontract-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha11.klib",
          "size": 26575,
          "sha512": "f6abdd2f9e6d39f4a9a80f09a28b9195cffdcabffc4232a6e047f5aff17cc4c2c5addb56d5e3769a9405377befb45c85f30d15c402c0bae69e9f333ae13f8aa0",
          "sha256": "8f20eac0b9d0d83d88afbf7c589af17edfb362224e3f62013b6371c350b5b787",
          "sha1": "8f1a0b8768d8cc7b7fd1b33eea3a7320e21b7b54",
          "md5": "0f9a32c8e336e8e75aec82b6729e1c9b"
        }
      ]
    }
  ]
}
