{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha15/viewmodel-1.0.0-alpha15.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha15-debug.aar",
          "size": 84404,
          "sha512": "ce61257f0cc24003437708d76c1abe32df6e4ba0f7ddd90397fe7f871e36d9e609c822f927fbe6cb57fe402c8d1af4d7820519b5a9436751065653c8f38f45a1",
          "sha256": "cf30483b5876a1f219157ec646cb69e9581415dd14874c43bba59bb8be69f16d",
          "sha1": "7a304d0677bda89e0b5fe772f2b06a399486b62c",
          "md5": "b03855616f58c841e9b066e2177f44ac"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha15-debug.aar",
          "size": 84404,
          "sha512": "ce61257f0cc24003437708d76c1abe32df6e4ba0f7ddd90397fe7f871e36d9e609c822f927fbe6cb57fe402c8d1af4d7820519b5a9436751065653c8f38f45a1",
          "sha256": "cf30483b5876a1f219157ec646cb69e9581415dd14874c43bba59bb8be69f16d",
          "sha1": "7a304d0677bda89e0b5fe772f2b06a399486b62c",
          "md5": "b03855616f58c841e9b066e2177f44ac"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha15.aar",
          "size": 80496,
          "sha512": "7b99846142829040dccdf05142cdb61ea039128bcd8a09004697ee6989565c63f6d464449db9f1f82462feff15dd29560f5dc178252853d344ddf2cfab7d3f3a",
          "sha256": "bcce68b264216776832dd4e117e98eccf4a7a01052a7822e9519c482cfdde0e1",
          "sha1": "c3819fafe3834c7e8d8ad4864fbfd1bf1c3fa1f7",
          "md5": "2c71ee44caf7542843070ecfbe68a6b5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha15.aar",
          "size": 80496,
          "sha512": "7b99846142829040dccdf05142cdb61ea039128bcd8a09004697ee6989565c63f6d464449db9f1f82462feff15dd29560f5dc178252853d344ddf2cfab7d3f3a",
          "sha256": "bcce68b264216776832dd4e117e98eccf4a7a01052a7822e9519c482cfdde0e1",
          "sha1": "c3819fafe3834c7e8d8ad4864fbfd1bf1c3fa1f7",
          "md5": "2c71ee44caf7542843070ecfbe68a6b5"
        }
      ]
    }
  ]
}
