{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-iosx64/1.0.0-alpha4/core-iosx64-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "core-iosx64",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha4.jar",
          "url": "core-metadata-1.0.0-alpha4.jar",
          "size": 6817,
          "sha512": "f698f8670cb18492d99b7b70d7ee870e56717286d596d9e496f0b584b197f048fb0b2041093b3d3dce3c6c426be7162faec9a81f513f79861022962e06caa417",
          "sha256": "a904387f9344e4aa36056b3248aedc394277847c533d57f11604afd23b2054bb",
          "sha1": "885ff15cf7b84f5c32469ec302204d286f6fcadd",
          "md5": "f1c1a26582106a2649caf4934a5e56e1"
        }
      ]
    }
  ]
}
