{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.4/viewmodel-0.0.4.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qkfbndnh6jfalpfv2y37cujupm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.4.jar",
          "url": "viewmodel-metadata-0.0.4.jar",
          "size": 5530,
          "sha512": "c215c4234d5ec21579d59f03d74d292a6b9126f02343996e23816b8d2e503ab3d30a5ba8fb7168d5d410cc824d6699c0441d2b9d15d1d3c0f6678b612fdec5b",
          "sha256": "6adeceec3c86970d79edf95ed4769a4c801f2c2f0c6d7d6b633af1faa300ad63",
          "sha1": "2b5e8a4dedbcdf5c05fcfc63062f943f17313060",
          "md5": "c73321c7b52d488683614f2cf5a79984"
        }
      ]
    }
  ]
}
