{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.5/contract-0.0.5.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5f2uil5yr5anjo2xrdrfwpkzma"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.5.jar",
          "url": "contract-metadata-0.0.5.jar",
          "size": 7235,
          "sha512": "ee5ae99fecf4f59f946a5927038fc24b4319be5255d8fbcbd3ce2b948972c3c208472cf6ebf5ff44099c93f3856588b001fc63198efba599c8fde40a54ac9acb",
          "sha256": "f156f8772b711bb3ae44c89b34e6ad6b9f04030d5dd3bd2d893b8321d6b4d2db",
          "sha1": "fe72a52600d6ef51176a76ba2c16ab4dfe5b7b60",
          "md5": "7c1b57ab303ec85e5ab9235e1608f8ec"
        }
      ]
    }
  ]
}
