{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.11/contract-0.0.11.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.11.jar",
          "url": "contract-metadata-0.0.11.jar",
          "size": 7675,
          "sha512": "0ed00fe3dd4bc25bb538e0a14361731e34f5fae2ddc78911937bb733c0a00db15f25bba9c2c68b3a15ccaea3ce7b64fb3b2d8910bed47a6424d7f5e01cc971c1",
          "sha256": "7a2c49ecf165798cf1d414012edd3328a88cadeb8e82c0d932211ca159aff5f4",
          "sha1": "5065ed9653c44dee75135663c54f17cbf02c66a5",
          "md5": "bab6d8b943c6a38e88e704884401f167"
        }
      ]
    }
  ]
}
