{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.26/contract-0.0.26.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.26.jar",
          "url": "contract-jvm-0.0.26.jar",
          "size": 17931,
          "sha512": "a68eec2eb2450b6d15b03793549fb6115a51054c80114659c8b7b33cf85422af65ac3b0604fad0b3d45c5c41fe3af40a02e65c88398864c3b067cb106f7f8268",
          "sha256": "4077097cd39d6125b4c6e5b4f8a4957e9db4e19103b19d1e89ad4f9305392f13",
          "sha1": "8bf74b752755266a36384a0c779a84c264dcca0c",
          "md5": "50c680a57d96037bf9451bb1ec5b0cbf"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.26.jar",
          "url": "contract-jvm-0.0.26.jar",
          "size": 17931,
          "sha512": "a68eec2eb2450b6d15b03793549fb6115a51054c80114659c8b7b33cf85422af65ac3b0604fad0b3d45c5c41fe3af40a02e65c88398864c3b067cb106f7f8268",
          "sha256": "4077097cd39d6125b4c6e5b4f8a4957e9db4e19103b19d1e89ad4f9305392f13",
          "sha1": "8bf74b752755266a36384a0c779a84c264dcca0c",
          "md5": "50c680a57d96037bf9451bb1ec5b0cbf"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.26/contract-metadata-0.0.26.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.26"
      }
    }
  ]
}
