{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha11/viewcontract-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "7g7z7ezk5vaxvor6gqfcljloxy"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosx64-1.0.0-alpha11.klib",
          "size": 26559,
          "sha512": "4c18357bea908adb774e2584ebc60786a78c1ab4b000fff4a3776e1b63e248f329262c0e872a8fbd241d43f75dcfac97ad991c02a140218d89987a24866cce59",
          "sha256": "1d453e0ee52ebe5620a2b799e3b12b16b845a1ab8e28806eb7f06ad6158f6b8a",
          "sha1": "430aaea0d58e550f0966860cfc2661a590344bf6",
          "md5": "d480dd3ac7c5383b7e9747878aa015e4"
        }
      ]
    }
  ]
}
