{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha15.jar",
          "url": "generator-1.0.0-alpha15.jar",
          "size": 192942,
          "sha512": "27bfe4cf16028a3908fb9b48668a1da0c1069d1c03ebe35f6a6ecd4740d2b6c5e7f1c302d6ee1e1ef76b9e6ab6383e7a72a5dbec0a1c574abf861435144dfde8",
          "sha256": "a3a280d65d7a1562414c0709619665a39bf3ba4aee316cea9d697248f26bd437",
          "sha1": "76e6c6688657f81f8157d6ec7fa56c0f1fd2927d",
          "md5": "95c168298364525f79affad08a549a0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha15.jar",
          "url": "generator-1.0.0-alpha15.jar",
          "size": 192942,
          "sha512": "27bfe4cf16028a3908fb9b48668a1da0c1069d1c03ebe35f6a6ecd4740d2b6c5e7f1c302d6ee1e1ef76b9e6ab6383e7a72a5dbec0a1c574abf861435144dfde8",
          "sha256": "a3a280d65d7a1562414c0709619665a39bf3ba4aee316cea9d697248f26bd437",
          "sha1": "76e6c6688657f81f8157d6ec7fa56c0f1fd2927d",
          "md5": "95c168298364525f79affad08a549a0e"
        }
      ]
    }
  ]
}
