{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.45.jar",
          "url": "contract-0.0.45.jar",
          "size": 8535,
          "sha512": "53bd34bc7e216691d5a84c17472f5771f18ae76cb13b90193d98138a8b11d80aab766b38b95a21c909fbc1b7d72d29172fb0ad3f9517457685aaf219e3110ee4",
          "sha256": "9f4913b097987cc3dd846cd5ac4cf9751b6dfa63f734b9893260323bf4fac27e",
          "sha1": "62aceb43d59824a3e12a75dc64ca02afd6656eb5",
          "md5": "68cb55619588aeff1d15d4dbcc3549e5"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../contract-iosarm64/0.0.45/contract-iosarm64-0.0.45.module",
        "group": "tech.skot",
        "module": "contract-iosarm64",
        "version": "0.0.45"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../contract-iosx64/0.0.45/contract-iosx64-0.0.45.module",
        "group": "tech.skot",
        "module": "contract-iosx64",
        "version": "0.0.45"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../contract-jvm/0.0.45/contract-jvm-0.0.45.module",
        "group": "tech.skot",
        "module": "contract-jvm",
        "version": "0.0.45"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../contract-jvm/0.0.45/contract-jvm-0.0.45.module",
        "group": "tech.skot",
        "module": "contract-jvm",
        "version": "0.0.45"
      }
    }
  ]
}
