{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.41/contract-0.0.41.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mg55xkylpzdfpow33thce6zcgu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.41.jar",
          "url": "contract-metadata-0.0.41.jar",
          "size": 8468,
          "sha512": "a890bbbe26b164f9655fa970c1751d9382f6be1c9901442de0e87e1ff94f15c59184295ad56ba268fc5d8b1fb33142b8457bded657af259a0a8d8d2ef8ba4768",
          "sha256": "5319c2abee210e7019d4de8b90f72b009a95f626e0bbf13b4532d38c5df4321f",
          "sha1": "b5113e23a436a9224db63da0183ce9d7b1b1ebf4",
          "md5": "7b26fbf145ec3cc082a25c8f3241cd4c"
        }
      ]
    }
  ]
}
