{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha5/modelcontract-1.0.0-alpha5.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha5.klib",
          "size": 14902,
          "sha512": "b711f17a2d8be9387df96052e0d9985d867d4093ca329ee37f235df4a0f276926acd0d1f7f50537a6d3b8391c9d044bcd217adeaa48cb858a6205f21d413213b",
          "sha256": "3c1a3620b339eeb97ea772101ff81e4087561c2ffb282d2b461471ed6857810f",
          "sha1": "7e4e7b65be87d27898510f61186b68cd44dd397a",
          "md5": "18c0dfe49bf3d8e578add0753838221e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../modelcontract-metadata/1.0.0-alpha5/modelcontract-metadata-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "modelcontract-metadata",
        "version": "1.0.0-alpha5"
      }
    }
  ]
}
