{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.1/model-0.0.1.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xev66rvdfzgj5boulrz2n5qhre"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.1.jar",
          "url": "model-metadata-0.0.1.jar",
          "size": 11377,
          "sha512": "31e1b6e4741ab7179dd687a366e66af35058aeb68e671e7086c0b9d36598827757bd04905b6124ef68c6e14ac56ba1a19634bb6ab0f064ff37e835032faa98f4",
          "sha256": "463b3397e0d16abf82c3277f23cb912bd334ac93af1321bcf0c686d309430611",
          "sha1": "aef4799a24c0d2ae573439010716845dd930dbac",
          "md5": "d062493b653812490e3a642502233e8c"
        }
      ]
    }
  ]
}
