{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rcsqc6iufne5ve6vpfzg2hyyae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.51.jar",
          "url": "generator-0.0.51.jar",
          "size": 94157,
          "sha512": "6bcbae64598ee3301f2d92e4ef0d3bb0583f37d556fb1356db013426cc9507c76791869049a8e5d3b680fbe4d3efb6b985ccd4d49762ed92a2ca965d672c4ac2",
          "sha256": "3d301c285ac5d3bcc9fa234200218a02b61a72860ff60d96271154646eeeaf12",
          "sha1": "86c6ac9e494c85ff28f0c94df8a15b00999f656b",
          "md5": "f34dd38778c99967c78faf153d6a1795"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.51"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.51.jar",
          "url": "generator-0.0.51.jar",
          "size": 94157,
          "sha512": "6bcbae64598ee3301f2d92e4ef0d3bb0583f37d556fb1356db013426cc9507c76791869049a8e5d3b680fbe4d3efb6b985ccd4d49762ed92a2ca965d672c4ac2",
          "sha256": "3d301c285ac5d3bcc9fa234200218a02b61a72860ff60d96271154646eeeaf12",
          "sha1": "86c6ac9e494c85ff28f0c94df8a15b00999f656b",
          "md5": "f34dd38778c99967c78faf153d6a1795"
        }
      ]
    }
  ]
}
