{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha62/modelcontract-1.0.0-alpha62.module",
    "group": "com.github.skot-framework.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.2-native-mt",
            "requires": "1.5.2-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha62.klib",
          "size": 32698,
          "sha512": "0fe18b775b8f27b2fdde7105e86f537d3d447aca0dbfe75782d404e121f79a01a23fd06d884cfdcea04ac4b6f32c20f306d7473919f5bb52ae78cf7410a3885e",
          "sha256": "4304992432cea02ac2bb23369008c5299a3467b29bc86f12fa8efc65d4656868",
          "sha1": "18750429a0ead772df9f6d6d9549d88f6064acba",
          "md5": "afeec770bf1f71ca6312b0c76d9fd1bf"
        }
      ]
    }
  ]
}
