{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha20.jar",
          "url": "viewmodel-1.0.0-alpha20.jar",
          "size": 15278,
          "sha512": "18cb144e238b0339731a0ac96bac8f5a31712482acbbc6b0b9ba5668f7d42515f3d6d8cb901edd6c9e34b5a46dc6f3bb9bb3909dbe687f557b3716c269c1e4b1",
          "sha256": "495968b471dd3705a3a2f8fe8ca5129537580aa57fbef66b541eeb123c09725b",
          "sha1": "dc1bda3eadcdc263dd5dd74cae2b2a0e3f56f353",
          "md5": "a0ed304293b8ebcd83e17e6261a9ce14"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha20/viewmodel-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha20/viewmodel-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha20/viewmodel-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha20/viewmodel-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha20"
      }
    }
  ]
}
