{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha26/viewcontract-1.0.0-alpha26.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha26.klib",
          "size": 40151,
          "sha512": "ac6bcad12a8bda6064d7568a90d7531400ed281c52fcf0c3bee685df4e181296d0646031b88fe2a8df5b5e25b698131d902b0923f74504a3f02b83ae07cc1277",
          "sha256": "ec50fbece3e59662adcb9da20531ee20b2c0447ecc2cfdbe9ce0c1cb1ff43b42",
          "sha1": "3e346ab039914d6941ed9af42bf818ef9f278a1f",
          "md5": "487959962d78e6f7ff0078193d82476c"
        }
      ]
    }
  ]
}
