{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha12.jar",
          "url": "generator-1.0.0-alpha12.jar",
          "size": 170308,
          "sha512": "cf3e57be9286378fe49c80cbf63ba491ea1b3b826ab6ef953391aec0d712d85261ab4d7d327d5bdc772dee4f613d67ef32e358d34a78b3f4c75917108e8d63f4",
          "sha256": "15aef4916f718c2b5ae11d19047cc76a801c4fbde981b6d93cf4f201ef1c33de",
          "sha1": "76296e021a951c7b61c1cb0a3fb6f888f6739a34",
          "md5": "ebc5b00e76d32663c02078605fcfa603"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha12.jar",
          "url": "generator-1.0.0-alpha12.jar",
          "size": 170308,
          "sha512": "cf3e57be9286378fe49c80cbf63ba491ea1b3b826ab6ef953391aec0d712d85261ab4d7d327d5bdc772dee4f613d67ef32e358d34a78b3f4c75917108e8d63f4",
          "sha256": "15aef4916f718c2b5ae11d19047cc76a801c4fbde981b6d93cf4f201ef1c33de",
          "sha1": "76296e021a951c7b61c1cb0a3fb6f888f6739a34",
          "md5": "ebc5b00e76d32663c02078605fcfa603"
        }
      ]
    }
  ]
}
