{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.14/view-0.0.14.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.14.jar",
          "url": "view-metadata-0.0.14.jar",
          "size": 5556,
          "sha512": "cf3993b778d74a4a4f86d36c43e1c3444ffa6a88aae685940cb652430d749ed2e54e3745b5d607e5efff05fb10578c4cf5451a83665fb5d094fff51386188149",
          "sha256": "8ab40ae2c6390535cd64f022334d170c169c178cc4e9569173ca408099fa6725",
          "sha1": "774af0ed5c5299bfba0915c506b566076a96ccfc",
          "md5": "70441507f7d96655737ee8112ab4a061"
        }
      ]
    }
  ]
}
