{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.11.jar",
          "url": "generator-0.0.11.jar",
          "size": 92123,
          "sha512": "26531d251756d4e597b5c2d65ea5ea9c4f06ecf833543d311fb7a3593a089d77290f49038f54090e008f1fa33bfa5d11b455d627be6eec1846c38cd46310a632",
          "sha256": "c7873332932486794e8f468c1e467acba33dd7f4679a259e76eb1d9f3b182b39",
          "sha1": "03a5ef150741b339a55d14a482da3885e7108b94",
          "md5": "8b3e8fa173a625776abcba79a333f371"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.11.jar",
          "url": "generator-0.0.11.jar",
          "size": 92123,
          "sha512": "26531d251756d4e597b5c2d65ea5ea9c4f06ecf833543d311fb7a3593a089d77290f49038f54090e008f1fa33bfa5d11b455d627be6eec1846c38cd46310a632",
          "sha256": "c7873332932486794e8f468c1e467acba33dd7f4679a259e76eb1d9f3b182b39",
          "sha1": "03a5ef150741b339a55d14a482da3885e7108b94",
          "md5": "8b3e8fa173a625776abcba79a333f371"
        }
      ]
    }
  ]
}
