{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract-jvm/1.0.0-alpha5/viewcontract-jvm-1.0.0-alpha5.module",
    "group": "tech.skot",
    "module": "viewcontract-jvm",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-metadata-1.0.0-alpha5.jar",
          "url": "viewcontract-metadata-1.0.0-alpha5.jar",
          "size": 11133,
          "sha512": "ea9ead65a883d0d818615889a232705bbd7bfae613d3487e4453ca3ae30facd3c02994c686dfc463ef6b48e34116f41c124d3183e7c0ab428a3021e375e42264",
          "sha256": "e16b20c615195d1f0be262a795c2775086a394d86d11e09df52d58c2051bdf22",
          "sha1": "c872ee81bd0a624131ada1cf119c9864aa950e83",
          "md5": "0391f4ebda314b60c867b6cf85cfd34a"
        }
      ]
    }
  ]
}
