{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha19/viewcontract-1.0.0-alpha19.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha19.jar",
          "url": "viewcontract-jvm-1.0.0-alpha19.jar",
          "size": 54498,
          "sha512": "cc663b2172abc42541fb902e79f4226dea903bc4c1c48d2be6feb5b4cbc6dadf4bb7fd755af8099f4968115d3b1bee4c5e422a8321147fd408a22f23de5b5b0e",
          "sha256": "67215bc9b5118ae27058fff06145be727f25dbfcbba91e0af488d00b6de0d897",
          "sha1": "37bff9a403b887b42295572e5c25105825ff0110",
          "md5": "4f5c2cc3d68ef5dcfe6931fe1cba6353"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha19.jar",
          "url": "viewcontract-jvm-1.0.0-alpha19.jar",
          "size": 54498,
          "sha512": "cc663b2172abc42541fb902e79f4226dea903bc4c1c48d2be6feb5b4cbc6dadf4bb7fd755af8099f4968115d3b1bee4c5e422a8321147fd408a22f23de5b5b0e",
          "sha256": "67215bc9b5118ae27058fff06145be727f25dbfcbba91e0af488d00b6de0d897",
          "sha1": "37bff9a403b887b42295572e5c25105825ff0110",
          "md5": "4f5c2cc3d68ef5dcfe6931fe1cba6353"
        }
      ]
    }
  ]
}
