{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.10/model-0.0.10.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.10.jar",
          "url": "model-metadata-0.0.10.jar",
          "size": 11242,
          "sha512": "9b095c7746e7173f34062c15d152b83935defa08c2f90db807db7a9efc141d06d1c23723d3ebbb7e5b2c176bfc80c9ac201e3eab04d2805eb89b9dd28c47cc5c",
          "sha256": "653052d1f5a71d6d991a4da65d20c52b632d7bd2f20a59fd5d60014f5fc54340",
          "sha1": "5530d27f08b9bf1a8f11c381f43938644d4a00ee",
          "md5": "6a2e4c254496c1aa2ec9f345f7238b9b"
        }
      ]
    }
  ]
}
