{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha5.jar",
          "url": "core-1.0.0-alpha5.jar",
          "size": 6938,
          "sha512": "09134a6231cabcdf891e151826cd59a2c2549fed1fba9f59dba515dcbe977ffa28abf95a63ee7a7fb2320443db23a68095efc46fa6e670f9f5658f39e3a07725",
          "sha256": "578ed0909d0b121afacc5acf2d4ed65e6aa9390d51faf78015ddfbf2f088cd86",
          "sha1": "4e66b6fd4da222cbe9353d27c2d91ab50997d3d4",
          "md5": "28f353f35640344a28ba8b7c62be827e"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha5/core-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha5/core-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha5/core-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha5/core-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha5/core-iosarm64-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha5/core-iosx64-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha5"
      }
    }
  ]
}
