{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.48/core-0.0.48.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "adu4mcp7tnfvfaxt3d3ep6dpwa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.48.jar",
          "url": "core-jvm-0.0.48.jar",
          "size": 17701,
          "sha512": "b1406aef0a8fedc5b30f1aff3bad4e7a54740f9b2336cc15939b3f569e8e1e0e6d98a0231de8ffd2d2507d8f36eebf75e1e0fcd4cbfa02ee6ef8b62ac19eecfe",
          "sha256": "00439307b698a6fba3330f824ab065bd692e5c93ffecf3529bbf455cdd7481d1",
          "sha1": "cd9b462a0fcf49571c653ec1236a8450ea7ee6f8",
          "md5": "9167b68d8761ae778795136aceb0758d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.48.jar",
          "url": "core-jvm-0.0.48.jar",
          "size": 17701,
          "sha512": "b1406aef0a8fedc5b30f1aff3bad4e7a54740f9b2336cc15939b3f569e8e1e0e6d98a0231de8ffd2d2507d8f36eebf75e1e0fcd4cbfa02ee6ef8b62ac19eecfe",
          "sha256": "00439307b698a6fba3330f824ab065bd692e5c93ffecf3529bbf455cdd7481d1",
          "sha1": "cd9b462a0fcf49571c653ec1236a8450ea7ee6f8",
          "md5": "9167b68d8761ae778795136aceb0758d"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/0.0.48/core-metadata-0.0.48.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "0.0.48"
      }
    }
  ]
}
