{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha23.jar",
          "url": "generator-1.0.0-alpha23.jar",
          "size": 194050,
          "sha512": "17e96a1a3ccffe5c7f5adbc9ef91c0383b817756a4776188462cd035a22f68bdfdb72c2f97e30f9162a6adf0453d6b0456cc17012d5bf78251e279aacddd59b6",
          "sha256": "f9e0e3e1d014469de84364291dd6a7ea2506edd0c19b59e79491758a6d0db7ff",
          "sha1": "ea4ff955f388fb5f0a5e62d53562d6128994df41",
          "md5": "ecfe1415c9f8bb760452c91a7a14b34e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha23"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha23.jar",
          "url": "generator-1.0.0-alpha23.jar",
          "size": 194050,
          "sha512": "17e96a1a3ccffe5c7f5adbc9ef91c0383b817756a4776188462cd035a22f68bdfdb72c2f97e30f9162a6adf0453d6b0456cc17012d5bf78251e279aacddd59b6",
          "sha256": "f9e0e3e1d014469de84364291dd6a7ea2506edd0c19b59e79491758a6d0db7ff",
          "sha1": "ea4ff955f388fb5f0a5e62d53562d6128994df41",
          "md5": "ecfe1415c9f8bb760452c91a7a14b34e"
        }
      ]
    }
  ]
}
