{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.5/model-0.0.5.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5f2uil5yr5anjo2xrdrfwpkzma"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.5.jar",
          "url": "model-metadata-0.0.5.jar",
          "size": 11206,
          "sha512": "a18209bb9d3cd7654b89d27247bf24dfda71e01663ca9834805c785bb6f04e7f1f4caadc11c84ecb5f2993fc86e5a5365581ebeb289fd42e47b8f07a8fb84be",
          "sha256": "4918ccc737844990ef8d5826d4419840389e330fd85f48d5a8fb8038275dc33",
          "sha1": "922e33d3ab1b3a89d6ca95268446627231dbddb",
          "md5": "e3734372359d1f60a22a94586f13ad07"
        }
      ]
    }
  ]
}
