{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.37/contract-0.0.37.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6ad6ifprjjfd5g5alw3qha32pu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.37.jar",
          "url": "contract-jvm-0.0.37.jar",
          "size": 18620,
          "sha512": "c8fec9706e0dc9c54c1ddeff40f206110420b5dd3dd7078bd9bc9fd883b1171910e3642fd437afb96235d2d695c024ad441269c73d28ceb80f7328f6ca180b33",
          "sha256": "9c0612c22a38c015597e66891dafeae05320d454d0e74aa0652805ad6c1d9d77",
          "sha1": "3aa1d8e25cbdf6426ca742203720df231cb317e5",
          "md5": "704fdfa41c4a0371cc784c5f2db88c65"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.37.jar",
          "url": "contract-jvm-0.0.37.jar",
          "size": 18620,
          "sha512": "c8fec9706e0dc9c54c1ddeff40f206110420b5dd3dd7078bd9bc9fd883b1171910e3642fd437afb96235d2d695c024ad441269c73d28ceb80f7328f6ca180b33",
          "sha256": "9c0612c22a38c015597e66891dafeae05320d454d0e74aa0652805ad6c1d9d77",
          "sha1": "3aa1d8e25cbdf6426ca742203720df231cb317e5",
          "md5": "704fdfa41c4a0371cc784c5f2db88c65"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.37/contract-metadata-0.0.37.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.37"
      }
    }
  ]
}
