{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.45"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.45.jar",
          "url": "viewmodel-0.0.45.jar",
          "size": 7429,
          "sha512": "5924314efead7a7ba4f8def65998a4805a08f77fc4eff6a7b19553dab03bf1e12b95cbae3b7e5494cb6f3037039cfb09787ca632aa95fecc695f51fc0c5b8c3e",
          "sha256": "551eac1b108706161176a33e6337e212865bf59dab603e787542fa4ebde7953f",
          "sha1": "f1e5d861383d4724e5730973c155caf759b17b01",
          "md5": "47b2e29adc48c99e8a64bee89b4806b8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.45/viewmodel-android-0.0.45.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.45"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.45/viewmodel-android-0.0.45.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.45"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.45/viewmodel-android-0.0.45.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.45"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.45/viewmodel-android-0.0.45.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.45"
      }
    }
  ]
}
