{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.9/contract-0.0.9.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xtqqandxyva3tauucku2734sky"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.9.jar",
          "url": "contract-jvm-0.0.9.jar",
          "size": 15654,
          "sha512": "10f7386e941179702e1ea3506753969c61a70f869cd84e9be051f1d57228d451b44f2b05d3edbc825eca385ffffab02868f4830a67583dc0a89c93f5d3b38160",
          "sha256": "71f2590e2c1ff3132d400a6db01bbdf6910654efff63d6dd520dbdf6596cf2eb",
          "sha1": "61d9fc53abc47a30d4d8d4b06e5332a4ee33d06e",
          "md5": "d3d690a32a7dfe83aa307bf154f3514c"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.9.jar",
          "url": "contract-jvm-0.0.9.jar",
          "size": 15654,
          "sha512": "10f7386e941179702e1ea3506753969c61a70f869cd84e9be051f1d57228d451b44f2b05d3edbc825eca385ffffab02868f4830a67583dc0a89c93f5d3b38160",
          "sha256": "71f2590e2c1ff3132d400a6db01bbdf6910654efff63d6dd520dbdf6596cf2eb",
          "sha1": "61d9fc53abc47a30d4d8d4b06e5332a4ee33d06e",
          "md5": "d3d690a32a7dfe83aa307bf154f3514c"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.9/contract-metadata-0.0.9.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.9"
      }
    }
  ]
}
