{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.8/core-0.0.8.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5vu6ywwiijbhlbbtlao5nfwm2q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.8.jar",
          "url": "core-metadata-0.0.8.jar",
          "size": 4883,
          "sha512": "6ed38efcf7d4c9ef71461b22548fbba324a458536f6693c2baa795430deb1d709c1639231a292a7c7e1b2d0997ebaeab9728561dd34b1f17c7a32af84c9acbd",
          "sha256": "b18daa1147e0a3d5e6c546405ad4e2118f89a8346f32ce6dfd7fdf590e1f38f8",
          "sha1": "3390c85a3735cdee90c89c095a3b1f4abd214384",
          "md5": "f85d6e012a18c3a55bafad6bf8dc135"
        }
      ]
    }
  ]
}
