{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha4/core-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-1.0.0-alpha4-debug.aar",
          "size": 22056,
          "sha512": "775bb0e0903465de740cb17a9f248de729c7490316eb599c1a75b8ac8945c168ea03dec0a54a5a035d33f61b84e829384463e05f6a61ac3950acde5289aa8c18",
          "sha256": "1b4840072a0cd4411191e93b7a2ef6051325eaa717cd9ffb4534becbad65d06f",
          "sha1": "92610878074369243c5653ebca04866dcde8c625",
          "md5": "e078f73014d824680ec88b24bf776768"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-1.0.0-alpha4-debug.aar",
          "size": 22056,
          "sha512": "775bb0e0903465de740cb17a9f248de729c7490316eb599c1a75b8ac8945c168ea03dec0a54a5a035d33f61b84e829384463e05f6a61ac3950acde5289aa8c18",
          "sha256": "1b4840072a0cd4411191e93b7a2ef6051325eaa717cd9ffb4534becbad65d06f",
          "sha1": "92610878074369243c5653ebca04866dcde8c625",
          "md5": "e078f73014d824680ec88b24bf776768"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-1.0.0-alpha4.aar",
          "size": 21451,
          "sha512": "b4b3c2caab879408e707a7817c9c85b93313e1cf5b00b27b7147d37d231eed3d62a2a1d7a8269f7c2588aff5f1d498804b66d6802074f851384d75483a521510",
          "sha256": "3f7af300ef22edb9926edf97187f6f02d9609cfe2b14b0d8cdbf0a776368ab4b",
          "sha1": "6ae09fe5216bc174bbeb3301e1f4299142bcb671",
          "md5": "ca034e5cb0f592e82fe4a4a2334d2613"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-1.0.0-alpha4.aar",
          "size": 21451,
          "sha512": "b4b3c2caab879408e707a7817c9c85b93313e1cf5b00b27b7147d37d231eed3d62a2a1d7a8269f7c2588aff5f1d498804b66d6802074f851384d75483a521510",
          "sha256": "3f7af300ef22edb9926edf97187f6f02d9609cfe2b14b0d8cdbf0a776368ab4b",
          "sha1": "6ae09fe5216bc174bbeb3301e1f4299142bcb671",
          "md5": "ca034e5cb0f592e82fe4a4a2334d2613"
        }
      ]
    }
  ]
}
