{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.35/model-0.0.35.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "giu2xg36zfb4vbk5yuetpxzity"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.35"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.35.jar",
          "url": "model-metadata-0.0.35.jar",
          "size": 13166,
          "sha512": "396ab8c95d64c334943ab03d20c4638ccf95831a1cd04ee4c0baff204c80f414f086b5e0daa4f2a2b2ef3339088616c569672db6ef9926dfec6bd514f4b5350d",
          "sha256": "c42de9e4a63f8d0c2d4c5f7365a0c951ae6de3fa6dab7162c0a1269c754f201e",
          "sha1": "7c9071e0d6c4ffad13dfcde8762dbc6c30232a61",
          "md5": "3c29929bc5069c0a9db901bc7650f789"
        }
      ]
    }
  ]
}
