{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests-metadata",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.47.jar",
          "url": "androidTests-metadata-0.0.47.jar",
          "size": 261,
          "sha512": "c67ca710dc3897c4042c8e10d36891cfa874c9064cea17970c511056533eb640b2871ab53347733d3bdb4441f2496dd74d58dcd546e93e2a0025173aa39c401a",
          "sha256": "f2802772e327228aadb344fd49450639fb89dee7040a70ab6afaf6f245c4914e",
          "sha1": "59e5214c127f96be6f6c4848663efcfb2a836483",
          "md5": "3c71c8c698945b09c068119b09d3f6c4"
        }
      ]
    }
  ]
}
