{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.9/androidTests-0.0.9.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xtqqandxyva3tauucku2734sky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.9.jar",
          "url": "androidTests-metadata-0.0.9.jar",
          "size": 261,
          "sha512": "7f91a94bde17eb60ea18f54ecb2abbd7a8c0b7eaa5bfcf734bf45433b7c5782008d35b34b6991b9b89a97e8d8f773e02884f81ec62cb79f2702bd93e833554fb",
          "sha256": "dbe5814ed0df20b9cd35b8aaba0193121e3752735439676afe1b2f4a8801759f",
          "sha1": "b1932d27e3c7ae9309e306f797299d7fde25dca8",
          "md5": "795181fc752caedbfa553e1a9d9ae950"
        }
      ]
    }
  ]
}
