{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha22/viewcontract-1.0.0-alpha22.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosx64-1.0.0-alpha22.klib",
          "size": 39430,
          "sha512": "470f6f1f41807356b3d863e0857eee185e38393a5f937ae202b8d2e14ab05ed28a6bc3e7985c687880afb41e8f37aca103d289ddb352631f6a8eb5fab8ade513",
          "sha256": "75bc01de0b1a42cb362faa018c7cb75d2be23dc446e044bfd8ffa0f4a2421b8e",
          "sha1": "a29defa2fe8f203f7cbed1b13f53539fefae3601",
          "md5": "4ecf2c7bc0e2c105e531337d8c7c59ed"
        }
      ]
    }
  ]
}
