{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.10/contract-0.0.10.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.10.jar",
          "url": "contract-metadata-0.0.10.jar",
          "size": 7675,
          "sha512": "ad73a89f4e73bc7e1eb357d559d41703e6006c0dda55569e8bf85e2c680b17e00f9911f8b20e96fa6c681e5995f143724f1d7dcc6e7787c14cffb5ddc83555dc",
          "sha256": "e6158b1856d06b0d40887686eb5386ff51b793a38acbd73a510bf15b8963434f",
          "sha1": "3566b65821d0a5079af2c094f4982940dc2c016b",
          "md5": "c142da6bd0a484251960454b2564eac9"
        }
      ]
    }
  ]
}
