{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.14/contract-0.0.14.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3dorn7aqgzbq3owi6pxgrw7ncy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.14.jar",
          "url": "contract-metadata-0.0.14.jar",
          "size": 7170,
          "sha512": "95b1a55e559dcf002f4ee00916220effe82472632b22f8d02411ca8116ec7ae17c986d1f98a37e1a90e1aa6fcfbe65cece40995b2f4aa91a58c78eff3975649a",
          "sha256": "df29ab83a650453df8e4a579e962b60d66591d8633de4854f84fbfd9ebc64d60",
          "sha1": "e47ff1dd6645f56064388373e533d2f401813ff1",
          "md5": "383ace3e250a025f1290e392f406a311"
        }
      ]
    }
  ]
}
