{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.14/contract-0.0.14.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.14.jar",
          "url": "contract-metadata-0.0.14.jar",
          "size": 7170,
          "sha512": "57c262856f5289c34a8025736bf25420a545444533c890d5fe7d3747076d10f608e609d769e504f9073b0012f6d7e8ebbb97fe32ebe957b49b47f224af195c5a",
          "sha256": "0e4345976eb1107de9bddf9286e67d9fa4afea5632b2953ba364d9bd8cad0815",
          "sha1": "83352956ae9ff2a2a82234128361da855f47b3a1",
          "md5": "f2d5acc9adbd7dba9030d5f2b794d0f2"
        }
      ]
    }
  ]
}
