{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.26/viewmodel-0.0.26.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.26.jar",
          "url": "viewmodel-metadata-0.0.26.jar",
          "size": 6999,
          "sha512": "1a44ac954cd4fcc226ef6f45f433541cb503d5d20cfe8c126d6f753dc5a0401ed128ad7d67d503e94a4245757d624b5c1b6bda36a193e8db3a17c6ffd667e114",
          "sha256": "3db6c606d1a35476d9bfb7e23e855ee480554bffd72512e11042237800adb4d8",
          "sha1": "94fc8e1f1b4e7e82dfb3cc22167027073dd898da",
          "md5": "e4fd6154c884d4694bc2eac9da1cb411"
        }
      ]
    }
  ]
}
