{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.27/contract-0.0.27.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "7rpxctj73vafjppxfjwlavvutq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.27.jar",
          "url": "contract-metadata-0.0.27.jar",
          "size": 7614,
          "sha512": "bc72c1ea42c18b6b93dfe9cdc0c263abcc018504fede24873901e33cbf198c2eb1c03ad36bb74cc45374aa65d730dd9f8d37149c2a7928d98ec7b44fd7b076bc",
          "sha256": "e3005565dbf122e9663315217cb91c915b8cc0761dddb1b2f9dfe9d41147ad0e",
          "sha1": "250e27d2dba2d42ab5f4c7a264ac02036d05fd73",
          "md5": "2c6971404f9e17b485600e9b8b3285fd"
        }
      ]
    }
  ]
}
