{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-jvm/0.0.46/core-jvm-0.0.46.module",
    "group": "tech.skot",
    "module": "core-jvm",
    "version": "0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "2op6vpqzbfeszkvmuhojwr2oxe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.46.jar",
          "url": "core-metadata-0.0.46.jar",
          "size": 5341,
          "sha512": "ad38deed89eb5bee4d729e3f4b5300128d3aba8fa34398cf44eafce9e70cdd8344bc68fada66e08c843ee1e02fa5f35553a485db3393138596c7e87c32ad78bb",
          "sha256": "8850ae9851c5facc04c692a5f745765db102a4489a3b9c596323951165b1ffe5",
          "sha1": "1900cc7fffc66dff6fd68b0ea46270ddeedbcee8",
          "md5": "30d80014cbbe2d70fc526a27bf40657f"
        }
      ]
    }
  ]
}
