{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.3/viewmodel-0.0.3.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "su2tjwkhbbbjndaqanwwqcxe24"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.3.jar",
          "url": "viewmodel-metadata-0.0.3.jar",
          "size": 5530,
          "sha512": "7c2612faae130b58e6e28e93dfa6baf9f5b3b4faab227861296bd1bc79cc88306ed705624db9c989f0b0dd0a169e0555e5b86fb8a822312426e3ebb0d3c2bdc8",
          "sha256": "ce701f2125e88273a393e85fc26f9c2e8f62ebbc5fa86a4157768854e41ef017",
          "sha1": "b9f857b35c609111d2f9ec7470072c6776448240",
          "md5": "72e19bf936d84d3a4799a55dd455969d"
        }
      ]
    }
  ]
}
