{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.29/contract-0.0.29.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.29.jar",
          "url": "contract-metadata-0.0.29.jar",
          "size": 7614,
          "sha512": "9c706ccc59a38363c24ee0345ccd7bd5de12ec56903d57b9238cb4ac4f84cd58b1e374564495efc7f43ab737c3aedc774cc06703aecf117f309c35568d6072b6",
          "sha256": "aecdf14c1e1359f725e75e43ffe95915a1ceb59d1ee52c21cfe2b1bded7141f9",
          "sha1": "6da092b6722e0480af806b2a97f4e2b17ad9091a",
          "md5": "64414a4298ca8cba47bd83d1a441cb7c"
        }
      ]
    }
  ]
}
