{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.5/androidTests-0.0.5.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5f2uil5yr5anjo2xrdrfwpkzma"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.5.jar",
          "url": "androidTests-metadata-0.0.5.jar",
          "size": 261,
          "sha512": "ec1d4958e6ee82033c144b18815176857c3d262d3ed209eb69f54e90d219412d89cd206a9bb05a335a6b0c9fdbc1836d43e77a54ef6f9e2350f75517cc248ff9",
          "sha256": "9f0034e1a3036624b51b9a63db89ef66138686c800850e5a1e0747978dc8ea2d",
          "sha1": "aeb7bc09a3e5c319cddbbeadb4330395d6d3a3f9",
          "md5": "5002462665629c9f346a5f380716bf2"
        }
      ]
    }
  ]
}
