{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5q5bv5aktfh2fdqq25rjsv33bm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha8.jar",
          "url": "androidTests-1.0.0-alpha8.jar",
          "size": 261,
          "sha512": "0652cecfae0440b7956e42224abdd16f93655a812c06ac7e08ebfd3e07e758562168f1425c92f8004af6f3ff390db767aba095ffb68d84f0984fb2b701ba1371",
          "sha256": "4db75003db14695c0a688e021bf91286b605276720bac3d54c8731bd06e8eeb0",
          "sha1": "9c7e5492379d534a421026e09a6ccfe8d9f84633",
          "md5": "66080f664ea7a79aa22ed9ec05e80271"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha8/androidTests-android-1.0.0-alpha8.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha8"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha8/androidTests-android-1.0.0-alpha8.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha8"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha8/androidTests-android-1.0.0-alpha8.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha8"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha8/androidTests-android-1.0.0-alpha8.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha8"
      }
    }
  ]
}
