{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.28/contract-0.0.28.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.28.jar",
          "url": "contract-jvm-0.0.28.jar",
          "size": 17931,
          "sha512": "b221cd0a2049c1f3c109fb23717dc6cee9a30196d78a60f4ac35b92ad97874fec4ef201b474d3df8c6f4cdc4036de727b4f8563603d04c4f8a1f2a0878f5f5f3",
          "sha256": "506228fef29f2ecb1d5480a251c1c892fecec7d43e8ff0c43e407213a1f0eb8a",
          "sha1": "59862393330325a133ac1186344f7fce1e37eedc",
          "md5": "f8f6b2a4302f8ef01cfb9a6b9450f193"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.28.jar",
          "url": "contract-jvm-0.0.28.jar",
          "size": 17931,
          "sha512": "b221cd0a2049c1f3c109fb23717dc6cee9a30196d78a60f4ac35b92ad97874fec4ef201b474d3df8c6f4cdc4036de727b4f8563603d04c4f8a1f2a0878f5f5f3",
          "sha256": "506228fef29f2ecb1d5480a251c1c892fecec7d43e8ff0c43e407213a1f0eb8a",
          "sha1": "59862393330325a133ac1186344f7fce1e37eedc",
          "md5": "f8f6b2a4302f8ef01cfb9a6b9450f193"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.28/contract-metadata-0.0.28.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.28"
      }
    }
  ]
}
