{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.28/contract-0.0.28.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "t2w34ohvabccfdd6l3g4neepp4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.28.jar",
          "url": "contract-jvm-0.0.28.jar",
          "size": 17931,
          "sha512": "7dd4f735999dc155b398721ba3892c96a171c66b9a662f32f36f641ee37b15eb0b400c747c932f7a03efc89019540110f215e96931ed696830b032a436beeb41",
          "sha256": "4df38ec7547e928dd64d3d0724df88878815c9a7aa796734c7a8645eb83d28a8",
          "sha1": "727656be19543e43b6beeee4984f0b706d55e651",
          "md5": "7cfbea20a7924432155437a91b2a8984"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.28.jar",
          "url": "contract-jvm-0.0.28.jar",
          "size": 17931,
          "sha512": "7dd4f735999dc155b398721ba3892c96a171c66b9a662f32f36f641ee37b15eb0b400c747c932f7a03efc89019540110f215e96931ed696830b032a436beeb41",
          "sha256": "4df38ec7547e928dd64d3d0724df88878815c9a7aa796734c7a8645eb83d28a8",
          "sha1": "727656be19543e43b6beeee4984f0b706d55e651",
          "md5": "7cfbea20a7924432155437a91b2a8984"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.28/contract-metadata-0.0.28.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.28"
      }
    }
  ]
}
