{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.25.jar",
          "url": "generator-0.0.25.jar",
          "size": 92834,
          "sha512": "f9541912b9dbdf1b0a3e48c7fb0a67db69da967142a94ea707f374fb41d5590a65b32f607b4e04ee07ab5bcaf37c74fa3a73aba6ce24a6fa0fbbed7317651ca1",
          "sha256": "f58658cad5d9e1797a811853638d702b6961528cc5e46cabbbdbcc1eb5535ce0",
          "sha1": "bdc8a33824102b1fd42bb6da7cc148953b77a4bb",
          "md5": "765d9834ca667f0ed7be8b6009a24cf4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.25.jar",
          "url": "generator-0.0.25.jar",
          "size": 92834,
          "sha512": "f9541912b9dbdf1b0a3e48c7fb0a67db69da967142a94ea707f374fb41d5590a65b32f607b4e04ee07ab5bcaf37c74fa3a73aba6ce24a6fa0fbbed7317651ca1",
          "sha256": "f58658cad5d9e1797a811853638d702b6961528cc5e46cabbbdbcc1eb5535ce0",
          "sha1": "bdc8a33824102b1fd42bb6da7cc148953b77a4bb",
          "md5": "765d9834ca667f0ed7be8b6009a24cf4"
        }
      ]
    }
  ]
}
