{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.1/contract-0.0.1.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ufjfxwzc2be2tauzgvpgjsfwqm"
    }
  },
  "variants": [
    {
      "name": "ios-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract.klib",
          "url": "contract-ios-0.0.1.klib",
          "size": 17761,
          "sha512": "9352fa3870f0bb8644639433ce89618f0db1c416b70b9a872a17e6f882ca0c47e1d83cb6e1bc2602999de92bb7104411ab595344ab662be065d6eb9b6ba6fc0d",
          "sha256": "1e8109500ed35edbe77cf30d63dcdc631f31724f2e6bd3970ba0cc1f4f1ee5b8",
          "sha1": "deea60e5838d770dedb2bd1f611b0a9b6576df19",
          "md5": "2cdab1090e5b7ad936a1ef1d8eb8dfb8"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.1/contract-metadata-0.0.1.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.1"
      }
    }
  ]
}
