{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.34/view-0.0.34.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sdiuqgpfpvgqbhgb64jk7k3g3u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.34"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.34.jar",
          "url": "view-metadata-0.0.34.jar",
          "size": 6294,
          "sha512": "ce6f07e308458526feed9fc51a096fafe9f6870a9bb12b5fe9aff3ac8af8d91b2b391c2e99d6812acc23548f9e72a83359f0de7832ff0c356689e883896f6c4e",
          "sha256": "044b03c187b2a87a4f11800cc14ca9c16cfd155812e035565e1f7d3ada4e1017",
          "sha1": "f6d4dc0a2a730d9f13f83844db6e46457e57eb12",
          "md5": "d9c8fc52e619d00c03091769a159d8b6"
        }
      ]
    }
  ]
}
