{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yshs27cbmzfrdgxafso6bc577q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.21.jar",
          "url": "generator-0.0.21.jar",
          "size": 92131,
          "sha512": "8fcbbef3254ec6d5b3d7615f23c21346b192f92084f148ef290d6d2737a8bdb3fae2e54ba04e6554344285f34a52f0ff78c35a636441b2676d2346d573e1bb69",
          "sha256": "a8abf325189a20c5f070f175db16510a954a631361e9ec7d481282227f69afc6",
          "sha1": "003e5f2cd7f8b6186402e4efc457e77f89cee607",
          "md5": "8aff455d67ef3740548dc6cce75a37e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.21.jar",
          "url": "generator-0.0.21.jar",
          "size": 92131,
          "sha512": "8fcbbef3254ec6d5b3d7615f23c21346b192f92084f148ef290d6d2737a8bdb3fae2e54ba04e6554344285f34a52f0ff78c35a636441b2676d2346d573e1bb69",
          "sha256": "a8abf325189a20c5f070f175db16510a954a631361e9ec7d481282227f69afc6",
          "sha1": "003e5f2cd7f8b6186402e4efc457e77f89cee607",
          "md5": "8aff455d67ef3740548dc6cce75a37e0"
        }
      ]
    }
  ]
}
