{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.42/contract-0.0.42.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cfo2qvt3ynagjbvfb6ksv22jki"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.42.jar",
          "url": "contract-jvm-0.0.42.jar",
          "size": 20546,
          "sha512": "360aab0b8e538292f6d11be23db43d50fdcd61a2f9963e622532a03e07efec94ddf40889108a05a733697814864da67f1f81bd98b6d571af9a501d9a309685ad",
          "sha256": "e3b4b9d5339c8002a081fb51a422fc3255bc6bc531d7c90fe82a9cbb6f7cdf11",
          "sha1": "0b0d2cc397f95a6b09e0a57ac9d1bae3e9fb2a27",
          "md5": "62ba3122ea3d26035ea41aa20930b338"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.42.jar",
          "url": "contract-jvm-0.0.42.jar",
          "size": 20546,
          "sha512": "360aab0b8e538292f6d11be23db43d50fdcd61a2f9963e622532a03e07efec94ddf40889108a05a733697814864da67f1f81bd98b6d571af9a501d9a309685ad",
          "sha256": "e3b4b9d5339c8002a081fb51a422fc3255bc6bc531d7c90fe82a9cbb6f7cdf11",
          "sha1": "0b0d2cc397f95a6b09e0a57ac9d1bae3e9fb2a27",
          "md5": "62ba3122ea3d26035ea41aa20930b338"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.42/contract-metadata-0.0.42.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.42"
      }
    }
  ]
}
