{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.21/model-0.0.21.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yshs27cbmzfrdgxafso6bc577q"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.21-debug.aar",
          "size": 94026,
          "sha512": "04c716eb17f5759cca019e13e14dc719fdfd2ad5011fb3aee14f4df21c458359a0d165693bb313e86c6dd77602663c1d602ac9d1535b20a90327138635b58de5",
          "sha256": "fd15bced59cfc021b34811bbab25565fc8d44d5194c675278d114f81e334f821",
          "sha1": "26f82a84fef4cf9bf6fb60d51d0d73ef9d615eba",
          "md5": "339abf5f3e167be8c92d5095a023a79e"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.21-debug.aar",
          "size": 94026,
          "sha512": "04c716eb17f5759cca019e13e14dc719fdfd2ad5011fb3aee14f4df21c458359a0d165693bb313e86c6dd77602663c1d602ac9d1535b20a90327138635b58de5",
          "sha256": "fd15bced59cfc021b34811bbab25565fc8d44d5194c675278d114f81e334f821",
          "sha1": "26f82a84fef4cf9bf6fb60d51d0d73ef9d615eba",
          "md5": "339abf5f3e167be8c92d5095a023a79e"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.21.aar",
          "size": 90205,
          "sha512": "d32ab1361cd8211ef77b0a961d29447838c6f5dbff46ee93acb568317c652c00885b5154ece999e3595f028a11f44aff04b5d6836c643e5f2ddf3530727ee11e",
          "sha256": "d80616f900d5ec2330d2a6329fb19feaa086b8d8133d98f1552aa483cd3dadac",
          "sha1": "63e6094a8b6564f910f29f7e189bb10dd57759d3",
          "md5": "49e73355db12549dd03398e8094faae9"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.21.aar",
          "size": 90205,
          "sha512": "d32ab1361cd8211ef77b0a961d29447838c6f5dbff46ee93acb568317c652c00885b5154ece999e3595f028a11f44aff04b5d6836c643e5f2ddf3530727ee11e",
          "sha256": "d80616f900d5ec2330d2a6329fb19feaa086b8d8133d98f1552aa483cd3dadac",
          "sha1": "63e6094a8b6564f910f29f7e189bb10dd57759d3",
          "md5": "49e73355db12549dd03398e8094faae9"
        }
      ]
    }
  ]
}
