{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.21/model-0.0.21.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yshs27cbmzfrdgxafso6bc577q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.21.jar",
          "url": "model-metadata-0.0.21.jar",
          "size": 13100,
          "sha512": "ccd92181c32d17ff8581a668bbc22348155e9f0562502a3edfbaf1209b96f95561aa59c4d5d810ef4ddf2c3c256729784bf91942e013bd3a1d9ff05b6c3e6cd4",
          "sha256": "dd147cce9296697314186caf059b3dcc48bc882b4294b8c553106da7b4cb31de",
          "sha1": "23383f787ef1babe457d70bce0bc1ca76a26e9a9",
          "md5": "e6ea77c6b1a3d0cf6cc82dcfc5b3c7c0"
        }
      ]
    }
  ]
}
