{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha12/viewcontract-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosx64-1.0.0-alpha12.klib",
          "size": 35917,
          "sha512": "a93150dc659a6947c5172b116f37f800f1b97e051317be47d6cc0a9e77cf05208b9411069018512eb5960258e3e9832631ef0316a42dd5295356fa8833079f62",
          "sha256": "2994b15230f4d8c4187aa9f7bc51210b95a9e5ecb70aa451ec4cafdf4c188617",
          "sha1": "913940ab32caca6e402420ab4f260eef0a27c3f9",
          "md5": "ea5c8834c653e114bcba59593998652b"
        }
      ]
    }
  ]
}
