{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.41/androidTests-0.0.41.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "mg55xkylpzdfpow33thce6zcgu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.41.jar",
          "url": "androidTests-metadata-0.0.41.jar",
          "size": 261,
          "sha512": "5c7a738e60b96cbedf3eb6f76293c5c54ceee12d066a61d8e31ae9aa499a71bd4076df92e82679f86148e85ac2519242e5aef93cbe21f3b4b12daba72699b294",
          "sha256": "2b34e5186e5ff5ea32cb592ca5220c326456286134419d80c24dd2d2fe485b09",
          "sha1": "161352a71a5e420d673eae49da64eb794258f3d7",
          "md5": "85987cf9732485c6fde60f20423898ce"
        }
      ]
    }
  ]
}
