{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.14/core-0.0.14.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3dorn7aqgzbq3owi6pxgrw7ncy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.14.jar",
          "url": "core-metadata-0.0.14.jar",
          "size": 5327,
          "sha512": "7f67c210ac98c316d028418181cf9f28e64408312cbfaf24326548960817adbbc38242d2fd8286d0dc09637f0072888d384a73a82600958fff857ab748c0b21f",
          "sha256": "526867802cfaf28a9bd0454c4b28853ac167aaef785c1817cae957db9662492f",
          "sha1": "c39498d9b487987ab0cecc112e19d31630f34aca",
          "md5": "4f0f781d463c943c7395c68babfe3df0"
        }
      ]
    }
  ]
}
