{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.14/core-0.0.14.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.14.jar",
          "url": "core-metadata-0.0.14.jar",
          "size": 5327,
          "sha512": "bc5e034f33cb3f600b29734279e57d190facab6da83142fa50b3cf29730923cf68d738770843f01653e30a481ffa44aec488605f5fa3104c82e031730cfec904",
          "sha256": "6bba30444123936c7fd5c6c0e13b0b1f7eecd8ba7e0e7cbdb422acd3a9dbfac0",
          "sha1": "a5e12377d79a22137fda5fdb018eb3e31e50df4c",
          "md5": "dc5dfe3dd6bf41b9ab2bb982989ae671"
        }
      ]
    }
  ]
}
