{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.6/contract-0.0.6.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3w2f7l7ypffvjgcalkwzywgyy4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.6.jar",
          "url": "contract-jvm-0.0.6.jar",
          "size": 15654,
          "sha512": "16d1993950caaf237bee0176890c829264b6c16afb50f76a383842497a0a13cee387f7383a5958e97c323115b0b1c3d244cb993cbe57f894db2717d9df37a36",
          "sha256": "a87ad53bdc81a436c26c9c6dbf4076c5e55b9000b924fd7b077ad99e6da7fdc6",
          "sha1": "9d2311e54cb8339d93403aded9c790a559800dc2",
          "md5": "5ae3b07a0c54557bea2449deec5830f6"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.6.jar",
          "url": "contract-jvm-0.0.6.jar",
          "size": 15654,
          "sha512": "16d1993950caaf237bee0176890c829264b6c16afb50f76a383842497a0a13cee387f7383a5958e97c323115b0b1c3d244cb993cbe57f894db2717d9df37a36",
          "sha256": "a87ad53bdc81a436c26c9c6dbf4076c5e55b9000b924fd7b077ad99e6da7fdc6",
          "sha1": "9d2311e54cb8339d93403aded9c790a559800dc2",
          "md5": "5ae3b07a0c54557bea2449deec5830f6"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.6/contract-metadata-0.0.6.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.6"
      }
    }
  ]
}
