{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewlegacy",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "biqopuycmjhqla5bue3ohogk3m"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-metadata-1.0.0-alpha14.jar",
          "url": "viewlegacy-1.0.0-alpha14.jar",
          "size": 261,
          "sha512": "f3922912a893201dba9e872c8fb363d53cfc1044cbfb03fea18c5e36fb758b3bfdd76bb3342f2b5cbaaf2a1e165c33cdcba01b7820b65a875153176a467ae3d8",
          "sha256": "0428eec2b329053ec5a3bf598fb698f1ad0c89a54a59a9fa427eaeea35242194",
          "sha1": "4e94a1e277d7e612bd141ff646b3cd5cc1fc4565",
          "md5": "53248d50573cdfe039b9a25b88e40cdf"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha14/viewlegacy-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha14/viewlegacy-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha14/viewlegacy-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha14/viewlegacy-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha14"
      }
    }
  ]
}
