{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha5.jar",
          "url": "generator-1.0.0-alpha5.jar",
          "size": 121574,
          "sha512": "b1391750e460af0023c688bf40db99bc433427d36930bea5c02295714ecdcf6cda5d6bd75831b0bf1a29000f9e777176a57f24085f9223599392053d114c3eb0",
          "sha256": "7c4e3faa90ab029f957240b9fdb10f962c6326a4999bc0a5941194cfc3d15b33",
          "sha1": "e6bf5d79d6fe6eb759ce5762f2a70456da6c37cf",
          "md5": "2064968d07841274f95de0cd996e91b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha5"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha5.jar",
          "url": "generator-1.0.0-alpha5.jar",
          "size": 121574,
          "sha512": "b1391750e460af0023c688bf40db99bc433427d36930bea5c02295714ecdcf6cda5d6bd75831b0bf1a29000f9e777176a57f24085f9223599392053d114c3eb0",
          "sha256": "7c4e3faa90ab029f957240b9fdb10f962c6326a4999bc0a5941194cfc3d15b33",
          "sha1": "e6bf5d79d6fe6eb759ce5762f2a70456da6c37cf",
          "md5": "2064968d07841274f95de0cd996e91b4"
        }
      ]
    }
  ]
}
