{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tgichq4ydfcfnbmsheeguc344q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.12.jar",
          "url": "generator-0.0.12.jar",
          "size": 92123,
          "sha512": "f08cbf7ce3529dfa658e0d3266b7ce15593839cf3d687f81e239da7d4f322c04c42289b30c8963be11086605c824c6079dbb0506d984e30737b936a85898aab7",
          "sha256": "bbfc40b76cba24696dd0c08a67b6d62a535ee1b324f92d6dd974b25a7976b2fb",
          "sha1": "bf0e743c58d65a4f1cce4f25f18b12cd9ff742ab",
          "md5": "7cc22fb2e961bfbdff9de5e7ad6b6fd9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.12"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.12.jar",
          "url": "generator-0.0.12.jar",
          "size": 92123,
          "sha512": "f08cbf7ce3529dfa658e0d3266b7ce15593839cf3d687f81e239da7d4f322c04c42289b30c8963be11086605c824c6079dbb0506d984e30737b936a85898aab7",
          "sha256": "bbfc40b76cba24696dd0c08a67b6d62a535ee1b324f92d6dd974b25a7976b2fb",
          "sha1": "bf0e743c58d65a4f1cce4f25f18b12cd9ff742ab",
          "md5": "7cc22fb2e961bfbdff9de5e7ad6b6fd9"
        }
      ]
    }
  ]
}
