{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.4/model-0.0.4.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qkfbndnh6jfalpfv2y37cujupm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.4.jar",
          "url": "model-metadata-0.0.4.jar",
          "size": 11206,
          "sha512": "cc9c949246b18879d6f79ab518f8e3527bafa3b631b850dce93df85afab8044cd73bd0565c6983daf9078167f250ed0e31473ab02df89ecc7aa403de289fb2e4",
          "sha256": "31b46290e878463f2f8eef0ff559a8d24fd4cbe691e5be5a058cf7cf703098df",
          "sha1": "f3f654076552f249b72802a4b8d1d7f49d68bb69",
          "md5": "28f7c1f6c2deb25b07cc3b82c04952e5"
        }
      ]
    }
  ]
}
