{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.40/contract-0.0.40.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "vudukgf34fdc3murg37da3g47e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.40.jar",
          "url": "contract-metadata-0.0.40.jar",
          "size": 8468,
          "sha512": "e0bb0d1e033b7442fb98aeabde6a36b93f21bc3ca42d159cf190bcada01c4ecc299191576200cb48e14121a4392934300e7e39d397f4cd469d7caed26b87d2c4",
          "sha256": "66551b7093968ce24022aab6c421ab85439e99c9181ed87ce8643e0261445fbd",
          "sha1": "e684bfe2f5ac0a94fd830565852d94ce8ae2bcfd",
          "md5": "75f0b76c56196328ab7f9d5aff340109"
        }
      ]
    }
  ]
}
