{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-metadata-1.0.0-alpha17.jar",
          "url": "modelcontract-1.0.0-alpha17.jar",
          "size": 6063,
          "sha512": "537ff855745073cd920aa16d909286406ba2aef1ec94ceedca2c7ae5cb5d2fcec11d64e35d324863dcdb3c0068863ff2f1345a048648dc90c904eb271dcfaa2a",
          "sha256": "8672c5711d79f66b8467d9b933de05e43ae2af7ad88d4bfc59ec4450de137f2e",
          "sha1": "3e3e2b8d1baa8b858e97a7b2454a9afb6082ba25",
          "md5": "1db9cf8a99fe6c8cbd4e520938dd368e"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosarm64/1.0.0-alpha17/modelcontract-iosarm64-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "modelcontract-iosarm64",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosx64/1.0.0-alpha17/modelcontract-iosx64-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "modelcontract-iosx64",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha17/modelcontract-jvm-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha17/modelcontract-jvm-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha17"
      }
    }
  ]
}
