{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.23/core-0.0.23.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h626lwyzk5cqpjrywyt6pslmqm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.23.jar",
          "url": "core-metadata-0.0.23.jar",
          "size": 5327,
          "sha512": "644d19b877702acaaacb75b75b1d01f64d7ce62ab69876fd4de5d055efabd7953a25dcfb3efa63f89f5eb524bf44818c3b2010cd1d8171ba1fa54feaf8263d49",
          "sha256": "12c0629a49a8e5524a792399160caaa9dd50ad6db0b0544f3d7a62f28843ca5f",
          "sha1": "1b1fbe7ced976d6e117a05bba621b21889ec3b67",
          "md5": "b37cb62e0e8eb6d973980a855ee8537b"
        }
      ]
    }
  ]
}
