{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.4/core-0.0.4.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qkfbndnh6jfalpfv2y37cujupm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.4.jar",
          "url": "core-metadata-0.0.4.jar",
          "size": 4883,
          "sha512": "c6bbb334fc7fcf37e0e79c0342d7e357e324a5992a770c8d97278fe1c7560744b4a72bb5dde58089995c92a6fa44a41710631c5c6175cb7102a75ba60c42ce50",
          "sha256": "5c80cb0ae78ac60fb753e000f0064fd17da1013f3dcb893e2c2ede314eb20ac5",
          "sha1": "5e43f202d596f5cda34c68eb28f8807d72e43371",
          "md5": "3e7d7cf3f3e85aeea3315ace1132b9d9"
        }
      ]
    }
  ]
}
