{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.13/viewmodel-0.0.13.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "kwtsmjyvlzbw3aguhyqjzuuf5m"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.13.jar",
          "url": "viewmodel-metadata-0.0.13.jar",
          "size": 6919,
          "sha512": "60c2b005ea3e37c52249bc6d4d9fce8b88a9d33b8d8a9031a954ece530db5c955e1eb1753ab9a5e46a9dc9bca50650b4603fb0c7c227f56e268375b5dcc8e539",
          "sha256": "497eabc433cb0e40addb09df8afa76344636312e875e8421be32f0ff8094c9fa",
          "sha1": "84c9ac22fdf483c75f2039a138168b5594ca0302",
          "md5": "4d8ac8fe22990c073a995b5f4a125461"
        }
      ]
    }
  ]
}
