{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.47/model-0.0.47.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.47-debug.aar",
          "size": 92535,
          "sha512": "0e0201da62faecc193eb2e57a2c8f0dc32abaace35ccfb0656dbac9cf2cd64cf6de97266e13bdb3948f6f81af3e9e4cd08ebbfa763935e4741c71f2cbe6f73ed",
          "sha256": "49cef038d905850bb1415b676a0c83b48ea8ed5db310e17e88f34491441bd1bb",
          "sha1": "193855c9af3f749a6cdfd5ac9aa4fffa225c96c9",
          "md5": "afd29f6c5d2d4e1737696e7eb9eca5b0"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.47-debug.aar",
          "size": 92535,
          "sha512": "0e0201da62faecc193eb2e57a2c8f0dc32abaace35ccfb0656dbac9cf2cd64cf6de97266e13bdb3948f6f81af3e9e4cd08ebbfa763935e4741c71f2cbe6f73ed",
          "sha256": "49cef038d905850bb1415b676a0c83b48ea8ed5db310e17e88f34491441bd1bb",
          "sha1": "193855c9af3f749a6cdfd5ac9aa4fffa225c96c9",
          "md5": "afd29f6c5d2d4e1737696e7eb9eca5b0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.47.aar",
          "size": 88754,
          "sha512": "448499af36d373f5c5c180a87340a56f0af3937c89c5f52eea56eb37fdc46327afb0226ebc9e71003ffae74545f2dbaf15c6f4d628250e0a44fc3a6a9c2354e9",
          "sha256": "26a7361ed3d5b86c6d372b2aa7731bf3daee66aa51bce7dcb1784ae0f090113e",
          "sha1": "4e7f5a5530ca6baf17b4128c7f0d0891e188261d",
          "md5": "c8fdc714ca12fc4d48df900a44ba0db9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.47.aar",
          "size": 88754,
          "sha512": "448499af36d373f5c5c180a87340a56f0af3937c89c5f52eea56eb37fdc46327afb0226ebc9e71003ffae74545f2dbaf15c6f4d628250e0a44fc3a6a9c2354e9",
          "sha256": "26a7361ed3d5b86c6d372b2aa7731bf3daee66aa51bce7dcb1784ae0f090113e",
          "sha1": "4e7f5a5530ca6baf17b4128c7f0d0891e188261d",
          "md5": "c8fdc714ca12fc4d48df900a44ba0db9"
        }
      ]
    }
  ]
}
