{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha4/viewcontract-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha4.jar",
          "url": "viewcontract-jvm-1.0.0-alpha4.jar",
          "size": 32928,
          "sha512": "e9f27a70ff354e24b43601de0740e733c214397b11c7ab3173c537e36926a2f69a6400231e9ed02e36ebb3a633729f6162984b880b0f9fd12f8daa6f45af1efd",
          "sha256": "bad690d6175586000e3e2558a75a3e4f552aee5aa3d55d96b2e88e6334501c3d",
          "sha1": "d4745d7313b9bff77859cd97e6bbc20938e095c0",
          "md5": "2840a7266473e75851e096350084441c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha4.jar",
          "url": "viewcontract-jvm-1.0.0-alpha4.jar",
          "size": 32928,
          "sha512": "e9f27a70ff354e24b43601de0740e733c214397b11c7ab3173c537e36926a2f69a6400231e9ed02e36ebb3a633729f6162984b880b0f9fd12f8daa6f45af1efd",
          "sha256": "bad690d6175586000e3e2558a75a3e4f552aee5aa3d55d96b2e88e6334501c3d",
          "sha1": "d4745d7313b9bff77859cd97e6bbc20938e095c0",
          "md5": "2840a7266473e75851e096350084441c"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../viewcontract-metadata/1.0.0-alpha4/viewcontract-metadata-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "viewcontract-metadata",
        "version": "1.0.0-alpha4"
      }
    }
  ]
}
