{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.26/contract-0.0.26.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.26.jar",
          "url": "contract-metadata-0.0.26.jar",
          "size": 7614,
          "sha512": "c144825427317c0a8c3000e9ab0e16132e186ba632c9e45f9422041cafa0f86cc90a0c6506737552de6d1b9cc39fe5d81d62a61aedbe87eeab671bd5e94de52f",
          "sha256": "5bc372f3c52a83d0785f7858ed404292e2892207d58fb33936316ef9ed68f55e",
          "sha1": "25ef37a77ee0e9286cb132acd7b5962df3022ac6",
          "md5": "32eee5ffe80074bd9dabf27b8628513c"
        }
      ]
    }
  ]
}
