{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha5/modelcontract-1.0.0-alpha5.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha5.jar",
          "url": "modelcontract-jvm-1.0.0-alpha5.jar",
          "size": 29719,
          "sha512": "1fdff453ed0c650278206af9d4814885fe5d9d43e9ffef0af68d823c99f07bf648820379052e4eb2697c1bd188c32936e8700bc4d2766427b1fe462f75566292",
          "sha256": "d2c3ab6fb5c1db7c913c155788605ca75f1e4c74c76f7ccb72bc81644bbd4790",
          "sha1": "9afc74bbd7fb8b46886402cbd9299adce92ca62f",
          "md5": "ca0f238ff782e4d67fa50836097f3561"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha5.jar",
          "url": "modelcontract-jvm-1.0.0-alpha5.jar",
          "size": 29719,
          "sha512": "1fdff453ed0c650278206af9d4814885fe5d9d43e9ffef0af68d823c99f07bf648820379052e4eb2697c1bd188c32936e8700bc4d2766427b1fe462f75566292",
          "sha256": "d2c3ab6fb5c1db7c913c155788605ca75f1e4c74c76f7ccb72bc81644bbd4790",
          "sha1": "9afc74bbd7fb8b46886402cbd9299adce92ca62f",
          "md5": "ca0f238ff782e4d67fa50836097f3561"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../modelcontract-metadata/1.0.0-alpha5/modelcontract-metadata-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "modelcontract-metadata",
        "version": "1.0.0-alpha5"
      }
    }
  ]
}
