{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.1/contract-0.0.1.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zk7tjfukpff7tmn3tiqtxdfuzy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.1.jar",
          "url": "contract-jvm-0.0.1.jar",
          "size": 14537,
          "sha512": "f4f1bfc705732ca339261bcd1bce20f125c6a3f6d18c601651e0d573d8bca413b3f9c98cefa9b6669f603d6e06a088162ddc4ad7f80c6d20ec7105e0a414f740",
          "sha256": "e95efcca8a5d3fd0739fedf2c37cc4c893972c8e7cfb2d475e685c996b13363",
          "sha1": "2833862d9992ce145774c3e7d990c54b03909fc8",
          "md5": "99442e48da448d043ea665df5bfd7cc0"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.1.jar",
          "url": "contract-jvm-0.0.1.jar",
          "size": 14537,
          "sha512": "f4f1bfc705732ca339261bcd1bce20f125c6a3f6d18c601651e0d573d8bca413b3f9c98cefa9b6669f603d6e06a088162ddc4ad7f80c6d20ec7105e0a414f740",
          "sha256": "e95efcca8a5d3fd0739fedf2c37cc4c893972c8e7cfb2d475e685c996b13363",
          "sha1": "2833862d9992ce145774c3e7d990c54b03909fc8",
          "md5": "99442e48da448d043ea665df5bfd7cc0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.1/contract-metadata-0.0.1.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.1"
      }
    }
  ]
}
