{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "adu4mcp7tnfvfaxt3d3ep6dpwa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.48.jar",
          "url": "androidTests-0.0.48.jar",
          "size": 261,
          "sha512": "7cf7e8c0031d7732490434ebc77ffc399857affc67a8f4f0f218b2d8a7f1987f4d7670c32a1ecea99dae127e242d62ec1a01c3cc95d85e6116a853cc75a2a610",
          "sha256": "c79b7134843d3df505683803077271719e8c63fe0ed0e99009b87fc16ba8042c",
          "sha1": "29a2e22ff15c798155ce8f0630876dd23f2c9c5d",
          "md5": "2459033b59d8b0e8b9f1b534d2b02092"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.48/androidTests-android-0.0.48.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.48"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.48/androidTests-android-0.0.48.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.48"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.48/androidTests-android-0.0.48.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.48"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.48/androidTests-android-0.0.48.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.48"
      }
    }
  ]
}
