{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.34/viewmodel-0.0.34.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sdiuqgpfpvgqbhgb64jk7k3g3u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.34.jar",
          "url": "viewmodel-metadata-0.0.34.jar",
          "size": 7418,
          "sha512": "01e55eb25b8fe934622f38676c2322f0f5d4d68783227d90c05dd88d501bb7cfb01144087d6d3ae3e856a5d87465ecc20d1015b3185702fdad2e44e38575a7a1",
          "sha256": "326b14c2b570be6090d9d4a21a63c8ad0d1e59f4e62ac3caae603b17439cbfab",
          "sha1": "371c5785fb41ea3bfa80f57b4b5269b4543ef3be",
          "md5": "30c4fb96f958312d6d6fbf135f64098a"
        }
      ]
    }
  ]
}
