{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha17/modelcontract-1.0.0-alpha17.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha17.jar",
          "url": "modelcontract-jvm-1.0.0-alpha17.jar",
          "size": 57610,
          "sha512": "d245880a21360adc683894edd53e26e2f3986368df7d0b8e8f3e072f9744e4326e88aece8e555beeea3bea1d57b7e9c7508b0696df9de5aed4f484298146b903",
          "sha256": "03a0c43a2cee6f7623512a2376aedc7c2c9e697c66eb4de73e2f5ae28e1c87fd",
          "sha1": "55181c47b754cdf4713b9c2e6ff479f0b714a31e",
          "md5": "ab0a50f9512be6474bb7d275259894a5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha17.jar",
          "url": "modelcontract-jvm-1.0.0-alpha17.jar",
          "size": 57610,
          "sha512": "d245880a21360adc683894edd53e26e2f3986368df7d0b8e8f3e072f9744e4326e88aece8e555beeea3bea1d57b7e9c7508b0696df9de5aed4f484298146b903",
          "sha256": "03a0c43a2cee6f7623512a2376aedc7c2c9e697c66eb4de73e2f5ae28e1c87fd",
          "sha1": "55181c47b754cdf4713b9c2e6ff479f0b714a31e",
          "md5": "ab0a50f9512be6474bb7d275259894a5"
        }
      ]
    }
  ]
}
