{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "542d3vhgfrhaxgd5li4auko6d4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha14.jar",
          "url": "viewmodel-1.0.0-alpha14.jar",
          "size": 15146,
          "sha512": "f745eecf495df180ea89ad6cfd26ecc3c8bb3fcb0c9952302bb84b775f6ae465d3dcbb198bdd4308742039a5ba77718ef99b14849f9b83a6fe2df77798f261b4",
          "sha256": "6811a8ee5f58332ea2e72f10e59b4496ba55ccf8821f06ffad9b977695023f9d",
          "sha1": "590c0b6137365c04d8efc745898b2c0d0d2c3471",
          "md5": "32dfab34d6d6491c93e20facafb604a0"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha14/viewmodel-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha14/viewmodel-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha14/viewmodel-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha14/viewmodel-android-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha14"
      }
    }
  ]
}
