{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "viewcontract",
    "version": "1.0.0-iosalpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-metadata-1.0.0-iosalpha62.jar",
          "url": "viewcontract-1.0.0-iosalpha62.jar",
          "size": 20316,
          "sha512": "f1ad40c0a7a988ec1211f4bf4a2e0cd0a88d831d445c268c18af111288b4ee6d1856d57a5e56efd7f6a786c00fa4211b58894b62aa8ba6e261d9c64ff835610b",
          "sha256": "9e0b882ba2ec354dac6ca5f2f647125b89736cd951fbcd3be76af532ff3b6080",
          "sha1": "d6cf8488da07c13e81957b1ee31d7ea065f326eb",
          "md5": "10162051a5d4d75924c1dfe79d8480d0"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosarm64/1.0.0-iosalpha62/viewcontract-iosarm64-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewcontract-iosarm64",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosx64/1.0.0-iosalpha62/viewcontract-iosx64-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewcontract-iosx64",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-iosalpha62/viewcontract-jvm-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-iosalpha62/viewcontract-jvm-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-iosalpha62"
      }
    }
  ]
}
