{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha16.jar",
          "url": "androidTests-1.0.0-alpha16.jar",
          "size": 261,
          "sha512": "f23ee64a3b8e326fae74d41061c806de71e5d115fb64f98c36b13f9d508eb430cca36205d92d8efeea99cca3f8c952809c437e2359d0f8ca829fa2a4b9886a67",
          "sha256": "edbfc3faa0b769dbf8dd279966e4b76e67e1648c4cbca011f17282342aeaa3ad",
          "sha1": "232a625ad9f02e06f47c50ba9a1d7dcdfe5cbb38",
          "md5": "05063b6d53822f4026b4d14bcc2443d0"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha16/androidTests-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha16/androidTests-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha16/androidTests-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha16/androidTests-android-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha16"
      }
    }
  ]
}
