{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "t2w34ohvabccfdd6l3g4neepp4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.28.jar",
          "url": "generator-0.0.28.jar",
          "size": 92895,
          "sha512": "47c73b46a789ad5650244e1abb2a6a9670be75d87895b7efee49bd77fe76c0be231f2e71d0a3fac97ea720eefcc9f79f10724224f00d2f3774e00792229d3311",
          "sha256": "61a2fb057b605c7f4e12442a06f7d9fda61cb68038da44001312a2b16ee49595",
          "sha1": "b6a732cf3984490b0c1a969068e7c9b1922755bf",
          "md5": "c05f6211327116df5689c4daccf17f89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.28.jar",
          "url": "generator-0.0.28.jar",
          "size": 92895,
          "sha512": "47c73b46a789ad5650244e1abb2a6a9670be75d87895b7efee49bd77fe76c0be231f2e71d0a3fac97ea720eefcc9f79f10724224f00d2f3774e00792229d3311",
          "sha256": "61a2fb057b605c7f4e12442a06f7d9fda61cb68038da44001312a2b16ee49595",
          "sha1": "b6a732cf3984490b0c1a969068e7c9b1922755bf",
          "md5": "c05f6211327116df5689c4daccf17f89"
        }
      ]
    }
  ]
}
