{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.28.jar",
          "url": "generator-0.0.28.jar",
          "size": 93268,
          "sha512": "553194f8c0e9461928726157bada3dcb53ef6839ab18def1ecff119f69ed84112508a241deb5051371967101e51c97ac86971dd75de7447a4b8555912b9aeecd",
          "sha256": "2156fa9a8428852cea384df75f3396af7e8750bf845a3f68cc816c8cf568987c",
          "sha1": "ff02d340c16814ba23f8fd2becf2b0aeb0b15ac2",
          "md5": "410450f2675f9565cd82dd08b4a6fb09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.28.jar",
          "url": "generator-0.0.28.jar",
          "size": 93268,
          "sha512": "553194f8c0e9461928726157bada3dcb53ef6839ab18def1ecff119f69ed84112508a241deb5051371967101e51c97ac86971dd75de7447a4b8555912b9aeecd",
          "sha256": "2156fa9a8428852cea384df75f3396af7e8750bf845a3f68cc816c8cf568987c",
          "sha1": "ff02d340c16814ba23f8fd2becf2b0aeb0b15ac2",
          "md5": "410450f2675f9565cd82dd08b4a6fb09"
        }
      ]
    }
  ]
}
