{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.39/androidTests-0.0.39.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "wulvo6iqbzfl3evraorhz65oge"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.39.jar",
          "url": "androidTests-metadata-0.0.39.jar",
          "size": 261,
          "sha512": "fa1e14238c0efa7c040a609b2f3ebc377de12236df82540d9c884620c1fac4a293c368db31bec349989b929f783782de257a1d37f34737b6d9fae0c5a21c84c1",
          "sha256": "36492e23e897c2d387e916c47db09537e44f464d31f1a373d0ae4436abf4e883",
          "sha1": "ac67d072a8e612e46f62d7f7fd53207366c72d16",
          "md5": "d86cd95b7e4ebd9cdb3ca0292deee2bf"
        }
      ]
    }
  ]
}
