{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.42/view-0.0.42.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cfo2qvt3ynagjbvfb6ksv22jki"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.42"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.42.jar",
          "url": "view-metadata-0.0.42.jar",
          "size": 6294,
          "sha512": "1d43aeccb06f0ab68e159c37000f6b967ea04f7ed6cf8d88a5d8f33b1c63ceb08c8525afa0b7f8e0f491745f5490dc8fe8003c97ddf38c33c39acc100a08c093",
          "sha256": "4615032cf019c46a0a52c471abbce4056b263cc57e8ac6e2fa13b4d6fa6f0052",
          "sha1": "7547bf23808b70ca2dcde6e81b10afd1bd4c605a",
          "md5": "8f76822a2ccaa8aef51c01badacb155d"
        }
      ]
    }
  ]
}
