{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h2qswlibvbgzncub57ri5633aa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.50.jar",
          "url": "contract-0.0.50.jar",
          "size": 8537,
          "sha512": "c7cff651e9f0693d104ab348284f66f2caa9c377afd415de73a17c367beda2cbae0124558d1a1be7f1c0fcc7b36e002447180ff2678236d6c9cfb946ed041bec",
          "sha256": "d611199126ce379aa6ac1efb8f8e8a02d6c9082171a0b0a7b882f0695c24f96d",
          "sha1": "948ceea5ba66c467382e792afcd7aa55e991fc06",
          "md5": "3837ea86c41b5ca4d8684335268d2e49"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../contract-iosarm64/0.0.50/contract-iosarm64-0.0.50.module",
        "group": "tech.skot",
        "module": "contract-iosarm64",
        "version": "0.0.50"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../contract-iosx64/0.0.50/contract-iosx64-0.0.50.module",
        "group": "tech.skot",
        "module": "contract-iosx64",
        "version": "0.0.50"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../contract-jvm/0.0.50/contract-jvm-0.0.50.module",
        "group": "tech.skot",
        "module": "contract-jvm",
        "version": "0.0.50"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../contract-jvm/0.0.50/contract-jvm-0.0.50.module",
        "group": "tech.skot",
        "module": "contract-jvm",
        "version": "0.0.50"
      }
    }
  ]
}
