{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.25/androidTests-0.0.25.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.25.jar",
          "url": "androidTests-metadata-0.0.25.jar",
          "size": 261,
          "sha512": "ace93281cb9fb989cce2646ba4651a560253c234eb5442658be063f4c3a5855459f282800c4870c24170247276c8cd4869d28ec135bac55a8992470fe155a21f",
          "sha256": "0d749eef1da7f12e1cd6d9d1d6e5c83a53ace364f9f02cfb211c82f4c00af21f",
          "sha1": "b45f0c4c8af5ec496df6f04fb1eb2e57272507c7",
          "md5": "d3efef53f02eb8752ab59bc5431b11b2"
        }
      ]
    }
  ]
}
