{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/1.0.0-alpha11/model-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "model.klib",
          "url": "model-iosx64-1.0.0-alpha11.klib",
          "size": 48125,
          "sha512": "eef026386fd4e1c7253ab53dc7794e6504ec2a6943e7b5ac22106c706117c83d8e71784e04264e40e70e80735d79865d0fd7716a34fea92a2114a4c54d210715",
          "sha256": "126f880fbfa83b166e6c8a5d7542c2d61ebb9c2c364e88b1c16a4cc70e79cbcd",
          "sha1": "555bbce2696e2f8c1c871d85c17fefd08046ad19",
          "md5": "68fad5b0522e956781fb0d6dbfee6bb0"
        }
      ]
    }
  ]
}
