{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.9/core-0.0.9.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xtqqandxyva3tauucku2734sky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.9.jar",
          "url": "core-metadata-0.0.9.jar",
          "size": 4883,
          "sha512": "1eaba5652155519143f0ff455fec63607cd6200760779e8f11a8622510adda7a86a06d71b80fb6e674408e059e1006ee9af67edeeb21c0a257fc40f29b2e6864",
          "sha256": "9723e28cd050f512a8f3714a4469b7bc48e0e54811cbd210557c76b246526946",
          "sha1": "84a1a8521558b14f52999cb9a376966a2fd3a344",
          "md5": "2cd6b239109c048c666b789d8466717c"
        }
      ]
    }
  ]
}
