{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha14/modelcontract-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "542d3vhgfrhaxgd5li4auko6d4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0",
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha14.klib",
          "size": 25612,
          "sha512": "41cf78a60ccaf1c8b88fe90e653bc8189695f7d332aca78e5000cb541224c2afe8654d7f842bed0e99cd356031a9c1343dbdbdf5a61bb5941febd15661a63f8f",
          "sha256": "5cb321acac592c177bf5208a6fc9a54133981e30d26062619903b0064923dcd0",
          "sha1": "c1ec7a0ff07eaed2669a180079d99eb8791c889b",
          "md5": "868b1486a7c542c530a0f9bba5614f74"
        }
      ]
    }
  ]
}
