{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha11/modelcontract-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha11.jar",
          "url": "modelcontract-jvm-1.0.0-alpha11.jar",
          "size": 33338,
          "sha512": "625b42f393718fe7ed608025ad2ae48c0563ed7aa9337b43c7060b7d14eb31042474d83bb666ca2aa461e15865ca8e49fade72168198d9b4164081afcf4dc8f2",
          "sha256": "b359ee506d33d3c5dcf2b73083e321b30c701a446a9cbf18063a95832617ac4a",
          "sha1": "8ccb48b8fe01cfe40e14e6d18b19ac61e11fa3f4",
          "md5": "14e35b4979c7617ec5972fb5fc77a149"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha11.jar",
          "url": "modelcontract-jvm-1.0.0-alpha11.jar",
          "size": 33338,
          "sha512": "625b42f393718fe7ed608025ad2ae48c0563ed7aa9337b43c7060b7d14eb31042474d83bb666ca2aa461e15865ca8e49fade72168198d9b4164081afcf4dc8f2",
          "sha256": "b359ee506d33d3c5dcf2b73083e321b30c701a446a9cbf18063a95832617ac4a",
          "sha1": "8ccb48b8fe01cfe40e14e6d18b19ac61e11fa3f4",
          "md5": "14e35b4979c7617ec5972fb5fc77a149"
        }
      ]
    }
  ]
}
