{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/1.0.0-alpha12/model-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-1.0.0-alpha12-debug.aar",
          "size": 110444,
          "sha512": "5f58cdb5d141ab47fd04fdbeac65e2dcd9faa15d24bc66a3e86ada1d4cd5fc79200a1a1f63be9ffd7dfb92e3ac60ab67293731e490480a34c2dc947e1008713b",
          "sha256": "a1724ff82e1466c8307c684a2aa4e4c93fb3be24473cae3a55363243f52b5af9",
          "sha1": "ef4624b8274ae40da0a450cf2419bfff06dbe69b",
          "md5": "3354c279bb54a6436aeb6840264e7a24"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-1.0.0-alpha12-debug.aar",
          "size": 110444,
          "sha512": "5f58cdb5d141ab47fd04fdbeac65e2dcd9faa15d24bc66a3e86ada1d4cd5fc79200a1a1f63be9ffd7dfb92e3ac60ab67293731e490480a34c2dc947e1008713b",
          "sha256": "a1724ff82e1466c8307c684a2aa4e4c93fb3be24473cae3a55363243f52b5af9",
          "sha1": "ef4624b8274ae40da0a450cf2419bfff06dbe69b",
          "md5": "3354c279bb54a6436aeb6840264e7a24"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-1.0.0-alpha12.aar",
          "size": 105920,
          "sha512": "347563ba19e18741fef325dd46ae8598a872cc2104b26a990dab93cdc49676e0a6b3adc766f144cc807377829d3e74ba485de27d6216c2c6402f3860b1c51ee9",
          "sha256": "82fa7ed71402810490d4f10040501eee46deb75893b9d3eaee12c02b06eeb2a8",
          "sha1": "f2cb042c2cb85308e7ff0f2cf60f634b26225750",
          "md5": "62fea5f91962c4d47c579c108a244703"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-1.0.0-alpha12.aar",
          "size": 105920,
          "sha512": "347563ba19e18741fef325dd46ae8598a872cc2104b26a990dab93cdc49676e0a6b3adc766f144cc807377829d3e74ba485de27d6216c2c6402f3860b1c51ee9",
          "sha256": "82fa7ed71402810490d4f10040501eee46deb75893b9d3eaee12c02b06eeb2a8",
          "sha1": "f2cb042c2cb85308e7ff0f2cf60f634b26225750",
          "md5": "62fea5f91962c4d47c579c108a244703"
        }
      ]
    }
  ]
}
