{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha15/modelcontract-1.0.0-alpha15.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha15.klib",
          "size": 25574,
          "sha512": "edb23d2748399eea0ec4f313876040df2cd2bc34a2c919bdd4ff769f5951f6e371282f84b065bc574fc86bb7b594d6a1cb35a6f46444c5c3593ffe4b77a0c95c",
          "sha256": "df15d790dbc57179d2ae7894104347b2f4d8cea986db207caf896f54fc48a93d",
          "sha1": "f2205fe9a5a9225f67359a83fc28d20e70c8e61f",
          "md5": "4cb93d006e189447d25c9649e9db2b47"
        }
      ]
    }
  ]
}
