{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h2ihyef5ird4dpcb6ziswov2gq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha9.jar",
          "url": "generator-1.0.0-alpha9.jar",
          "size": 112780,
          "sha512": "80dfa068754a4980e98c893a304a2c8bd753150606a93e3d33bdb6442f0c9498ef740cce8a2f336199fa7ffb30c5cb253b59c81b9eebc5f921c187584433b6fd",
          "sha256": "2982dc5c18b4bda395f4aa9a2c28aeaabf68aef7c500e1eb13c47d78a4782ffe",
          "sha1": "70dc92d81e169312e98a4a3289e318b6abd0e090",
          "md5": "e650f007a9830437bf086e8fc28b636d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha9.jar",
          "url": "generator-1.0.0-alpha9.jar",
          "size": 112780,
          "sha512": "80dfa068754a4980e98c893a304a2c8bd753150606a93e3d33bdb6442f0c9498ef740cce8a2f336199fa7ffb30c5cb253b59c81b9eebc5f921c187584433b6fd",
          "sha256": "2982dc5c18b4bda395f4aa9a2c28aeaabf68aef7c500e1eb13c47d78a4782ffe",
          "sha1": "70dc92d81e169312e98a4a3289e318b6abd0e090",
          "md5": "e650f007a9830437bf086e8fc28b636d"
        }
      ]
    }
  ]
}
