{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.50/model-0.0.50.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h2qswlibvbgzncub57ri5633aa"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.50-debug.aar",
          "size": 92791,
          "sha512": "873270a0a396ff1bba29252fdd34f914baf0c04591ebe58e338357ecc89592e9e7247eb57639995329be3942c07bbcd73bf3e29e58fe39074c6b2542022d92ab",
          "sha256": "e12343ce9fd2b130ed887b9a79c591a46af3f8f0fee62aa4f227be297025f86b",
          "sha1": "12ddef7da8c2b0a9733576fa4c9b4be6f7a50b93",
          "md5": "3cd2ea52037b338393eb21838ebc5288"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.50-debug.aar",
          "size": 92791,
          "sha512": "873270a0a396ff1bba29252fdd34f914baf0c04591ebe58e338357ecc89592e9e7247eb57639995329be3942c07bbcd73bf3e29e58fe39074c6b2542022d92ab",
          "sha256": "e12343ce9fd2b130ed887b9a79c591a46af3f8f0fee62aa4f227be297025f86b",
          "sha1": "12ddef7da8c2b0a9733576fa4c9b4be6f7a50b93",
          "md5": "3cd2ea52037b338393eb21838ebc5288"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.50.aar",
          "size": 89094,
          "sha512": "88610b9d2b6c05dd39a10a7e0433ae919460831f99a7e1e9bd2c37dbf9b9cfe8c7ee4f4e9d2960083e81da398e6e288a56e18cc3c2748dbb4fd1d6ace0a451bd",
          "sha256": "4d8be7d0ef69d37c9da20b9abdc2b2be8d900cce540985b89adac507184643ae",
          "sha1": "4333b27b66e26a970e755cc962d89295cd755618",
          "md5": "d1bdde599536fc4b65cbc42be0e80dae"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.50.aar",
          "size": 89094,
          "sha512": "88610b9d2b6c05dd39a10a7e0433ae919460831f99a7e1e9bd2c37dbf9b9cfe8c7ee4f4e9d2960083e81da398e6e288a56e18cc3c2748dbb4fd1d6ace0a451bd",
          "sha256": "4d8be7d0ef69d37c9da20b9abdc2b2be8d900cce540985b89adac507184643ae",
          "sha1": "4333b27b66e26a970e755cc962d89295cd755618",
          "md5": "d1bdde599536fc4b65cbc42be0e80dae"
        }
      ]
    }
  ]
}
