{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.29/view-0.0.29.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.29.jar",
          "url": "view-metadata-0.0.29.jar",
          "size": 6291,
          "sha512": "e13e8cdabeaa797a39290f1720aa0eec870f5f30b42123c5f222d9c23a872db71e92a6f6bd06dee98cbe4228e87a4725967a34fd867b573f491ad9aafd996128",
          "sha256": "fde980154f0bea9bb17f1c90ef616e8a7849db3fb33c507e7cb48955a195e11f",
          "sha1": "f524fcc065ab3a85142e795b4fd754d0e6e17420",
          "md5": "fefaabc811641a4b3cabb2b8bc692844"
        }
      ]
    }
  ]
}
