{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.8/androidTests-0.0.8.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5vu6ywwiijbhlbbtlao5nfwm2q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.8.jar",
          "url": "androidTests-metadata-0.0.8.jar",
          "size": 261,
          "sha512": "31fdc364aa46a778faa514f71b888dea3e9cedeed813d3a645be690f374bcc197d41748389297fdcc39290e994c39382b45d32c9c99eabb6a634a341db3463be",
          "sha256": "1db26fca68e8e7348565156df136944bc9d476130d3aaf8a86e4fb138c6bde4e",
          "sha1": "43ded0c6cf4254b4d1c92f11deb2bf8c8cbc1b9f",
          "md5": "c12e187424278fd8892af17837f91840"
        }
      ]
    }
  ]
}
