{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.25/core-0.0.25.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.25.jar",
          "url": "core-metadata-0.0.25.jar",
          "size": 5327,
          "sha512": "dc0b6e0583c086fc429a39a6df8a3410a45dc6afb095ea969ec2fee52ee41bcec10538e1022dd909844fc0f79547e1647216466a83dffa893df8b9ee1fd1b137",
          "sha256": "0ca0780114c65d7ef6f9d7dda53221c1a4da974b9b9c029a0ed368266836ba77",
          "sha1": "fd796c72c67e64d1975a0723163e579980af6d49",
          "md5": "82175d230f2f4d3cd357e251ee78c11e"
        }
      ]
    }
  ]
}
