{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha12/viewcontract-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha12.klib",
          "size": 35934,
          "sha512": "80226a9e08121e79993d47226b6e2c86662363e2e7b5450532a3fc7f856ca07695b256c4f9d44d6ca78d888ba3603709527ed1f110a35477efcb284861f7c814",
          "sha256": "49cccea2c42cf671714e8d9dbbb182a8836d7cccd93570fdb72be99ea68aef30",
          "sha1": "620667a7882704eaad8e28ff7b3382630e83279e",
          "md5": "05138146ce429c1f47d3849f127672a3"
        }
      ]
    }
  ]
}
