{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha22.jar",
          "url": "generator-1.0.0-alpha22.jar",
          "size": 194050,
          "sha512": "870d9752f4454cff517a4960686d123dffa5f0e709821d7479403a35dc865423cd52f7f0c35794471426a30f783cfb44f44d0680cd1277cfe454d01f9ac84634",
          "sha256": "20b7e548ae6164a47376698f31dda3f39938ecaae6942aa2910ca14f0ad8ce91",
          "sha1": "882b7e9ede564341e1f1855a0ae501dabf50db84",
          "md5": "b926ccfd158851747a273effe69a6a72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha22.jar",
          "url": "generator-1.0.0-alpha22.jar",
          "size": 194050,
          "sha512": "870d9752f4454cff517a4960686d123dffa5f0e709821d7479403a35dc865423cd52f7f0c35794471426a30f783cfb44f44d0680cd1277cfe454d01f9ac84634",
          "sha256": "20b7e548ae6164a47376698f31dda3f39938ecaae6942aa2910ca14f0ad8ce91",
          "sha1": "882b7e9ede564341e1f1855a0ae501dabf50db84",
          "md5": "b926ccfd158851747a273effe69a6a72"
        }
      ]
    }
  ]
}
