{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/1.0.0-alpha14/model-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "biqopuycmjhqla5bue3ohogk3m"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "model.klib",
          "url": "model-iosx64-1.0.0-alpha14.klib",
          "size": 52623,
          "sha512": "bc51ee5a9e735d409ca2710641d9b84acc3b529361622af1ed61351a64a324fd046b445f0ff5aa7e74939fec662e842a3ee2ed84af36ff383ec2803b1ca0ee58",
          "sha256": "9a4b811e7edc020ef2bf950b7a0079fab3ce6978dc6aefc3ae9a22f4321500ef",
          "sha1": "412546b447fcf0c041c9ec16457736429db2cd1d",
          "md5": "36f76b9177a6edc5c3f436bb2d50ab44"
        }
      ]
    }
  ]
}
