{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.11/viewmodel-0.0.11.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.11-debug.aar",
          "size": 46846,
          "sha512": "045756ee923fc615203a7911d9687e100624a60aec5052bc15696d7ac86d5e1d775ec292ddde2329a530ab47c9e357ed285fc21047ce66cc57c1168dc218489c",
          "sha256": "76ff8bab2ca825b7525c59f5d81a96d10121eba8ece7492d8734df9eb3dd8b77",
          "sha1": "eb37436bddef4bedbb3d8040dd74ad2259d5384e",
          "md5": "b8905a622d599a80e907d194ea690a1e"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.11-debug.aar",
          "size": 46846,
          "sha512": "045756ee923fc615203a7911d9687e100624a60aec5052bc15696d7ac86d5e1d775ec292ddde2329a530ab47c9e357ed285fc21047ce66cc57c1168dc218489c",
          "sha256": "76ff8bab2ca825b7525c59f5d81a96d10121eba8ece7492d8734df9eb3dd8b77",
          "sha1": "eb37436bddef4bedbb3d8040dd74ad2259d5384e",
          "md5": "b8905a622d599a80e907d194ea690a1e"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.11.aar",
          "size": 45395,
          "sha512": "1e67a72a5e00bea44b77acfe2fdf0780a0965ef049d528d312ac1b15951c108c31f737e1b7e09f2a7f83a24cca9269d77bf4db82a8484856e14c9a91865e3d0b",
          "sha256": "045e702669f3828743d731c88144dfad0b64fed8395628b1121032309af5efc3",
          "sha1": "0e63ef8936865b112ff20706e2141aa427359c00",
          "md5": "92c5048a0534abb01bb281c22df37884"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.11.aar",
          "size": 45395,
          "sha512": "1e67a72a5e00bea44b77acfe2fdf0780a0965ef049d528d312ac1b15951c108c31f737e1b7e09f2a7f83a24cca9269d77bf4db82a8484856e14c9a91865e3d0b",
          "sha256": "045e702669f3828743d731c88144dfad0b64fed8395628b1121032309af5efc3",
          "sha1": "0e63ef8936865b112ff20706e2141aa427359c00",
          "md5": "92c5048a0534abb01bb281c22df37884"
        }
      ]
    }
  ]
}
