{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.2-native-mt",
            "requires": "1.5.2-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-metadata-1.0.0-alpha62.jar",
          "url": "modelcontract-1.0.0-alpha62.jar",
          "size": 6618,
          "sha512": "0f58f3d00c632c44bec0bb5702deed41beee22963d3e6bf05b64dd0e4410a483c4421eae7480d486f2ffb827a7345a47f4a8e23bb28e156c17c8135a7d584621",
          "sha256": "8ea26e63f485f3f20047a89b64b80319d45032ac5e16d9f9a833a8b05cb37906",
          "sha1": "c11694c74f9d5ce4d03beb595b110f5d2cbad51a",
          "md5": "256a5bf63027891d20f9ffb4cab325a3"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosarm64/1.0.0-alpha62/modelcontract-iosarm64-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "modelcontract-iosarm64",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosx64/1.0.0-alpha62/modelcontract-iosx64-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "modelcontract-iosx64",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha62/modelcontract-jvm-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha62/modelcontract-jvm-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha62"
      }
    }
  ]
}
