{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.15/viewmodel-0.0.15.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gqpemdskoneufiyethujbxdcv4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.15"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.15.jar",
          "url": "viewmodel-metadata-0.0.15.jar",
          "size": 6919,
          "sha512": "c4446d55b5ded00e887fb519df561bf0de14110f89829e9e69ffabef64e79488a1d46099638dde0fe0190481fc54658db318c96f50f0386da224017a25064230",
          "sha256": "197e26b1d980ff6c03c6725848a131bfc25c6225d4e4af847527d45cfbf20577",
          "sha1": "b208f4bce27b461d5a5bebfadb2f858fbd08982a",
          "md5": "552cd13939a70d8a395cba819bea039a"
        }
      ]
    }
  ]
}
