{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.11/contract-0.0.11.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.11.jar",
          "url": "contract-jvm-0.0.11.jar",
          "size": 15805,
          "sha512": "9924c5f2ebb22be9f9664b7bc52bb8a7ab8acb6660738e4a73aed22d17d06ac2d789d21b70a83ee8aa04d1772a37a11174698f330f1a720a565d16601f7462ae",
          "sha256": "07a188b34d33b40874cc97c3679ad41f0e66576189a8e99cea48f65fada18fcd",
          "sha1": "ab9b03d7472356e3a95a9c48e3f99b1ef2e11bbb",
          "md5": "a6c5cacb06b3d642e1c014c81dfd9ba5"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.11.jar",
          "url": "contract-jvm-0.0.11.jar",
          "size": 15805,
          "sha512": "9924c5f2ebb22be9f9664b7bc52bb8a7ab8acb6660738e4a73aed22d17d06ac2d789d21b70a83ee8aa04d1772a37a11174698f330f1a720a565d16601f7462ae",
          "sha256": "07a188b34d33b40874cc97c3679ad41f0e66576189a8e99cea48f65fada18fcd",
          "sha1": "ab9b03d7472356e3a95a9c48e3f99b1ef2e11bbb",
          "md5": "a6c5cacb06b3d642e1c014c81dfd9ba5"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.11/contract-metadata-0.0.11.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.11"
      }
    }
  ]
}
