{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.34/contract-0.0.34.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sdiuqgpfpvgqbhgb64jk7k3g3u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.34.jar",
          "url": "contract-metadata-0.0.34.jar",
          "size": 7617,
          "sha512": "16ad9b9266de63e0aa21d9775ac2fa3399b59aef088cf5110307b5c8c62c35187f7f484b7617da98db3c365220b645e805aef5dd30647e6cc4d3375ed423cd70",
          "sha256": "5cb13669050b69b35923ffc10fb547f8d720f9cbe8df3f8603d0556ba1d15003",
          "sha1": "f9b66cf1ff94fedc4eb47807f0956bad04886c68",
          "md5": "55c755b7f34360d1f3fc1e64457637db"
        }
      ]
    }
  ]
}
