{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.15/contract-0.0.15.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gqpemdskoneufiyethujbxdcv4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.15.jar",
          "url": "contract-metadata-0.0.15.jar",
          "size": 7170,
          "sha512": "4d815466c8535015138ad1747a5ac3d0b99b7dbfcf8985cf266a0303aca665b536870c6e33c7eec8186ab542844b967c8df21867350cb7ab3d539abcad49b5fc",
          "sha256": "5bf338658c3a246c9e3ef7030d117e3702e6cec16d9502adba9b6fae208f5c2a",
          "sha1": "2b4e21b92caf350d902c5a4c0d2fcfb5aa45a423",
          "md5": "a9f479f9cbbaa0ae4e843668cd6f1b79"
        }
      ]
    }
  ]
}
