{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.52/view-0.0.52.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "jc6y725iebc23nmj56aixso43i"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.52"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.52-debug.aar",
          "size": 156592,
          "sha512": "2ceb924b502e91a56ec16c247a62681d00ad9273fee27969a5756dafccd3e94d6c92db1b934939c4980db165be26416e7ffe282998d4830686f78c64d416cc13",
          "sha256": "76cd745965ef035e3ebd939f98f6ffbc4263451a6859c16264b9102d686a1356",
          "sha1": "b1048a74562f1fa69e29ab215ffddebf70cde135",
          "md5": "5ed85fe51ca67737b797401f1ad8e270"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.52"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.52"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.52-debug.aar",
          "size": 156592,
          "sha512": "2ceb924b502e91a56ec16c247a62681d00ad9273fee27969a5756dafccd3e94d6c92db1b934939c4980db165be26416e7ffe282998d4830686f78c64d416cc13",
          "sha256": "76cd745965ef035e3ebd939f98f6ffbc4263451a6859c16264b9102d686a1356",
          "sha1": "b1048a74562f1fa69e29ab215ffddebf70cde135",
          "md5": "5ed85fe51ca67737b797401f1ad8e270"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.52"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.52.aar",
          "size": 151718,
          "sha512": "dbcb2a7e9cd2b2bebee28586ab8894b44f3aaf62daecbeda022a88053bf6605c5165b32edf3efecec251b55a0eb11bccbaa301aea23b9572ac5e0222235a347d",
          "sha256": "cb666f276bab863a99dcddd2e80b64348d990e123d1e538a3c157c1d55500510",
          "sha1": "031b34c9d454095e8c9da57f9a6b71caf3440d97",
          "md5": "ecf28e4374809999031fc87bc91d8e7d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.52"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.52"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.52.aar",
          "size": 151718,
          "sha512": "dbcb2a7e9cd2b2bebee28586ab8894b44f3aaf62daecbeda022a88053bf6605c5165b32edf3efecec251b55a0eb11bccbaa301aea23b9572ac5e0222235a347d",
          "sha256": "cb666f276bab863a99dcddd2e80b64348d990e123d1e538a3c157c1d55500510",
          "sha1": "031b34c9d454095e8c9da57f9a6b71caf3440d97",
          "md5": "ecf28e4374809999031fc87bc91d8e7d"
        }
      ]
    }
  ]
}
