{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha8/viewmodel-1.0.0-alpha8.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5q5bv5aktfh2fdqq25rjsv33bm"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha8-debug.aar",
          "size": 48596,
          "sha512": "d7985a0732e5b0142fabbbaf6923e2b551f04f38e30f8d42f6494a69c5bb7a8ea7425d0c15161f4bb8d80a11951d6bf6debaf025fcdcf7067d138c3e7b307176",
          "sha256": "3f4380cee7c07353644fe14b8e553d9a4d72a77935798b03522c1cac7de26cec",
          "sha1": "bc5c70ddce894d2bfac28dc37a084b94e717acf7",
          "md5": "cb37a78768f5bdc602e49b24cad6caf1"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha8-debug.aar",
          "size": 48596,
          "sha512": "d7985a0732e5b0142fabbbaf6923e2b551f04f38e30f8d42f6494a69c5bb7a8ea7425d0c15161f4bb8d80a11951d6bf6debaf025fcdcf7067d138c3e7b307176",
          "sha256": "3f4380cee7c07353644fe14b8e553d9a4d72a77935798b03522c1cac7de26cec",
          "sha1": "bc5c70ddce894d2bfac28dc37a084b94e717acf7",
          "md5": "cb37a78768f5bdc602e49b24cad6caf1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha8.aar",
          "size": 46154,
          "sha512": "f617ea2db2f5714bf9a4d6f8f2250262dcbfbb8f5433ce4398f8c23765b46f0fba63dc9d7e2971b5358430a4ebaa6f358628e09349475f53c48e9f815b641389",
          "sha256": "a48cc4811722c060faf1c17fd5c2c695dbdbab729a5641b481e9dd96d367cf9f",
          "sha1": "7d19fdbaee14f999fa8345cf5b2c38dc6f24a6a1",
          "md5": "0e4052542c350d8bef3fc2bf7013ce21"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha8.aar",
          "size": 46154,
          "sha512": "f617ea2db2f5714bf9a4d6f8f2250262dcbfbb8f5433ce4398f8c23765b46f0fba63dc9d7e2971b5358430a4ebaa6f358628e09349475f53c48e9f815b641389",
          "sha256": "a48cc4811722c060faf1c17fd5c2c695dbdbab729a5641b481e9dd96d367cf9f",
          "sha1": "7d19fdbaee14f999fa8345cf5b2c38dc6f24a6a1",
          "md5": "0e4052542c350d8bef3fc2bf7013ce21"
        }
      ]
    }
  ]
}
