{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha14/modelcontract-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "biqopuycmjhqla5bue3ohogk3m"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0",
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha14.jar",
          "url": "modelcontract-jvm-1.0.0-alpha14.jar",
          "size": 57030,
          "sha512": "04aaa624377e6ee0f4593204cb98f79320177e334bb8a213304ac73604da387bbfab106333f13ded1169082117941509e74db3e28272d648ceebfd7355efeab9",
          "sha256": "a298f160a27e1995c7b49cc2adcb17b7333db91b1ffc6b161e547dea49a785b4",
          "sha1": "66fdf841da7208bce6f9011e621e32e1241f097f",
          "md5": "931588d07343cd4c105afcf93a612c5b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0",
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha14.jar",
          "url": "modelcontract-jvm-1.0.0-alpha14.jar",
          "size": 57030,
          "sha512": "04aaa624377e6ee0f4593204cb98f79320177e334bb8a213304ac73604da387bbfab106333f13ded1169082117941509e74db3e28272d648ceebfd7355efeab9",
          "sha256": "a298f160a27e1995c7b49cc2adcb17b7333db91b1ffc6b161e547dea49a785b4",
          "sha1": "66fdf841da7208bce6f9011e621e32e1241f097f",
          "md5": "931588d07343cd4c105afcf93a612c5b"
        }
      ]
    }
  ]
}
