{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.10/model-0.0.10.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.10-debug.aar",
          "size": 82711,
          "sha512": "0c9bf5c334039b7461cefc79af27a0ea4417d5d501679bf5cba8b5fb0ff14f52faae8599ab5d7ffaa975acd399ec74fcf1deda840ceab821ef57d30ffba5c07b",
          "sha256": "2bd878ce07b9cfc1c595dcba7db708aa51911e09788b900f6d6391be6fc110fd",
          "sha1": "f4de7cf9b4ffcf50bd6a41c4ff7232748858fade",
          "md5": "7ca515eb6a7498d3a8c7d99544bad45f"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.10-debug.aar",
          "size": 82711,
          "sha512": "0c9bf5c334039b7461cefc79af27a0ea4417d5d501679bf5cba8b5fb0ff14f52faae8599ab5d7ffaa975acd399ec74fcf1deda840ceab821ef57d30ffba5c07b",
          "sha256": "2bd878ce07b9cfc1c595dcba7db708aa51911e09788b900f6d6391be6fc110fd",
          "sha1": "f4de7cf9b4ffcf50bd6a41c4ff7232748858fade",
          "md5": "7ca515eb6a7498d3a8c7d99544bad45f"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.10.aar",
          "size": 79393,
          "sha512": "266a383a56ddef3aa0f856076be838aec778949d2d46b3467e76d59a2fc6b5ead08d95e830297a4e0e15db58d1da91826ee25869d0b44f8b1e324682b7ec4189",
          "sha256": "22f0ccf6d471fd56d792406e279352edaee7f046b9865e597de5b521c4b623b0",
          "sha1": "72df31ba578f070b64f518a86aa8aedbeedd9527",
          "md5": "804e744bed69f87f796f78aa8af457a3"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.10.aar",
          "size": 79393,
          "sha512": "266a383a56ddef3aa0f856076be838aec778949d2d46b3467e76d59a2fc6b5ead08d95e830297a4e0e15db58d1da91826ee25869d0b44f8b1e324682b7ec4189",
          "sha256": "22f0ccf6d471fd56d792406e279352edaee7f046b9865e597de5b521c4b623b0",
          "sha1": "72df31ba578f070b64f518a86aa8aedbeedd9527",
          "md5": "804e744bed69f87f796f78aa8af457a3"
        }
      ]
    }
  ]
}
