{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.39/contract-0.0.39.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "wulvo6iqbzfl3evraorhz65oge"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.39.jar",
          "url": "contract-metadata-0.0.39.jar",
          "size": 8039,
          "sha512": "e87fe912953f0060cc6d706a279fe7f66aa64780c8b927982ddcdb7c2c5a56ea00a837285c35ee7601f22c55fe985572ffd92e4b9f00ecfddc7d019bd452b98b",
          "sha256": "f0a9830c1b793f97f1a3aa819d05408c237cf6b3367cda3e7b17f72d0985fb20",
          "sha1": "ce1ddab7c443137fd9510db952ab0c3a08bd1e56",
          "md5": "ad5573694acac405d56cccbb91acfedc"
        }
      ]
    }
  ]
}
