{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha9/viewcontract-1.0.0-alpha9.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h2ihyef5ird4dpcb6ziswov2gq"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosx64-1.0.0-alpha9.klib",
          "size": 26815,
          "sha512": "b918b3ae1384e62fc2ab8b397617bdd1b4aeb09e51018276b2152976fdd18b023d64ea393fca45e876eda995e061e0c5e16f0ba849ff54b163927dc419d423da",
          "sha256": "f512952f79db1909b5ead3b62154cf3e7c6bdc7efb0e0fa6c50dbbec19db4580",
          "sha1": "ec159562d85645d9c62acb1383eeadd4e62d59a9",
          "md5": "5b8b6ace67d94df6c6f51dc766fc34dc"
        }
      ]
    }
  ]
}
