{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha5/core-1.0.0-alpha5.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3",
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-1.0.0-alpha5.klib",
          "size": 20659,
          "sha512": "6d6089b27f700ae4bc5f2451bbe80cc3c3b944f6f9c40e475a7c83c9a6b3f18ab6f7332d846c6bd36ee545b8884658e4ad2fb0551739aa23653ddcd677278cc9",
          "sha256": "7d7ba1d95170566c1dd18d0ac2727faa56114cfee2aa27e38ff1708246ac4947",
          "sha1": "dfd4644e0c7639d1d6a0adfe6ba468ca175c8613",
          "md5": "fc3a1ac6063e8cfd8c03752881b30ae4"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/1.0.0-alpha5/core-metadata-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "1.0.0-alpha5"
      }
    }
  ]
}
