{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.1/core-0.0.1.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zk7tjfukpff7tmn3tiqtxdfuzy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.1.jar",
          "url": "core-metadata-0.0.1.jar",
          "size": 4224,
          "sha512": "2367a183f246486451a8785028925c399939d99be413bc7f58b25c37d960535ba71a24c4479b51f149efb52a6837b721f255a5a73b75c52b1f649edb7d6d67a8",
          "sha256": "a8a057165b870191d7b80af2f367830bc019301113b546d405d811af8727fac0",
          "sha1": "da03dcdc6c10cae325ce62d667420ae45bba0ac6",
          "md5": "f87e2cf6d846da017827ab563a9be606"
        }
      ]
    }
  ]
}
