{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.2_1.0.0-alpha59/viewmodel-0.0.2_1.0.0-alpha59.module",
    "group": "com.github.skot-framework.sk-tabbar",
    "module": "viewmodel",
    "version": "0.0.2_1.0.0-alpha59",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.2_1.0.0-alpha59"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.2_1.0.0-alpha59-debug.aar",
          "size": 17010,
          "sha512": "a1cadad821f2bcbc166919f77f34a635a288b0ccf04da4658e5921b3fc934e0f3c95d20d0e8c2b0bb79567c20ff1e1b2f808cbeb5ab50b8ad2eb8d59df428656",
          "sha256": "a5ac7da97a3f6e643c5d6c1247d852fdb01cff5adfaa99fde2ba1e393687854b",
          "sha1": "5cb31c91932221f3fce0ffed618b4dd76f2603b3",
          "md5": "0374c314c92d387b7955778ed36702b3"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.2_1.0.0-alpha59"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewmodel",
          "version": {
            "requires": "1.0.0-alpha59"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.2_1.0.0-alpha59-debug.aar",
          "size": 17010,
          "sha512": "a1cadad821f2bcbc166919f77f34a635a288b0ccf04da4658e5921b3fc934e0f3c95d20d0e8c2b0bb79567c20ff1e1b2f808cbeb5ab50b8ad2eb8d59df428656",
          "sha256": "a5ac7da97a3f6e643c5d6c1247d852fdb01cff5adfaa99fde2ba1e393687854b",
          "sha1": "5cb31c91932221f3fce0ffed618b4dd76f2603b3",
          "md5": "0374c314c92d387b7955778ed36702b3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.2_1.0.0-alpha59"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.2_1.0.0-alpha59.aar",
          "size": 16234,
          "sha512": "f1acd074be83d665f74baf1ed2073d07025544bbefdb4271c2b6110438b31475dae3eac5efc18ea09621fd3e62c80b4e61c6a1f0cbb4754376357b359213f301",
          "sha256": "97f7697fd537f3dca77d5ef6f08c4e16a64f6993138db0177e67f3f2f529ddbd",
          "sha1": "e67aa135b62f1edeb3b1e7742909ed4e83ee5f6d",
          "md5": "b7951db6552f7cdff51c2e9d4d171c37"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.2_1.0.0-alpha59"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewmodel",
          "version": {
            "requires": "1.0.0-alpha59"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.2_1.0.0-alpha59.aar",
          "size": 16234,
          "sha512": "f1acd074be83d665f74baf1ed2073d07025544bbefdb4271c2b6110438b31475dae3eac5efc18ea09621fd3e62c80b4e61c6a1f0cbb4754376357b359213f301",
          "sha256": "97f7697fd537f3dca77d5ef6f08c4e16a64f6993138db0177e67f3f2f529ddbd",
          "sha1": "e67aa135b62f1edeb3b1e7742909ed4e83ee5f6d",
          "md5": "b7951db6552f7cdff51c2e9d4d171c37"
        }
      ]
    }
  ]
}
