{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha26"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha26"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha26"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha26.jar",
          "url": "viewmodel-1.0.0-alpha26.jar",
          "size": 15848,
          "sha512": "18f7d8cc38bcf5e315117a828ecef0b071a256908ab4295269edafd5d414c9d5116b425b609049987447e5bc3a52b00610cc688f596a1c91a7f2b312cb1255ec",
          "sha256": "bd6dcfee4480f5eb52411eee069d2cf5941fcc0e2138336f3c8444bc29b41c27",
          "sha1": "e4c79e3b4c8e00fb59b8ccf84a4d2d552e0efb28",
          "md5": "69b72809d18c175195ab6e587853d915"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha26/viewmodel-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha26/viewmodel-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha26/viewmodel-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha26/viewmodel-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha26"
      }
    }
  ]
}
