{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha13/viewcontract-1.0.0-alpha13.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosx64-1.0.0-alpha13.klib",
          "size": 36989,
          "sha512": "91cb770ea96b94b4df92fda0fadb3bec666472cbc5ebb1b8151a82c8ca306ff357160193d234d2e59eaa08358e21f7782fbad2c0b8f7922d9c46df683f6aab83",
          "sha256": "bfb33cde49146cc6cc6302db7b69b5556c9cf706c461bc8818ff2d4bff687196",
          "sha1": "f43c3255e6003fc397508b28ffa0431a1ccdcbc7",
          "md5": "1980f231891688c443513b8e46d4ba85"
        }
      ]
    }
  ]
}
