{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha26/modelcontract-1.0.0-alpha26.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha26.klib",
          "size": 29975,
          "sha512": "e4946773ccc831395fb6850ba5756bc054a76d97b1332b2919eaaf493fceefbff791125269ce705d48ca0bb26e9cdae69ab454b793ccf1a9f26c5c9dc5518c62",
          "sha256": "2051c2082c456ecf75520f6c5af1ca9793509141edf1be4351e2a86a23ed13e8",
          "sha1": "05323bda471993556645231399da531ac78227f1",
          "md5": "10f530325603d4e84f5b457609f2ac7c"
        }
      ]
    }
  ]
}
