{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha19/viewcontract-1.0.0-alpha19.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha19.klib",
          "size": 39164,
          "sha512": "05aa4f6407fb16b920c44a42a27c47a76b4dd5e40659ab1a0657a47c6fa7c43e235ba9baae9fb8b58187591492494d0ffb7da00a7bf37ce9e3d71edb00630b0b",
          "sha256": "a5ad2abc4a94e013ab75ac760244c380af6a85b21b4f0c3de61785d6d82ecf4b",
          "sha1": "261acf92568aeabd64d56d002f8fb0a90500e43f",
          "md5": "864eb021867c266b4a10e1bc44d56a7f"
        }
      ]
    }
  ]
}
