{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.25/contract-0.0.25.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.25.jar",
          "url": "contract-jvm-0.0.25.jar",
          "size": 15726,
          "sha512": "062ac59ed4eea0232dcda798877686f218f30893107e972053aea9956f6cce3cd905b0b718bb6de8c4c5598f40d410d4a505ac1a7e7791b983db171a0bacd740",
          "sha256": "c3e5b5759427cacb9e14150996e25749ca8b776d59b8c7da756d6cfa909c2fb9",
          "sha1": "611c4daecc5242c760c66190829419557acc2a1e",
          "md5": "0ab166fedf6574be4bae9b14548b9b19"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.25.jar",
          "url": "contract-jvm-0.0.25.jar",
          "size": 15726,
          "sha512": "062ac59ed4eea0232dcda798877686f218f30893107e972053aea9956f6cce3cd905b0b718bb6de8c4c5598f40d410d4a505ac1a7e7791b983db171a0bacd740",
          "sha256": "c3e5b5759427cacb9e14150996e25749ca8b776d59b8c7da756d6cfa909c2fb9",
          "sha1": "611c4daecc5242c760c66190829419557acc2a1e",
          "md5": "0ab166fedf6574be4bae9b14548b9b19"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.25/contract-metadata-0.0.25.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.25"
      }
    }
  ]
}
