{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.3/core-0.0.3.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "su2tjwkhbbbjndaqanwwqcxe24"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.3.jar",
          "url": "core-metadata-0.0.3.jar",
          "size": 4224,
          "sha512": "4d950d682eb240c217206006fb90c83f1d0f5da1dcbf2e992b04d38b92a333e3994dfd42bc977720adb81f527ca0d364f4ead74af76a0d0addcce10a9c51a8a4",
          "sha256": "f38b9b214e71af7394dd54e0e325312af9b097df609649169432045ae2af5465",
          "sha1": "1ccab65b9804c4007519abf130ab71c7ee312241",
          "md5": "ea5366b3284ecf3972143806ec0780fd"
        }
      ]
    }
  ]
}
