{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.38/view-0.0.38.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h3wjxn3zcban5fnecihtr5lrqi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.38"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.38.jar",
          "url": "view-metadata-0.0.38.jar",
          "size": 6294,
          "sha512": "ec0e27593c30cee40ed1e0a329f599be81fe662e8a49f4917b8ea5dab4c95c4aef63d65da4f38d7b6fd173b36f735e17f5b26058d007d199f5454412808d6271",
          "sha256": "762f57a60dc0da4ed91161ace5c2be5144a84780495c346506bf9e8cd209a34a",
          "sha1": "dc9afa52ab22d576bd7423351fcd09e09df0ef1a",
          "md5": "56fef45cb0185ac93911d676f2f64663"
        }
      ]
    }
  ]
}
