{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-1.0.0-alpha4.jar",
          "url": "model-1.0.0-alpha4.jar",
          "size": 14701,
          "sha512": "13439809a8d0c9d20ec63573bb98cf2c3bf8e691ca9cb7300ceb51b5f2a40112622145fd8b707a247f791e0545516d693be38dd5675940f2d57ff7616c1392fd",
          "sha256": "1a3ce5ae0c27af792d947b155c5427d088991ada68bc61ce373b8a4e7f03b644",
          "sha1": "aa636792f8af31e762dd141b4f0acc840140b8e2",
          "md5": "9179e326031a6884aee5ad0185d9a915"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha4/model-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha4/model-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha4/model-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha4/model-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosarm64/1.0.0-alpha4/model-iosarm64-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "model-iosarm64",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosx64/1.0.0-alpha4/model-iosx64-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "model-iosx64",
        "version": "1.0.0-alpha4"
      }
    }
  ]
}
