{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.26/core-0.0.26.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.26.jar",
          "url": "core-metadata-0.0.26.jar",
          "size": 5327,
          "sha512": "1b913d0bf0ee145e094dd261075d5ff1d2c2aecd47437af90bda00580622dea53507b7bef397e226284df09fd779bf669c82f0d2899c05ec36b771039ebd327f",
          "sha256": "33970f07fb2a328ab40fe790e15942fe2d0d78be632f1045ddfb989c90a6e037",
          "sha1": "57ff1f213e1d8eda8e03a469317df068756bb23a",
          "md5": "4ee2cf275eea3e77358893a8d9e4b495"
        }
      ]
    }
  ]
}
