{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.43/viewmodel-0.0.43.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "umuh4wxdqfdghocu4tjfq6qmxe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.43"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.43.jar",
          "url": "viewmodel-metadata-0.0.43.jar",
          "size": 7429,
          "sha512": "a5aaada2199b7642a6253cf542d953d449b40c4d54656d026fd09ab33e4a67106f77094d070e62252bf642c2c84c8aa702f3cf58d50d7364646784d7c96486d9",
          "sha256": "f38a9bd67f7117bf9e82b6bded09f78cc5344eae8a8fb46bd98d418a1be81adc",
          "sha1": "5818adefa0ed60312a7cdd4538ce226f3e43529f",
          "md5": "da30fa817bce9fb66cc5b34df14792c4"
        }
      ]
    }
  ]
}
