{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.39/view-0.0.39.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "wulvo6iqbzfl3evraorhz65oge"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.39"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.39.jar",
          "url": "view-metadata-0.0.39.jar",
          "size": 6294,
          "sha512": "9b1b7e0ce03b8d21b240028a06ed81a582ca889e3fa95b8df639ead5018dce0c58edf0906da1486ee23875e12f94a7ca4e65db0558aaab044384c15e983c909f",
          "sha256": "f7f8f9ed499057d54b3eace7b3dc4598c1ef5b56b8292c883189887429ee8d04",
          "sha1": "917ccb96d7fad41865cf84d10f0a13ce8323591c",
          "md5": "af7eabadb11a0db026bd9e32e3778cff"
        }
      ]
    }
  ]
}
