{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.33/core-0.0.33.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "dpaczj3htbf6dbuy2gp2yf4ski"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.33.jar",
          "url": "core-metadata-0.0.33.jar",
          "size": 5329,
          "sha512": "e1df8e5229f36b38ad69597866f27cadb3e1cd784a6524c49b960e29b600f370d68eef25fb3423bbe5e1f5c930588c568fa9d241e6c9486ef07bdb189a2fdedb",
          "sha256": "c04225ad2aaf0198e21823ef9fe6fec1f05a3e157293a17662441a2fe5f025bc",
          "sha1": "f43760e12d779abc73e6b9c94c82cf1521846706",
          "md5": "50a8d971e18115fea5d189cbd1159b3c"
        }
      ]
    }
  ]
}
