{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.35/androidTests-0.0.35.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "giu2xg36zfb4vbk5yuetpxzity"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.35.jar",
          "url": "androidTests-metadata-0.0.35.jar",
          "size": 261,
          "sha512": "7091261f88194446e54752c9d75a1ac4b3ccb0d9fa0e392cf166d02c932fa0a4755f35ac84ffb3d726509e5354e088975198ad9cff43590115417ad589243a8c",
          "sha256": "5711a3a02c7499ad3b47310743da0c6033d0fe37866eb9ff3a3a34922e704c56",
          "sha1": "868a5c792824dc0103d225401e9c7cafcc75f3be",
          "md5": "1078d16264798e8bc92da1b44f532f27"
        }
      ]
    }
  ]
}
