{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha20/core-1.0.0-alpha20.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-1.0.0-alpha20.klib",
          "size": 21982,
          "sha512": "a9b63ca86a05b1655050c6cd3aed544da84b03c4ad9ba90560516b95a0ac314d9f4f19fb7165a41283287d36ee3656060f58aaaaebd5b354a1849156264f474d",
          "sha256": "569137e9c8723792c0624519f6bf125e109ddc0b9150ba36dd73a5ad3baf675c",
          "sha1": "e80e6bfc57384fbdb2ff64767aac11c439128388",
          "md5": "5522ce2bfe63b0a4ab52b239481bfe5e"
        }
      ]
    }
  ]
}
