{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.sk-tabbar",
    "module": "viewmodel",
    "version": "0.0.2_1.0.0-alpha61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.2_1.0.0-alpha61"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.2_1.0.0-alpha61.jar",
          "url": "viewmodel-0.0.2_1.0.0-alpha61.jar",
          "size": 4246,
          "sha512": "1444dc87f0b58514781276d797918b15ca23b21cc44a27be83305baed4e5967001d6c142e9ccfbb5bceb3bc8c3ddb0e0457fb5b1a0d6683b29e29ad1ea86f68b",
          "sha256": "e2c4d3a826a2e4dc5d1ac2ba990b694736af6b5951784350a1d21dd0fbb79744",
          "sha1": "0dbc58c00e90ff478f48ccbb847828dc2b3e20cc",
          "md5": "44303256c7bf96bc518edbf609b59ae6"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.2_1.0.0-alpha61/viewmodel-android-0.0.2_1.0.0-alpha61.module",
        "group": "com.github.skot-framework.sk-tabbar",
        "module": "viewmodel-android",
        "version": "0.0.2_1.0.0-alpha61"
      }
    }
  ]
}
