{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/0.0.2_1.0.0-alpha60/viewcontract-0.0.2_1.0.0-alpha60.module",
    "group": "com.github.skot-framework.sk-tabbar",
    "module": "viewcontract",
    "version": "0.0.2_1.0.0-alpha60",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha60"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-0.0.2_1.0.0-alpha60.jar",
          "url": "viewcontract-jvm-0.0.2_1.0.0-alpha60.jar",
          "size": 3610,
          "sha512": "98e1af84d4917f1881de8d56991dbec6b7d92b911dbf184ca741456d069210898290ab446725867e0a8f644eb83c8ae6237df417d536e7f038300f6edd0f7bef",
          "sha256": "16357a023efca986b5fd0d8ea8a9aa3efc399de867984d909f0cca9bbcb554d9",
          "sha1": "901f94ba51112cf5c346ad323456c3e7bd688e92",
          "md5": "0148ebc4e272fe7b0e13dc0b0369cd6e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha60"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-0.0.2_1.0.0-alpha60.jar",
          "url": "viewcontract-jvm-0.0.2_1.0.0-alpha60.jar",
          "size": 3610,
          "sha512": "98e1af84d4917f1881de8d56991dbec6b7d92b911dbf184ca741456d069210898290ab446725867e0a8f644eb83c8ae6237df417d536e7f038300f6edd0f7bef",
          "sha256": "16357a023efca986b5fd0d8ea8a9aa3efc399de867984d909f0cca9bbcb554d9",
          "sha1": "901f94ba51112cf5c346ad323456c3e7bd688e92",
          "md5": "0148ebc4e272fe7b0e13dc0b0369cd6e"
        }
      ]
    }
  ]
}
