{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.19/contract-0.0.19.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "julmyh4b25dnnegsjouy3lg5q4"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.19.jar",
          "url": "contract-jvm-0.0.19.jar",
          "size": 15079,
          "sha512": "dde63c0502a84b9cb43591048542dcb2e275d3f4150fd0e02cb9c0703facaad58e9c373e8e71286fe08e2bb39687cacf512e3aa7280d7b87a0217737d5922c41",
          "sha256": "949ff377c7ec54b2d2b653bf2968912fe00cafc09c461129168fb238e8a3a877",
          "sha1": "e47a62754757be0a6910464c20ff56c80f656c31",
          "md5": "15dddfd541d9ee03304b4769293f66d0"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.19.jar",
          "url": "contract-jvm-0.0.19.jar",
          "size": 15079,
          "sha512": "dde63c0502a84b9cb43591048542dcb2e275d3f4150fd0e02cb9c0703facaad58e9c373e8e71286fe08e2bb39687cacf512e3aa7280d7b87a0217737d5922c41",
          "sha256": "949ff377c7ec54b2d2b653bf2968912fe00cafc09c461129168fb238e8a3a877",
          "sha1": "e47a62754757be0a6910464c20ff56c80f656c31",
          "md5": "15dddfd541d9ee03304b4769293f66d0"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.19/contract-metadata-0.0.19.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.19"
      }
    }
  ]
}
