{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.32/model-0.0.32.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6qssia3r7rbwpb5cs5jxxg4cpy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.32"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0-RC2"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.32.jar",
          "url": "model-metadata-0.0.32.jar",
          "size": 13166,
          "sha512": "77105645c42604429f39e843d077f124e3cd96e296c162a32b90747cfa4d559a00d5c0f824dc6189f4942175a918694e20b229a5ff6aabdac74d8e317cc1727c",
          "sha256": "dbc3fdfc549d079345355a135b2610ca297cf66e0692cc57e0f64ee6363a13c7",
          "sha1": "2d15302248cbcaf51ee5bb971c809564ebc1f798",
          "md5": "fe332580e12c2eceae4fe9215c176e19"
        }
      ]
    }
  ]
}
