{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model-metadata",
    "version": "0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "2op6vpqzbfeszkvmuhojwr2oxe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.46"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.46.jar",
          "url": "model-metadata-0.0.46.jar",
          "size": 13116,
          "sha512": "a1d4d96fa4066f803bfe7a275aefc81a1ec94fa8cb829ed873307be6d0ef2df39ce20470d37c2398f01dea4f85107f2fd07d0fcb502609a3cc6df44ad3e77735",
          "sha256": "5da86a6d7c317b376cfc1dd78b6b9ca88f45b264c21787af6f962afbaf2997ae",
          "sha1": "06d2086c8f61af3c301efa3b99d909ff6da81e94",
          "md5": "4381054741976623691b5ea7523dec2f"
        }
      ]
    }
  ]
}
