{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-jvm/0.0.47/core-jvm-0.0.47.module",
    "group": "tech.skot",
    "module": "core-jvm",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.47.jar",
          "url": "core-metadata-0.0.47.jar",
          "size": 5341,
          "sha512": "2dd0f0c31f52c2cb99de8a45eb7f7c5bba673e80e570e5385a0f99383a4850dbff269bfd90d6421b2b9b4dc7c3ee58e2c92dc6337700d3e9e6b2961f1c3e4901",
          "sha256": "8638eb304133dba15605c8eb60a88b4ed495a12c91d10bfb77f140cb18d615c7",
          "sha1": "3ed3827a7deca64e9eba16f14b92d26016d7d1cf",
          "md5": "8cc1ef6cfe7c6d64def1efa578faf80c"
        }
      ]
    }
  ]
}
