{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.26/viewmodel-0.0.26.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.26-debug.aar",
          "size": 52132,
          "sha512": "908950c2b69b51e7b1a748fd2d6326111667ccf8f7bc3f31d3ade47064e01ab46d9ae11e35e1bf0755d595369b4e551def548901c6d9f09046f0da6644abeb63",
          "sha256": "295c252697344afc6c60f1e8324c48097141cc1300982c97371ccfb0b86c5723",
          "sha1": "27f3f38dbb1e069c13a5d5016b01074bc8325fdc",
          "md5": "f7289439a3b30deae832d6a19c8f50b5"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.26-debug.aar",
          "size": 52132,
          "sha512": "908950c2b69b51e7b1a748fd2d6326111667ccf8f7bc3f31d3ade47064e01ab46d9ae11e35e1bf0755d595369b4e551def548901c6d9f09046f0da6644abeb63",
          "sha256": "295c252697344afc6c60f1e8324c48097141cc1300982c97371ccfb0b86c5723",
          "sha1": "27f3f38dbb1e069c13a5d5016b01074bc8325fdc",
          "md5": "f7289439a3b30deae832d6a19c8f50b5"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.26.aar",
          "size": 50474,
          "sha512": "d9702a26dbfb32e113a798f8bcdc540a72c272d6e0252e3c84fbae435e6bd9541e4ecbd7e08236c083ddf752c83bcad6a487a35e816ca0f052a909f5de57455b",
          "sha256": "ab99f52fba02d4a9ecac2a11c24c622ecf91f6448642a01fe16858f18db40ebb",
          "sha1": "1ded7d4811150ea753b52a0585fa6b92427ded5f",
          "md5": "1852d2e83d8c70e3ac3812f3a8dcbf42"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.26.aar",
          "size": 50474,
          "sha512": "d9702a26dbfb32e113a798f8bcdc540a72c272d6e0252e3c84fbae435e6bd9541e4ecbd7e08236c083ddf752c83bcad6a487a35e816ca0f052a909f5de57455b",
          "sha256": "ab99f52fba02d4a9ecac2a11c24c622ecf91f6448642a01fe16858f18db40ebb",
          "sha1": "1ded7d4811150ea753b52a0585fa6b92427ded5f",
          "md5": "1852d2e83d8c70e3ac3812f3a8dcbf42"
        }
      ]
    }
  ]
}
