{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha20.jar",
          "url": "androidTests-1.0.0-alpha20.jar",
          "size": 261,
          "sha512": "3594a71f79a2de7b3083514f497872ca85ad1778e3f40e13de6b483d3bc3124e2ea984619787ea0b6c66b8b1b3e92eae7b0f3cbd23c4bab39425d8534deee005",
          "sha256": "28a1cbb9e0697fad38ca7c6ac7c2423f9db4f1d068fd395de91576d21f11e73c",
          "sha1": "6bab22ea87a08dc8031ae2f69296763693b27f26",
          "md5": "11677c6d4f5978a13a57aeeef68735c8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha20/androidTests-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha20/androidTests-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha20/androidTests-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha20/androidTests-android-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha20"
      }
    }
  ]
}
