{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha18.jar",
          "url": "generator-1.0.0-alpha18.jar",
          "size": 193711,
          "sha512": "11819cef732caf4b6a999c8d4e89a5b3c20d4d807c1229861e8454e8311d600db21140fbafb03cc7030cb3932531a4e5b31968adfaedf6b0f2369845019b204a",
          "sha256": "acc09426ec805219ec0e7a6ab54b1610e805497a15013d3999ad00a57a934e79",
          "sha1": "487b7cfd8fe4b207192756dcdf2bfc8740b2ce0c",
          "md5": "97537aac3ef5cad937d6f1a1959bc6fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha18"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha18.jar",
          "url": "generator-1.0.0-alpha18.jar",
          "size": 193711,
          "sha512": "11819cef732caf4b6a999c8d4e89a5b3c20d4d807c1229861e8454e8311d600db21140fbafb03cc7030cb3932531a4e5b31968adfaedf6b0f2369845019b204a",
          "sha256": "acc09426ec805219ec0e7a6ab54b1610e805497a15013d3999ad00a57a934e79",
          "sha1": "487b7cfd8fe4b207192756dcdf2bfc8740b2ce0c",
          "md5": "97537aac3ef5cad937d6f1a1959bc6fe"
        }
      ]
    }
  ]
}
