{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract-jvm/1.0.0-alpha4/viewcontract-jvm-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "viewcontract-jvm",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-metadata-1.0.0-alpha4.jar",
          "url": "viewcontract-metadata-1.0.0-alpha4.jar",
          "size": 11133,
          "sha512": "25272b9c69aaace61665f7a1443b8095beb34006b33f0215c1623a5ee7d6fe78082f04058b1f0d37d588a7164b07abd116554972d3db3004f6b6aba53b7a15cd",
          "sha256": "a5693f845fd02f271e4342426b273afca214c1d1a0565a3401371bfdc9414168",
          "sha1": "441ceca91cb77b590a8618940a214bcc1f5a6119",
          "md5": "a46f6178a07696ff528405b4aa352c36"
        }
      ]
    }
  ]
}
