{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h2qswlibvbgzncub57ri5633aa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.50.jar",
          "url": "generator-0.0.50.jar",
          "size": 94157,
          "sha512": "caebfa4fd541fd6d59c4f4d2108ec971c62c860a1cabaa6fa10664abed456c364fd00faf8f6ffe20b377126d01f8b15dcf9e65aee65b50718a3d46c0a8fccace",
          "sha256": "8f6bfdce0de79581bef3960abf010f4ad926dd4855df483d1ab82776d92895aa",
          "sha1": "1c3478345ca5fe2d2227c7060a6d5ebecec9a6c3",
          "md5": "2a718229cc6e25badb4e77ad586ae264"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.50.jar",
          "url": "generator-0.0.50.jar",
          "size": 94157,
          "sha512": "caebfa4fd541fd6d59c4f4d2108ec971c62c860a1cabaa6fa10664abed456c364fd00faf8f6ffe20b377126d01f8b15dcf9e65aee65b50718a3d46c0a8fccace",
          "sha256": "8f6bfdce0de79581bef3960abf010f4ad926dd4855df483d1ab82776d92895aa",
          "sha1": "1c3478345ca5fe2d2227c7060a6d5ebecec9a6c3",
          "md5": "2a718229cc6e25badb4e77ad586ae264"
        }
      ]
    }
  ]
}
