{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.46/contract-0.0.46.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "2op6vpqzbfeszkvmuhojwr2oxe"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.46.jar",
          "url": "contract-jvm-0.0.46.jar",
          "size": 20679,
          "sha512": "3c71f62324c714fa497c07314dd0b8409032b33533b2f6a60a71cacb5f0807120204c8284a3bd733447dd725c46313111fcb2e460385fa08e5c9823093353b2d",
          "sha256": "f0363053a2147c24bc4ac21c23d3796f6bf5f5a2a5a06863bc7f010b93ade0dc",
          "sha1": "a6c906e621a2ff12fe4c6a3c8de06c8336351bd6",
          "md5": "b15754ddb6c711b177b17ce29b6edd15"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.46.jar",
          "url": "contract-jvm-0.0.46.jar",
          "size": 20679,
          "sha512": "3c71f62324c714fa497c07314dd0b8409032b33533b2f6a60a71cacb5f0807120204c8284a3bd733447dd725c46313111fcb2e460385fa08e5c9823093353b2d",
          "sha256": "f0363053a2147c24bc4ac21c23d3796f6bf5f5a2a5a06863bc7f010b93ade0dc",
          "sha1": "a6c906e621a2ff12fe4c6a3c8de06c8336351bd6",
          "md5": "b15754ddb6c711b177b17ce29b6edd15"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.46/contract-metadata-0.0.46.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.46"
      }
    }
  ]
}
