{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewlegacy-metadata",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-metadata-1.0.0-alpha4.jar",
          "url": "viewlegacy-metadata-1.0.0-alpha4.jar",
          "size": 261,
          "sha512": "757f9665691493b92cfacdf6a20c0fb8f630e06804a96545726e246ecbdac2d61d6ef23c2dc283fbdd5f20cd66827f810c555b3a3eb5efd239a17cb2f5b28d90",
          "sha256": "876a15c5ce84c0fa3dcffb826f2f4ee979bc601742b84e7f549b0addeb747bd7",
          "sha1": "036b4c68acc9ca2015c4de19a94913dd5b3e4a83",
          "md5": "cac7330e293f3c2b695bf1cc16cdc8c0"
        }
      ]
    }
  ]
}
