{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha12/modelcontract-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha12.jar",
          "url": "modelcontract-jvm-1.0.0-alpha12.jar",
          "size": 53926,
          "sha512": "4f62e882381c292599f905910f08ad2439c7e9a0de8f85973f85a3cf4ba3f32a1bc6d1475596c6b862e4b628e2af4cdcdf0916cdfaca0ea8290a0589259fabde",
          "sha256": "125e64bdfbaabf28af733e11533ff54c91df6c43fc04c7417e9abb32e82c8144",
          "sha1": "be94ef3ce16dc5b002a4615b0b7e8917424f2996",
          "md5": "4164c7720d537354136b9966d09c84b7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha12.jar",
          "url": "modelcontract-jvm-1.0.0-alpha12.jar",
          "size": 53926,
          "sha512": "4f62e882381c292599f905910f08ad2439c7e9a0de8f85973f85a3cf4ba3f32a1bc6d1475596c6b862e4b628e2af4cdcdf0916cdfaca0ea8290a0589259fabde",
          "sha256": "125e64bdfbaabf28af733e11533ff54c91df6c43fc04c7417e9abb32e82c8144",
          "sha1": "be94ef3ce16dc5b002a4615b0b7e8917424f2996",
          "md5": "4164c7720d537354136b9966d09c84b7"
        }
      ]
    }
  ]
}
