{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.34/core-0.0.34.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sdiuqgpfpvgqbhgb64jk7k3g3u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.34.jar",
          "url": "core-metadata-0.0.34.jar",
          "size": 5329,
          "sha512": "abea2875797ae90843a0ee33361c93d84fd2be2e919016be9443657d11dc89c62b4db0869fe2f7c410d7957d54df72647b45f93bbec671cb8af6bbd89a1b00cc",
          "sha256": "acd4574ce5b986610a17c27cf17b2e184407b03d82e0e17cfaf342fa4d2e1b0c",
          "sha1": "bf886bd7e84800f61e0355e46d49119a9b5e3d9b",
          "md5": "48a1c0b9ae54af64c57412cd03e95fcd"
        }
      ]
    }
  ]
}
