{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha18.jar",
          "url": "core-1.0.0-alpha18.jar",
          "size": 7358,
          "sha512": "27a26c9f62281a83714120d4c32c88755ac1b6a134f1da7710438ee706afcaca10853f28aaf1e9c221f70775a6864420ccf18e22801656dcbcd4ea93b27ce64b",
          "sha256": "39254bdcfb0b25d468408fde290ecc999d34f5441c9df0b5c4c6ad887c42224e",
          "sha1": "f924103080e51fb6c294807693a229f888e4e73e",
          "md5": "cbea1dbd331bf75ef7566a424cccfc52"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha18/core-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha18/core-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha18/core-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha18/core-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha18/core-iosarm64-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha18/core-iosx64-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha18"
      }
    }
  ]
}
