{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.7/core-0.0.7.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "igasumkhiveslbdlejoqxrssj4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.7.jar",
          "url": "core-metadata-0.0.7.jar",
          "size": 4883,
          "sha512": "45939caddb342765dbcf57c49be03c08f228bc65759caaed481e3b2e9081d6839925ed37ff02e6047866c8d70d332e0545e4c2f4bdf9934a11cda72cd6a9412e",
          "sha256": "6072b80de8df28b49b0d2d28326e11f13cb7464d09c75f72cd2c6e57011b62da",
          "sha1": "2711212f9f86e7ebd22025579f14957b6189e339",
          "md5": "a0a04bffc3059a6e164ce1fec355b4b9"
        }
      ]
    }
  ]
}
