{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.30/contract-0.0.30.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "45vyvjpy25d6rogm6vet7cshky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.30.jar",
          "url": "contract-metadata-0.0.30.jar",
          "size": 7614,
          "sha512": "ae665891a827d276ee6693a4a64d2857ec7dc8a7d792b87596f006f92c54edb1fbe21c31e7c6872224b2f70cbc41f22dfd4b3e6ddd97b16ac78d1fb62fee6365",
          "sha256": "032910cf835f5392e52558ea7e06c340ef327fd1657d8f4ef8bfee1331e410e3",
          "sha1": "71604172a187556767f8e534aad29561779ccdf2",
          "md5": "4f035fe5c042149dff3be23b656da00e"
        }
      ]
    }
  ]
}
