{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha23/viewcontract-1.0.0-alpha23.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha23.jar",
          "url": "viewcontract-jvm-1.0.0-alpha23.jar",
          "size": 54995,
          "sha512": "7ce94854b3780b5f59395ff67bd7bcb94f66ec696c7bf9dafab9608498b25fd72024d1618cbbbb35cf2e170ada631b44d33d6ca3ac8cbed7b21ebc399f4731c3",
          "sha256": "e3f5292513a48cfb3c842858269c4b4f320911d947b9612335b795e8ff7f28ff",
          "sha1": "82408a75528e762ad97f1d51f722a5e69b54bf80",
          "md5": "8c5488691a03409fba7c772a904f921f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha23.jar",
          "url": "viewcontract-jvm-1.0.0-alpha23.jar",
          "size": 54995,
          "sha512": "7ce94854b3780b5f59395ff67bd7bcb94f66ec696c7bf9dafab9608498b25fd72024d1618cbbbb35cf2e170ada631b44d33d6ca3ac8cbed7b21ebc399f4731c3",
          "sha256": "e3f5292513a48cfb3c842858269c4b4f320911d947b9612335b795e8ff7f28ff",
          "sha1": "82408a75528e762ad97f1d51f722a5e69b54bf80",
          "md5": "8c5488691a03409fba7c772a904f921f"
        }
      ]
    }
  ]
}
