{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.36/model-0.0.36.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yghnb2gewvenvmp42l64g7zv3y"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.36.jar",
          "url": "model-metadata-0.0.36.jar",
          "size": 13166,
          "sha512": "187d195329e70ed121e5954e598f6b68a891eb5aa339e3955ae5e5343575e9aebf7ba68d0f476aa4d2dbb3b2df2f9a59d19646b55d0c50817c12e6eb1b5c92fa",
          "sha256": "188335f2bcd19866e6c65957f87e5079c610d18e3e758244fc73491157f93fa9",
          "sha1": "0bf6029d3ab08985cb962b4d325d5f827889037c",
          "md5": "22d747d87dfea641df301c1da795d353"
        }
      ]
    }
  ]
}
