{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.2/androidTests-0.0.2.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "r76z3av2pjgf5gaz7k45ehatda"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.2.jar",
          "url": "androidTests-metadata-0.0.2.jar",
          "size": 261,
          "sha512": "60a1b9d7673b4e72af2e813dd6b82152e6b03b63193033713c7db4b96469505b02f46a70b1387239a13ee5eb395d6b40dcfd3588117597cde4d591018d7d823",
          "sha256": "5f8787fd366d52bbc0aa953ea1c64fb0421fa2b4b20b1ea452b8f6f14781778b",
          "sha1": "81a4fd996b26839e5bc157d2dfcff82381bce45e",
          "md5": "6c3cb693ac4c3ebec8949277643e10"
        }
      ]
    }
  ]
}
