{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5vu6ywwiijbhlbbtlao5nfwm2q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.8.jar",
          "url": "generator-0.0.8.jar",
          "size": 92115,
          "sha512": "ac311dc690d624f725e578a2ce801dee7586c01fa708c0098b41fc82fa22e1e687c2750b6d44b1605abfb36d7ee84f3a260a89a71788a812dac1998b763e6f29",
          "sha256": "826f17e47b78538f611918c2c3d9b826479037a3f13ac6be8828df6806e99947",
          "sha1": "f7f7d0d7708e4ee6e6412e9254dc90dc74b05bde",
          "md5": "4ec40012f9548daa193eac9014f6f908"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.8.jar",
          "url": "generator-0.0.8.jar",
          "size": 92115,
          "sha512": "ac311dc690d624f725e578a2ce801dee7586c01fa708c0098b41fc82fa22e1e687c2750b6d44b1605abfb36d7ee84f3a260a89a71788a812dac1998b763e6f29",
          "sha256": "826f17e47b78538f611918c2c3d9b826479037a3f13ac6be8828df6806e99947",
          "sha1": "f7f7d0d7708e4ee6e6412e9254dc90dc74b05bde",
          "md5": "4ec40012f9548daa193eac9014f6f908"
        }
      ]
    }
  ]
}
