{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.43/contract-0.0.43.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "umuh4wxdqfdghocu4tjfq6qmxe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.43.jar",
          "url": "contract-metadata-0.0.43.jar",
          "size": 8535,
          "sha512": "d301213e60df5636e329cd7b94aa60fa73a90ae4a053efe9a43365d9637e47a458fcd754a89ab23fca628b5e45ee888e448e707f22aa481445fef03356c53d1c",
          "sha256": "82aea2c76d366331c72f95d372a2ba8f9233fee3911378d69e08441b7c3f5d04",
          "sha1": "49d127c2042b6789da27effbe6bf8314c18e3901",
          "md5": "25256c6546fa8014607c29f857a0d7c7"
        }
      ]
    }
  ]
}
