{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.49/contract-0.0.49.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.49.jar",
          "url": "contract-jvm-0.0.49.jar",
          "size": 20679,
          "sha512": "d3dd4d1ce784df088bbeaf6cb10559bc680a750b8232041aabbd3df4fb57782d683b2e62c0f00ca8e82a917104cfbe7b3e5c275d02cad1c7ba01c97bf43a6f6c",
          "sha256": "237138e437626cd4fc82cffdec515dc98bc606a113e79fecff65eaa2c1c54a81",
          "sha1": "f19c41fa6ab7ff383512164cd2374b899c76bee0",
          "md5": "741cca678bb574eb2d415ec01f6118fb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.49.jar",
          "url": "contract-jvm-0.0.49.jar",
          "size": 20679,
          "sha512": "d3dd4d1ce784df088bbeaf6cb10559bc680a750b8232041aabbd3df4fb57782d683b2e62c0f00ca8e82a917104cfbe7b3e5c275d02cad1c7ba01c97bf43a6f6c",
          "sha256": "237138e437626cd4fc82cffdec515dc98bc606a113e79fecff65eaa2c1c54a81",
          "sha1": "f19c41fa6ab7ff383512164cd2374b899c76bee0",
          "md5": "741cca678bb574eb2d415ec01f6118fb"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.49/contract-metadata-0.0.49.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.49"
      }
    }
  ]
}
