{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha16/modelcontract-1.0.0-alpha16.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha16.jar",
          "url": "modelcontract-jvm-1.0.0-alpha16.jar",
          "size": 57086,
          "sha512": "350e767dbe4ce73d08aeb39c26921eb5b9d9b6ed9a37b8b16acf46c425f7e8c1ace5fa57b9725d7aabcaa9ad3a2d5b55c73703e1ee419d822f2c336b643dfbf5",
          "sha256": "710b080d4313838d44c9007d03cb536d6c7ada3edaa28316d6baad4bd6436316",
          "sha1": "79459bb12b7602a3b4e9b445422b44b51096531a",
          "md5": "57bc26b49b1801b7cecda2d06789954f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha16.jar",
          "url": "modelcontract-jvm-1.0.0-alpha16.jar",
          "size": 57086,
          "sha512": "350e767dbe4ce73d08aeb39c26921eb5b9d9b6ed9a37b8b16acf46c425f7e8c1ace5fa57b9725d7aabcaa9ad3a2d5b55c73703e1ee419d822f2c336b643dfbf5",
          "sha256": "710b080d4313838d44c9007d03cb536d6c7ada3edaa28316d6baad4bd6436316",
          "sha1": "79459bb12b7602a3b4e9b445422b44b51096531a",
          "md5": "57bc26b49b1801b7cecda2d06789954f"
        }
      ]
    }
  ]
}
