{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.15/view-0.0.15.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gqpemdskoneufiyethujbxdcv4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.15.jar",
          "url": "view-metadata-0.0.15.jar",
          "size": 5556,
          "sha512": "8d18473cf6afd4145ad068ab6e9816f730a8980b2f6fb7c1712de174efa717f86713f45a80b2531f9fcd44c9432c32d78edb5e9adaa7b282c8600963abf47b4e",
          "sha256": "2adf783477f3d68dad782d053c8192b0733b3b03d9c84b2b82316e9f8aff86d1",
          "sha1": "e7dd77105df44f6de7b3393bc6c0d3718cac6b66",
          "md5": "5a080edf916b0675d907ff685c86dcfb"
        }
      ]
    }
  ]
}
