{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.2/core-0.0.2.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "r76z3av2pjgf5gaz7k45ehatda"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.2.jar",
          "url": "core-metadata-0.0.2.jar",
          "size": 4224,
          "sha512": "37225ff7b3f6604fe02c73e210455f1c0cb0d5d4bf7cd92fb81960c19763ab34e3aa54de844b7ddf89c01924a05024386da2b9cb608dad6a346fc84024f9a3e",
          "sha256": "10376fc589851286fb21db246432ed164e495d437f2346d2dae223831179568a",
          "sha1": "a39ee9100cba0e4b7b604d731c8a90fd29114f7a",
          "md5": "eb55167e364de305fb349e40afa9bf2f"
        }
      ]
    }
  ]
}
