{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.2/contract-0.0.2.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "r76z3av2pjgf5gaz7k45ehatda"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.2.jar",
          "url": "contract-metadata-0.0.2.jar",
          "size": 6871,
          "sha512": "20415d96da5f420c37d1cc6e7344a3074ce420dffd3fb1f01d18a6f5bde9776bf2cad3545960ab964af79654428b821bf6c1fa8e35ed99988584a1970b9bccf",
          "sha256": "b2b23e985aecc1d3c90325a36392b6f2dfaadd22b46fc1ff18a2b52305813562",
          "sha1": "a45e1a92cb4f8d80e715a120ffa4ad0193937e6d",
          "md5": "f7f14919b143eb34df038a9ae40ce631"
        }
      ]
    }
  ]
}
