{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.8/contract-0.0.8.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5vu6ywwiijbhlbbtlao5nfwm2q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.8.jar",
          "url": "contract-metadata-0.0.8.jar",
          "size": 7621,
          "sha512": "907c19ae1e976908fec52be0652d1503a6fb90b8407557b37d07d9394852ed4abd1db722c06cfee02c06a5f0f93b591ac8a865798abe1ffacdfd5769b6616353",
          "sha256": "98b8218b0b86226afda3ab91752563ca1e79677b0216db822ebc4ec3b1af2671",
          "sha1": "8cfab7c197ec80ce6f00b9cc3cad8f8414a4f4fb",
          "md5": "4982098b82063687d7ee9311523e90ca"
        }
      ]
    }
  ]
}
