{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-1.0.0-alpha13.jar",
          "url": "core-1.0.0-alpha13.jar",
          "size": 7333,
          "sha512": "f92f9ecdbfc91f332d01a856e4e1a5b918daa1b27d23cb4d72d25996eaeebfde5b31f55b14f44adb8b6daa02958a32af904519f694b137ff4b241f7558d74655",
          "sha256": "7044fe99a8c15c16b74781ed717756251e3fc916dd960524b88923321f06e530",
          "sha1": "1cfb6b2a57bdddcae9eec2dd8fcd38f0cde44479",
          "md5": "53d1dfc36d7c8e6bc6aaea2c27c29c0e"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha13/core-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha13/core-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha13/core-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/1.0.0-alpha13/core-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosarm64/1.0.0-alpha13/core-iosarm64-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "core-iosarm64",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../core-iosx64/1.0.0-alpha13/core-iosx64-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "core-iosx64",
        "version": "1.0.0-alpha13"
      }
    }
  ]
}
