{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.4/androidTests-0.0.4.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qkfbndnh6jfalpfv2y37cujupm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.4.jar",
          "url": "androidTests-metadata-0.0.4.jar",
          "size": 261,
          "sha512": "7d7f5d9ea496808ed22600c48f8b84797c7905990209efd79d50cd8f2e827b95ac397021e958f2d86e1e40a69a7ab00decc2f73592a8879224e69b840944804a",
          "sha256": "186844aa067ee3a0dc806746196fea6c4daa7da316281aa6f326c026d79d7ee4",
          "sha1": "d517d099b90cf00f8e2a458abeb8ffde2fb0549",
          "md5": "ad30b5cc24c491810b9682f458b6c40c"
        }
      ]
    }
  ]
}
