{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "2op6vpqzbfeszkvmuhojwr2oxe"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.46"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.46.jar",
          "url": "view-0.0.46.jar",
          "size": 6294,
          "sha512": "6889141cb53f82c44f8b7593ef617d7fdd8f02fb5bbc2d70a44cc55051a146ab080ad4b63e3d9abcc3c0001fe79b8bafc6bdbe4973a37af706779812460c8286",
          "sha256": "3d23c1510ea7f688a20fdc0944eb759e4834e82732e6a5e9239ab0742e760c1e",
          "sha1": "4c19e938bc1061ca724fa2cd4abee7f238b61d8a",
          "md5": "9bbd95d8ebfe1605fc5d3c0557d88bb0"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.46/view-android-0.0.46.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.46"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.46/view-android-0.0.46.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.46"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.46/view-android-0.0.46.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.46"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.46/view-android-0.0.46.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.46"
      }
    }
  ]
}
