{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yghnb2gewvenvmp42l64g7zv3y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.36.jar",
          "url": "generator-0.0.36.jar",
          "size": 94266,
          "sha512": "b3ff464e647b61f3e9c2a2096ae63ee271933a6c27bfaebada32053e0a6ea4f9a90cda1ecffceba37457e508f8451e827457dfc432e8110f324ca519c6bbddf8",
          "sha256": "36efa11a1df6adee4491c7d0e8a8f6bc0fae7f134efb632998a0a35f3cfc16e4",
          "sha1": "581249a9a7c18d1abea0aed6a67b1066c6a64e7e",
          "md5": "f4801f492b05e61815c4aa9c416a50ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.36.jar",
          "url": "generator-0.0.36.jar",
          "size": 94266,
          "sha512": "b3ff464e647b61f3e9c2a2096ae63ee271933a6c27bfaebada32053e0a6ea4f9a90cda1ecffceba37457e508f8451e827457dfc432e8110f324ca519c6bbddf8",
          "sha256": "36efa11a1df6adee4491c7d0e8a8f6bc0fae7f134efb632998a0a35f3cfc16e4",
          "sha1": "581249a9a7c18d1abea0aed6a67b1066c6a64e7e",
          "md5": "f4801f492b05e61815c4aa9c416a50ca"
        }
      ]
    }
  ]
}
