{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.3/androidTests-0.0.3.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "su2tjwkhbbbjndaqanwwqcxe24"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.3.jar",
          "url": "androidTests-metadata-0.0.3.jar",
          "size": 261,
          "sha512": "16b46590d9a2590aa83213d9fa928ac5d28d9d45334d2e5aaab7db0d059bc42dc9de76e86cf95403b81c3079674f4cc80e6e8e20aa1c61fda8c84bf25995983e",
          "sha256": "f917c184cf15cd2567f9190f23a20fcaf5f5460f8f6f17997600ae522e8b6fe3",
          "sha1": "d3b99a9b8bf56be3a5313de70da4833301bdcf3e",
          "md5": "1ad5f4541c9e157dbf8b2047ea3a4400"
        }
      ]
    }
  ]
}
