{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.44/viewmodel-0.0.44.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i7olmwxatfdhths5wu7quwrrny"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.44.jar",
          "url": "viewmodel-metadata-0.0.44.jar",
          "size": 7429,
          "sha512": "15cf1473cf9d1c26f68a05e54523585d130fb507afc6aaab94b8ed2193a814946baa7c827ab1f1d5824d513b15f243f1d1b8b079d94d0dca49e879c8c3eb0cdf",
          "sha256": "b506af929edaac2409517148fc341bcbdac9f907182222ed1087e3d12fcbffcc",
          "sha1": "6f35d04fc1cc86a05fd5c9cd8591f3fd6f74a2dd",
          "md5": "04c316b9a1faa9570a61996780d866dd"
        }
      ]
    }
  ]
}
