{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.40/contract-0.0.40.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "vudukgf34fdc3murg37da3g47e"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.40.jar",
          "url": "contract-jvm-0.0.40.jar",
          "size": 20546,
          "sha512": "a72093e60106172416533c12e1277878c2679f5151bd278be78a63fe34d144f226cd5e1f94ea6db5fcb52b8fa941b3230ee9cdbb9d7a34c612b9aa16caf1cb55",
          "sha256": "beb9609ab45db7f5dfede7cf8e867f25ee8cacc6c6b2a76584d950454cb45b31",
          "sha1": "dd3d3d680037dbf1d3fd86158ae0ee585dd28d87",
          "md5": "1c722f14c13861f8470815c16068bc65"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.40.jar",
          "url": "contract-jvm-0.0.40.jar",
          "size": 20546,
          "sha512": "a72093e60106172416533c12e1277878c2679f5151bd278be78a63fe34d144f226cd5e1f94ea6db5fcb52b8fa941b3230ee9cdbb9d7a34c612b9aa16caf1cb55",
          "sha256": "beb9609ab45db7f5dfede7cf8e867f25ee8cacc6c6b2a76584d950454cb45b31",
          "sha1": "dd3d3d680037dbf1d3fd86158ae0ee585dd28d87",
          "md5": "1c722f14c13861f8470815c16068bc65"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.40/contract-metadata-0.0.40.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.40"
      }
    }
  ]
}
