{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.34/androidTests-0.0.34.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sdiuqgpfpvgqbhgb64jk7k3g3u"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.34.jar",
          "url": "androidTests-metadata-0.0.34.jar",
          "size": 261,
          "sha512": "e5792f316161051567703c12c76e9168571b9a4d95f47e84fe9646c932b77a447af2bbfb8531377ef2a8bcfc162da62127cea777252318871b42e4a52bc83fac",
          "sha256": "792b769f833c932b960efaf70a39e25c3e621cc3cffab2e048d2461e8afb64cd",
          "sha1": "a8bda52129353c04f32df544a9871283381916ef",
          "md5": "ca18ba78092001086e6d349957980eef"
        }
      ]
    }
  ]
}
