{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.6/contract-0.0.6.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3w2f7l7ypffvjgcalkwzywgyy4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.6.jar",
          "url": "contract-metadata-0.0.6.jar",
          "size": 7621,
          "sha512": "eab5fd908e8374414805165574afc126cf0b69988a3f62b124e2a5636d7f9c242642225ba1c0ebec4c9b99867d1df4cfff01436901d9ee3ccd05f06442257424",
          "sha256": "b57a0b44e9db84674ab8bbc44650f3f0102fc1a25f01aa6d7d2fc599587b0be6",
          "sha1": "5519331a834801de1338547ddbf87e5adfd3dbe0",
          "md5": "2231d1041f2a08b30ed7790e797f0623"
        }
      ]
    }
  ]
}
