{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha14/viewcontract-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "542d3vhgfrhaxgd5li4auko6d4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha14.jar",
          "url": "viewcontract-jvm-1.0.0-alpha14.jar",
          "size": 53940,
          "sha512": "da2cc31afd0ca1785e19e26f057bd4441548fb55feebc56e7c7ab8bc49a98ef9c1631a3c18372877c382620b4c49e09ce898ea817f1e4c65d51c24ecbd4a537e",
          "sha256": "40f20c566c29212a051c5a591ee475ec60f434ec0b9b5cc51c7196a848062df0",
          "sha1": "73ae5b6e8fca6b5f86d922da31be6e1909197861",
          "md5": "16de55a82170e6eab7290ccc216007ec"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha14.jar",
          "url": "viewcontract-jvm-1.0.0-alpha14.jar",
          "size": 53940,
          "sha512": "da2cc31afd0ca1785e19e26f057bd4441548fb55feebc56e7c7ab8bc49a98ef9c1631a3c18372877c382620b4c49e09ce898ea817f1e4c65d51c24ecbd4a537e",
          "sha256": "40f20c566c29212a051c5a591ee475ec60f434ec0b9b5cc51c7196a848062df0",
          "sha1": "73ae5b6e8fca6b5f86d922da31be6e1909197861",
          "md5": "16de55a82170e6eab7290ccc216007ec"
        }
      ]
    }
  ]
}
