{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.1/viewmodel-0.0.1.module",
    "group": "tech.skot.libraries.tabbar",
    "module": "viewmodel",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.1-debug.aar",
          "size": 16968,
          "sha512": "1e96ef79a893ad70714926da6d15450586b862c5e45d28431c61a1f831fcd12e4a99f77046ed15d4d5e58d54e866d704b351a386305048ef1cc6de9e8ab4273d",
          "sha256": "4fa7621b13a799bc2d3462d7fcceaac26c7ec6a2c5f1287851fe72b4af0a9762",
          "sha1": "76886f9b01d24ba9859964a457e5d3dafe6c6a2e",
          "md5": "2e4ed58b3637c6c1b34799097cf1e885"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewmodel",
          "version": {
            "requires": "1.0.0-alpha25"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.1-debug.aar",
          "size": 16968,
          "sha512": "1e96ef79a893ad70714926da6d15450586b862c5e45d28431c61a1f831fcd12e4a99f77046ed15d4d5e58d54e866d704b351a386305048ef1cc6de9e8ab4273d",
          "sha256": "4fa7621b13a799bc2d3462d7fcceaac26c7ec6a2c5f1287851fe72b4af0a9762",
          "sha1": "76886f9b01d24ba9859964a457e5d3dafe6c6a2e",
          "md5": "2e4ed58b3637c6c1b34799097cf1e885"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.1.aar",
          "size": 16209,
          "sha512": "75b8af7b842ac793d6a8fddc38216d921efa099cf241c13401f728db1faa6fcb37a6536e3f843a1f273b2b4b1928970b2279391f0d426ca48457c1a953ca4c93",
          "sha256": "db176bd73440823aa50c49a8b55487275a0dcf3c1373745e1b0c90e5c9b4f5de",
          "sha1": "1fabb9ee20a0e67cbe52af11459fbf4b45393496",
          "md5": "88d643429586b4fe1c708a1a0dcd8ccf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewmodel",
          "version": {
            "requires": "1.0.0-alpha25"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.1.aar",
          "size": 16209,
          "sha512": "75b8af7b842ac793d6a8fddc38216d921efa099cf241c13401f728db1faa6fcb37a6536e3f843a1f273b2b4b1928970b2279391f0d426ca48457c1a953ca4c93",
          "sha256": "db176bd73440823aa50c49a8b55487275a0dcf3c1373745e1b0c90e5c9b4f5de",
          "sha1": "1fabb9ee20a0e67cbe52af11459fbf4b45393496",
          "md5": "88d643429586b4fe1c708a1a0dcd8ccf"
        }
      ]
    }
  ]
}
