{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.1/viewmodel-0.0.1.module",
    "group": "tech.skot.libraries.tabbar",
    "module": "viewmodel",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.1-debug.aar",
          "size": 17147,
          "sha512": "c58a04462c4f8b1db45f72da29ea7ad2bd4788ac1c7eab4592602973f72ddf1c0955f810dd82af8b98a24a479e6d4759a9af6a196c8502192b622ee717109bbe",
          "sha256": "97baaebd05d46f27bb29808656ca4bf08c6c929579da9738115825e8e0c460d6",
          "sha1": "9c192f26db86f1bdd93ded1c21f5a5138167a051",
          "md5": "c1bfc00e7e17672a4c26d5c11337b907"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewmodel",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.1-debug.aar",
          "size": 17147,
          "sha512": "c58a04462c4f8b1db45f72da29ea7ad2bd4788ac1c7eab4592602973f72ddf1c0955f810dd82af8b98a24a479e6d4759a9af6a196c8502192b622ee717109bbe",
          "sha256": "97baaebd05d46f27bb29808656ca4bf08c6c929579da9738115825e8e0c460d6",
          "sha1": "9c192f26db86f1bdd93ded1c21f5a5138167a051",
          "md5": "c1bfc00e7e17672a4c26d5c11337b907"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.1.aar",
          "size": 16387,
          "sha512": "ee12eeae527ceed63c6bab94d30dce92257c154357f3fc5887d477bb9bc2523baf2403ee5639f3969fed1ac46d8174ac7d365c567fd8ba321319e2a349a7889f",
          "sha256": "b31d30e5390e65d8dd2cbad04988841ccad061270b8183b3457db040f1ce02ca",
          "sha1": "92f32224d6000e70871f428e2d9c30196c99f79d",
          "md5": "1318683de76d553599534a72de1c7a52"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewcontract",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewmodel",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.1.aar",
          "size": 16387,
          "sha512": "ee12eeae527ceed63c6bab94d30dce92257c154357f3fc5887d477bb9bc2523baf2403ee5639f3969fed1ac46d8174ac7d365c567fd8ba321319e2a349a7889f",
          "sha256": "b31d30e5390e65d8dd2cbad04988841ccad061270b8183b3457db040f1ce02ca",
          "sha1": "92f32224d6000e70871f428e2d9c30196c99f79d",
          "md5": "1318683de76d553599534a72de1c7a52"
        }
      ]
    }
  ]
}
