{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.29/model-0.0.29.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.29"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.29.jar",
          "url": "model-metadata-0.0.29.jar",
          "size": 13171,
          "sha512": "ec5aef0aaac4e4d6deb8013acd43e039c869c89fedcbe8eebc1867fd547ee2e52a004aceb681f3d6f3677551d29c5c763a9ddbf4c80638a98591908d5a7f4264",
          "sha256": "647359833c21da0b470c35f9e31798fe903b433d6ff09c99a38a554d5861a672",
          "sha1": "0e322dd7bf906e5f34e289f26bc91970d155ecd6",
          "md5": "e2428543e6033af69c22b4c604d87c7f"
        }
      ]
    }
  ]
}
