{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha4/modelcontract-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosx64-1.0.0-alpha4.klib",
          "size": 14218,
          "sha512": "26e1eb5e578f3bb5f98d884b47410b1c598529bb793f2441604a7a4285a650b39284214ea7dc31a1b5c7d052dd6e663d3eb7844bd37ad31b54169348168ad95a",
          "sha256": "5e35bc07292a967e0fc74bc0d96e13c02be008f913c16a857b42b5dc0bc82e49",
          "sha1": "f51da2fa6f7b60043cd7d337cd0222eb3757fede",
          "md5": "a5c976236744fe40b1e4553a54fbb7d5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../modelcontract-metadata/1.0.0-alpha4/modelcontract-metadata-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "modelcontract-metadata",
        "version": "1.0.0-alpha4"
      }
    }
  ]
}
