{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.33/androidTests-0.0.33.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "dpaczj3htbf6dbuy2gp2yf4ski"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.33.jar",
          "url": "androidTests-metadata-0.0.33.jar",
          "size": 261,
          "sha512": "abd2e337a38194cb6243b241ebb74db78fc774eeebfcf6d5eda08a711cbc0660b54e640eb18b12b795002016025e56f74fd49edfe86e823c395c62821552d8e0",
          "sha256": "c12c3139505bcedc019aefc9fa6b2a297e089582e147d07da57778bbc5f3cd34",
          "sha1": "c07d3bcba8cf171aed2ce1ff7d9e5ae55a6fcd1f",
          "md5": "f3af6295f9ebcf6241f4001ea351711f"
        }
      ]
    }
  ]
}
