{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha18/viewcontract-1.0.0-alpha18.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha18.jar",
          "url": "viewcontract-jvm-1.0.0-alpha18.jar",
          "size": 54321,
          "sha512": "af37e5557229b3d2f1cba56cd48867c81b8073f6a400b49296d6cfa4d90a90fa312699ea7a632164439384f33968ed3ff37a7cd49ea437fe9231d33e26a0ce78",
          "sha256": "998d3139aebfeba2e7d1fc8b932ec9bfa34a138744f6d990b53af74abd1cb048",
          "sha1": "49b9df8e9fd7a1c2f61b33b5e652f75dea8e3aef",
          "md5": "1a58663804a6ae66b2f4066fa4891502"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha18.jar",
          "url": "viewcontract-jvm-1.0.0-alpha18.jar",
          "size": 54321,
          "sha512": "af37e5557229b3d2f1cba56cd48867c81b8073f6a400b49296d6cfa4d90a90fa312699ea7a632164439384f33968ed3ff37a7cd49ea437fe9231d33e26a0ce78",
          "sha256": "998d3139aebfeba2e7d1fc8b932ec9bfa34a138744f6d990b53af74abd1cb048",
          "sha1": "49b9df8e9fd7a1c2f61b33b5e652f75dea8e3aef",
          "md5": "1a58663804a6ae66b2f4066fa4891502"
        }
      ]
    }
  ]
}
