{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.3/model-0.0.3.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "su2tjwkhbbbjndaqanwwqcxe24"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.3.jar",
          "url": "model-metadata-0.0.3.jar",
          "size": 11377,
          "sha512": "75fdf95348a21cac79d247d1c23b01f872fa39ac3bc8a339c30056fd271dd58af1ca8e49d41c8e620fc0e0497e59dd9c7096155732266da18a40b2a666863973",
          "sha256": "355febbb7dcc477d185f571f65b9276e6b075c4ec89827052a99643207ab3ad1",
          "sha1": "7fd5bcd73bb3e3fe2c9ea6d03acd1d2970d6b829",
          "md5": "4f3910d42cf8afaadc142398fdf22523"
        }
      ]
    }
  ]
}
