{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.32/core-0.0.32.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6qssia3r7rbwpb5cs5jxxg4cpy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.32.jar",
          "url": "core-metadata-0.0.32.jar",
          "size": 5329,
          "sha512": "d7d84fb677cc97d8b766e121bcd82a6c83bdc2daf509b08247010921286f8ff2938904c55cba88dd907dda00b42f5b0235d2ea20eebdac37ab3a57fc355f77d0",
          "sha256": "d15b34047ede18957d36e729e071d6c05818d8ec22dfceb5d7a299c11c2c86d8",
          "sha1": "0d2ce8dab4db3b5de9969d6bb6532a7f32dd9d56",
          "md5": "42c5c08f5dd1a3c9d64898456cd694fd"
        }
      ]
    }
  ]
}
