{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.27/model-0.0.27.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "7rpxctj73vafjppxfjwlavvutq"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.27-debug.aar",
          "size": 93387,
          "sha512": "fa770fca5474446c2fde1c8a2e3bf512fbfeebe83686cf58c5e06fd93f25c28e6fc0f9afe909c59730f86b67740f0df32497ca5bca0a97df690ccc2fc639acc4",
          "sha256": "04a5f51edc4015804ce02b775986391de43b23a7a68ab9546993dce76b078591",
          "sha1": "9f65b5a37a81451137bf17560239d8e79c6e098e",
          "md5": "6aa82e1943cb43c9fc4d4cbc7424e651"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.27-debug.aar",
          "size": 93387,
          "sha512": "fa770fca5474446c2fde1c8a2e3bf512fbfeebe83686cf58c5e06fd93f25c28e6fc0f9afe909c59730f86b67740f0df32497ca5bca0a97df690ccc2fc639acc4",
          "sha256": "04a5f51edc4015804ce02b775986391de43b23a7a68ab9546993dce76b078591",
          "sha1": "9f65b5a37a81451137bf17560239d8e79c6e098e",
          "md5": "6aa82e1943cb43c9fc4d4cbc7424e651"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.27.aar",
          "size": 89585,
          "sha512": "8275e28d48f39fde259852c31417e25d2523872866331e21617249088827920619c110805612b6553bbdce3861350077b77eb809be9c9b97e240f97711d3aa30",
          "sha256": "8a060cc4d59e6f1da2fac129f8f921355ab509debf484f4f63405174063e5930",
          "sha1": "9e3b27da45bcae48484bb45f9d868dd7de420d31",
          "md5": "8d033643daa9ee4d6ef2760c7aa32d40"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.27.aar",
          "size": 89585,
          "sha512": "8275e28d48f39fde259852c31417e25d2523872866331e21617249088827920619c110805612b6553bbdce3861350077b77eb809be9c9b97e240f97711d3aa30",
          "sha256": "8a060cc4d59e6f1da2fac129f8f921355ab509debf484f4f63405174063e5930",
          "sha1": "9e3b27da45bcae48484bb45f9d868dd7de420d31",
          "md5": "8d033643daa9ee4d6ef2760c7aa32d40"
        }
      ]
    }
  ]
}
