{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.31/contract-0.0.31.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "4g4dsdf7yvgxndmmqjq6s6i2gm"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.31.jar",
          "url": "contract-jvm-0.0.31.jar",
          "size": 17931,
          "sha512": "dd6dff132e383058d45757a68d6622150e829f20189cbfc0651f321e465d40b6c2b68464a539439c5952e02c3c25aea0ce57380ef2d564322237553dd0a8241f",
          "sha256": "6e2987421f17fc8aef97d5c78f9a780b1d6564ebdabb13cc05ddbb81594a0fda",
          "sha1": "9608b1965a09e8e191bd52310b02b4936e330666",
          "md5": "c1c99fbe7db64728876779dc35334083"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.31.jar",
          "url": "contract-jvm-0.0.31.jar",
          "size": 17931,
          "sha512": "dd6dff132e383058d45757a68d6622150e829f20189cbfc0651f321e465d40b6c2b68464a539439c5952e02c3c25aea0ce57380ef2d564322237553dd0a8241f",
          "sha256": "6e2987421f17fc8aef97d5c78f9a780b1d6564ebdabb13cc05ddbb81594a0fda",
          "sha1": "9608b1965a09e8e191bd52310b02b4936e330666",
          "md5": "c1c99fbe7db64728876779dc35334083"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.31/contract-metadata-0.0.31.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.31"
      }
    }
  ]
}
