{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.36/viewmodel-0.0.36.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yghnb2gewvenvmp42l64g7zv3y"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.36"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.36.jar",
          "url": "viewmodel-metadata-0.0.36.jar",
          "size": 7418,
          "sha512": "4536436d72fa86e0940f9b84c160d57aeb89911f385d76e7c0cddb5fcc729b8ca1c14013c8dd350de4827cf7f937f56575c8c12acdc6ae91bd5ced6c1082a00f",
          "sha256": "cabae5e2219bcff9bd8304261155733b9d37688687b775be56ee32f1c4ab071b",
          "sha1": "b8dc6098b81e357693733f736bd44f024f5b84c9",
          "md5": "41b3f2ff88224cb097a3aecab124d4fe"
        }
      ]
    }
  ]
}
