{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.37/viewmodel-0.0.37.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6ad6ifprjjfd5g5alw3qha32pu"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.37"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.37-debug.aar",
          "size": 52857,
          "sha512": "2b62f87a53ee683ab6fd072aded48658315ec29c10f641d841c23b2ca5e8c3cc3809cba2cb1911b8822b62e212eb6e9688d2bdbe36bc4aef1722f636ca8c728f",
          "sha256": "59b4f158c8431e57343a49822be88c65289ce1968fbc6b91e8f6bb4da6627d6a",
          "sha1": "3b360404532c40486d760e349a4d32d8ff0bf85e",
          "md5": "0a3946a19522ffa03384506ffeef8be6"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.37"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.37"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.37-debug.aar",
          "size": 52857,
          "sha512": "2b62f87a53ee683ab6fd072aded48658315ec29c10f641d841c23b2ca5e8c3cc3809cba2cb1911b8822b62e212eb6e9688d2bdbe36bc4aef1722f636ca8c728f",
          "sha256": "59b4f158c8431e57343a49822be88c65289ce1968fbc6b91e8f6bb4da6627d6a",
          "sha1": "3b360404532c40486d760e349a4d32d8ff0bf85e",
          "md5": "0a3946a19522ffa03384506ffeef8be6"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.37"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.37.aar",
          "size": 51219,
          "sha512": "2971995c0f49017224762334d915c55eb813961592f5b79e481bbbdd435d385149ca2369292b016cf9d1f4441191865cc1d2100fa002fd0285d94390c4a4e1f1",
          "sha256": "e18f8147e1126e57a17295ce186c33d47cace4a00dd6e9686fdcee575936192a",
          "sha1": "324374d537e982be6fb5ee5cf5cedc184f646842",
          "md5": "b6fab9bef6f3d375dd8f2f6512c32ff6"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.37"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.37"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.37.aar",
          "size": 51219,
          "sha512": "2971995c0f49017224762334d915c55eb813961592f5b79e481bbbdd435d385149ca2369292b016cf9d1f4441191865cc1d2100fa002fd0285d94390c4a4e1f1",
          "sha256": "e18f8147e1126e57a17295ce186c33d47cace4a00dd6e9686fdcee575936192a",
          "sha1": "324374d537e982be6fb5ee5cf5cedc184f646842",
          "md5": "b6fab9bef6f3d375dd8f2f6512c32ff6"
        }
      ]
    }
  ]
}
