{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r323g3eu6re6rhuxjhc3etletm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0",
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-metadata-1.0.0-alpha14.jar",
          "url": "modelcontract-1.0.0-alpha14.jar",
          "size": 5712,
          "sha512": "522fd479bcb392d29f20d39fe8b3b0cf1f9b94e51067df867ddff6cecfe5a69a10ddfc6b81d0bdd9fd62121f681d66c48701468434c3159671e883d268eff3f3",
          "sha256": "469c8bcf0e029ac9a8537303799de9bc4a9f437fc52877b0f255f2e0b0d4f4a1",
          "sha1": "775f4a4e6bddc3d8d0b83caee78f091f3b852db1",
          "md5": "5a6c0b50c38cca8f0b625d4d9a77befc"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosarm64/1.0.0-alpha14/modelcontract-iosarm64-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "modelcontract-iosarm64",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosx64/1.0.0-alpha14/modelcontract-iosx64-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "modelcontract-iosx64",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha14/modelcontract-jvm-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha14"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha14/modelcontract-jvm-1.0.0-alpha14.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha14"
      }
    }
  ]
}
