{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha23"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha23"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha23"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha23.jar",
          "url": "viewmodel-1.0.0-alpha23.jar",
          "size": 15848,
          "sha512": "75bf345940b2567ba56fac734d9fa996e00fea0e187e2675b34091ae66b35eeba91c0169af2da3904e8c34dca191e047147b7801f2c7de6ae2f627c7b440c695",
          "sha256": "2d2b8cb53f3dd7b7c663e36b872d93988873627881728c234fd67f6e7edcc8e0",
          "sha1": "6cf84a0206a5da08bcd2bbce74049a6125432993",
          "md5": "cd5277497b09e19032448fde0e1b37aa"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha23/viewmodel-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha23"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha23/viewmodel-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha23"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha23/viewmodel-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha23"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha23/viewmodel-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha23"
      }
    }
  ]
}
