{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.40/core-0.0.40.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "vudukgf34fdc3murg37da3g47e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.40.jar",
          "url": "core-metadata-0.0.40.jar",
          "size": 5341,
          "sha512": "b132c07a60cc583df670c2f69b7869b6751d983c42c31515d780e0f2b5e57468f8c2c1f380895ce0b804a2bdc7f244abf54233ccb6da7cf530cf3ef0e52e06b3",
          "sha256": "36b6e885d704b090fa4f7a79d3859cf90d2b898255c01760a3538001e20bad9a",
          "sha1": "1f0da389860dc9666297e6aaa0ee883aa2dc5eb0",
          "md5": "9d9c87afcaebdd6f1c6094e6c275178c"
        }
      ]
    }
  ]
}
