{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.26/model-0.0.26.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.26-debug.aar",
          "size": 93394,
          "sha512": "42c6d53cc1d050cf82e291aa52e08e38eb989d1eab359dea7832adbf3a355a7f113ce5da427c262dbec7a667b3fbc43eb476448bdf4d8c2a9639b22b7e48101d",
          "sha256": "ba047ef4921086cb49da1a0d6b7d3269bb02012d835c2438ba4d9dd0df6027e9",
          "sha1": "0993a73d195424ee068320db4fef8eafcf26df47",
          "md5": "dd43f62e307c73f8deb33409110fe562"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.26-debug.aar",
          "size": 93394,
          "sha512": "42c6d53cc1d050cf82e291aa52e08e38eb989d1eab359dea7832adbf3a355a7f113ce5da427c262dbec7a667b3fbc43eb476448bdf4d8c2a9639b22b7e48101d",
          "sha256": "ba047ef4921086cb49da1a0d6b7d3269bb02012d835c2438ba4d9dd0df6027e9",
          "sha1": "0993a73d195424ee068320db4fef8eafcf26df47",
          "md5": "dd43f62e307c73f8deb33409110fe562"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.26.aar",
          "size": 89599,
          "sha512": "91acb8164120181c282c2c38c7c615d7819ca34ed854bb421332318ffe4c399dc26e5651c3a9bf59462331ba4b61601c57c244afda960f82f41e6c1d27b33a0d",
          "sha256": "3fc96f30530347e51f4926ec7b9fe7ee87e2eb92350250f73655042e61a8e3bf",
          "sha1": "0ae949c619e5f8c9ac6ee4783b1f85714c28bdfc",
          "md5": "fe1e37448a365379a32525c2b2337d19"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.26.aar",
          "size": 89599,
          "sha512": "91acb8164120181c282c2c38c7c615d7819ca34ed854bb421332318ffe4c399dc26e5651c3a9bf59462331ba4b61601c57c244afda960f82f41e6c1d27b33a0d",
          "sha256": "3fc96f30530347e51f4926ec7b9fe7ee87e2eb92350250f73655042e61a8e3bf",
          "sha1": "0ae949c619e5f8c9ac6ee4783b1f85714c28bdfc",
          "md5": "fe1e37448a365379a32525c2b2337d19"
        }
      ]
    }
  ]
}
