{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha4/modelcontract-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha4.klib",
          "size": 14235,
          "sha512": "e5af7e815e749e1ecce3598e5e908e4565197feb65aadb2369c2c2e7d415342aa2a8f202b31f460628d2d4466a8e8082fe0f8bac0e58c386e4a042e390d9c436",
          "sha256": "346aaa0cf0266e7360496c0c69afc3ef5bdf6c6ad32166dced305a7bc3602291",
          "sha1": "a01f7980988e4736e47971f7f19d998041bb8e8b",
          "md5": "7a381090b0ec0840ebd8185d84261fca"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../modelcontract-metadata/1.0.0-alpha4/modelcontract-metadata-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "modelcontract-metadata",
        "version": "1.0.0-alpha4"
      }
    }
  ]
}
