{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewlegacy",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-metadata-1.0.0-alpha11.jar",
          "url": "viewlegacy-1.0.0-alpha11.jar",
          "size": 261,
          "sha512": "fc32ef47a1e93d13f19eb8449c44e14684d39e93251252407ac2654ba7edaafa610ed0bae136291099e04d62e392781e5a9c6ac32bf8c79e8b1d93869bf4b7bd",
          "sha256": "027522444e2c68487d4f97dc55d2e1213677452d5b0d88d091cd40c758bc6a78",
          "sha1": "4879d41930b723e7e7e26a672498ebb2f3917610",
          "md5": "d0659f5e12971b3cb9e5d6169fa57b92"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha11/viewlegacy-android-1.0.0-alpha11.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha11/viewlegacy-android-1.0.0-alpha11.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha11/viewlegacy-android-1.0.0-alpha11.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha11"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha11/viewlegacy-android-1.0.0-alpha11.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha11"
      }
    }
  ]
}
