{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.35/core-0.0.35.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "giu2xg36zfb4vbk5yuetpxzity"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.35.jar",
          "url": "core-metadata-0.0.35.jar",
          "size": 5329,
          "sha512": "0f256556091e1a2e04ce80b3e9cf14c5f3ddb6ed89dbff8e1a0f4993b75eff7e1d3d541efe0bbc95d4c5852b1162df2205f1ab0a4803cbaaa0787d6d1ba9a76b",
          "sha256": "29705614fcee3d84179768dc4fcb1b2d129cdb8e9d8f0dbe547a90cbd50fb70b",
          "sha1": "e4bf8a51c4477b8ebae12442901dd4e6b67252ec",
          "md5": "3617330bd2bbe2fc65170a7f22c26af2"
        }
      ]
    }
  ]
}
