{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/1.0.0-alpha14/model-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r323g3eu6re6rhuxjhc3etletm"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "model.klib",
          "url": "model-iosarm64-1.0.0-alpha14.klib",
          "size": 52640,
          "sha512": "f02a9f71107ef2bc4cf0b4eff36de5fbc772324e0327c53873c2635e471584536ff44ec0bb2b74e71f2108679bbc1c3728c15fc1985fd04c5bfb9d3f17a2368c",
          "sha256": "8d10f914fe1e4f3c972e36d4109b54fe0fd4dcaac7300319ef8a87820009f5e9",
          "sha1": "a8afaa4fe1b0cb2b93e509c3a73dcb8346f5ff64",
          "md5": "48f915f9544e92bdf2a3cae517fba96b"
        }
      ]
    }
  ]
}
