{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha17/viewmodel-1.0.0-alpha17.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha17-debug.aar",
          "size": 84694,
          "sha512": "222256dc4d36ee0cf34138902744eeb6eb7d8d746de5c6898e8b33b2458d5dda80f73206c79525329b50982e5f4f6c599745538b000a1966e980059bd64583bb",
          "sha256": "0b48151c542203c737717dd9682a907562bf95a1ef57985aa5d4ce78ae35ec94",
          "sha1": "de7aa3be309108f77e002f533e789f339be3f002",
          "md5": "c188de852bf819c06d948f7a9b0daef6"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha17-debug.aar",
          "size": 84694,
          "sha512": "222256dc4d36ee0cf34138902744eeb6eb7d8d746de5c6898e8b33b2458d5dda80f73206c79525329b50982e5f4f6c599745538b000a1966e980059bd64583bb",
          "sha256": "0b48151c542203c737717dd9682a907562bf95a1ef57985aa5d4ce78ae35ec94",
          "sha1": "de7aa3be309108f77e002f533e789f339be3f002",
          "md5": "c188de852bf819c06d948f7a9b0daef6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha17.aar",
          "size": 80798,
          "sha512": "70c23d388eb67d0216d9e9cf4a82d8789571eafbdf575493986bb0e44bc23c43b1d85d0d7ae57307b4c52d75d95f497d01c403f0b5a43da823e72c30d0ef889d",
          "sha256": "0e865b22d76c4cba4a41ec55d652e6284011a90294d18e5aec6a60cb2fac3128",
          "sha1": "1ca2e7a4e2085e0014e012d2822b0d8fc4bd7528",
          "md5": "18a3321388acd68cd49a8b481d0bd544"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha17.aar",
          "size": 80798,
          "sha512": "70c23d388eb67d0216d9e9cf4a82d8789571eafbdf575493986bb0e44bc23c43b1d85d0d7ae57307b4c52d75d95f497d01c403f0b5a43da823e72c30d0ef889d",
          "sha256": "0e865b22d76c4cba4a41ec55d652e6284011a90294d18e5aec6a60cb2fac3128",
          "sha1": "1ca2e7a4e2085e0014e012d2822b0d8fc4bd7528",
          "md5": "18a3321388acd68cd49a8b481d0bd544"
        }
      ]
    }
  ]
}
