{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.15/model-0.0.15.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gqpemdskoneufiyethujbxdcv4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.15"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.15.jar",
          "url": "model-metadata-0.0.15.jar",
          "size": 13100,
          "sha512": "824537688da50ea099d67c8d7cb25d4ae1bf65b29c1a88c0f79d67a5e8ac451e106b17f6e9f641cae8ebb72d28a3fc10e19882fac9d24c2983153a1acb9d174f",
          "sha256": "6e815f67b465b3a67b226705300f8b275e16af7f8bbbc22664a3b90342f4e618",
          "sha1": "cad8b1d2110de4430f046e81a0a7136f2df3f379",
          "md5": "61080671fa7d50ba88accfc33695e061"
        }
      ]
    }
  ]
}
