{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.47.jar",
          "url": "generator-0.0.47.jar",
          "size": 94622,
          "sha512": "bac1cd279a9e6a9a5f6f300ce366fa5f8c4f907549646380c0a0b94bfed819894f52bfb56b9afdd1a188e7b3d3728a1b0543051aee38f4870f2f1e12722c72d5",
          "sha256": "c08e913bdf7941f81e4b9f5db19a3f9cf7a245ebe4db36b883d29a32b236b582",
          "sha1": "7953da2ecb7c7f5df667afe2738f890a326578cf",
          "md5": "62bfee9f7c328a155a911890c891c15e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.47"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.47.jar",
          "url": "generator-0.0.47.jar",
          "size": 94622,
          "sha512": "bac1cd279a9e6a9a5f6f300ce366fa5f8c4f907549646380c0a0b94bfed819894f52bfb56b9afdd1a188e7b3d3728a1b0543051aee38f4870f2f1e12722c72d5",
          "sha256": "c08e913bdf7941f81e4b9f5db19a3f9cf7a245ebe4db36b883d29a32b236b582",
          "sha1": "7953da2ecb7c7f5df667afe2738f890a326578cf",
          "md5": "62bfee9f7c328a155a911890c891c15e"
        }
      ]
    }
  ]
}
