{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.29/contract-0.0.29.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.29.jar",
          "url": "contract-jvm-0.0.29.jar",
          "size": 17931,
          "sha512": "fc76f059a4598db5bc42be134307305752364b9ff21fdd7004ef1fd597c62f1096d8abd6df1aee76c0246c9eb7e36e9dce9b2ef8a73739d39518da3a4ce18550",
          "sha256": "e519404fe9c8de3033613cd2d64dee400fe76309857db87b0bd04ed91b8c456b",
          "sha1": "af6555a59ce343d6d07661696861472e7e5d28dc",
          "md5": "36e78fd7ac1c1ddde50438bbde3946b2"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.29.jar",
          "url": "contract-jvm-0.0.29.jar",
          "size": 17931,
          "sha512": "fc76f059a4598db5bc42be134307305752364b9ff21fdd7004ef1fd597c62f1096d8abd6df1aee76c0246c9eb7e36e9dce9b2ef8a73739d39518da3a4ce18550",
          "sha256": "e519404fe9c8de3033613cd2d64dee400fe76309857db87b0bd04ed91b8c456b",
          "sha1": "af6555a59ce343d6d07661696861472e7e5d28dc",
          "md5": "36e78fd7ac1c1ddde50438bbde3946b2"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.29/contract-metadata-0.0.29.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.29"
      }
    }
  ]
}
