{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewlegacy/1.0.0-alpha10/viewlegacy-1.0.0-alpha10.module",
    "group": "tech.skot",
    "module": "viewlegacy",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "vrvei6o5trhotpxc7jm4yf4dri"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-1.0.0-alpha10-debug.aar",
          "size": 186855,
          "sha512": "dced1001f5ea0b3b40fe39b5bc462a8f7981fbd40d43543405880792c54434e5d031dcb6e97c446b7bd9d28fd48c51056335a1208c9796b93d19755ea1dd646e",
          "sha256": "d0a03e9d32880e12eaeb2638c43ed20451df8225eff0bb8a23b6def161d24b5d",
          "sha1": "c972a09e1cd5c087f8a8f6cc83e1cf55f35c5c18",
          "md5": "8b2be945e72c9126336f8d817188e96d"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-1.0.0-alpha10-debug.aar",
          "size": 186855,
          "sha512": "dced1001f5ea0b3b40fe39b5bc462a8f7981fbd40d43543405880792c54434e5d031dcb6e97c446b7bd9d28fd48c51056335a1208c9796b93d19755ea1dd646e",
          "sha256": "d0a03e9d32880e12eaeb2638c43ed20451df8225eff0bb8a23b6def161d24b5d",
          "sha1": "c972a09e1cd5c087f8a8f6cc83e1cf55f35c5c18",
          "md5": "8b2be945e72c9126336f8d817188e96d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-1.0.0-alpha10.aar",
          "size": 180328,
          "sha512": "0ef43d4c1c1bd4795b9f1e12cdfb77d8c347640e34cd15626a2925156987938cda2e8bdf6f21944d2d1117fbaf3e999fabd3b33904c7887defe866bcd05392a5",
          "sha256": "e5044134fca5c25d76b0456b75076d0ee58ca5e7e8ca83ca06c94469f0f96493",
          "sha1": "ba3d314d1c1071c3c22a2c443e483da60af22d49",
          "md5": "28fdb7524804a9129f18c34eec93873b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-1.0.0-alpha10.aar",
          "size": 180328,
          "sha512": "0ef43d4c1c1bd4795b9f1e12cdfb77d8c347640e34cd15626a2925156987938cda2e8bdf6f21944d2d1117fbaf3e999fabd3b33904c7887defe866bcd05392a5",
          "sha256": "e5044134fca5c25d76b0456b75076d0ee58ca5e7e8ca83ca06c94469f0f96493",
          "sha1": "ba3d314d1c1071c3c22a2c443e483da60af22d49",
          "md5": "28fdb7524804a9129f18c34eec93873b"
        }
      ]
    }
  ]
}
