{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.37/androidTests-0.0.37.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6ad6ifprjjfd5g5alw3qha32pu"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.37.jar",
          "url": "androidTests-metadata-0.0.37.jar",
          "size": 261,
          "sha512": "344c2d21b364988ece3a5307243a784863c0cb194077d460f22e5162af5ab503d6f6e95fc312d8c3c0959483035d95af8e4a7c92ff2a49435512a22a7408850b",
          "sha256": "018ca3649657d58c9550036fd9326f730b8c5c12c4c2bfc54edb759d8e1ff475",
          "sha1": "27a44eb5908631b21668a094e5ad323ad3dbfe82",
          "md5": "1065ca5ccd6c22ae5a45b6901163f633"
        }
      ]
    }
  ]
}
