{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.18/contract-0.0.18.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "nrva6vite5hrni2xsf6nk6q4ge"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.18.jar",
          "url": "contract-jvm-0.0.18.jar",
          "size": 15079,
          "sha512": "24a84fc63d8c2a4b1187880853d57981e8eb8c39f74ce31f015d07eeca233057432480c28fe534eaff4d3148cebfb2cbff5c9e14c9397b8cdde5ca195ac7f358",
          "sha256": "e1297360e50527bc60c2ed22c7f02526620f38fd0650407d6611613523705739",
          "sha1": "e35e4302e65224e217ce57a5672251e0b36dcb73",
          "md5": "7d895216cb63be73a0a6b7362f60f677"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.18.jar",
          "url": "contract-jvm-0.0.18.jar",
          "size": 15079,
          "sha512": "24a84fc63d8c2a4b1187880853d57981e8eb8c39f74ce31f015d07eeca233057432480c28fe534eaff4d3148cebfb2cbff5c9e14c9397b8cdde5ca195ac7f358",
          "sha256": "e1297360e50527bc60c2ed22c7f02526620f38fd0650407d6611613523705739",
          "sha1": "e35e4302e65224e217ce57a5672251e0b36dcb73",
          "md5": "7d895216cb63be73a0a6b7362f60f677"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.18/contract-metadata-0.0.18.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.18"
      }
    }
  ]
}
