{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.39/core-0.0.39.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.39",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "wulvo6iqbzfl3evraorhz65oge"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.39.jar",
          "url": "core-metadata-0.0.39.jar",
          "size": 5329,
          "sha512": "181d7af213c854b3b0841349bac8a3f790925251261e542a801cce1c490e96b702c52a0049539fedb986db151fdd6bf0fe72ebfb24ca2ceb0694924888ea89e9",
          "sha256": "4953c24a9448b3ccac03b2600f7d0524763e966b1da30655aec17f6993e50f43",
          "sha1": "bb86ba144629b8f8856979f6c905908fb9da91fc",
          "md5": "34891c7b6ed24bb7fa3d2987dad12282"
        }
      ]
    }
  ]
}
