{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha15.jar",
          "url": "androidTests-1.0.0-alpha15.jar",
          "size": 261,
          "sha512": "32cd3a32bd272270f1031f63a4ee22c9a33d806f564259698881408de2b6ab782b53f41b9f046c4661a88e397b4ec9694c2fad0ebaea6c6c736fb6bb719c78e0",
          "sha256": "3059a2847d833cb407c460b2af8c96574277642ff34c336a2685b374d8fc4ff9",
          "sha1": "178ed6386504a6665febf475e65a4ea0e2a39c4e",
          "md5": "5516801f3619f87ea2eacdb86f640b48"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha15/androidTests-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha15/androidTests-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha15/androidTests-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha15/androidTests-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha15"
      }
    }
  ]
}
