{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core-jvm/0.0.49/core-jvm-0.0.49.module",
    "group": "tech.skot",
    "module": "core-jvm",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.49.jar",
          "url": "core-metadata-0.0.49.jar",
          "size": 5341,
          "sha512": "f9184165d290b1835b6eb7c21e8977189230e35a20a97c0449b9776681c3798af84bc04ef147a6420fd9fa70a0468b8345abafd88aedbca118b72c3aaba14c85",
          "sha256": "e0e96d79aa49193421d9965587c602798a864e5d04027b79f2007a1239192bdc",
          "sha1": "d4dfacc58403c37ed12c9a6a0017b9422de4772c",
          "md5": "185e98a6abdb30d4298d4101c31082fe"
        }
      ]
    }
  ]
}
