{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model-metadata",
    "version": "0.0.48",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "adu4mcp7tnfvfaxt3d3ep6dpwa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.48"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.48.jar",
          "url": "model-metadata-0.0.48.jar",
          "size": 13116,
          "sha512": "89c0f042ba3bb8204e65768dde9ccf803f13d49dd8c1271b003b4d825b23ef6505e19a5bfd5772ed1dfaadc6cf0eb16001fd9b8770a441af19a82ee58b11357c",
          "sha256": "7af91d7277fd86e463e63e65b74780f518c08030ef7228dc40a40ff0d2a7c30e",
          "sha1": "c2299403cf625ce1543703c5148330b40403e365",
          "md5": "bfd00fc033b9c8d4067fd47e1157d6ad"
        }
      ]
    }
  ]
}
