{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.47/contract-0.0.47.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.47.jar",
          "url": "contract-jvm-0.0.47.jar",
          "size": 20679,
          "sha512": "a1f53feae3b7d59a2ccdb4cbd14edd784a007b5ea5b6d43d512b82b0abd728df85ae4c1bb01fc1d09942c2b4b7b97a8b6d68197a9dbdc7fb9b72a43e2311eded",
          "sha256": "6e8e525ef8b655ba5d37ea226d8f48908a211a26149595156579127fa9b6121b",
          "sha1": "a73b5a6a7cd45c82f105add9f613d8058d09cb6f",
          "md5": "aea3be900fbf0c2c38750bd137096f2e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.47.jar",
          "url": "contract-jvm-0.0.47.jar",
          "size": 20679,
          "sha512": "a1f53feae3b7d59a2ccdb4cbd14edd784a007b5ea5b6d43d512b82b0abd728df85ae4c1bb01fc1d09942c2b4b7b97a8b6d68197a9dbdc7fb9b72a43e2311eded",
          "sha256": "6e8e525ef8b655ba5d37ea226d8f48908a211a26149595156579127fa9b6121b",
          "sha1": "a73b5a6a7cd45c82f105add9f613d8058d09cb6f",
          "md5": "aea3be900fbf0c2c38750bd137096f2e"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.47/contract-metadata-0.0.47.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.47"
      }
    }
  ]
}
