{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.37",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6ad6ifprjjfd5g5alw3qha32pu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.37.jar",
          "url": "generator-0.0.37.jar",
          "size": 94266,
          "sha512": "e09c8f6a43d5df379e455f259a3b2ecffc06664bca78eed0b1e6aaa2e1bfa89d7c329f024b508da395f6556f61e183ec9e48667ae1bd4d9072b159f6d092f004",
          "sha256": "b26ef8c6a42e76e4cbb733eff864a3ace0fb9e336f49d42a880af5e27c718033",
          "sha1": "580370e12c1b19773feb00e18be995c650bffa2b",
          "md5": "ff48979b2ba88f64b5390dbd9d7bdfd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.37"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.37.jar",
          "url": "generator-0.0.37.jar",
          "size": 94266,
          "sha512": "e09c8f6a43d5df379e455f259a3b2ecffc06664bca78eed0b1e6aaa2e1bfa89d7c329f024b508da395f6556f61e183ec9e48667ae1bd4d9072b159f6d092f004",
          "sha256": "b26ef8c6a42e76e4cbb733eff864a3ace0fb9e336f49d42a880af5e27c718033",
          "sha1": "580370e12c1b19773feb00e18be995c650bffa2b",
          "md5": "ff48979b2ba88f64b5390dbd9d7bdfd6"
        }
      ]
    }
  ]
}
