{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.42/model-0.0.42.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "cfo2qvt3ynagjbvfb6ksv22jki"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.42"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.42.jar",
          "url": "model-metadata-0.0.42.jar",
          "size": 13116,
          "sha512": "16a7f4c8b1bbc6af68f9fa9dd79e79ee3474458127e0f188983ad58dbc4ebfdc371718ec24bc7c4ae85f37a7826310bee8b08bfe50d8db62ce467b1ccb07df31",
          "sha256": "c447f3727fcb3719cdfa74861826016c3a15c8e80c5592dfb1d7ac30cff6b370",
          "sha1": "b1aeae2520118c23744fc20a4cb479b148ed641c",
          "md5": "fc2fc1a472d6cf8a5b5b256af53e8a1c"
        }
      ]
    }
  ]
}
