{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.16/contract-0.0.16.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "xduo2x3rkbaepe3emobddesovq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.16.jar",
          "url": "contract-metadata-0.0.16.jar",
          "size": 7170,
          "sha512": "deb8ad51af8bc94cde63bbab50079b3a9ed305edae0a84ee11282b1f510263f6b028503b3a03a07a6c5bee67851685810f4e587c13fb5e3c5ee38090bad8d210",
          "sha256": "0c6b94636aea882acb7639c0ac8f57f833cac463b2a445457ed34c99a137f08d",
          "sha1": "5522fb8516d64450974bfc979f4b49ca6e24a3a4",
          "md5": "b316cc9c2abe81a4d38b600228e5ba31"
        }
      ]
    }
  ]
}
