{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/1.0.0-alpha12/model-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "native-driver",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-ios",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "model.klib",
          "url": "model-iosarm64-1.0.0-alpha12.klib",
          "size": 51517,
          "sha512": "34d0f1fc9f8219114a038abe3165e60426261055abca3b2bee7fb61c240fcf925d61d015a50e2ec36db0ee816fedb6ceaae0b444da99bccdb7851f7eee7c8fe8",
          "sha256": "eb9b3bfecd98c6bf7810342864b7b47a9ff5b2119ed1aefd0ba32b776ec82492",
          "sha1": "9e3d4254ae5fcc549f431f1964fbf82792584c34",
          "md5": "939753bbdb78812d4e102c09f786781f"
        }
      ]
    }
  ]
}
