{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.34",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "sdiuqgpfpvgqbhgb64jk7k3g3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.34.jar",
          "url": "generator-0.0.34.jar",
          "size": 93851,
          "sha512": "0e1cda6118c88886cd7a61f8ceb4e33f1baf22a7080fc540717dcaca231d3a651a98004158b962b7b7a047a4560c01035879ac0463af6842c9a87c530032a5bb",
          "sha256": "f1178f6eb433bb705e22cc82916c5981d36587054d723f1b2695dedeed25d26a",
          "sha1": "f0c191f32ffaf3c7518325e98fdf7b9b32d830ea",
          "md5": "fc775dd1bfbc0ef0be57cc9c20738e52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.34"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.34.jar",
          "url": "generator-0.0.34.jar",
          "size": 93851,
          "sha512": "0e1cda6118c88886cd7a61f8ceb4e33f1baf22a7080fc540717dcaca231d3a651a98004158b962b7b7a047a4560c01035879ac0463af6842c9a87c530032a5bb",
          "sha256": "f1178f6eb433bb705e22cc82916c5981d36587054d723f1b2695dedeed25d26a",
          "sha1": "f0c191f32ffaf3c7518325e98fdf7b9b32d830ea",
          "md5": "fc775dd1bfbc0ef0be57cc9c20738e52"
        }
      ]
    }
  ]
}
