{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.20/viewmodel-0.0.20.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2r2ojxqr5ffvpf4fmosdnmnn7i"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.20.jar",
          "url": "viewmodel-metadata-0.0.20.jar",
          "size": 6984,
          "sha512": "6b3c4d8be3100ea90e4301de4015e9f4472bbe0af906d344813d3fdc5e07bfa0def89bd13e3eb98332bb1973dff81e9f58cd6e8c4bc20d2d78a4b65d6d8b8662",
          "sha256": "8960b425c3d8ee1d297e89369d954f600e543c14b15790a2112841d518a00a9a",
          "sha1": "88b33287481f782bc91eb02e2ff0804ba4a92001",
          "md5": "2a5677ad32d47e0368193ba4a5ddd7ea"
        }
      ]
    }
  ]
}
