{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha12/modelcontract-1.0.0-alpha12.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5mtantqkyvfevdw27fzlpmvhg4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosx64-1.0.0-alpha12.klib",
          "size": 23407,
          "sha512": "84cb42db93517df011e8abfe0f81b0deb3f1adc2f3e250295bbeefe2ee6f4a9af31051b958af75ed62db841120dc6a45b753d9e859ffd32320f5fc27d0035e08",
          "sha256": "ed838ae5afa81f0cc37676a4c28e623f9b6a597de65a3e47a5e1bd5725fbd3d0",
          "sha1": "c0bb48c96f3a923c9125b1469720e16296f4fc28",
          "md5": "40d13ad836ac49d8572c3afaecd08d84"
        }
      ]
    }
  ]
}
