{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h3wjxn3zcban5fnecihtr5lrqi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.38.jar",
          "url": "generator-0.0.38.jar",
          "size": 94266,
          "sha512": "603951a075492ada48c6432d3d0cdaedb6942084fd01594cdf130be706647bd8bf1851db8b40f864184f18545dbb59c0a86c2dd631f92f8cee0f7b54c1e62b3c",
          "sha256": "adc9a3d2f76a5d0070c73a529a78ef4121b2f98b32ddc0f7154b63ce149250f4",
          "sha1": "cf7728bac87bcae99362ddb565416b2d9fbb14ed",
          "md5": "2c7d053c05eac55e0c8e44cdb80cfc2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.38"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.38.jar",
          "url": "generator-0.0.38.jar",
          "size": 94266,
          "sha512": "603951a075492ada48c6432d3d0cdaedb6942084fd01594cdf130be706647bd8bf1851db8b40f864184f18545dbb59c0a86c2dd631f92f8cee0f7b54c1e62b3c",
          "sha256": "adc9a3d2f76a5d0070c73a529a78ef4121b2f98b32ddc0f7154b63ce149250f4",
          "sha1": "cf7728bac87bcae99362ddb565416b2d9fbb14ed",
          "md5": "2c7d053c05eac55e0c8e44cdb80cfc2f"
        }
      ]
    }
  ]
}
