{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.30/viewmodel-0.0.30.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "45vyvjpy25d6rogm6vet7cshky"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.30"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.30-debug.aar",
          "size": 52743,
          "sha512": "c165be67858ea4730e81f41f9dd41218ffcaaa22f062f0c251f4b5fa5c23aad0bb497f0e32fc8e83975245387d45ff485250663bc86962dd375515d4440b6096",
          "sha256": "bb933dffac5d191617983ab791bc59d6f400d0a06feb99d3b1224e6d93235dab",
          "sha1": "894ec07fe66e55983e2c1d98ba6316991b44a2b2",
          "md5": "4b7d0bc4af7a19652d8b94c9270c77d9"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.30"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.30-debug.aar",
          "size": 52743,
          "sha512": "c165be67858ea4730e81f41f9dd41218ffcaaa22f062f0c251f4b5fa5c23aad0bb497f0e32fc8e83975245387d45ff485250663bc86962dd375515d4440b6096",
          "sha256": "bb933dffac5d191617983ab791bc59d6f400d0a06feb99d3b1224e6d93235dab",
          "sha1": "894ec07fe66e55983e2c1d98ba6316991b44a2b2",
          "md5": "4b7d0bc4af7a19652d8b94c9270c77d9"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.30"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.30.aar",
          "size": 51100,
          "sha512": "dad722495bd8df3b83815514c37dd9cd2857cee4a195576e9e9427140ec0707a58f9733cf946afc11341fb5d66524b5eb704a0ff4d516b6268e2dd1a3e3d156e",
          "sha256": "ad2a0050181946fbacb355945b5c776601ee2c1df6b863feeb0e37115a13b41f",
          "sha1": "0fb2aabdd01062b094f8220eb9243772c54c3ff1",
          "md5": "6eaddde69971287ef63c1dd2de5574a8"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.30"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.30.aar",
          "size": 51100,
          "sha512": "dad722495bd8df3b83815514c37dd9cd2857cee4a195576e9e9427140ec0707a58f9733cf946afc11341fb5d66524b5eb704a0ff4d516b6268e2dd1a3e3d156e",
          "sha256": "ad2a0050181946fbacb355945b5c776601ee2c1df6b863feeb0e37115a13b41f",
          "sha1": "0fb2aabdd01062b094f8220eb9243772c54c3ff1",
          "md5": "6eaddde69971287ef63c1dd2de5574a8"
        }
      ]
    }
  ]
}
