{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha13/modelcontract-1.0.0-alpha13.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha13.klib",
          "size": 23344,
          "sha512": "a779cbf3d313c8e5752692b56e3922692845e5cb04e86e50b050ea0b53f83c003cd3f611e68b9738125f8cb2d9e1e88fc1b971514be02afea51e8810247fd9d8",
          "sha256": "c35c32e4f84a559f0a61c07127b5e2f260cf2e63a82969aea1796c0827ec9604",
          "sha1": "44606d587e671cad4357c9803e340e789f4385fb",
          "md5": "d2b6ffe13e8ec5cdbacc4b34f9d06934"
        }
      ]
    }
  ]
}
