{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.28/contract-0.0.28.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.28.jar",
          "url": "contract-metadata-0.0.28.jar",
          "size": 7614,
          "sha512": "3b3822bcc9c67050f3ce184b4403eb048815dba93b26a678ff0a0a1a1f1d5eca9140e0a4956e12edd97cf16864f8aeafd067cf11acb20582f6d38cad1f02e2b0",
          "sha256": "dd1e2c94f79f1db13bf61d11c24f3c9f30abbcf91cf321501e2756506f4cb0a1",
          "sha1": "8a55bb718b4efe1ecb0ac9ccd1328a25d7b5c650",
          "md5": "2ffa9d3815af9350142cfbee36d762f2"
        }
      ]
    }
  ]
}
