{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.28/contract-0.0.28.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "t2w34ohvabccfdd6l3g4neepp4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.28.jar",
          "url": "contract-metadata-0.0.28.jar",
          "size": 7614,
          "sha512": "837cf87d922e4479beb4a33cb0b62110b4c81e320f61a633a6734e63306d993da3eec9d41fc67d25784dc8e8c9d27d0a06fe30b8f83f1cd96ca5f78fc02750d4",
          "sha256": "871e6300b724e6970b4f389a501db46eefda57ba535e88625d36b12bfda87f1c",
          "sha1": "5a7cab20962404eba38353f62a3571a120eeae47",
          "md5": "92a7de468092f42dacb5b5406f6ac8d4"
        }
      ]
    }
  ]
}
