{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.44/androidTests-0.0.44.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i7olmwxatfdhths5wu7quwrrny"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.44.jar",
          "url": "androidTests-metadata-0.0.44.jar",
          "size": 261,
          "sha512": "b177c9b87a372afd94c81c3a8cef75082130ee20397157dd6556d3e8e6ef1875caa70c53bc09e7b1cbaad53b1e20ffc921c2837ab6d14dca6570f4a852907350",
          "sha256": "5a7006f3bc8276f84e97171acce6eaf3e361736a1accf8e0c87631d91edfca75",
          "sha1": "bb36a4bcb397f91e3060340a722e985c689d1508",
          "md5": "7e3951933fd3294695a20baf1f5edba2"
        }
      ]
    }
  ]
}
