{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model-iosx64/1.0.0-alpha6/model-iosx64-1.0.0-alpha6.module",
    "group": "tech.skot",
    "module": "model-iosx64",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-json",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-1.0.0-alpha6.jar",
          "url": "model-metadata-1.0.0-alpha6.jar",
          "size": 15245,
          "sha512": "8f6de2afcbba53e0b0091c4c5e0b1909f3e18ebfba8702716971b0ba5d1b7a4461ec5b152c9ad60c963a9bd069b5ad06a6c53f0b8f875a7ac0ff6d711217dd1d",
          "sha256": "a2f3baa09f0ff2fee56d3dcedf2c28822e08c293aa9090ea9b3edb3b9969c17d",
          "sha1": "849ac8459c26244df3a0e7d4a77a0916b84e908a",
          "md5": "8bb0bc1580f688addabfffc9e24ec2bb"
        }
      ]
    }
  ]
}
