{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.14/viewmodel-0.0.14.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.14.jar",
          "url": "viewmodel-metadata-0.0.14.jar",
          "size": 6919,
          "sha512": "6e32eb0ac2360f613d925e79c7b6181bccb0f9b5c3763b967b0fe066997a274ce5abea9703cfd1f0a2398dcc120d03911f809e7192f32c0d0d846d30573ae4fa",
          "sha256": "2a0a0c0755786d47d319c364975083d691b8bb56c5f07a704c18fd9fe7badd2f",
          "sha1": "f9a2c927cedc79d05061917f67525cfd432240b8",
          "md5": "919abb918a2caaf1ab430d635b19fe0e"
        }
      ]
    }
  ]
}
