{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.19/core-0.0.19.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "julmyh4b25dnnegsjouy3lg5q4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.19.jar",
          "url": "core-metadata-0.0.19.jar",
          "size": 5327,
          "sha512": "ea5d483fb3ac6b189706e6b396ba99434d3becb4d63f56b404775d95b10bd2cec0f29b2fa3cf5a0e4ac6aa60945f92b9d604a80b7e370b724acc6d347543842d",
          "sha256": "dc134284c856b87dcf1711b74dd91cf736da76b66a6232b788fe9f85ca709633",
          "sha1": "95983cdb5211cc8240741718ee2fdbc468528d14",
          "md5": "357182c87354d7a10dd506efc80401b5"
        }
      ]
    }
  ]
}
