{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.30/androidTests-0.0.30.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "45vyvjpy25d6rogm6vet7cshky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.30.jar",
          "url": "androidTests-metadata-0.0.30.jar",
          "size": 261,
          "sha512": "180b36cad64eab2fb905b3b6729c2f869bfe145c769e61f5bbf5b9910cf7c275cf6f739873fcb855422ebd423743fd87837a37ef69b19851e95ce2402cca492d",
          "sha256": "f480370df509b1c82468255e59569b72c9c6df5e782d6b72e8ab30a24da58f9e",
          "sha1": "a7e504af6bb6ee74e94d6e2d9d2e6b7371d691c6",
          "md5": "9bc91597b3fd4807fce0a1fd900e6551"
        }
      ]
    }
  ]
}
