{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha4/core-1.0.0-alpha4.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.4.3",
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosarm64-1.0.0-alpha4.klib",
          "size": 19603,
          "sha512": "1b3ede5fa3bcb4c58ba3493eda1779b7a559d44bd8f224db2b1205cfbd8b7de045127a0c3c2eb5e5e765e0c937f8a335b33025136efc0f058daf702dcfef4758",
          "sha256": "6348007a7735d2ea53782fc923eb07c5d8e4178cc81033080324bd03e1c87c5c",
          "sha1": "ee36aa7a058486d76eacb9cf307d91a1dffb25ad",
          "md5": "06e673b9d1997663b8eb6a847110ff01"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/1.0.0-alpha4/core-metadata-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "1.0.0-alpha4"
      }
    }
  ]
}
