{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.27/androidTests-0.0.27.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "eivbo7yrmzcdnc7ypzmvwqtxd4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.27.jar",
          "url": "androidTests-metadata-0.0.27.jar",
          "size": 261,
          "sha512": "1d057ccd7b649b137e172e35f0c98c4661c7f21c0498a11c8e971348951e6f2e1f53b3b78428700df20a4e3f51b6aad22e062ce812a588209ce387b0f3e4c9a1",
          "sha256": "1377c10c05414526621c7a58c54ed5d1218d24e8e18ff053a427cefda8d8e25c",
          "sha1": "7ec17c26987bc3c1edc54f03972300de30b7c34e",
          "md5": "5de71c0a7c61d4f55ec43413c721901a"
        }
      ]
    }
  ]
}
