{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-metadata-1.0.0-alpha16.jar",
          "url": "modelcontract-1.0.0-alpha16.jar",
          "size": 5712,
          "sha512": "87fdf0d3472690171d1529a971c531ddd12f05bdbe6ab16a1c3f48d79bb0c9177838f21c387686a50c6d1ee3fd2e376c5afbdc26a6a45a3bd364f30108b6ddb5",
          "sha256": "47ada1ed2850da1a99bd2d0b5e456d78ad843c557b460804510bc259e5b3968c",
          "sha1": "9992f0f8df84c36e38162ed4dfcfffc0f74b7188",
          "md5": "62a1733c13d59c4266936eccd7d771f0"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosarm64/1.0.0-alpha16/modelcontract-iosarm64-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "modelcontract-iosarm64",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../modelcontract-iosx64/1.0.0-alpha16/modelcontract-iosx64-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "modelcontract-iosx64",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha16/modelcontract-jvm-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha16"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../modelcontract-jvm/1.0.0-alpha16/modelcontract-jvm-1.0.0-alpha16.module",
        "group": "tech.skot",
        "module": "modelcontract-jvm",
        "version": "1.0.0-alpha16"
      }
    }
  ]
}
