{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.29/androidTests-0.0.29.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.29.jar",
          "url": "androidTests-metadata-0.0.29.jar",
          "size": 261,
          "sha512": "fa3917043ff1e60f4d9278dc7fa85229637f1ece96518700514b24b2e3a58a36006d6d2161016bb6b0b1205026460025a8a718e7d7cbdc10f13eac0e30c81264",
          "sha256": "b9742fe61a25c8f1922d1708cc87564cc171fe44afb43d9b582b6f052d819b81",
          "sha1": "d4526195fed1f5a5732785703134f8f57b8fddad",
          "md5": "8c935fb0ab712e4b243b07b27fdca8dc"
        }
      ]
    }
  ]
}
