{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.9/contract-0.0.9.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xtqqandxyva3tauucku2734sky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.9.jar",
          "url": "contract-metadata-0.0.9.jar",
          "size": 7621,
          "sha512": "169721b23aa1adcd39ac411d0875229e05245c70026f3b72a6660be0b19469678fd6b8ccfcc6ffcc3ebbf39cc35d25a7191b744b56814f8716c7b454673ee094",
          "sha256": "fbeb4fe49b4056ad9bebdd8c5ad39c9711dd31e617627c7b2d4578e48b052ff",
          "sha1": "33768cf505bf266b91ad883aa1e4a32a06a95025",
          "md5": "fac51ef4ddc59e0276b3f866c0adfbd6"
        }
      ]
    }
  ]
}
