{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "45vyvjpy25d6rogm6vet7cshky"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.30.jar",
          "url": "generator-0.0.30.jar",
          "size": 93268,
          "sha512": "74918ea4a2a1f47091fe1e6dd4e7f23e939c15a74da22244df6c39e6544e1af8b2291e6aa959f235eadd7a8d334de24255d74291494933def365858e12003477",
          "sha256": "c3432860c55fcaa89606ac9eb15664f4323afd1e78b0e30aa4f5952bbc35cf51",
          "sha1": "9e5f764346f0210707ee3c55a96647801a1b498f",
          "md5": "8d0b2c499a5af249322b49dd91a1747d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.30"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.30.jar",
          "url": "generator-0.0.30.jar",
          "size": 93268,
          "sha512": "74918ea4a2a1f47091fe1e6dd4e7f23e939c15a74da22244df6c39e6544e1af8b2291e6aa959f235eadd7a8d334de24255d74291494933def365858e12003477",
          "sha256": "c3432860c55fcaa89606ac9eb15664f4323afd1e78b0e30aa4f5952bbc35cf51",
          "sha1": "9e5f764346f0210707ee3c55a96647801a1b498f",
          "md5": "8d0b2c499a5af249322b49dd91a1747d"
        }
      ]
    }
  ]
}
