{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-metadata-1.0.0-alpha26.jar",
          "url": "viewcontract-1.0.0-alpha26.jar",
          "size": 18199,
          "sha512": "cac177f1bde3a172f64e2228a483d9eb8ab9eaedc8abdac8477ebaf9a8d302afb1d48601a0ba659372b6429041340fbca28265c6f6590eac83d1d87845b3681b",
          "sha256": "f5cc3af97863482357dccdaa1df9d6b4defcd9035218fb6f6cca6a8029d99696",
          "sha1": "8ae66d5600e1b6f02986ed0925ad2efb06afee1a",
          "md5": "603d0132af1a04ff8847dcbc1c3a473c"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosarm64/1.0.0-alpha26/viewcontract-iosarm64-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewcontract-iosarm64",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosx64/1.0.0-alpha26/viewcontract-iosx64-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewcontract-iosx64",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha26/viewcontract-jvm-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha26/viewcontract-jvm-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha26"
      }
    }
  ]
}
