{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha26.jar",
          "url": "androidTests-1.0.0-alpha26.jar",
          "size": 261,
          "sha512": "4bbcba8eb397ac2bb1c1d640b4b1119c94f43a7465b796d7cc419394e0039522bde609eb3fbd4d9f1343fd4f343c201d8af8dcc3e0e4fd4b2d325e75910ce809",
          "sha256": "0788c0e291e2e1a37b13ec9180f4318886ac78468cac2691af682c776641786e",
          "sha1": "f560b6d548eac472b543665a1518a1481fdcc9e9",
          "md5": "6627cb2e9bc7d8abfd92515f954274ac"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha26/androidTests-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha26/androidTests-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha26/androidTests-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha26"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha26/androidTests-android-1.0.0-alpha26.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha26"
      }
    }
  ]
}
