{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.46/core-0.0.46.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.46",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "2op6vpqzbfeszkvmuhojwr2oxe"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.46.jar",
          "url": "core-jvm-0.0.46.jar",
          "size": 17701,
          "sha512": "e44bff8c473808ee3287d39a48d3618752849e3dfea01d5f278be32b740364cf4a93dcf5cad8189154cf42d1f2331eb03bc83a8fe532fad57cafebb21f704aa1",
          "sha256": "fe774ac3aaca74fc8e6fb9e4397143869e131eee8438bfeba3425b68f209c482",
          "sha1": "bbbf9037b047a5f5087e23afcab1efb59b6ce348",
          "md5": "8a46d6cab1c6de7cf041dacb36492ce5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-jvm-0.0.46.jar",
          "url": "core-jvm-0.0.46.jar",
          "size": 17701,
          "sha512": "e44bff8c473808ee3287d39a48d3618752849e3dfea01d5f278be32b740364cf4a93dcf5cad8189154cf42d1f2331eb03bc83a8fe532fad57cafebb21f704aa1",
          "sha256": "fe774ac3aaca74fc8e6fb9e4397143869e131eee8438bfeba3425b68f209c482",
          "sha1": "bbbf9037b047a5f5087e23afcab1efb59b6ce348",
          "md5": "8a46d6cab1c6de7cf041dacb36492ce5"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../core-metadata/0.0.46/core-metadata-0.0.46.module",
        "group": "tech.skot",
        "module": "core-metadata",
        "version": "0.0.46"
      }
    }
  ]
}
