{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha25.jar",
          "url": "plugin-1.0.0-alpha25.jar",
          "size": 221288,
          "sha512": "3ff36ea0d640e82ed28adcdab7b11340a2203e0ea0d994da72f702cfcbb3640d9b4048ae304c65e051e5ea7b2d2885354aecb9aa425eb91a13eb9d3f351dc5b3",
          "sha256": "4fdde7d8f5a0553f5f7b5d99b2262611789463ee345ff11d8eab18dce45814ec",
          "sha1": "25bb4f6b6603952ffe244ae0bf18ad67d81570f9",
          "md5": "541710dd469ffcf2b65b8ad227f07f2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha25.jar",
          "url": "plugin-1.0.0-alpha25.jar",
          "size": 221288,
          "sha512": "3ff36ea0d640e82ed28adcdab7b11340a2203e0ea0d994da72f702cfcbb3640d9b4048ae304c65e051e5ea7b2d2885354aecb9aa425eb91a13eb9d3f351dc5b3",
          "sha256": "4fdde7d8f5a0553f5f7b5d99b2262611789463ee345ff11d8eab18dce45814ec",
          "sha1": "25bb4f6b6603952ffe244ae0bf18ad67d81570f9",
          "md5": "541710dd469ffcf2b65b8ad227f07f2a"
        }
      ]
    }
  ]
}
