{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha25"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha25"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha25"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha25.jar",
          "url": "viewmodel-1.0.0-alpha25.jar",
          "size": 15848,
          "sha512": "69a1dc79ba43f086e9a556948681d9fcbe484fc6cdc5b9d114239be462e45757ee41d3feb90552707997c68761108e65dcf79c28506ab374444a0df53d41dd93",
          "sha256": "ae255084120af070ab308f43a53afd1816574f7d346ad1e1e45a60ce2e62b0fb",
          "sha1": "c635405b80152e6ba5ae8acc8d08379ee23fffa5",
          "md5": "a3c92bac686fb72b1f4f09bad2e5e684"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha25/viewmodel-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha25/viewmodel-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha25/viewmodel-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha25/viewmodel-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha25"
      }
    }
  ]
}
