{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha20.jar",
          "url": "generator-1.0.0-alpha20.jar",
          "size": 193712,
          "sha512": "34b93f47bb854c7314cddd870a44795b15eb34ef169309fff439615d80d37289fd1776948662c3cceb58ea968c500ef363d362811da4db8064efb838794aa688",
          "sha256": "241959797d0fa5b07db781f9a2e0685eba7a6734312fa4127086f4d55d60aec4",
          "sha1": "024b4c08665742dc5647065f04b5e2f9196fbc74",
          "md5": "90c06ab4b6fdbead79b5119a8c10768d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha20.jar",
          "url": "generator-1.0.0-alpha20.jar",
          "size": 193712,
          "sha512": "34b93f47bb854c7314cddd870a44795b15eb34ef169309fff439615d80d37289fd1776948662c3cceb58ea968c500ef363d362811da4db8064efb838794aa688",
          "sha256": "241959797d0fa5b07db781f9a2e0685eba7a6734312fa4127086f4d55d60aec4",
          "sha1": "024b4c08665742dc5647065f04b5e2f9196fbc74",
          "md5": "90c06ab4b6fdbead79b5119a8c10768d"
        }
      ]
    }
  ]
}
