{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha18.jar",
          "url": "androidTests-1.0.0-alpha18.jar",
          "size": 261,
          "sha512": "2fb1645c5b8a7e7f517e02779ebf01ddce98c2f30fbb92f68a4b0d6627f8277c04043ec635cda36515e210d100394bfb5a83ae8b878917f10c8a5bf7ce434024",
          "sha256": "99c301c001bf55045574de8afe208a2075263d8b44787786dc4f1f0db1c93adf",
          "sha1": "4242d92376ec4880d2cfbcec9b774ced41c84f0a",
          "md5": "58420d94d65f4aeaa82e145588579bde"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha18/androidTests-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha18/androidTests-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha18/androidTests-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha18/androidTests-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha18"
      }
    }
  ]
}
