{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.12/core-0.0.12.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tgichq4ydfcfnbmsheeguc344q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.12.jar",
          "url": "core-metadata-0.0.12.jar",
          "size": 4883,
          "sha512": "40a381f95f89daf1e5e6cf0260ba15082b48a354409d99e42b28b186a1fd7bbeb20c10ad2f9905caa7e319ba978bb04caf4924883b7e7f6269ebae63d9ce7f75",
          "sha256": "3ec968e5b00f7c45dff1ec7ec8af1bdb3d7f1451de11972d7da4965ed1d0196b",
          "sha1": "1885344c006dadc4a0f47f4f48336548ad2b4917",
          "md5": "e24288eb66624a90deec5d26b0ddf449"
        }
      ]
    }
  ]
}
