{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.27/core-0.0.27.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "eivbo7yrmzcdnc7ypzmvwqtxd4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.27.jar",
          "url": "core-metadata-0.0.27.jar",
          "size": 5327,
          "sha512": "18a0160e9b992ecf33deca385cefd206b6819edd46f51c3c91753266c50af47d96966c9ec97177fba3acb7fb64f76867186b22f697fbc198350d10e32483be08",
          "sha256": "3379488a62118307405bc44f97b74c4f8525c820b60dace4caf3a4f89665b877",
          "sha1": "222ab69e61048e74330135106b00444195a17533",
          "md5": "34a822e58d89e24196b98860fcfa7139"
        }
      ]
    }
  ]
}
