{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.29/core-0.0.29.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-0.0.29-debug.aar",
          "size": 17271,
          "sha512": "6e6ac3aa9962879ca93fec714ec884e4857179cd5c921a1087c72e2e305b7b4db6dd0eab6ff898cffdb2cfe8dc9ee1a39a4006aa1780fbf6d14b0746f5d24c99",
          "sha256": "b2047bb482e0bbcc8c55f27ba85e2b193052ffee2238ca66e171353358eb25bb",
          "sha1": "767e4e4d6173101856aa4d246f679ddf5e137c44",
          "md5": "a59eea265d4c0591c225b883b7688f4a"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-0.0.29-debug.aar",
          "size": 17271,
          "sha512": "6e6ac3aa9962879ca93fec714ec884e4857179cd5c921a1087c72e2e305b7b4db6dd0eab6ff898cffdb2cfe8dc9ee1a39a4006aa1780fbf6d14b0746f5d24c99",
          "sha256": "b2047bb482e0bbcc8c55f27ba85e2b193052ffee2238ca66e171353358eb25bb",
          "sha1": "767e4e4d6173101856aa4d246f679ddf5e137c44",
          "md5": "a59eea265d4c0591c225b883b7688f4a"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.0.29.aar",
          "size": 16812,
          "sha512": "3acf3e110a9c1dca2e1e2ca50a35189e3d5b4ab7faebc5075aed33d1df387109ffa0e76917a318591402c76bd12548c9c30282967818178955932df04a003512",
          "sha256": "ec1bb99bf550ac7acee82ffc1867eb72b04e4c787cbe33deafb453c854317b9c",
          "sha1": "9a977bcc64955619c19092eded22935fdd0c2173",
          "md5": "ee69457eab687b4e04060db398fa2735"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-0.0.29.aar",
          "size": 16812,
          "sha512": "3acf3e110a9c1dca2e1e2ca50a35189e3d5b4ab7faebc5075aed33d1df387109ffa0e76917a318591402c76bd12548c9c30282967818178955932df04a003512",
          "sha256": "ec1bb99bf550ac7acee82ffc1867eb72b04e4c787cbe33deafb453c854317b9c",
          "sha1": "9a977bcc64955619c19092eded22935fdd0c2173",
          "md5": "ee69457eab687b4e04060db398fa2735"
        }
      ]
    }
  ]
}
