{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.7/model-0.0.7.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "igasumkhiveslbdlejoqxrssj4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.7.jar",
          "url": "model-metadata-0.0.7.jar",
          "size": 11242,
          "sha512": "a62dd4cb35c374286c7c20694e3f5cff5cd68b6169c7286b50ed1112fc04d414a1d876f1d65535a9754c601b47a0e2b2acd5ed73d9550232732779bcc80c0e4",
          "sha256": "30fb8c83eba3e2703d00b3c320550de0c435ae0a9520cfb3d0446681dd40b5f8",
          "sha1": "2e0ca925faf16ce4c95355a3697c81da5aa6432a",
          "md5": "4a7a6f9d2522ff54ad044f6835fe89a3"
        }
      ]
    }
  ]
}
