{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha13.jar",
          "url": "viewmodel-1.0.0-alpha13.jar",
          "size": 13550,
          "sha512": "4a7fdbea09108b67e47b4cbd88695b90a5484f73959d5a244781f96ae49ecf6e932005e4594af097a4180b4516b2a3f00ade0b8efd97bdb266d3f4c405c554c5",
          "sha256": "455ee933cff6a8286507c03cb9842b314e99416c3b080595d03525f1650bf8e8",
          "sha1": "244af901c176648992e5526b4c30db8cd0d91480",
          "md5": "9322a21a812f2df60424ebd4cab78ee6"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha13/viewmodel-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha13/viewmodel-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha13/viewmodel-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha13"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha13/viewmodel-android-1.0.0-alpha13.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha13"
      }
    }
  ]
}
