{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.32/contract-0.0.32.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6qssia3r7rbwpb5cs5jxxg4cpy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.32.jar",
          "url": "contract-metadata-0.0.32.jar",
          "size": 7617,
          "sha512": "a76ba8334fbfad73585d9597e86dd7a34bea9442f9d19e733dbdc875bec75378f39a7b4f855bd994c6de937644e2ce5f9f3e544b69cb0fd5fc03732c3cf27f17",
          "sha256": "686d8507d490672322269219f92057a6ffe471b78027889c8d88f1d0aa2a4a39",
          "sha1": "faca7abbe7ef49144cae58aca647c011f4951458",
          "md5": "79351d3987e55ac427ac223229e33f4c"
        }
      ]
    }
  ]
}
