{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.1/contract-0.0.1.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zk7tjfukpff7tmn3tiqtxdfuzy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.1.jar",
          "url": "contract-metadata-0.0.1.jar",
          "size": 6871,
          "sha512": "43884bf747c94e4a977c28750d947f3ea7110fb640a333b08c2c79a5401e4ad50152470b29d8a520c75800028accef4591d37124f275b9980b9000b4dc487821",
          "sha256": "a327cb369587d30b069966591a08c79550513f06cef53eebfccaaf475a8db863",
          "sha1": "2f4ed6dafa939eb01bfcbcf6a2d192bfe63cc0bc",
          "md5": "106710d31cb8c58d3ebc3c03aed5ab6c"
        }
      ]
    }
  ]
}
