{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.26/model-0.0.26.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3thpamqrjzg25foeovfbvbtxmy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.26"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.26.jar",
          "url": "model-metadata-0.0.26.jar",
          "size": 13118,
          "sha512": "cd9000880e401200921f9ebf98089185abb6bae33caf4c71b5bd5acbcaa6fb60b815a894bed6525140d3f00acbbe31ed767209dba6600adad1d9cbc0d092b55e",
          "sha256": "234b02d0e4e662e3a8072e7ce2d023cb5f8688b23c28c7bcf95c2399189a738c",
          "sha1": "bcb9664dd58010892589ff99d3a54fa97e9cb335",
          "md5": "89cbd6d56c37825aebb29b9cabe2f43f"
        }
      ]
    }
  ]
}
