{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.3/contract-0.0.3.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "su2tjwkhbbbjndaqanwwqcxe24"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.3.jar",
          "url": "contract-metadata-0.0.3.jar",
          "size": 6871,
          "sha512": "1649a1df11154a881eb01b575855aa528b5f1437047c833f438617b9dde52cd0be9410a01bfcbf884a54f4251e5de8b92470584b9bd373c2dd78033500ab8087",
          "sha256": "581bd27fbddfb5ffe70fd578477d1b03246f1c2a5c9a214728d4e22b6c5fe7a7",
          "sha1": "5c92b60c160f143d928ee265f57aa5998d8d6602",
          "md5": "6663875eeca2cdcb9e4a2e990bd240e4"
        }
      ]
    }
  ]
}
