{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.28/core-0.0.28.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.28.jar",
          "url": "core-metadata-0.0.28.jar",
          "size": 5327,
          "sha512": "81590f216df34eb1ea4e7ac9f5a550aefd78e33cf7d20567390d23aa635d9828bc43ff8eb91e0ff8dd64528efadf61a5947ec5a98fa5296c7480d71597a837c0",
          "sha256": "09d76ba9cae4ebedb6106c49b604d030a910ade1b2d157c1c682a9cf31acf518",
          "sha1": "0a4f473ce49258aec3e422d9e44c624926ccf727",
          "md5": "53a12fee1eaa7b58f40aa627a1109b1e"
        }
      ]
    }
  ]
}
