{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.28/core-0.0.28.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "t2w34ohvabccfdd6l3g4neepp4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.28.jar",
          "url": "core-metadata-0.0.28.jar",
          "size": 5327,
          "sha512": "077dc27abbd825c398b9998e3d2152e6da1221a17a5b1cdc0c58f2b4d24ef8ec4c85a70e1682d4a0a6a4f0ad40ab80c064cae2fa0a8d1f33e8bf33a752abf315",
          "sha256": "efacf253952f2893dedc12ba1393bcb00038d1f298699923ccaae6c73c59a963",
          "sha1": "502a818e013de897e5b603743ca42c817da0c0e9",
          "md5": "c140b40ea599a9d26f4af334bc90eb5d"
        }
      ]
    }
  ]
}
