{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5q5bv5aktfh2fdqq25rjsv33bm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha8.jar",
          "url": "generator-1.0.0-alpha8.jar",
          "size": 112780,
          "sha512": "f859db737b541360b205c522e351145c147280717d31d8a44d26ec5a79c0cbd77026eed897d9001645810f4e29abf887ebaaee74b227f95982e723da29ed31e2",
          "sha256": "bfdf3f0b0c44193046eb62c2d0391a206baab0919bf1a6ec5a6dc574a7517b11",
          "sha1": "980ff52782ea07ab08415d2eddf87f3290bd4c40",
          "md5": "45824bb205e9caf2b46a9c257266cecb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha8"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha8.jar",
          "url": "generator-1.0.0-alpha8.jar",
          "size": 112780,
          "sha512": "f859db737b541360b205c522e351145c147280717d31d8a44d26ec5a79c0cbd77026eed897d9001645810f4e29abf887ebaaee74b227f95982e723da29ed31e2",
          "sha256": "bfdf3f0b0c44193046eb62c2d0391a206baab0919bf1a6ec5a6dc574a7517b11",
          "sha1": "980ff52782ea07ab08415d2eddf87f3290bd4c40",
          "md5": "45824bb205e9caf2b46a9c257266cecb"
        }
      ]
    }
  ]
}
