{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.38/viewmodel-0.0.38.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h3wjxn3zcban5fnecihtr5lrqi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.38"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.38.jar",
          "url": "viewmodel-metadata-0.0.38.jar",
          "size": 7396,
          "sha512": "5feb045b28b8e6c7761f4cc360604b78ec4551f65d4f5031107f7ee142785d173d9b8e68729e9d18e8de5dbed85699805e04ad56fab4a45e2ecd63ea6a271f60",
          "sha256": "a2fe8bada0fd06aff54bb2448c2a8941e892b2e2d66c3f76cfa35158ff2a6619",
          "sha1": "c041779d855784c0901fca1ff42754638d74fdfe",
          "md5": "841c2684f84311a158ae9368812544b0"
        }
      ]
    }
  ]
}
