{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.1/viewmodel-0.0.1.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zk7tjfukpff7tmn3tiqtxdfuzy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.1.jar",
          "url": "viewmodel-metadata-0.0.1.jar",
          "size": 5530,
          "sha512": "c2b3b64f04b83e3bb5eead91da2d01f9105f069cf75c7c60b0eba0ebe633199e561b0520b6423944e162be9c29c1b0fde0d613d57b353c3a1177b6d59099d2e2",
          "sha256": "613987f2a25bcb25db0d7ddadc27d635739a67016c660c6d9f8265d885a123dd",
          "sha1": "4b2a7de6fae40dc2c08fdf774566ddec6872224d",
          "md5": "96e1954b5167d15a275e1394971f4896"
        }
      ]
    }
  ]
}
