{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.6/model-0.0.6.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3w2f7l7ypffvjgcalkwzywgyy4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.6.jar",
          "url": "model-metadata-0.0.6.jar",
          "size": 11206,
          "sha512": "81f677a7cee073014741bacf7f2f4e3758d4853e3db3c3ce5195813d02c206219fa1ab07fd5c044f49433233d062195dccf6f8b5db83fc95138b04bf38ff38a3",
          "sha256": "e4e4e9d200066abcd3361307afbb9c5716996c28ce9bdc5fcf60f40c09be0ad0",
          "sha1": "1ca35ddbf407ebf79bc9e060344a5c758731a4b7",
          "md5": "436cf00b30a22762754dae29b3555c2c"
        }
      ]
    }
  ]
}
