{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.49/view-0.0.49.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.49-debug.aar",
          "size": 154622,
          "sha512": "9059e61d88cdb1e3e581d8608ec81ced936cfe53a28b7c0c1cbbb6c264c7c7d03abd662ca99f17e94425c7a8d9bad67090dec43de3b1fc34f65ef180e66d92b4",
          "sha256": "3914245771dfb2c335df3a0d26ac31948544d57ddf048a2841742e7758f754aa",
          "sha1": "c37f9c40e8c5784bc588a273d5b3d33ca3ec8f4e",
          "md5": "37970b7bc979422d735b58794ceb6ab1"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.49-debug.aar",
          "size": 154622,
          "sha512": "9059e61d88cdb1e3e581d8608ec81ced936cfe53a28b7c0c1cbbb6c264c7c7d03abd662ca99f17e94425c7a8d9bad67090dec43de3b1fc34f65ef180e66d92b4",
          "sha256": "3914245771dfb2c335df3a0d26ac31948544d57ddf048a2841742e7758f754aa",
          "sha1": "c37f9c40e8c5784bc588a273d5b3d33ca3ec8f4e",
          "md5": "37970b7bc979422d735b58794ceb6ab1"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.49.aar",
          "size": 149788,
          "sha512": "6756df8a12332df7012c91b48bdcdadb27cf8ff2effaa2584c9b576561b0c5b13b46389e7756f6c267133d18e7ad17c71c5faa48cb88d2e4fb72ba490e9b5519",
          "sha256": "9ea5e42ee5ee3aa1b389a87ae768451f68419749e145a62769f323b5f7ec2667",
          "sha1": "6389d94a7d3ff1633f0f8c529d618af7f8b44d2b",
          "md5": "541d44ae7cddbb9ee225ebaa15fcead3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.49.aar",
          "size": 149788,
          "sha512": "6756df8a12332df7012c91b48bdcdadb27cf8ff2effaa2584c9b576561b0c5b13b46389e7756f6c267133d18e7ad17c71c5faa48cb88d2e4fb72ba490e9b5519",
          "sha256": "9ea5e42ee5ee3aa1b389a87ae768451f68419749e145a62769f323b5f7ec2667",
          "sha1": "6389d94a7d3ff1633f0f8c529d618af7f8b44d2b",
          "md5": "541d44ae7cddbb9ee225ebaa15fcead3"
        }
      ]
    }
  ]
}
