{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.5/view-0.0.5.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "5f2uil5yr5anjo2xrdrfwpkzma"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.5.jar",
          "url": "view-metadata-0.0.5.jar",
          "size": 5556,
          "sha512": "a79c9763d848387175a3e292cc209255e8bcce696a73dc47332b3034bcfe756f6b385c3297b24c07477e0eb44d4a7e9477ccde547a1cbfa7c71e251ee788f33a",
          "sha256": "2901f743d7d796bd62472e9555b3a92a376932f2c141a8ab73748ca7e639f642",
          "sha1": "2548c69c6336e1141d43574b9483ef297bc7f481",
          "md5": "555db88a2a66be1015c763a7a77f2a59"
        }
      ]
    }
  ]
}
