{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests-metadata",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha6.jar",
          "url": "androidTests-metadata-1.0.0-alpha6.jar",
          "size": 261,
          "sha512": "7ceff46285def5d62a6e168981cb050765a7ccd33c4dd87a5dfa5a03e3a13cc8a8105848074779aa1e55af00446ca172748f44c51813aacf2de6e5294c6fa137",
          "sha256": "0332f25a03a57de88a9825d7b3eab3f52b66509b754203fb67b6a74431785334",
          "sha1": "70f937961c5c8cc1b67399cce1855ee3cbd07af7",
          "md5": "7c63ea242786ecff578528dca96e4eba"
        }
      ]
    }
  ]
}
