{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha4.jar",
          "url": "androidTests-1.0.0-alpha4.jar",
          "size": 261,
          "sha512": "13986088afbec6e44ddd514c7b10894c815e4b6ca93e52f9f059dfbcf502dae654e41d8704c5d2d032202136da1d1adc063374791c2a1109d12b74e5f420fc2f",
          "sha256": "8d279974baa967185ac5e7f357c2580c7c80807f4896f91085e5f5bfe5ffb604",
          "sha1": "86b30105e46f2e14a1781e1bdca035488e545fd7",
          "md5": "6292124f6696bd1280c3cd9eaa2abb0f"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha4/androidTests-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha4/androidTests-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha4/androidTests-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha4/androidTests-android-1.0.0-alpha4.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha4"
      }
    }
  ]
}
