{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewlegacy/0.0.1/viewlegacy-0.0.1.module",
    "group": "tech.skot.libraries.tabbar",
    "module": "viewlegacy",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-0.0.1-debug.aar",
          "size": 66909,
          "sha512": "40dd9c94851c5c1b20a60d65894d98a252292a882f008f6e7cccc411e566832522d75c981d45d4b0ad4ea37ddc249d6dcedf930ff07fab0cffd8a8018a5314c7",
          "sha256": "0be75f49bb04b637c10c0bd75ac1bdd62d573436844d77bc42a2dfb62b4b13ab",
          "sha1": "ff7ceb015d1f2afc556668075808925f880f0715",
          "md5": "b240b63dddd053a4790a959ffc37c89e"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewlegacy",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewmodel",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-0.0.1-debug.aar",
          "size": 66909,
          "sha512": "40dd9c94851c5c1b20a60d65894d98a252292a882f008f6e7cccc411e566832522d75c981d45d4b0ad4ea37ddc249d6dcedf930ff07fab0cffd8a8018a5314c7",
          "sha256": "0be75f49bb04b637c10c0bd75ac1bdd62d573436844d77bc42a2dfb62b4b13ab",
          "sha1": "ff7ceb015d1f2afc556668075808925f880f0715",
          "md5": "b240b63dddd053a4790a959ffc37c89e"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-0.0.1.aar",
          "size": 64969,
          "sha512": "56dc663c421599a83022fb83b4bc9f956d16807f11c91d175d4f357644d1cf64b66e3134f7be8c440834ea57bcdb2a74e749b4110a5d52a07e443287c03e6eb2",
          "sha256": "41471e751b793796b8016a8db355a44349f3853120a63e740e7110565669c7a0",
          "sha1": "2814d48d6ecd9f2dd657e30b531a99f9f1487f91",
          "md5": "d0a0bb7d3ead0270ead122f796f3e98b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewlegacy",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewmodel",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-0.0.1.aar",
          "size": 64969,
          "sha512": "56dc663c421599a83022fb83b4bc9f956d16807f11c91d175d4f357644d1cf64b66e3134f7be8c440834ea57bcdb2a74e749b4110a5d52a07e443287c03e6eb2",
          "sha256": "41471e751b793796b8016a8db355a44349f3853120a63e740e7110565669c7a0",
          "sha1": "2814d48d6ecd9f2dd657e30b531a99f9f1487f91",
          "md5": "d0a0bb7d3ead0270ead122f796f3e98b"
        }
      ]
    }
  ]
}
