{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewlegacy/0.0.1/viewlegacy-0.0.1.module",
    "group": "tech.skot.libraries.tabbar",
    "module": "viewlegacy",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-0.0.1-debug.aar",
          "size": 67036,
          "sha512": "3d432da0171ecbf385ab054fee3614b50e20ca4132128cd3f02242ba015b72e311e8a1d81bd3b5a7d052d5f61802bbb0366ee161120d5839c2b6b9bece8e550c",
          "sha256": "be0603666bf3398f446a8d7cda92ca4f3429dde0069103862dc7031808298731",
          "sha1": "ea08150bcb24b3441c7729f58387f5b8daaa976b",
          "md5": "3871261f072e99b507bf4a1e4aa584c3"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewlegacy",
          "version": {
            "requires": "1.0.0-alpha25"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewmodel",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-0.0.1-debug.aar",
          "size": 67036,
          "sha512": "3d432da0171ecbf385ab054fee3614b50e20ca4132128cd3f02242ba015b72e311e8a1d81bd3b5a7d052d5f61802bbb0366ee161120d5839c2b6b9bece8e550c",
          "sha256": "be0603666bf3398f446a8d7cda92ca4f3429dde0069103862dc7031808298731",
          "sha1": "ea08150bcb24b3441c7729f58387f5b8daaa976b",
          "md5": "3871261f072e99b507bf4a1e4aa584c3"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-0.0.1.aar",
          "size": 65096,
          "sha512": "4e1276a6848aaf0687a02a974f66673f454c4c056b705d249ab56fa1d3fea4022f03bf800b2222497ebca169d2372af8bafc793c3c325ab04fb6d116d853ee50",
          "sha256": "89911cb1d247d29c8c3488c53a6d250f0f8c2f6b8554019ab8c1c9e482dc5131",
          "sha1": "f14c65f8fd310da1f0385719feff8c27a01afb2f",
          "md5": "87b2744bc8b5d538d1b2365c1f83ae27"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewlegacy",
          "version": {
            "requires": "1.0.0-alpha25"
          }
        },
        {
          "group": "tech.skot.libraries.tabbar",
          "module": "viewmodel",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-0.0.1.aar",
          "size": 65096,
          "sha512": "4e1276a6848aaf0687a02a974f66673f454c4c056b705d249ab56fa1d3fea4022f03bf800b2222497ebca169d2372af8bafc793c3c325ab04fb6d116d853ee50",
          "sha256": "89911cb1d247d29c8c3488c53a6d250f0f8c2f6b8554019ab8c1c9e482dc5131",
          "sha1": "f14c65f8fd310da1f0385719feff8c27a01afb2f",
          "md5": "87b2744bc8b5d538d1b2365c1f83ae27"
        }
      ]
    }
  ]
}
