{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha18"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha18"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha18"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha18.jar",
          "url": "viewmodel-1.0.0-alpha18.jar",
          "size": 15230,
          "sha512": "5ae26d8829b33c508fe09bfed6e180cd0f68acd36a263d20b797a10b9a06ab4ee50d771b6787d8c268842e1c6ce9ee18e6ab9ccea5f57f2af9d849d07696f7e3",
          "sha256": "8087e9af1a5c48e63973fa9dd741b85110e60ea2c1e95883699af668b4792aac",
          "sha1": "92ab0305d3d0005cc071b17c8bb60911c06b403e",
          "md5": "b14c86b79ee61ea3647914488145317d"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha18/viewmodel-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha18/viewmodel-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha18/viewmodel-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha18"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha18/viewmodel-android-1.0.0-alpha18.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha18"
      }
    }
  ]
}
