{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.49.jar",
          "url": "plugin-0.0.49.jar",
          "size": 56865,
          "sha512": "7d96eca70c82be5a113974c1f176265e0661df25bd9c4209e388f37d84847b36f67c4966f7577c9031adc564acfe37f817c3698b9053bc8e21cc4f6bafcfa661",
          "sha256": "edc35fdea81fc923b190ce793a81ee66d0dff9363319c61bafa82bb4f257e1cd",
          "sha1": "cc3641561dd997857261d9158861d1709eb8a236",
          "md5": "a0a9b144b50a3def930ae823ad80a400"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "+"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-0.0.49.jar",
          "url": "plugin-0.0.49.jar",
          "size": 56865,
          "sha512": "7d96eca70c82be5a113974c1f176265e0661df25bd9c4209e388f37d84847b36f67c4966f7577c9031adc564acfe37f817c3698b9053bc8e21cc4f6bafcfa661",
          "sha256": "edc35fdea81fc923b190ce793a81ee66d0dff9363319c61bafa82bb4f257e1cd",
          "sha1": "cc3641561dd997857261d9158861d1709eb8a236",
          "md5": "a0a9b144b50a3def930ae823ad80a400"
        }
      ]
    }
  ]
}
