{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.29/core-0.0.29.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gwf6dkvyzrgrfdke5mvnkun2xi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.29.jar",
          "url": "core-metadata-0.0.29.jar",
          "size": 5327,
          "sha512": "9e8282be2e06d73ac34485aa042240701ff3949b7fdd793d68318dd029903d8673ffc4dbfd451ef1b3ccb4ee0e43d88e4a8bf234d5a9c885a3687ec26e3171d4",
          "sha256": "05cc27135a1fc53e916d706af84f4b70a81e7bb5734e1b6bf1f1d84967549178",
          "sha1": "1f5b4ef8f0f6172c90947f79d6a9e436eceac037",
          "md5": "b0525596282a597ba2b110f77d0bc6e4"
        }
      ]
    }
  ]
}
