{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.16/viewmodel-0.0.16.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "xduo2x3rkbaepe3emobddesovq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.16"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.16.jar",
          "url": "viewmodel-metadata-0.0.16.jar",
          "size": 6919,
          "sha512": "ee9a7e9ab29f36a24c0ce18df9bad92207b885a0c601bcec5d9b3bc1e727eea6d67daec8b8bc21b9fe4ceaca0db3b8d5adc675191874f842e69524457323a887",
          "sha256": "95b796d6fc09cf80fa1b8f936dadb7031130f7ac15b2e3a582750c165b054332",
          "sha1": "8dbbff467368cc9b266d04d4327d7ebfd6f3aa65",
          "md5": "b1e210061d330218d56cbf2645db03b3"
        }
      ]
    }
  ]
}
