{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.20/model-0.0.20.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2r2ojxqr5ffvpf4fmosdnmnn7i"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.20-debug.aar",
          "size": 94005,
          "sha512": "52a89b448b613fbb40b49fb82d7f8b69702eebbc5ab5780934abcb5051e97ff640438627576b9c7bee9b08fd5f6db9ac4d4f20d1636fb2763950ccf6960ce1c8",
          "sha256": "d519321e70321b58c1bdddb32b599ed5ed00e117a1579f7e12c316c2508c3d82",
          "sha1": "0b014fe9e3e978c8b94e478fdaf7e983e905efee",
          "md5": "07a76377e381fb41bd30650107081b88"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.20-debug.aar",
          "size": 94005,
          "sha512": "52a89b448b613fbb40b49fb82d7f8b69702eebbc5ab5780934abcb5051e97ff640438627576b9c7bee9b08fd5f6db9ac4d4f20d1636fb2763950ccf6960ce1c8",
          "sha256": "d519321e70321b58c1bdddb32b599ed5ed00e117a1579f7e12c316c2508c3d82",
          "sha1": "0b014fe9e3e978c8b94e478fdaf7e983e905efee",
          "md5": "07a76377e381fb41bd30650107081b88"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.20.aar",
          "size": 90190,
          "sha512": "e3a45139c1e1d7654df29c69dd22a952e53859b5441a35dfb3c444d8650dab71d28fb1355699de802cdaa68611b5d4e2cea5076058e36f0fdd5c1b785fda1bb4",
          "sha256": "a790e3ebafe54b9d6294229f345a383349e884bbbf05015cfe11a89aed22c0da",
          "sha1": "c34036311900dbca9d0755148787221b08010b48",
          "md5": "8a2710de35b408fbe2a3befd6e5c285a"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.20.aar",
          "size": 90190,
          "sha512": "e3a45139c1e1d7654df29c69dd22a952e53859b5441a35dfb3c444d8650dab71d28fb1355699de802cdaa68611b5d4e2cea5076058e36f0fdd5c1b785fda1bb4",
          "sha256": "a790e3ebafe54b9d6294229f345a383349e884bbbf05015cfe11a89aed22c0da",
          "sha1": "c34036311900dbca9d0755148787221b08010b48",
          "md5": "8a2710de35b408fbe2a3befd6e5c285a"
        }
      ]
    }
  ]
}
