{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-metadata-1.0.0-alpha20.jar",
          "url": "viewcontract-1.0.0-alpha20.jar",
          "size": 17665,
          "sha512": "af7b2614256b93e047a27f447ef779582c1098488ea0a11a4619d40ba7fe26e3884cc0f40e1548d6599f29690e064646c3401d6a70baf1c1d677a37168fcce79",
          "sha256": "cac294273c210e8c4878ee56c4f3e81b8278a1f422099d912a3e81ccd778faf6",
          "sha1": "0ef5f87459c3968ee433646a6393f49f3fe612e3",
          "md5": "ff1268af61bb125e1dc81022fc97c988"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosarm64/1.0.0-alpha20/viewcontract-iosarm64-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewcontract-iosarm64",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosx64/1.0.0-alpha20/viewcontract-iosx64-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewcontract-iosx64",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha20/viewcontract-jvm-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha20"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha20/viewcontract-jvm-1.0.0-alpha20.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha20"
      }
    }
  ]
}
