{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.20/androidTests-0.0.20.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2r2ojxqr5ffvpf4fmosdnmnn7i"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.20.jar",
          "url": "androidTests-metadata-0.0.20.jar",
          "size": 261,
          "sha512": "c5c17b1385d63421f02aea193282d89fb50774f68f9031c330cce329275746b57a9d2e466231a6a287a54a641abcbe74a34fab16a90b247b49f9d28c0425296d",
          "sha256": "345dac33ce35e12878b6672590f90e3ee656204116bd3d386a69929a0be27565",
          "sha1": "893084844782905d61571069df5a7e67cda21e44",
          "md5": "c8666fc3c2a283d28fa1aadd7fa0ed2f"
        }
      ]
    }
  ]
}
