{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.19/viewmodel-0.0.19.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "julmyh4b25dnnegsjouy3lg5q4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.19.jar",
          "url": "viewmodel-metadata-0.0.19.jar",
          "size": 6974,
          "sha512": "7329ca62fd0a0ffd7950e7b5166d76b3886d420622f3b134d5ca407e2de3f54d360d551c8dfe245b13591f157c5d9740af892f61d55ace1d24c3cef0da543908",
          "sha256": "023a2d06a7331232ad88ce715ca1b5bfbce0d6bdf398d923863435b3a5c6ba87",
          "sha1": "3ef96a79eb99ceceed2476f9846b3cea15012d10",
          "md5": "4fe281f05595697152a60336af361a6c"
        }
      ]
    }
  ]
}
