{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.6/androidTests-0.0.6.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3w2f7l7ypffvjgcalkwzywgyy4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.6.jar",
          "url": "androidTests-metadata-0.0.6.jar",
          "size": 261,
          "sha512": "d456533906829f0146af153a9100d81154a782c32ce9da791f31392caef8b741cd6ac053969c9d20b6b52301656a0266ba3b0960e86c7e1b35db8316c80ecd89",
          "sha256": "be9681cd55a824906e5b7d63de671c6dcc954dedaaf9a76cab5fc4075dd69080",
          "sha1": "4756a12bffe633c6f5438e2f70c018a8d91ce72",
          "md5": "32eb6fd96521972849daded77b914220"
        }
      ]
    }
  ]
}
