{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha24.jar",
          "url": "plugin-1.0.0-alpha24.jar",
          "size": 221285,
          "sha512": "3721875a97049958058db1171824a259f9cd02c2f39d203cee39138a5a34a2ad3347851ff6e70db21180cb241556b320f9f3a35fed904a21cf7f9772b357559c",
          "sha256": "1f9db1c57a165ed2e7ea3555e63929576a1890792c9fec86542fec4766846c0f",
          "sha1": "90998e97d732419334af3e2e6771cadaa1d9442a",
          "md5": "b89c6057f002ab05fcc3aa245db8a964"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha24.jar",
          "url": "plugin-1.0.0-alpha24.jar",
          "size": 221285,
          "sha512": "3721875a97049958058db1171824a259f9cd02c2f39d203cee39138a5a34a2ad3347851ff6e70db21180cb241556b320f9f3a35fed904a21cf7f9772b357559c",
          "sha256": "1f9db1c57a165ed2e7ea3555e63929576a1890792c9fec86542fec4766846c0f",
          "sha1": "90998e97d732419334af3e2e6771cadaa1d9442a",
          "md5": "b89c6057f002ab05fcc3aa245db8a964"
        }
      ]
    }
  ]
}
