{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.7/viewmodel-0.0.7.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "igasumkhiveslbdlejoqxrssj4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.7.jar",
          "url": "viewmodel-metadata-0.0.7.jar",
          "size": 5530,
          "sha512": "b7314ebdbc7249814026360e248eda86938985c09a72f8129393b02b42c370ed349b0914208361d452a568d7a56a7d026843534679f7ffbcf1e31c8878ce3a4a",
          "sha256": "96b55dcaecfd32978ad63adda3e6e47e9b2b697324c63923af71a20c98791b34",
          "sha1": "5f430da35a166ddc9a0b801560ea24df92a3166c",
          "md5": "988b81e638a6029f68ef8c0bfdee0f6c"
        }
      ]
    }
  ]
}
