{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha13/modelcontract-1.0.0-alpha13.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosx64-1.0.0-alpha13.klib",
          "size": 23327,
          "sha512": "7fd1d69eb8e64bc88d6bf4b8b830d1626499c0f32ec5460679248b8c561359d1553adae05bf3c4bbc3351708919f8eee0c45386864f7c493a3882c476cd656eb",
          "sha256": "49fad1cb2baac0ff40dfead902fee5d7338d64e8ba8b0da1486cc81fb1a66c93",
          "sha1": "07df102cc5fe2afc9c56f5ddb271305c0e8da03b",
          "md5": "49cb3cb0c95f4d949ad732ea677224a7"
        }
      ]
    }
  ]
}
