{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model-metadata",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.45"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.45.jar",
          "url": "model-metadata-0.0.45.jar",
          "size": 13116,
          "sha512": "ee7ebf7a92fe3cf619aefa06a0ba4aefb3b9d532b30eeb8969e61fd70b673424a8863381553bad2fedc41bb50129bfed36cd469c663f9401acf27b36766113ef",
          "sha256": "31594820f3c7a4aba4f4a499ccd7f2658634db4331a5694a63ba9a1407518bbd",
          "sha1": "04a6cf3db6a234b0949a02d2ddb963010d159fe0",
          "md5": "000e2ccf2828dc3baf1cfd432f53986b"
        }
      ]
    }
  ]
}
