{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha11/modelcontract-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosx64-1.0.0-alpha11.klib",
          "size": 15022,
          "sha512": "dd34be9124654d95c24f74ceb99852034659aee799018e115df89f0406de31b5d35a7f154f5a9d4e0701bc2ae72071ff3b27c1cda48fb8fc588f247f7a5c1d1e",
          "sha256": "d4db30b355ba44e224949d68c9885b89e84c6030ee551bf974448bcf626e0f09",
          "sha1": "c8468089365497ca5dec74637c6db041ead1f17c",
          "md5": "eb0f0d55308c873a82d8c725c221f185"
        }
      ]
    }
  ]
}
