{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.19/androidTests-0.0.19.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "julmyh4b25dnnegsjouy3lg5q4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.19.jar",
          "url": "androidTests-metadata-0.0.19.jar",
          "size": 261,
          "sha512": "cc4b019cb7aebd4b286cfc9f041adcbb060d0aea6fff2a5d7f505ad023db2ea571f68d374b96f3f79b82c842a20f1d0f000ea4b6cbe91de1e96388e7789ba269",
          "sha256": "75d92410ece8bae7f5cba30baebaa50bae9fe5032a88a2b4b45f15004c277e72",
          "sha1": "f3a26ff63a5451666bc05d784914d74e89fbe8ed",
          "md5": "3714a5646ec1d7742e190eb33f38fc34"
        }
      ]
    }
  ]
}
