{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.22/contract-0.0.22.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6uskpwxm4nhbnbsedqteegk7ke"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.22.jar",
          "url": "contract-jvm-0.0.22.jar",
          "size": 15726,
          "sha512": "79f0a98d45c9fe992e2a23ea8879b8abb7b9fa261abf330cf36c2446c42295eebb73ec6b59baaea92ca7f1bc0272087031cea187d5dfc53b63d4bebcd1034838",
          "sha256": "cbb6e8941cdfd839dfa65c65e7ab0ae7b0983f295844c1a1cbd488697486ceff",
          "sha1": "fa1ffb1956c104d279e3bad0b727900612440c97",
          "md5": "442dbaf7e0f13a5d7d74b05bc33c8234"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.22.jar",
          "url": "contract-jvm-0.0.22.jar",
          "size": 15726,
          "sha512": "79f0a98d45c9fe992e2a23ea8879b8abb7b9fa261abf330cf36c2446c42295eebb73ec6b59baaea92ca7f1bc0272087031cea187d5dfc53b63d4bebcd1034838",
          "sha256": "cbb6e8941cdfd839dfa65c65e7ab0ae7b0983f295844c1a1cbd488697486ceff",
          "sha1": "fa1ffb1956c104d279e3bad0b727900612440c97",
          "md5": "442dbaf7e0f13a5d7d74b05bc33c8234"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.22/contract-metadata-0.0.22.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.22"
      }
    }
  ]
}
