{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.31/model-0.0.31.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "4g4dsdf7yvgxndmmqjq6s6i2gm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.31.jar",
          "url": "model-metadata-0.0.31.jar",
          "size": 13171,
          "sha512": "1147cdb619262be787e972460de6189a0ce7c4b97d40f37876d55a41cd571dd0ce5f234d8bcbc7f7dad90a10eb949ff1e8149c9795daf9f6113adfe2d6046edb",
          "sha256": "4696909c5e80fade053b89d4223a214ffbda06cd52e8524d15b030673dc1f80d",
          "sha1": "1250e6060cb10524d385bdca9826386cea68208e",
          "md5": "318279520e018ee02aef886d10b9298e"
        }
      ]
    }
  ]
}
