{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.28/model-0.0.28.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.28.jar",
          "url": "model-metadata-0.0.28.jar",
          "size": 13118,
          "sha512": "cf8c5905d59cd6de8e176ae7a978955fb23d1e1f12ad349119cad612215f1f87a3baa011c576bdab443dd4ca0b4df111f1c4f2312f4eb860ef6c97a3f07fb13f",
          "sha256": "99e5c3a9cf023f4644a1649afcf525abf3ff318cf6a10f6232ae542e1b3731bb",
          "sha1": "0b470ad723249ad3622d011dea9134a7d0443292",
          "md5": "40970aca9af0d2fbe1e194dbb76921f8"
        }
      ]
    }
  ]
}
