{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "model",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-1.0.0-alpha19.jar",
          "url": "model-1.0.0-alpha19.jar",
          "size": 13583,
          "sha512": "11d4f31bfa42a65e320460db6fe64bacac81c5cab9481237a20a49d9e6b84f4deee7e6344bf59cdff34601aebad83d33d4f4b4d9f1e1101d140c25c49dab3b29",
          "sha256": "8a6ee81f882c6658690de3b7ee47d8652e37ffab427ba69e8fcc9cc2928329ba",
          "sha1": "73f99380b46e2eade4f5db2329dfe5143d4eb0cf",
          "md5": "efcd82288f03589c8efea27012dd6945"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha19/model-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha19/model-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha19/model-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-alpha19/model-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "model-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosarm64/1.0.0-alpha19/model-iosarm64-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "model-iosarm64",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosx64/1.0.0-alpha19/model-iosx64-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "model-iosx64",
        "version": "1.0.0-alpha19"
      }
    }
  ]
}
