{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha17.jar",
          "url": "androidTests-1.0.0-alpha17.jar",
          "size": 261,
          "sha512": "af1bb7ef508f6fe5cd76aed30785184aacec77adc65af3f5d07c65f585b7b908975b01703d59633aafe5288a9a498dd9e66af85be4c846cde2bc631a28949e9e",
          "sha256": "9544212bccd509a9b5867ad2e3910c33af49dce0dd7d17dd679fc3715a08543e",
          "sha1": "878a62d1717788c8e8f5f4d60e63a8cf5a0463ce",
          "md5": "d0f892ace91061927524b2d9c765d82f"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha17/androidTests-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha17/androidTests-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha17/androidTests-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha17"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha17/androidTests-android-1.0.0-alpha17.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha17"
      }
    }
  ]
}
