{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "generator",
    "version": "1.0.0-iosalpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-iosalpha62.jar",
          "url": "generator-1.0.0-iosalpha62.jar",
          "size": 219771,
          "sha512": "8405da70fd75e954a5c0317f5723357eb90b64c384884857f159acd0a914c52bb23c4e2d5d4712cd7532d49322e63cc9bff148da70da1f9d329032f55d188677",
          "sha256": "705b76b966455b2744071d5218dd66ed3fd9460f226af29b5bb23c6df07833c8",
          "sha1": "743f8440a12a2c07de994d6689aef7528d238c5e",
          "md5": "0f1b6b0dd9c7c6550e2c7d74db580ba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-iosalpha62.jar",
          "url": "generator-1.0.0-iosalpha62.jar",
          "size": 219771,
          "sha512": "8405da70fd75e954a5c0317f5723357eb90b64c384884857f159acd0a914c52bb23c4e2d5d4712cd7532d49322e63cc9bff148da70da1f9d329032f55d188677",
          "sha256": "705b76b966455b2744071d5218dd66ed3fd9460f226af29b5bb23c6df07833c8",
          "sha1": "743f8440a12a2c07de994d6689aef7528d238c5e",
          "md5": "0f1b6b0dd9c7c6550e2c7d74db580ba9"
        }
      ]
    }
  ]
}
