{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewlegacy/1.0.0-alpha17/viewlegacy-1.0.0-alpha17.module",
    "group": "tech.skot",
    "module": "viewlegacy",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-1.0.0-alpha17-debug.aar",
          "size": 299502,
          "sha512": "1de2a1a543e528c8c29cd58c9f109f62ad54c5c5537f1d2e66868a73e242fc45bbbb2bf1fe8ce3c0550cd4ddeb34e7d6b527a0bc03a36d2ddb269800909a2edb",
          "sha256": "8f03d7a5dc5bdd148db4b05468bc0ac177bec49cacbf4d91bff500212f842a18",
          "sha1": "fe67eedc0305f292eaed4b2cd8e4f8f37602b13d",
          "md5": "f0f8f24195d2de5354ea34e0a8fece8c"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-1.0.0-alpha17-debug.aar",
          "size": 299502,
          "sha512": "1de2a1a543e528c8c29cd58c9f109f62ad54c5c5537f1d2e66868a73e242fc45bbbb2bf1fe8ce3c0550cd4ddeb34e7d6b527a0bc03a36d2ddb269800909a2edb",
          "sha256": "8f03d7a5dc5bdd148db4b05468bc0ac177bec49cacbf4d91bff500212f842a18",
          "sha1": "fe67eedc0305f292eaed4b2cd8e4f8f37602b13d",
          "md5": "f0f8f24195d2de5354ea34e0a8fece8c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-1.0.0-alpha17.aar",
          "size": 287011,
          "sha512": "a7fb2de646b13477221672e98d37ba1e39eb5ff4f092777aaadc49040e7f1b7e29e1e571be7a55191a04d08590b959eba36be63507f2e650acf54a4f60eb69af",
          "sha256": "b3e43568d173df540c1ab86930b42c4adacd8cb1cc8720f60b6c65abfb7448a2",
          "sha1": "add8fc395b5dc9329adeabfbe6f6db5df04e67c1",
          "md5": "9b9441730edbe8c1e5ee205d389fcd4f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-1.0.0-alpha17.aar",
          "size": 287011,
          "sha512": "a7fb2de646b13477221672e98d37ba1e39eb5ff4f092777aaadc49040e7f1b7e29e1e571be7a55191a04d08590b959eba36be63507f2e650acf54a4f60eb69af",
          "sha256": "b3e43568d173df540c1ab86930b42c4adacd8cb1cc8720f60b6c65abfb7448a2",
          "sha1": "add8fc395b5dc9329adeabfbe6f6db5df04e67c1",
          "md5": "9b9441730edbe8c1e5ee205d389fcd4f"
        }
      ]
    }
  ]
}
