{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2mo2nnyckfb5ncqso4y6gwemnm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.18.jar",
          "url": "generator-0.0.18.jar",
          "size": 92130,
          "sha512": "190b064e215fee76110126196e1ec5308dac6d67bdad408d15ec1acaf0db0176fd518651e62dc689aa6114ad01251d712b4d33f3a9395868bfdafff52ec6dd14",
          "sha256": "00aacc316aaabd10c35d7afe53fcd1216fc1c9188b0415399eadad2749447c9f",
          "sha1": "23c397d4e098fa1ac69ff1a9825a568e7c0350fb",
          "md5": "c78ad752eab6e5f3db6fc6390ce0c8f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.18"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.18.jar",
          "url": "generator-0.0.18.jar",
          "size": 92130,
          "sha512": "190b064e215fee76110126196e1ec5308dac6d67bdad408d15ec1acaf0db0176fd518651e62dc689aa6114ad01251d712b4d33f3a9395868bfdafff52ec6dd14",
          "sha256": "00aacc316aaabd10c35d7afe53fcd1216fc1c9188b0415399eadad2749447c9f",
          "sha1": "23c397d4e098fa1ac69ff1a9825a568e7c0350fb",
          "md5": "c78ad752eab6e5f3db6fc6390ce0c8f2"
        }
      ]
    }
  ]
}
