{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.30/core-0.0.30.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "45vyvjpy25d6rogm6vet7cshky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.30.jar",
          "url": "core-metadata-0.0.30.jar",
          "size": 5327,
          "sha512": "efc43be828a04aa8d9281de25cc577a02f7150eab8aa362b69542c6b730a07dc0d04fb3bc7614e1f2404bca0716acf28b50f86ec07bdb415e65a1c0f07b2e9ad",
          "sha256": "169c21d2a8c31d986a8368ff233cbfb0c6ce0ff85c4fa4e6d0b6e4abacd698ac",
          "sha1": "3d55aaf0756f1e87387e19c3b40798330836a92f",
          "md5": "d012711e3fd5cda39023ec49553c826c"
        }
      ]
    }
  ]
}
