{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha17/modelcontract-1.0.0-alpha17.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha17.klib",
          "size": 25719,
          "sha512": "0ab4f616e4afb594279f146b26e1bb176576cbaccd98ede6222f831457863cff5bc50f79c93dfa3d7de999e103b4c7a4f55ed19d0b64ff2735c2659ac2cba7f4",
          "sha256": "d2a07ce2f38dfc683da2495d020d1044fb9576efdf4bd97d2a724ac1cb082129",
          "sha1": "16f4edd00970fb12a4186c974e84b05e3e0b0ad8",
          "md5": "f97875859feaecf7ef4f5394e2bb92c0"
        }
      ]
    }
  ]
}
