{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.27/androidTests-0.0.27.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "7rpxctj73vafjppxfjwlavvutq"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-debug.aar",
          "url": "androidTests-android-0.0.27-debug.aar",
          "size": 56712,
          "sha512": "e589628079b461d5183de9cb109a3a9c62d218566f7c5bfcadb63b5b6d81f8959c56c244e6380516dde7e3d6b374d5a9ac017dfb4141c8f6e99653950ef37088",
          "sha256": "9dc828fbd162c4fdebadc5d597840e0796963a71441cb6b2ea4a95f1cf62ca86",
          "sha1": "9f17ea1895492315eb0f56554f0facc03ad2dc3b",
          "md5": "89f76d4a30ecade5753da9f3e60d12fe"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-debug.aar",
          "url": "androidTests-android-0.0.27-debug.aar",
          "size": 56712,
          "sha512": "e589628079b461d5183de9cb109a3a9c62d218566f7c5bfcadb63b5b6d81f8959c56c244e6380516dde7e3d6b374d5a9ac017dfb4141c8f6e99653950ef37088",
          "sha256": "9dc828fbd162c4fdebadc5d597840e0796963a71441cb6b2ea4a95f1cf62ca86",
          "sha1": "9f17ea1895492315eb0f56554f0facc03ad2dc3b",
          "md5": "89f76d4a30ecade5753da9f3e60d12fe"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-release.aar",
          "url": "androidTests-android-0.0.27.aar",
          "size": 55174,
          "sha512": "906bf40d55e4b684864fbe9324f3c6404d49f2d79e31b444164f02d9cee71c0b76b5eec6ab0edbeffbc07cdcf1ed8939d0661fa37b080d0609ce9241a331a1d3",
          "sha256": "3e4827ddf0b1512e0f62261f7fe71cf47e4d42dc075600334062217250a3ebba",
          "sha1": "af6c57fa179fd60ad539ce5f22e7c38384f6a5e6",
          "md5": "69f06e45246bbb69ac597a19bf57c6d6"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.27"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-web",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-testing",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-release.aar",
          "url": "androidTests-android-0.0.27.aar",
          "size": 55174,
          "sha512": "906bf40d55e4b684864fbe9324f3c6404d49f2d79e31b444164f02d9cee71c0b76b5eec6ab0edbeffbc07cdcf1ed8939d0661fa37b080d0609ce9241a331a1d3",
          "sha256": "3e4827ddf0b1512e0f62261f7fe71cf47e4d42dc075600334062217250a3ebba",
          "sha1": "af6c57fa179fd60ad539ce5f22e7c38384f6a5e6",
          "md5": "69f06e45246bbb69ac597a19bf57c6d6"
        }
      ]
    }
  ]
}
