{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.38/androidTests-0.0.38.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h3wjxn3zcban5fnecihtr5lrqi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.38.jar",
          "url": "androidTests-metadata-0.0.38.jar",
          "size": 261,
          "sha512": "edef6fc5f976d7d9d7f27f8f9cd385c01fcea3f0475d841a4a4d98fcae1719d49d5447d6216fcb27575350d6c76ea1644a2886176630171d16e494e992e1e18e",
          "sha256": "273a4564463a8833fe3d4aa8d7a8321c77a6008da5ba7f29f7ebad259311aaee",
          "sha1": "fa173182f1414badc084d40f21f153193e63ae0b",
          "md5": "11c4d3bcfd86bb3a9fd3698f2cd5b12b"
        }
      ]
    }
  ]
}
