{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "vudukgf34fdc3murg37da3g47e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.40.jar",
          "url": "generator-0.0.40.jar",
          "size": 94663,
          "sha512": "6e2ce72a2b2abcf490348900fdee9d34491274634d1ffe0efa156b30e503969c0640ee479515d7c2f1818587ee674986c2965e7d85f8bb846989cd0876986acb",
          "sha256": "92c193a6783d3f79dc192f8536a59112e71b79011f08fc3a596231704fb6fed7",
          "sha1": "599540fbc01ebac129767dd9d663b7e2ce15e867",
          "md5": "4b94db354551589c750dce34068902c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.40"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.40.jar",
          "url": "generator-0.0.40.jar",
          "size": 94663,
          "sha512": "6e2ce72a2b2abcf490348900fdee9d34491274634d1ffe0efa156b30e503969c0640ee479515d7c2f1818587ee674986c2965e7d85f8bb846989cd0876986acb",
          "sha256": "92c193a6783d3f79dc192f8536a59112e71b79011f08fc3a596231704fb6fed7",
          "sha1": "599540fbc01ebac129767dd9d663b7e2ce15e867",
          "md5": "4b94db354551589c750dce34068902c1"
        }
      ]
    }
  ]
}
