{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.17/viewmodel-0.0.17.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "43amt7eqbfabtkb5q6646kb3hm"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.17"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.17-debug.aar",
          "size": 51755,
          "sha512": "9c453cccb3107b63a127fddfba6b8b1ebc196b1f26d41b3f2357882b88102353d6b0f1a424470a6b4834024865fa12d4c52140a24a4fbacc0fd5125cfb9e69a9",
          "sha256": "1df884e154bdc24090f87b1182d03fbcc05faf2c6051c78e4c173cdf533dbd5e",
          "sha1": "047c6c9d433c9948f3ebc3dfd33d1fc31eb0a139",
          "md5": "1a094d72dc1547c54a2fd14b176c7ef5"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.17"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.17-debug.aar",
          "size": 51755,
          "sha512": "9c453cccb3107b63a127fddfba6b8b1ebc196b1f26d41b3f2357882b88102353d6b0f1a424470a6b4834024865fa12d4c52140a24a4fbacc0fd5125cfb9e69a9",
          "sha256": "1df884e154bdc24090f87b1182d03fbcc05faf2c6051c78e4c173cdf533dbd5e",
          "sha1": "047c6c9d433c9948f3ebc3dfd33d1fc31eb0a139",
          "md5": "1a094d72dc1547c54a2fd14b176c7ef5"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.17"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.17.aar",
          "size": 50134,
          "sha512": "56170bfede3b8120fe0b4c937b1b65a8b429eabf1cb45cf8bc86a8b553129acb7ea7c33f6863a9d72c420b0c9829f2724a7422bf043d01229356f450d5410f80",
          "sha256": "7ac97e55f29c9aaf883080489ae1ca5414b39b6b38f2bbb7daa30f1ec3a8b392",
          "sha1": "3468a80f0e7c658ca50231be624602615b368a14",
          "md5": "dec3cf0771ee7567a8e7f6714c7bda06"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.17"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.17"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.17.aar",
          "size": 50134,
          "sha512": "56170bfede3b8120fe0b4c937b1b65a8b429eabf1cb45cf8bc86a8b553129acb7ea7c33f6863a9d72c420b0c9829f2724a7422bf043d01229356f450d5410f80",
          "sha256": "7ac97e55f29c9aaf883080489ae1ca5414b39b6b38f2bbb7daa30f1ec3a8b392",
          "sha1": "3468a80f0e7c658ca50231be624602615b368a14",
          "md5": "dec3cf0771ee7567a8e7f6714c7bda06"
        }
      ]
    }
  ]
}
