{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.31/androidTests-0.0.31.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "4g4dsdf7yvgxndmmqjq6s6i2gm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.31.jar",
          "url": "androidTests-metadata-0.0.31.jar",
          "size": 261,
          "sha512": "798fa2590aa201749933576853f696d0b3472e4ee460de0d02867646d7b249101c8f47ebe7c1cf6be0b077af56a6e61f341ed4c849ba8291004ad6d308f475b5",
          "sha256": "67cde362e1b1e2874ca8d01122a5c4b966f05270f28fe3784adcb405fb6706c2",
          "sha1": "f233c7765515dc37ae0718321c3b47eea71ee25a",
          "md5": "d2e8424bcadd7b34e4d7d839bbb957d9"
        }
      ]
    }
  ]
}
