{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.44/view-0.0.44.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "i7olmwxatfdhths5wu7quwrrny"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.44-debug.aar",
          "size": 153574,
          "sha512": "20c30083e9a76d18fa12690a4062085820b188c9b8dd2e015dc796168e50311799e152c24dfc017f23742e865536eb8f60b2706b86c2b16241b8a55271e6aeb5",
          "sha256": "44c79894d2fc1777e5c4b7109ef6334df03d03cfb268a5449fe462ce03037b99",
          "sha1": "5544f552709943bc7aca77836ad0c06d6333829f",
          "md5": "cd8991681a0189680c63ce4d9941d92e"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-debug.aar",
          "url": "view-android-0.0.44-debug.aar",
          "size": 153574,
          "sha512": "20c30083e9a76d18fa12690a4062085820b188c9b8dd2e015dc796168e50311799e152c24dfc017f23742e865536eb8f60b2706b86c2b16241b8a55271e6aeb5",
          "sha256": "44c79894d2fc1777e5c4b7109ef6334df03d03cfb268a5449fe462ce03037b99",
          "sha1": "5544f552709943bc7aca77836ad0c06d6333829f",
          "md5": "cd8991681a0189680c63ce4d9941d92e"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.44.aar",
          "size": 148813,
          "sha512": "14795c5e3f10d2c764c54425e09fa9059d1c8cffde60b096e6f6186a738b377d33f83cd0ac971adbec111feb195661b957f5136f890ae2de88dc36071f6b4087",
          "sha256": "2e24ff0d620986fde3413ec85454dbd0a78f72dc0f6e0736e14bb82210bbc0b7",
          "sha1": "224a10ccb0b61fb61f1c40e60391458e1a5f8570",
          "md5": "d196706ceed50d76655354e9262c5718"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.44"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "view-release.aar",
          "url": "view-android-0.0.44.aar",
          "size": 148813,
          "sha512": "14795c5e3f10d2c764c54425e09fa9059d1c8cffde60b096e6f6186a738b377d33f83cd0ac971adbec111feb195661b957f5136f890ae2de88dc36071f6b4087",
          "sha256": "2e24ff0d620986fde3413ec85454dbd0a78f72dc0f6e0736e14bb82210bbc0b7",
          "sha1": "224a10ccb0b61fb61f1c40e60391458e1a5f8570",
          "md5": "d196706ceed50d76655354e9262c5718"
        }
      ]
    }
  ]
}
