{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "model",
    "version": "1.0.0-iosalpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-1.0.0-iosalpha62.jar",
          "url": "model-1.0.0-iosalpha62.jar",
          "size": 16034,
          "sha512": "1cfe58ff4d63e6f9ba3fd6c20ef4175e32eb15356a68c23e94cdb5489dcb92c0bd1a2f06ea3eb3e3cbf58b279ae6d57bfaa526047bdb3b4ed3bc204c6b5c8b38",
          "sha256": "5b0e65b991c7398d10dbe206d67ca745ee7d2a9a99c1455aefaac2f23844f719",
          "sha1": "fda54113298bf414abc78829a0e7c25f535d8683",
          "md5": "9a31aa575defe3ad5c5cf48cf183e51c"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-iosalpha62/model-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "model-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-iosalpha62/model-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "model-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-iosalpha62/model-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "model-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../model-android/1.0.0-iosalpha62/model-android-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "model-android",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosarm64/1.0.0-iosalpha62/model-iosarm64-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "model-iosarm64",
        "version": "1.0.0-iosalpha62"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../model-iosx64/1.0.0-iosalpha62/model-iosx64-1.0.0-iosalpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "model-iosx64",
        "version": "1.0.0-iosalpha62"
      }
    }
  ]
}
