{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.14.jar",
          "url": "generator-0.0.14.jar",
          "size": 92130,
          "sha512": "0a278e328caa7751d47ec9c50f451b462da0d794f4477c92d9921066e13cf502c499534fcfd5f5c86f7bb716ede3ec08e76177e0fd53a65a412834fab8fd7599",
          "sha256": "2e351ab8f31563d4025f0472d03df82a793cd5f03ea19e89e4f213a6f6c9ad69",
          "sha1": "bcb494e5117f04240bdb9e31c4f6e028b6ce202a",
          "md5": "44e4a1282f8e3bbf726d9e25ccd14711"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.14.jar",
          "url": "generator-0.0.14.jar",
          "size": 92130,
          "sha512": "0a278e328caa7751d47ec9c50f451b462da0d794f4477c92d9921066e13cf502c499534fcfd5f5c86f7bb716ede3ec08e76177e0fd53a65a412834fab8fd7599",
          "sha256": "2e351ab8f31563d4025f0472d03df82a793cd5f03ea19e89e4f213a6f6c9ad69",
          "sha1": "bcb494e5117f04240bdb9e31c4f6e028b6ce202a",
          "md5": "44e4a1282f8e3bbf726d9e25ccd14711"
        }
      ]
    }
  ]
}
