{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h2qswlibvbgzncub57ri5633aa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.50.jar",
          "url": "core-0.0.50.jar",
          "size": 5344,
          "sha512": "66e9bf32f5034571ba18b7ede1937f5a775c3ed5c868dcc0c9456a0d894e9e15e864cb3ce33a196cf1af30d2f71b236354d882569ed71ed7ec8c204dee197c94",
          "sha256": "01ff117def009b1c42e29db27e50081291315e928677768f9f9ff568666246b1",
          "sha1": "c1d4f1b15b0208d7eaabf0ad005e20b96afeffab",
          "md5": "f9ea82dd3881894423d1d39bc19791f3"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.50/core-android-0.0.50.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.50"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.50/core-android-0.0.50.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.50"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.50/core-android-0.0.50.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.50"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.50/core-android-0.0.50.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.50"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.0.50/core-jvm-0.0.50.module",
        "group": "tech.skot",
        "module": "core-jvm",
        "version": "0.0.50"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.0.50/core-jvm-0.0.50.module",
        "group": "tech.skot",
        "module": "core-jvm",
        "version": "0.0.50"
      }
    }
  ]
}
