{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewlegacy",
    "version": "1.0.0-alpha24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-metadata-1.0.0-alpha24.jar",
          "url": "viewlegacy-1.0.0-alpha24.jar",
          "size": 261,
          "sha512": "15b4732fb86cb8a16a1a80fb2730f655f84519dc6f6911d99e0a3807519c2a591977977aa761eb98129961a829d33cbcb427c276c3652c03eee3f60547570f5a",
          "sha256": "ce1682c8f71c0a180c96cfb4fdfaec255b604e87d6ac71f7346dab04e2db5878",
          "sha1": "21d7177f819f10bd08eaece5ec95cc64abee6bda",
          "md5": "f918409b8294df580008a4bf11838f29"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha24/viewlegacy-android-1.0.0-alpha24.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha24"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha24/viewlegacy-android-1.0.0-alpha24.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha24"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha24/viewlegacy-android-1.0.0-alpha24.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha24"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewlegacy-android/1.0.0-alpha24/viewlegacy-android-1.0.0-alpha24.module",
        "group": "tech.skot",
        "module": "viewlegacy-android",
        "version": "1.0.0-alpha24"
      }
    }
  ]
}
