{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.11/core-0.0.11.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.11.jar",
          "url": "core-metadata-0.0.11.jar",
          "size": 4883,
          "sha512": "c0d24e4c76f286ae5820b8bf8465386ff8184876f0b527d76df63d66d50161122e20e248b584f3dc48ac05ff0e770bac2d7c0903f4805bbfe9ae7707e2f1053f",
          "sha256": "17cc60e5d1222f05508ae7f4c5e213ed9278270469e843a7a6cf0582f98e0670",
          "sha1": "187174fe3d43f40b0359e3ba934dcc770bad5adc",
          "md5": "a33e4332e754c5e037bd000934f7f138"
        }
      ]
    }
  ]
}
