{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.11/androidTests-0.0.11.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.11.jar",
          "url": "androidTests-metadata-0.0.11.jar",
          "size": 261,
          "sha512": "28cb12e081790114a46d62731119c220bf9616a29e9e1429daaa0986de36553d392738390dfb8366f83efe43b846030dd0a4346c8b79d37f0fa107c2a4c380b8",
          "sha256": "aded6fd8aafca0e9d8ab96db7b9c8c07c08c67b81bc77d24b56c49101fd118dc",
          "sha1": "efc4024ac3820a1882e22096b97c22ad44d86f22",
          "md5": "c8752fe458f5214020c1898ac86b5fe3"
        }
      ]
    }
  ]
}
