{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "ukmbwru3nfajnc7s472ijwocfa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha4.jar",
          "url": "generator-1.0.0-alpha4.jar",
          "size": 116076,
          "sha512": "d017a95a7ca36ad3e705751245fa356ce9a88bfa2b8c915b6174e518e496b637571e6f62f270efaeb6fa63e17e9e8a26889221bfff16638dd475127226fcaf18",
          "sha256": "2d2492aec2bb2d0a9aa3b0dad1860b9d2e9c9391605b51c608a72dcbbbfa0847",
          "sha1": "f64943c54bf3b7804683a0b0e3acbb19b3987834",
          "md5": "44a8da3938b4bb1eecc39dfb7a1cbdb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha4.jar",
          "url": "generator-1.0.0-alpha4.jar",
          "size": 116076,
          "sha512": "d017a95a7ca36ad3e705751245fa356ce9a88bfa2b8c915b6174e518e496b637571e6f62f270efaeb6fa63e17e9e8a26889221bfff16638dd475127226fcaf18",
          "sha256": "2d2492aec2bb2d0a9aa3b0dad1860b9d2e9c9391605b51c608a72dcbbbfa0847",
          "sha1": "f64943c54bf3b7804683a0b0e3acbb19b3987834",
          "md5": "44a8da3938b4bb1eecc39dfb7a1cbdb2"
        }
      ]
    }
  ]
}
