{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "biqopuycmjhqla5bue3ohogk3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha14.jar",
          "url": "generator-1.0.0-alpha14.jar",
          "size": 192914,
          "sha512": "f9599671560dc917618db51bcadaac72d82885caf75b204ce8f2f9865513529754081029d3c925bc9a509d8b9ae58f3dc2f793b5e796c39f561ea80287573528",
          "sha256": "83f326b609f865c299d63428d3c3955d13e63fd7be8248c252ea2edc31c6d404",
          "sha1": "5a18ad20155fa6d8dbc072228ee3a7a7785e83e0",
          "md5": "a29cd97db6e4f2e67e57ae0ec5041e83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha14.jar",
          "url": "generator-1.0.0-alpha14.jar",
          "size": 192914,
          "sha512": "f9599671560dc917618db51bcadaac72d82885caf75b204ce8f2f9865513529754081029d3c925bc9a509d8b9ae58f3dc2f793b5e796c39f561ea80287573528",
          "sha256": "83f326b609f865c299d63428d3c3955d13e63fd7be8248c252ea2edc31c6d404",
          "sha1": "5a18ad20155fa6d8dbc072228ee3a7a7785e83e0",
          "md5": "a29cd97db6e4f2e67e57ae0ec5041e83"
        }
      ]
    }
  ]
}
