{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "view-metadata",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "vj4sbvbumvfv5bapwhxdwgkp54"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.45"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.45.jar",
          "url": "view-metadata-0.0.45.jar",
          "size": 6294,
          "sha512": "01c9960279a1fb27ba5264715c45a62480595440ffcdcbb9ba43c6597eed30a3d77ebc182a9fd227937635eded29af29341255899ae111bc65f266566df8571b",
          "sha256": "0ac61715f9df27d4e7be2bd07b9b21b4385bf6f0eccc6dffed381b70de4118b2",
          "sha1": "e9d05dff9521a8a46d88c74cb80d7999380f08ac",
          "md5": "ec8dd9b8e389de86abc4ae24e8c8200a"
        }
      ]
    }
  ]
}
