{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.10/contract-0.0.10.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.10.jar",
          "url": "contract-jvm-0.0.10.jar",
          "size": 15805,
          "sha512": "b4b79177b556ed5de31eff7f134691bb5293aedd6c9beeae1f90a6dd99fcba2d017cfa49d6159f28c30b5cb80fc18769c6b8ce3417e74feea1e0dca55f8c408f",
          "sha256": "694301b6221a36d3467b467a988ad9cbdf422b1494a1df58c58b2877e031685e",
          "sha1": "34eca4715302b1c0e15b42a8d5cca22531b529af",
          "md5": "dbce4ffe9868eb98fd0870eb8c0a1fd9"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.10.jar",
          "url": "contract-jvm-0.0.10.jar",
          "size": 15805,
          "sha512": "b4b79177b556ed5de31eff7f134691bb5293aedd6c9beeae1f90a6dd99fcba2d017cfa49d6159f28c30b5cb80fc18769c6b8ce3417e74feea1e0dca55f8c408f",
          "sha256": "694301b6221a36d3467b467a988ad9cbdf422b1494a1df58c58b2877e031685e",
          "sha1": "34eca4715302b1c0e15b42a8d5cca22531b529af",
          "md5": "dbce4ffe9868eb98fd0870eb8c0a1fd9"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.10/contract-metadata-0.0.10.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.10"
      }
    }
  ]
}
