{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-alpha14/viewmodel-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "biqopuycmjhqla5bue3ohogk3m"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha14-debug.aar",
          "size": 84214,
          "sha512": "b8ef9a84ef347a2647f81ea28ec7bc41274cbb338cd768647ea575d3b54638fb998224f467a5f3b7fb09d11ec2286af6f6a92ece123328a769c17a97fcdc4e62",
          "sha256": "31c1395a36954beee1a2ec025ba004ccd27e69c94c45eaf8777b2b4318bad9b5",
          "sha1": "c3feb840d24771455d03d24b93b53303b3c12f8a",
          "md5": "a1999f6ca71a68b903cc06cefa8bd547"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-1.0.0-alpha14-debug.aar",
          "size": 84214,
          "sha512": "b8ef9a84ef347a2647f81ea28ec7bc41274cbb338cd768647ea575d3b54638fb998224f467a5f3b7fb09d11ec2286af6f6a92ece123328a769c17a97fcdc4e62",
          "sha256": "31c1395a36954beee1a2ec025ba004ccd27e69c94c45eaf8777b2b4318bad9b5",
          "sha1": "c3feb840d24771455d03d24b93b53303b3c12f8a",
          "md5": "a1999f6ca71a68b903cc06cefa8bd547"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha14.aar",
          "size": 80319,
          "sha512": "01e1faec4e8657fce34cc0c066633b942d8a9b47805168e08f2317b30e46a6236c99a5e8afffaf9a6ddcf4f4c75b6c6f78b70e4e36bca48806a191f273ffd821",
          "sha256": "87c5ac8f3719a27f99d21ff498e1398ed0d8402adeb040f87d69d13f1b8e6db0",
          "sha1": "85d6bf18c7a8639a32b4260f1aa53f3a679a1159",
          "md5": "559b01390abc7e2656d00d7e81181ab6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-1.0.0-alpha14.aar",
          "size": 80319,
          "sha512": "01e1faec4e8657fce34cc0c066633b942d8a9b47805168e08f2317b30e46a6236c99a5e8afffaf9a6ddcf4f4c75b6c6f78b70e4e36bca48806a191f273ffd821",
          "sha256": "87c5ac8f3719a27f99d21ff498e1398ed0d8402adeb040f87d69d13f1b8e6db0",
          "sha1": "85d6bf18c7a8639a32b4260f1aa53f3a679a1159",
          "md5": "559b01390abc7e2656d00d7e81181ab6"
        }
      ]
    }
  ]
}
