{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.49"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.49.jar",
          "url": "viewmodel-0.0.49.jar",
          "size": 7429,
          "sha512": "22722742e65140fa1334ab4b1ee653e6bcaa8dc5c130d993b6014e16118bdedf95bbe2a29e8896a597f9a4bcf15895070c770cd2a5f0da167d2c0587194d52f9",
          "sha256": "0315b9d92866f786510944cdfd05e0eee462b6432f44eb679b834887b0ec013b",
          "sha1": "edcc8d4d0021bd0c6515f521a0412127599b3290",
          "md5": "994b236759b802e3cf3d9728ec9aaecb"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.49/viewmodel-android-0.0.49.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.49"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.49/viewmodel-android-0.0.49.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.49"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.49/viewmodel-android-0.0.49.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.49"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.49/viewmodel-android-0.0.49.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.49"
      }
    }
  ]
}
