{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h2ihyef5ird4dpcb6ziswov2gq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha9"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha9.jar",
          "url": "viewmodel-1.0.0-alpha9.jar",
          "size": 8275,
          "sha512": "65dd577c66897838bf5fe045728b698897e96ca35fd4f63024c62f53bafa01f6e7e2e9d799eb7576065891986764e90c07bd54c056fb88daefeafe2d77d4e588",
          "sha256": "4a99f3bb8a38841b23172fd6fbe53742988b1a6c854a0aae9eb762af119510ab",
          "sha1": "2181ae002d59ffd2cc3aaedc6fb7878dcdba7413",
          "md5": "26666e92befe579a9b93cede4e810c1b"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha9/viewmodel-android-1.0.0-alpha9.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha9"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha9/viewmodel-android-1.0.0-alpha9.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha9"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha9/viewmodel-android-1.0.0-alpha9.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha9"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha9/viewmodel-android-1.0.0-alpha9.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha9"
      }
    }
  ]
}
