{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha9/modelcontract-1.0.0-alpha9.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h2ihyef5ird4dpcb6ziswov2gq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha9.jar",
          "url": "modelcontract-jvm-1.0.0-alpha9.jar",
          "size": 33338,
          "sha512": "6627618462e775a96ffe4668d34b8fd97c0a20427f6052862d58b1fbda75a1e59f8bfaf7a299eedbeba41688224dae2349614dc5bca0ae9bc0fb287c1650c3d1",
          "sha256": "b62b0c90e418b1f4bad5bc70d5085efa2e05411e6564b868bc8d8a0a0858c55c",
          "sha1": "b19318ddc93f190f9cb8f9ca7c7401b295b7885b",
          "md5": "40a17ee7818d67efd95fb0e6071a952e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha9.jar",
          "url": "modelcontract-jvm-1.0.0-alpha9.jar",
          "size": 33338,
          "sha512": "6627618462e775a96ffe4668d34b8fd97c0a20427f6052862d58b1fbda75a1e59f8bfaf7a299eedbeba41688224dae2349614dc5bca0ae9bc0fb287c1650c3d1",
          "sha256": "b62b0c90e418b1f4bad5bc70d5085efa2e05411e6564b868bc8d8a0a0858c55c",
          "sha1": "b19318ddc93f190f9cb8f9ca7c7401b295b7885b",
          "md5": "40a17ee7818d67efd95fb0e6071a952e"
        }
      ]
    }
  ]
}
