{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha6.jar",
          "url": "viewmodel-1.0.0-alpha6.jar",
          "size": 8249,
          "sha512": "6f1a1fd63ee5fffba03dd5dcd7b9d87833f3458dfe010f4b85370482b402c1c26b9e05e8f62bbe95de7dc523df096bfc836eeff33a1077dcc4b37d5bb1d3dc71",
          "sha256": "7527f24caa483f2c21e278d5cec4b62167fb2a2587709730cf3b9a27bdbe70cb",
          "sha1": "0134d1d110c402a48a4c8517ac1176f81fc9784b",
          "md5": "0768c72e9af92ba3272e37a0aa04a687"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha6/viewmodel-android-1.0.0-alpha6.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha6"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha6/viewmodel-android-1.0.0-alpha6.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha6"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha6/viewmodel-android-1.0.0-alpha6.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha6"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha6/viewmodel-android-1.0.0-alpha6.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha6"
      }
    }
  ]
}
