{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.28/viewmodel-0.0.28.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.28.jar",
          "url": "viewmodel-metadata-0.0.28.jar",
          "size": 7006,
          "sha512": "99ce4b6abf32198c753681b34940765fd1de4048efd42803f4185a949b35cc888fda39e0945304170a30736d158ef1cf3c66a027c6e0d244b8f895d7b9e7f8e7",
          "sha256": "74d30664cf66667ce3d4faa7b721ea026de00d71ed1e4376e5bdb8b0eaf124d7",
          "sha1": "86296c86b4d694e68bd33345cb498d7f07af3dc5",
          "md5": "e462a55564c176a2af4d6b13d010dd20"
        }
      ]
    }
  ]
}
