{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha15.jar",
          "url": "viewmodel-1.0.0-alpha15.jar",
          "size": 15176,
          "sha512": "8205408eeca89bcd4219cec91e4dc0c0f60d1a489c1bef6b94d861d5a5519e2ce81149d2ee8c4af9b630631e72a77c9cc065d939bc10579cfa7f925094ac8404",
          "sha256": "6d0eb6cc9556566e0fb9eee2e822f7fd4abad59013507b4216c1e45ca74058ab",
          "sha1": "8cba8ecd65699663d0a35855d3a86208dfe6cd95",
          "md5": "8b32458eba48865a60b09d9589fc9922"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha15/viewmodel-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha15/viewmodel-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha15/viewmodel-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha15"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha15/viewmodel-android-1.0.0-alpha15.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha15"
      }
    }
  ]
}
