{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.35/contract-0.0.35.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "giu2xg36zfb4vbk5yuetpxzity"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.35.jar",
          "url": "contract-jvm-0.0.35.jar",
          "size": 18620,
          "sha512": "544b82d4909faeb36cfffbc681c3ab42f3570a3ed265985a2ac426535c3500ba6ad78b39cd098b0f0dded9f1e254479bb9a495beee35f98abf81d1b32ebaac6d",
          "sha256": "f25e5147614d6d82311fbe8d6eeb0d9de821c88f701624de96e2b21583cf813a",
          "sha1": "bff56b1238041c1aaba72aa909da70d882834c94",
          "md5": "5246f993ceb656d2d3673f9490ba9215"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.35.jar",
          "url": "contract-jvm-0.0.35.jar",
          "size": 18620,
          "sha512": "544b82d4909faeb36cfffbc681c3ab42f3570a3ed265985a2ac426535c3500ba6ad78b39cd098b0f0dded9f1e254479bb9a495beee35f98abf81d1b32ebaac6d",
          "sha256": "f25e5147614d6d82311fbe8d6eeb0d9de821c88f701624de96e2b21583cf813a",
          "sha1": "bff56b1238041c1aaba72aa909da70d882834c94",
          "md5": "5246f993ceb656d2d3673f9490ba9215"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.35/contract-metadata-0.0.35.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.35"
      }
    }
  ]
}
