{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.43/androidTests-0.0.43.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "umuh4wxdqfdghocu4tjfq6qmxe"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.43.jar",
          "url": "androidTests-metadata-0.0.43.jar",
          "size": 261,
          "sha512": "d1489c78b28b69ec6ef7eed6c2061b7ad65c98632f0197a3d87cd30ef07701113f2334b4e9330511c0effcb855684667a035735816a7666262a4e049f902fd26",
          "sha256": "d01be9bfdf52c407380688660ec015c67675defbfae631bc378ea29a8bf942f9",
          "sha1": "7e97e8dbe17c2e075ce7f9545221cf678c80eca1",
          "md5": "c62771425653ddb279e179ce386a0bc1"
        }
      ]
    }
  ]
}
