{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.24/androidTests-0.0.24.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "outl7uxctrgmfpv6znqczvsuxy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.24.jar",
          "url": "androidTests-metadata-0.0.24.jar",
          "size": 261,
          "sha512": "a917a56030e05e5cdeec97bb45fb5f88d3b85868fa8a38a8fb1aad5ad1a0259e52fd2bb28e954db918467945f057b6ba1dfd31dabd287fba4c6034548e0bab87",
          "sha256": "7aa2ad07f28fdd8709b6c68b749dff94bf94190d0ae1e855770034de4ca3df69",
          "sha1": "a2fddab7d53396e158812f009017ac5840c06ed5",
          "md5": "91dd8a0eca50adfa74927d6e41d9f3e4"
        }
      ]
    }
  ]
}
