{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewlegacy-metadata",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-metadata-1.0.0-alpha6.jar",
          "url": "viewlegacy-metadata-1.0.0-alpha6.jar",
          "size": 261,
          "sha512": "82cff03487f66ba8588c1469621d3ec2e4086381389ec4f9d90d577332c7ce7fbc6f8ca6b3cfb9e279e7de7bda6db7a4a8c25a54abb08f93f7a3b54bb6ada707",
          "sha256": "72d046b0bc3b676f2fc45c41963faf7ed1267946f675c43d4aa81b4b919d9803",
          "sha1": "0c8efbed301c7f8edbe7cd6beae0becd85589fdc",
          "md5": "faed2639f7e00f47323ef23f2e544986"
        }
      ]
    }
  ]
}
