{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha8/modelcontract-1.0.0-alpha8.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5q5bv5aktfh2fdqq25rjsv33bm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha8.jar",
          "url": "modelcontract-jvm-1.0.0-alpha8.jar",
          "size": 33338,
          "sha512": "084a3ff74ceeedd3da29393cef61c8090cfff0f8d24a6a466aa294fc11c8ae345f428871dfd60edcf2a054f7be000c190bc34ac9113c7ead651fea7983823937",
          "sha256": "711d1aae9344d7a1e968c11e761d6634c3eeb86e0d1fe26ba1bef909d62a6075",
          "sha1": "ab18d765a2f852275ca595ec569d820ae37ac3c7",
          "md5": "c3a9de93ac695179a2edaa5a44554f33"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha8.jar",
          "url": "modelcontract-jvm-1.0.0-alpha8.jar",
          "size": 33338,
          "sha512": "084a3ff74ceeedd3da29393cef61c8090cfff0f8d24a6a466aa294fc11c8ae345f428871dfd60edcf2a054f7be000c190bc34ac9113c7ead651fea7983823937",
          "sha256": "711d1aae9344d7a1e968c11e761d6634c3eeb86e0d1fe26ba1bef909d62a6075",
          "sha1": "ab18d765a2f852275ca595ec569d820ae37ac3c7",
          "md5": "c3a9de93ac695179a2edaa5a44554f33"
        }
      ]
    }
  ]
}
