{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha5.jar",
          "url": "androidTests-1.0.0-alpha5.jar",
          "size": 261,
          "sha512": "18f77f538985267d52d9fa02902e3d52ec96d3f0887a95ac92305ed83dac461a816b78ff3556c6095312752fd0b791a23d8d1aad3440608cf8c85a10861539c1",
          "sha256": "9381e1627504e149140133f589a8b05fe27ca3beca5847b0fa34cf6d4f41e24a",
          "sha1": "1938a2a61ff6f4b61a495164950c719edeb6b4c9",
          "md5": "5b493739326034f0517177f908d1ffea"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha5/androidTests-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha5/androidTests-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha5/androidTests-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha5"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha5/androidTests-android-1.0.0-alpha5.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha5"
      }
    }
  ]
}
