{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha19.jar",
          "url": "viewmodel-1.0.0-alpha19.jar",
          "size": 15278,
          "sha512": "629f32c052ab7e23a3a493c5558114600e30c0945cda229d3c855ec384b4d84423bffc620ae40e9db9530c9bbd53279b4935eede948cfa7e654188ad282aed27",
          "sha256": "2dcb39f75a6f245db63b5ea1ff51c1631cf5b16e28cc7046e9d1381606ab5167",
          "sha1": "91f7e5135c825957029ffe7c84b5c82002710f3c",
          "md5": "a145f1b024a5eb2ce7c16f70203bb18c"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha19/viewmodel-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha19/viewmodel-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha19/viewmodel-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha19/viewmodel-android-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha19"
      }
    }
  ]
}
