{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qkfbndnh6jfalpfv2y37cujupm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.4.jar",
          "url": "generator-0.0.4.jar",
          "size": 90385,
          "sha512": "f9ac272e6197b713c949a28f4ba1994bfe7d3a249b38fe7b7d4adb1c0a634d2e59d51888e33688e07989c6f118e1d1a7d2c046e59192686f438223b1566e8ddf",
          "sha256": "32cb34f17c018e4ad5a8df3c08e0f9d9b08918b575ebb0b61d570993f567bdc3",
          "sha1": "a71292e8bf80b078d946988e7d3a0ed3be12c7d6",
          "md5": "99c5d128fe1cbe2f0920f07ea2a98ba9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.4.jar",
          "url": "generator-0.0.4.jar",
          "size": 90385,
          "sha512": "f9ac272e6197b713c949a28f4ba1994bfe7d3a249b38fe7b7d4adb1c0a634d2e59d51888e33688e07989c6f118e1d1a7d2c046e59192686f438223b1566e8ddf",
          "sha256": "32cb34f17c018e4ad5a8df3c08e0f9d9b08918b575ebb0b61d570993f567bdc3",
          "sha1": "a71292e8bf80b078d946988e7d3a0ed3be12c7d6",
          "md5": "99c5d128fe1cbe2f0920f07ea2a98ba9"
        }
      ]
    }
  ]
}
