{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha62.jar",
          "url": "viewmodel-1.0.0-alpha62.jar",
          "size": 16492,
          "sha512": "82ef5824e01fd007e68d21c34e97a10a64acb4a8816d80fa1542fd86514c9d469b9f0469665362165a2c9b455147a4655a2337cb36f44aaa09e2e43f71ec2545",
          "sha256": "1ed3f0c891d15ef6b8470a0a5a457beaa146d6a8655d0d379cdb654368210bc6",
          "sha1": "280b2aa321d38b4eda0e4c9019fa0fc0f2fd9507",
          "md5": "2141e91668966ae4ec68f4973334ef9b"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha62/viewmodel-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha62/viewmodel-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha62/viewmodel-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha62/viewmodel-android-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewmodel-iosarm64/1.0.0-alpha62/viewmodel-iosarm64-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-iosarm64",
        "version": "1.0.0-alpha62"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewmodel-iosx64/1.0.0-alpha62/viewmodel-iosx64-1.0.0-alpha62.module",
        "group": "com.github.skot-framework.skot",
        "module": "viewmodel-iosx64",
        "version": "1.0.0-alpha62"
      }
    }
  ]
}
