{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha13/viewcontract-1.0.0-alpha13.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "6gknnfvmsnde5hajwyvhjn2oni"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha13.klib",
          "size": 37006,
          "sha512": "d18609d499d4f9826ebfa4e2b0ff415739745a5834aa95324f60b4afeebc1ac25eb7b0c00b721b9271e5f910981993505e909c72d4c91180efc5b111ec06fa54",
          "sha256": "cce18e29f0a36a21d8b5e28ceee2abb35caa04337b52dd69f2546497a44d78bd",
          "sha1": "37708d0a56f20575c854379ceab264e4229dec8a",
          "md5": "a3b94c000368de538eb784de41463988"
        }
      ]
    }
  ]
}
