{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.9/model-0.0.9.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "xtqqandxyva3tauucku2734sky"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.9.jar",
          "url": "model-metadata-0.0.9.jar",
          "size": 11242,
          "sha512": "71be981b569f132e80aeb65d085f0e95f5d0f5e3d63956a59356964545b550f8515d633138acdefd5cd86ae9b8de333ab512100fe0feee5289776d15a754f11c",
          "sha256": "19876bb7828bd2044fe74eccbe252b89aab3eae71a2c1d8b98e8aeeee775248",
          "sha1": "12b102ec39cc0bd6268f5f58ec18e5c42b8acacb",
          "md5": "1956b110d6a37fd6de40d4f608628823"
        }
      ]
    }
  ]
}
