{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.36/contract-0.0.36.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yghnb2gewvenvmp42l64g7zv3y"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.36.jar",
          "url": "contract-metadata-0.0.36.jar",
          "size": 8039,
          "sha512": "43435dfd7a4f2056e7fa7778161d3c3bce6c736577884972a0fd7dbb0298fb9015511ddc4c898e29e6eb02fcada234b7a50589e98a71342b80bbe551b71fd181",
          "sha256": "dc7699f7e04da9d6a4f017e1764d64f7ecd211cca87642e59f6d87412d468899",
          "sha1": "8fd864fa43063b3a691533abc057940ba6fdc26b",
          "md5": "fac5498ad865d97b0ce6bc095e4fb560"
        }
      ]
    }
  ]
}
