{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.20/core-0.0.20.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "2r2ojxqr5ffvpf4fmosdnmnn7i"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.20.jar",
          "url": "core-metadata-0.0.20.jar",
          "size": 5327,
          "sha512": "f5faf952f63aeecbc0f5439f68dcd9b665f8b7b6cfaca364e507a1374f034f41d2f1e3f4a0310072c1e4e9ba4dec3361a9f8636a31f438c9b27d1efd90c05f5a",
          "sha256": "ea0bc81d0e8209d5923fb3c1f21f3faca4391adc0d051f96f1e4ce1a4737ff3c",
          "sha1": "b5298a7a4bda5e282af5952f251763594460f6fb",
          "md5": "3e93d6c94704c30c7ca86938c5af04e6"
        }
      ]
    }
  ]
}
