{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "h2qswlibvbgzncub57ri5633aa"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.50"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.50.jar",
          "url": "viewmodel-0.0.50.jar",
          "size": 7431,
          "sha512": "f3e6a0024b186e7d810a056885f0900c9971cd05ef30a6ec8bcae8ed75bc380d4d3f7c1b08aba96ed9241d2b255fb0b63188f9f367c8bbbf003c8c756e6829b0",
          "sha256": "7312b068b5748b3ba129a56c647ffb311b99eab825a4815b22865454d50ebc3d",
          "sha1": "16602b816847156ec28f23fb6448a834ed5908e4",
          "md5": "693f96f6028fd05ed016568345497385"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.50/viewmodel-android-0.0.50.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.50"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.50/viewmodel-android-0.0.50.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.50"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.50/viewmodel-android-0.0.50.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.50"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/0.0.50/viewmodel-android-0.0.50.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "0.0.50"
      }
    }
  ]
}
