{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.2/model-0.0.2.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "r76z3av2pjgf5gaz7k45ehatda"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.2-debug.aar",
          "size": 77191,
          "sha512": "81a1a4f9718956fbd19de306259f7435e6f4ad4ac0aba0a9240e0752be72d4c49997c01b6bd433ebb515fe61896bc488bbd0c10997eea2f56d1df2ef72357676",
          "sha256": "bc5686f6b6962865a21eb974c774e8c32e263258584923f570a384ecb7659798",
          "sha1": "87ed7174159a8c6ee5e6d07279cd17a7fa84a5bd",
          "md5": "2d7c2211ff98e072126f694d7c000ef"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.2-debug.aar",
          "size": 77191,
          "sha512": "81a1a4f9718956fbd19de306259f7435e6f4ad4ac0aba0a9240e0752be72d4c49997c01b6bd433ebb515fe61896bc488bbd0c10997eea2f56d1df2ef72357676",
          "sha256": "bc5686f6b6962865a21eb974c774e8c32e263258584923f570a384ecb7659798",
          "sha1": "87ed7174159a8c6ee5e6d07279cd17a7fa84a5bd",
          "md5": "2d7c2211ff98e072126f694d7c000ef"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.2.aar",
          "size": 74098,
          "sha512": "f55fc21d1ff254060f944fb160b0030b1e769ff3126c3e364340f6fd5cb1cd08b19be5295faec22e1992430b0431e894ed97fcdbfd07f29d5dd9c319949fd966",
          "sha256": "d64c6c66105ba5d39689329db42d7ca77969b3813ad388de0c00ed190ec2f44f",
          "sha1": "40d1ae9eeeec69c863cd9c4c690c4bb664268113",
          "md5": "74571db6cc4e71f34f3c33525b75ff6d"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.2.aar",
          "size": 74098,
          "sha512": "f55fc21d1ff254060f944fb160b0030b1e769ff3126c3e364340f6fd5cb1cd08b19be5295faec22e1992430b0431e894ed97fcdbfd07f29d5dd9c319949fd966",
          "sha256": "d64c6c66105ba5d39689329db42d7ca77969b3813ad388de0c00ed190ec2f44f",
          "sha1": "40d1ae9eeeec69c863cd9c4c690c4bb664268113",
          "md5": "74571db6cc4e71f34f3c33525b75ff6d"
        }
      ]
    }
  ]
}
