{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha26/viewcontract-1.0.0-alpha26.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosx64-1.0.0-alpha26.klib",
          "size": 40134,
          "sha512": "6e10f8fe0cc2939e09d0b33a3c757b8fa70e7cc0d83ae215f296600a099c35c35f57aa6bc58de6616de6e26c684bfa7f07f36d491caa04dc185fdf8aa6e0b45a",
          "sha256": "1ed4a375d8c38e1b1d19cc81605c00708fbe20fd9344218dbd298ccb6bd1ec04",
          "sha1": "67a28e9577230a8d337a9a1210129ae5b49a118b",
          "md5": "a0a6f5b9b4a79e76ba0e6507f4847c10"
        }
      ]
    }
  ]
}
