{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.25/model-0.0.25.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "zsuzp37jg5gzjmf4dpn3ufsume"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.25"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.25.jar",
          "url": "model-metadata-0.0.25.jar",
          "size": 13118,
          "sha512": "61fe0692261bc69165a41127e782cf2ecd2cdddd53a7f3e3ecdcbc35f7c369b9db84dd8666181a28011476b6477c95400b4795ad01238a7e05b45f93fd957d32",
          "sha256": "8a0e82cd7d1117a4a1e7d5afde45e3e1203d810aec439dd716bc532ee9bea8b1",
          "sha1": "24e3b32bea2dafdb8f2f1b92c5e301288bf449e7",
          "md5": "3b6da3f61781b7755121e581738caeb7"
        }
      ]
    }
  ]
}
