{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "vrvei6o5trhotpxc7jm4yf4dri"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-1.0.0-alpha10.jar",
          "url": "viewmodel-1.0.0-alpha10.jar",
          "size": 8275,
          "sha512": "d03b2aeda3f0690a0590fdd0ef62054bd32303ff0564581ecc921b5d287a6597d34e0cc8fe587ef402cbfb6de25f983ecf6e81418575a8eb274465dfec944fc6",
          "sha256": "c138dc38a720174a10c2f37e8071a8a179874ac4ed3007a7890e48487b17c0ba",
          "sha1": "d909cf07ee829e5a87c06d4e60ebe050417eabe6",
          "md5": "d15986a2629f84404d7af60aa65c609a"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha10/viewmodel-android-1.0.0-alpha10.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha10"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha10/viewmodel-android-1.0.0-alpha10.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha10"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha10/viewmodel-android-1.0.0-alpha10.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha10"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../viewmodel-android/1.0.0-alpha10/viewmodel-android-1.0.0-alpha10.module",
        "group": "tech.skot",
        "module": "viewmodel-android",
        "version": "1.0.0-alpha10"
      }
    }
  ]
}
