{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha62/viewcontract-1.0.0-alpha62.module",
    "group": "com.github.skot-framework.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha62.jar",
          "url": "viewcontract-jvm-1.0.0-alpha62.jar",
          "size": 65892,
          "sha512": "26c8d2d31aa6b9d566f0dbfd8ee24b9a3ea0a1e5cbde78df8769614989854c589df74d672b4a4cf97c2d1cac4e673f226b3ef66a64f77e2509a96b3c6bee2ef3",
          "sha256": "f2ae2e0d359581b5e98dc2cc7b8fcdeaa8c2faee28bc5207b962b6adc4460cab",
          "sha1": "dc01a174347989ebb99f79b4df9e3f407b38d72e",
          "md5": "42e407a1901f912b53822b9f2dced1db"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha62.jar",
          "url": "viewcontract-jvm-1.0.0-alpha62.jar",
          "size": 65892,
          "sha512": "26c8d2d31aa6b9d566f0dbfd8ee24b9a3ea0a1e5cbde78df8769614989854c589df74d672b4a4cf97c2d1cac4e673f226b3ef66a64f77e2509a96b3c6bee2ef3",
          "sha256": "f2ae2e0d359581b5e98dc2cc7b8fcdeaa8c2faee28bc5207b962b6adc4460cab",
          "sha1": "dc01a174347989ebb99f79b4df9e3f407b38d72e",
          "md5": "42e407a1901f912b53822b9f2dced1db"
        }
      ]
    }
  ]
}
