{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "mvvg2c2cg5ck5ely2nphe5geda"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.22.jar",
          "url": "generator-0.0.22.jar",
          "size": 92131,
          "sha512": "23ba1f83cca688ef2bc629f10d3e954b8801e1099558b24a432652e2e4bad5cbc6d88737f1e9ce8fb3cbbacc6ae921deb5e09b4d481fc8e2a768ac43afa88a0c",
          "sha256": "e04575676ffd6bd60f8a0a67dfeb35068b213c74046740ee2b162b1e50f31673",
          "sha1": "3047100c2881c42498fb59627e630e50478d7766",
          "md5": "727e89a9547c35abd3edc3b368d23b8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.22.jar",
          "url": "generator-0.0.22.jar",
          "size": 92131,
          "sha512": "23ba1f83cca688ef2bc629f10d3e954b8801e1099558b24a432652e2e4bad5cbc6d88737f1e9ce8fb3cbbacc6ae921deb5e09b4d481fc8e2a768ac43afa88a0c",
          "sha256": "e04575676ffd6bd60f8a0a67dfeb35068b213c74046740ee2b162b1e50f31673",
          "sha1": "3047100c2881c42498fb59627e630e50478d7766",
          "md5": "727e89a9547c35abd3edc3b368d23b8d"
        }
      ]
    }
  ]
}
