{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.38/core-0.0.38.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h3wjxn3zcban5fnecihtr5lrqi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.38.jar",
          "url": "core-metadata-0.0.38.jar",
          "size": 5329,
          "sha512": "1692c2cdb026cb3286ba8a1092b1f07c73ed938101d77117f7f0392433710687f9b07aa2f16c6acfb5a1ea4f412e29ffcef53ab9ae508481d4caf6f513adb7d2",
          "sha256": "e5d2fc2568dc0d85836ccaf6deb5d1998d15816f1a0986e38d5994f3f0874a70",
          "sha1": "29944205acf52e6b462e97fec483399362a7bb62",
          "md5": "0ac7e8624d9e715f3719e9c528455231"
        }
      ]
    }
  ]
}
