{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r2iat6l4kjcyrfebvz5rmffmqu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha5.jar",
          "url": "plugin-1.0.0-alpha5.jar",
          "size": 163592,
          "sha512": "b53fc64ae0bcb4eb1957863304396731fe927f7f80ab714d01f6d8dcca79361b5bf084e7a1aa8e1b1da0bd9c14815a73b9a7d18e2aa501f6d555e0d0d53980ea",
          "sha256": "e8b54be5ce0872d266cdeb56ea78a593f939884500b4a971180e5535adcd5859",
          "sha1": "5aed00cd1dad985cc21ae50e3127a40f07d230bc",
          "md5": "c1e1f3eafbd59355a33e35dba8db6012"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.google.gms",
          "module": "google-services",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-appdistribution-gradle",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics-gradle",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "perf-plugin",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha5.jar",
          "url": "plugin-1.0.0-alpha5.jar",
          "size": 163592,
          "sha512": "b53fc64ae0bcb4eb1957863304396731fe927f7f80ab714d01f6d8dcca79361b5bf084e7a1aa8e1b1da0bd9c14815a73b9a7d18e2aa501f6d555e0d0d53980ea",
          "sha256": "e8b54be5ce0872d266cdeb56ea78a593f939884500b4a971180e5535adcd5859",
          "sha1": "5aed00cd1dad985cc21ae50e3127a40f07d230bc",
          "md5": "c1e1f3eafbd59355a33e35dba8db6012"
        }
      ]
    }
  ]
}
