{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha15/viewcontract-1.0.0-alpha15.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha15.klib",
          "size": 39104,
          "sha512": "0c7b648b88ffc2362e676cff87a8807e3edda252c809630159b46d5b31cbf52d1a3d97a3bf169f6eb7e8dab519f9e64ed71208093815b123800a3aaf5164f63f",
          "sha256": "4a2347a809fa9e24d2db8159ea23fa3a63e559c4391673f2c552e302ad8e1ab4",
          "sha1": "08f3899baf0af3084f1b587d8d0f2666fb327fb0",
          "md5": "997edbb8d1017433c48a38d3d337adfd"
        }
      ]
    }
  ]
}
