{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.22/androidTests-0.0.22.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6uskpwxm4nhbnbsedqteegk7ke"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.22.jar",
          "url": "androidTests-metadata-0.0.22.jar",
          "size": 261,
          "sha512": "598f2b5478833a7f575dd919de91fa8bfdde7df32981bd220a630e12130e34feff1a0a3351428a5f10941613228c5638a8783563ede7ae2fbf627254663b3df4",
          "sha256": "8f799eddf15fd0515b12b219d79988e4510af7af4237eba2c549bd38d45dde7c",
          "sha1": "52b139f2a5f98872ecb78eba934d74a75636525b",
          "md5": "0bc5e127d562aeb18b1b783447d85c32"
        }
      ]
    }
  ]
}
