{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha7/modelcontract-1.0.0-alpha7.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "vuponvlkt5blhpe5a4symex76e"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha7.klib",
          "size": 15249,
          "sha512": "1203446c547ab732e17df1ca11faa781dc5b40c9a69a105695a4185579f1266ea293cd8bc33b786cf841997549d3a594132ea2031e578f987638ccf7dc1cf85e",
          "sha256": "feefc8a0e1f5752ab0fd07f854605c4afa726cb9c5580d97bf456f45f74ad841",
          "sha1": "d2e08a5fbcd14c2f565b31c9aadcfd3943d274a8",
          "md5": "204c7937cc01f75b8bb6ff7dac44f492"
        }
      ]
    }
  ]
}
