{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha22.jar",
          "url": "androidTests-1.0.0-alpha22.jar",
          "size": 261,
          "sha512": "7634fbbe69d50b5b2930c1a0457184b054e70988b39d38a3625bed143c742c4b58f63efca28aaa3303b45331c9b6da703e80147f46d24afd9ad01fd02a2c1c9f",
          "sha256": "d8874ae707eba9470585616b42d987f3aecbc0f48ebc8541aba6eb9b7f58678c",
          "sha1": "9c72ae07fb5a03b4d58897161001af007de08d70",
          "md5": "fe3acda12829659634a423ff0d003cd1"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha22/androidTests-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha22/androidTests-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha22/androidTests-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha22"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha22/androidTests-android-1.0.0-alpha22.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha22"
      }
    }
  ]
}
