{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.52",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "jc6y725iebc23nmj56aixso43i"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.52"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.52.jar",
          "url": "view-0.0.52.jar",
          "size": 6296,
          "sha512": "558b9d63a794a5af23688a804a4cecc1a60d9f4835848fad9df2e24416799793a35a766efbb28a93d19928b192478ed36f01a8d8abb00d3b506c17cc42be35ec",
          "sha256": "faacfc921cf71de53315c12833c4c63cb6359bbff63ea42139c96d2f31b453d0",
          "sha1": "d58362805d449a84c7d824af5a1502fc810763aa",
          "md5": "0f3418e3f94644eb39aace427ea1c794"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.52/view-android-0.0.52.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.52"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.52/view-android-0.0.52.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.52"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.52/view-android-0.0.52.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.52"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../view-android/0.0.52/view-android-0.0.52.module",
        "group": "tech.skot",
        "module": "view-android",
        "version": "0.0.52"
      }
    }
  ]
}
