{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha19.jar",
          "url": "plugin-1.0.0-alpha19.jar",
          "size": 207989,
          "sha512": "d02e61b53ea0be903b28e7e89692ce874003308286ce4c415371b463f974984c297f3830829a638baa2b7d1edf739a0e809e62cc942bc116c63de5cfcef48aa9",
          "sha256": "c27b6675f868adf682a09eda85cf7e87caccf69c460bb1b2b45a2e84c75705db",
          "sha1": "3bf8624eeed82dabb25e97f641acf4c52565f627",
          "md5": "326c81c17306a7f554da913f72782969"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha19.jar",
          "url": "plugin-1.0.0-alpha19.jar",
          "size": 207989,
          "sha512": "d02e61b53ea0be903b28e7e89692ce874003308286ce4c415371b463f974984c297f3830829a638baa2b7d1edf739a0e809e62cc942bc116c63de5cfcef48aa9",
          "sha256": "c27b6675f868adf682a09eda85cf7e87caccf69c460bb1b2b45a2e84c75705db",
          "sha1": "3bf8624eeed82dabb25e97f641acf4c52565f627",
          "md5": "326c81c17306a7f554da913f72782969"
        }
      ]
    }
  ]
}
