{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.21/core-0.0.21.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yshs27cbmzfrdgxafso6bc577q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.21.jar",
          "url": "core-metadata-0.0.21.jar",
          "size": 5327,
          "sha512": "0d9c6f53bc8fc3a5b2c4489e41a6120f864ba8e206211b44a1cb2f3c0561bb4ec76c4c73a0a48d74e1d50aa731fa1b3dc27171b9177ddf62d4bdb043043cfd8d",
          "sha256": "7dcfea654a768615e776c79a1b4aef67002ecf8f5d26249fbe07928ebe6ef54e",
          "sha1": "9c054bb17220f5f571211d6f2cca145d23db4b41",
          "md5": "9743a8a031526c12f08596f75e5c73e6"
        }
      ]
    }
  ]
}
