{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha19.jar",
          "url": "generator-1.0.0-alpha19.jar",
          "size": 193712,
          "sha512": "63ea34e304f0639c347f6491452a32597704fd41215c0ba39d9035710353e479afeb7bf9da7444b4bd15f3f253781912611996614c8ba94d7bf8f8bb46ce2751",
          "sha256": "0280060bf1d969ca6e2ac00352848900b332870251a8276d72eb4a70f32f5364",
          "sha1": "0fd657a60e61b66b718e85baf67966f3948c35aa",
          "md5": "2564d47d4913e7029609a55008a3ec42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha19.jar",
          "url": "generator-1.0.0-alpha19.jar",
          "size": 193712,
          "sha512": "63ea34e304f0639c347f6491452a32597704fd41215c0ba39d9035710353e479afeb7bf9da7444b4bd15f3f253781912611996614c8ba94d7bf8f8bb46ce2751",
          "sha256": "0280060bf1d969ca6e2ac00352848900b332870251a8276d72eb4a70f32f5364",
          "sha1": "0fd657a60e61b66b718e85baf67966f3948c35aa",
          "md5": "2564d47d4913e7029609a55008a3ec42"
        }
      ]
    }
  ]
}
