{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract-jvm/0.0.47/contract-jvm-0.0.47.module",
    "group": "tech.skot",
    "module": "contract-jvm",
    "version": "0.0.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "iyferfojs5awbn5uv47amw3ysy"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.47.jar",
          "url": "contract-metadata-0.0.47.jar",
          "size": 8535,
          "sha512": "e4c09342a80e7ea7a33e7f7aee21d189cebceb487c1127d2da00683c1a1c0a277f105dbd5117bb05bc8f7e7f41eb164806338e500a89aa33514126b7a1bcc56c",
          "sha256": "5d0bc1fde3ea46ea2ac08cfd12708a2ddfcbf32ff47c22cab07218b3956e15cc",
          "sha1": "890b18e6f55d6e7b73b491980d81bbb06a98e8d0",
          "md5": "0dbb4892226c8d6546efa57c92239f13"
        }
      ]
    }
  ]
}
