{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha22/viewcontract-1.0.0-alpha22.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha22.jar",
          "url": "viewcontract-jvm-1.0.0-alpha22.jar",
          "size": 55144,
          "sha512": "d56e48435cc6225eca182ea070fa7b4357f42136a41c35c790058bf4f6d7e45f412542f6ed14f0a066402d7e28f29dd8e59a27e3bbca541c9f5126cdd3ed1cfe",
          "sha256": "91b993d369268b233b204da6a206a169d4c500ab2001e5f41d6075e8e3464bbf",
          "sha1": "2f8aff0d9f5a06545322259cd40ecadc9be410d0",
          "md5": "ab26f8c85c247819d1f0ca6b74d5f6f2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha22.jar",
          "url": "viewcontract-jvm-1.0.0-alpha22.jar",
          "size": 55144,
          "sha512": "d56e48435cc6225eca182ea070fa7b4357f42136a41c35c790058bf4f6d7e45f412542f6ed14f0a066402d7e28f29dd8e59a27e3bbca541c9f5126cdd3ed1cfe",
          "sha256": "91b993d369268b233b204da6a206a169d4c500ab2001e5f41d6075e8e3464bbf",
          "sha1": "2f8aff0d9f5a06545322259cd40ecadc9be410d0",
          "md5": "ab26f8c85c247819d1f0ca6b74d5f6f2"
        }
      ]
    }
  ]
}
