{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.51",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "rcsqc6iufne5ve6vpfzg2hyyae"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.51.jar",
          "url": "core-0.0.51.jar",
          "size": 5344,
          "sha512": "fc68e01b4fe8a8460f722dd63acb2d676e6f9bbfe39371cc8a18ea6d6a90bc1382abceb7af3e73be53b51d6720274fcd535e4cf805fda8ac9f13dd3f2d0d80d0",
          "sha256": "856448a718c748534c343b7494824ba50499d130c38574d74a37712be29b8d21",
          "sha1": "809223d96988c51be65067d0e44fdd7d99d175c5",
          "md5": "779aac5f48dcc7ecb546dd3848dbea28"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.51/core-android-0.0.51.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.51/core-android-0.0.51.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.51/core-android-0.0.51.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../core-android/0.0.51/core-android-0.0.51.module",
        "group": "tech.skot",
        "module": "core-android",
        "version": "0.0.51"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.0.51/core-jvm-0.0.51.module",
        "group": "tech.skot",
        "module": "core-jvm",
        "version": "0.0.51"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../core-jvm/0.0.51/core-jvm-0.0.51.module",
        "group": "tech.skot",
        "module": "core-jvm",
        "version": "0.0.51"
      }
    }
  ]
}
