{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/0.0.15/core-0.0.15.module",
    "group": "tech.skot",
    "module": "core",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gqpemdskoneufiyethujbxdcv4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata-0.0.15.jar",
          "url": "core-metadata-0.0.15.jar",
          "size": 5327,
          "sha512": "a686e9fd3ae926a675bf2d25c20a86e94039d0d5b358e400001ec9c2d6b36f3346c0d5b8e1e1f40c810c56e6d5e3ddfae869b303d3f132ca5e178b21dd1e21de",
          "sha256": "f783792db812338cf1815e5a00acec0b04aa5273f533d0bd8d43c35b1a93edde",
          "sha1": "2abb16385c851caadb61b79375497652d6e20d31",
          "md5": "0968adc94de0c9e1870b5e073356c910"
        }
      ]
    }
  ]
}
