{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "kwtsmjyvlzbw3aguhyqjzuuf5m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.13.jar",
          "url": "generator-0.0.13.jar",
          "size": 92130,
          "sha512": "ff06850fd681ee8751e5926918d77eb5fca089c9dd0413fc8a9fadef5d1817090ac15d5ea4e59649ff896492f0ee1d37a3e9b6fb1040f6f0e834d6d5f578ff3e",
          "sha256": "3b6fdab7bf3b17261993f60be5e8f1c3709ec24c3e3eafcc08fa95523c615c1a",
          "sha1": "1787a0f6f520172198e292f9509aec114e21b99d",
          "md5": "b98fff9f0ece4c29a262a4ad3f3cfe9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.13.jar",
          "url": "generator-0.0.13.jar",
          "size": 92130,
          "sha512": "ff06850fd681ee8751e5926918d77eb5fca089c9dd0413fc8a9fadef5d1817090ac15d5ea4e59649ff896492f0ee1d37a3e9b6fb1040f6f0e834d6d5f578ff3e",
          "sha256": "3b6fdab7bf3b17261993f60be5e8f1c3709ec24c3e3eafcc08fa95523c615c1a",
          "sha1": "1787a0f6f520172198e292f9509aec114e21b99d",
          "md5": "b98fff9f0ece4c29a262a4ad3f3cfe9b"
        }
      ]
    }
  ]
}
