{
  "formatVersion": "1.1",
  "component": {
    "url": "../../view/0.0.28/view-0.0.28.module",
    "group": "tech.skot",
    "module": "view",
    "version": "0.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "ikofuueoirgi5mitgyqwyl75xa"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.28"
          }
        }
      ],
      "files": [
        {
          "name": "view-metadata-0.0.28.jar",
          "url": "view-metadata-0.0.28.jar",
          "size": 6291,
          "sha512": "6757b7c72886045621faf61f004b45809e830b3d8738446610f98a2d7aa4af60a0d6e2b68c044c27c685b1571d37af4a24e894be0fa4870d51d9fc5e63198a9f",
          "sha256": "ca51083471fc7eb785dbee4a6cd18fc06f6634aef93f13bf910aa286d89b472d",
          "sha1": "a4d5e28edd7e74dc3902dddd3405ad936c7f38e7",
          "md5": "70e74a87869e34e10faf84efb5bab1e4"
        }
      ]
    }
  ]
}
