{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.14/model-0.0.14.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.14-debug.aar",
          "size": 94019,
          "sha512": "62b8a7b271c63da1f077bb76ea4b3880ad209e43d373ab25e291e33e712dec4dd623eca7f10d668b7ccf8ee8a3ddd91cb0791001eacd8d0af063e691d91557ea",
          "sha256": "1e56118930ec8ff4eaeba73d887b7b54fa2a5f47ca7392e797b10eb37ee76cc7",
          "sha1": "800bf931b53f6b5b289b9b8e00b64c172d630def",
          "md5": "3582f4b901f799c40543dfbdfeef0909"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.14-debug.aar",
          "size": 94019,
          "sha512": "62b8a7b271c63da1f077bb76ea4b3880ad209e43d373ab25e291e33e712dec4dd623eca7f10d668b7ccf8ee8a3ddd91cb0791001eacd8d0af063e691d91557ea",
          "sha256": "1e56118930ec8ff4eaeba73d887b7b54fa2a5f47ca7392e797b10eb37ee76cc7",
          "sha1": "800bf931b53f6b5b289b9b8e00b64c172d630def",
          "md5": "3582f4b901f799c40543dfbdfeef0909"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.14.aar",
          "size": 90274,
          "sha512": "602978aca5ec10426647a2b9868caaa205c61ab0652d189ecfa5de39a1c1006c07ef736989d2328c3bc26aedd9d27878fd0977940092876e5f9b02742573719a",
          "sha256": "3f170588816a1b572cb32b6624382c617277c04c1386957128bd8d6e92cc2361",
          "sha1": "9c6cdf185f84d7dfc39ff81daa9a6e258ea39790",
          "md5": "2d98f62fd9c2690859750636dcd71244"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.14.aar",
          "size": 90274,
          "sha512": "602978aca5ec10426647a2b9868caaa205c61ab0652d189ecfa5de39a1c1006c07ef736989d2328c3bc26aedd9d27878fd0977940092876e5f9b02742573719a",
          "sha256": "3f170588816a1b572cb32b6624382c617277c04c1386957128bd8d6e92cc2361",
          "sha1": "9c6cdf185f84d7dfc39ff81daa9a6e258ea39790",
          "md5": "2d98f62fd9c2690859750636dcd71244"
        }
      ]
    }
  ]
}
