{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.14/model-0.0.14.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3dorn7aqgzbq3owi6pxgrw7ncy"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.14-debug.aar",
          "size": 94057,
          "sha512": "35721f85ef8c86a6e0e14e9e95ac09182c489d4984f30de58f24942aa458c4b7f94d51d9e0b1000d5c673681f002c6c94179f103a50a04815523fc1800b6a322",
          "sha256": "d29e62f52a7d93a4f4b4a5332fbbbd1a920fbd2a91aa057cf4601c4c0fd7dd15",
          "sha1": "725dd3ba68485c3d372164b3e5bc058fa998aca0",
          "md5": "dd72a7881bbe276ff57b61d22abce0b9"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-debug.aar",
          "url": "model-android-0.0.14-debug.aar",
          "size": 94057,
          "sha512": "35721f85ef8c86a6e0e14e9e95ac09182c489d4984f30de58f24942aa458c4b7f94d51d9e0b1000d5c673681f002c6c94179f103a50a04815523fc1800b6a322",
          "sha256": "d29e62f52a7d93a4f4b4a5332fbbbd1a920fbd2a91aa057cf4601c4c0fd7dd15",
          "sha1": "725dd3ba68485c3d372164b3e5bc058fa998aca0",
          "md5": "dd72a7881bbe276ff57b61d22abce0b9"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.14.aar",
          "size": 90319,
          "sha512": "7c75e3b5ea77b8c41004c3eb685b6bef8e8e6bd35dd9ba51279fa405a639efcefe77ed92e68eb86a0a45027470903966382823db0eafa4367eb9b2f917473171",
          "sha256": "56cd0d0e8ca39e515cd31d03d898558f4c0e6a95308462e44120fb4a5ff6b5ff",
          "sha1": "4326ce7f35855450ae33008f92ef4b27bab4f62c",
          "md5": "50410d3ba44bed9dce479f2a9fc3b643"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "runtime",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.sqldelight",
          "module": "android-driver",
          "version": {
            "requires": "1.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "model-release.aar",
          "url": "model-android-0.0.14.aar",
          "size": 90319,
          "sha512": "7c75e3b5ea77b8c41004c3eb685b6bef8e8e6bd35dd9ba51279fa405a639efcefe77ed92e68eb86a0a45027470903966382823db0eafa4367eb9b2f917473171",
          "sha256": "56cd0d0e8ca39e515cd31d03d898558f4c0e6a95308462e44120fb4a5ff6b5ff",
          "sha1": "4326ce7f35855450ae33008f92ef4b27bab4f62c",
          "md5": "50410d3ba44bed9dce479f2a9fc3b643"
        }
      ]
    }
  ]
}
