{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewlegacy/0.0.1_1.0.0-alpha57/viewlegacy-0.0.1_1.0.0-alpha57.module",
    "group": "com.github.skot-framework.sk-tabbar",
    "module": "viewlegacy",
    "version": "0.0.1_1.0.0-alpha57",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-0.0.1_1.0.0-alpha57-debug.aar",
          "size": 71509,
          "sha512": "6a0ed449a5a86a786353d7709444af8063ca546c571f1c351fc5453dc8f5a2ab0513c09b104fb30273c5708f9a16b8552d4ec529253120686afc5d50b57d00d4",
          "sha256": "cc849f565f5d9de902b74a367fa6d08680a90375633923ed708bf97ff01140f8",
          "sha1": "937f71dbd680e79909d4c8322839ef80b2176a28",
          "md5": "450b8c739e03beae63589aad8cd89969"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewlegacy",
          "version": {
            "requires": "1.0.0-alpha57"
          }
        },
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewmodel",
          "version": {
            "requires": "0.0.1_1.0.0-alpha57"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-debug.aar",
          "url": "viewlegacy-android-0.0.1_1.0.0-alpha57-debug.aar",
          "size": 71509,
          "sha512": "6a0ed449a5a86a786353d7709444af8063ca546c571f1c351fc5453dc8f5a2ab0513c09b104fb30273c5708f9a16b8552d4ec529253120686afc5d50b57d00d4",
          "sha256": "cc849f565f5d9de902b74a367fa6d08680a90375633923ed708bf97ff01140f8",
          "sha1": "937f71dbd680e79909d4c8322839ef80b2176a28",
          "md5": "450b8c739e03beae63589aad8cd89969"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-0.0.1_1.0.0-alpha57.aar",
          "size": 69546,
          "sha512": "2cf0eacb8ea86bae2ed6397fb7657a3a643b4ec9e12e787ba6cc6e572c8866479c00e8787153a7d521481d6c309b618499fb007d5cfe1d5d11d00b11f28fa399",
          "sha256": "505a58fc03c9b1da1c97917fa275b68dbde5f684ab7d5b66965c2f2ee05f3aee",
          "sha1": "81766679a33ab43be2e35a90cf8243d3d9dff693",
          "md5": "827767a177fccf102b43041a108bbe9b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewlegacy",
          "version": {
            "requires": "1.0.0-alpha57"
          }
        },
        {
          "group": "com.github.skot-framework.sk-tabbar",
          "module": "viewmodel",
          "version": {
            "requires": "0.0.1_1.0.0-alpha57"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "viewlegacy-release.aar",
          "url": "viewlegacy-android-0.0.1_1.0.0-alpha57.aar",
          "size": 69546,
          "sha512": "2cf0eacb8ea86bae2ed6397fb7657a3a643b4ec9e12e787ba6cc6e572c8866479c00e8787153a7d521481d6c309b618499fb007d5cfe1d5d11d00b11f28fa399",
          "sha256": "505a58fc03c9b1da1c97917fa275b68dbde5f684ab7d5b66965c2f2ee05f3aee",
          "sha1": "81766679a33ab43be2e35a90cf8243d3d9dff693",
          "md5": "827767a177fccf102b43041a108bbe9b"
        }
      ]
    }
  ]
}
