{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.16/contract-0.0.16.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "xduo2x3rkbaepe3emobddesovq"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.16.jar",
          "url": "contract-jvm-0.0.16.jar",
          "size": 15041,
          "sha512": "fd1a1dcabeecac040a3fe4bb6191c39d2b191ce5ba2e12c68d646fafa5ff3d5f56120a781f630d7a27fc391560eb9c8801ace2b36c8afea3dec3ae260689cc22",
          "sha256": "e2512338f347ee75605db423f32df55c0a00d5e903444ef1afdebeedc60f8590",
          "sha1": "ccea4a4137c29d0d8a74193a474671ab45376853",
          "md5": "259ad61cc158a35e2a68c432095aa8eb"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.16.jar",
          "url": "contract-jvm-0.0.16.jar",
          "size": 15041,
          "sha512": "fd1a1dcabeecac040a3fe4bb6191c39d2b191ce5ba2e12c68d646fafa5ff3d5f56120a781f630d7a27fc391560eb9c8801ace2b36c8afea3dec3ae260689cc22",
          "sha256": "e2512338f347ee75605db423f32df55c0a00d5e903444ef1afdebeedc60f8590",
          "sha1": "ccea4a4137c29d0d8a74193a474671ab45376853",
          "md5": "259ad61cc158a35e2a68c432095aa8eb"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.16/contract-metadata-0.0.16.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.16"
      }
    }
  ]
}
