{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.17/contract-0.0.17.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "43amt7eqbfabtkb5q6646kb3hm"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.17.jar",
          "url": "contract-jvm-0.0.17.jar",
          "size": 15079,
          "sha512": "a59773dc538f2cb5af36d3908db59c4485cc9a09d9eb62c8d4696c15ee4c421ef7494b8019c23ed245e1e0ec4cbf11f4d444d32f140bb199ecbe20148feefc8c",
          "sha256": "177f9fdca3194931955dff8eeed9159ea7a97f4737ec6a1b41368ecf364074f9",
          "sha1": "b6bcfdb7a0e9fd409af9954d02af3eae9e625bcb",
          "md5": "5bff547d9fdcdc69f4fc0c49ada3c511"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.17.jar",
          "url": "contract-jvm-0.0.17.jar",
          "size": 15079,
          "sha512": "a59773dc538f2cb5af36d3908db59c4485cc9a09d9eb62c8d4696c15ee4c421ef7494b8019c23ed245e1e0ec4cbf11f4d444d32f140bb199ecbe20148feefc8c",
          "sha256": "177f9fdca3194931955dff8eeed9159ea7a97f4737ec6a1b41368ecf364074f9",
          "sha1": "b6bcfdb7a0e9fd409af9954d02af3eae9e625bcb",
          "md5": "5bff547d9fdcdc69f4fc0c49ada3c511"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.17/contract-metadata-0.0.17.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.17"
      }
    }
  ]
}
