{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.23/androidTests-0.0.23.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h626lwyzk5cqpjrywyt6pslmqm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.23.jar",
          "url": "androidTests-metadata-0.0.23.jar",
          "size": 261,
          "sha512": "d981252afe61da56a31b9a3a2677537f7d813673f5db066966cf5f27146c8a246b4102bf7c010d69d8c632c0b05cbec2fbf467422ab32b508096dcd1542782d5",
          "sha256": "e4d03aab72165d72443a67189983d19ead9b1af7885dbffef52db529d6ff4b9e",
          "sha1": "8e9609acaa0562906627f4862332a26fd5585523",
          "md5": "5accabfb6774320e82bf63193921ab6b"
        }
      ]
    }
  ]
}
