{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.7/contract-0.0.7.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "igasumkhiveslbdlejoqxrssj4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.7.jar",
          "url": "contract-metadata-0.0.7.jar",
          "size": 7621,
          "sha512": "d9671352e35b2383dc80c349d24ddb6da4a72305b89386d308f60f49ce78f8668b998c59b669131dfeee3f678bb82c7dc65854152ec15269b50e96d3f62030cf",
          "sha256": "c46288c8703467c6784f53f3c61fd9128fdf10e9e51175c364f03eebc40de473",
          "sha1": "ebaee2c9bd4593c7a9be3bdb3b904f3ce53e4627",
          "md5": "4364945af2ccac362b2bbb6112672f48"
        }
      ]
    }
  ]
}
