{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha17/modelcontract-1.0.0-alpha17.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosx64-1.0.0-alpha17.klib",
          "size": 25702,
          "sha512": "9cfe4ac74faaa0933c51fcbc018ccc7aa64e115b01612849ab9f9fc597b9a464167d714d7c35e375d0ef28f99145bbc5fd49a03fe49428ed650c401b25b3b0ef",
          "sha256": "ca1b7220e435ca9a761e154df8d2d52830e8ed9f5b51c9e8facc4458c17a9274",
          "sha1": "d803cb423e06b9be98642a03edef50e8b2fe6c7c",
          "md5": "081d9653a41ed6979047500f5f15c00d"
        }
      ]
    }
  ]
}
