{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.19/model-0.0.19.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "julmyh4b25dnnegsjouy3lg5q4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.19"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.19.jar",
          "url": "model-metadata-0.0.19.jar",
          "size": 13100,
          "sha512": "df84185e652c0cfe87baeb67b67c5a3cc3686dea4332434b583831de62ba2614873b92d57c62aa0e25f0f386a6762f3d8834f8519a3911ae5d961a85a52d6303",
          "sha256": "11b77a1688e71169024029045e3efab58adf8b6b6809c28be93ab1e74e1ddca4",
          "sha1": "6c9c9f2082af0d8884d3afbd912d90d9d5e607d4",
          "md5": "b06e257b6222add35882e3c6ac9c84b0"
        }
      ]
    }
  ]
}
