{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.49",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8",
      "buildId": "twuon5pybnharnqywbcatd3y5q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.49.jar",
          "url": "androidTests-0.0.49.jar",
          "size": 261,
          "sha512": "18f7690d0504786239d7c7df2d34d8476b4d3c30bbc7d2a7a1dbb93d97ecfa935db7901764dfbb6464803dcb24b57061f56185acb482612b1995ebc1d7ee0d1c",
          "sha256": "ce5204577151cdb13f318062c1d97eeeeee365fb4e9a2b5e197e575900ef8adf",
          "sha1": "c4973be8c81993e4ddba265548f1997f6499b7a0",
          "md5": "29151cd53d2faddeb34b0940cca8b611"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.49/androidTests-android-0.0.49.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.49"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.49/androidTests-android-0.0.49.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.49"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.49/androidTests-android-0.0.49.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.49"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/0.0.49/androidTests-android-0.0.49.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "0.0.49"
      }
    }
  ]
}
