{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.21/contract-0.0.21.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "yshs27cbmzfrdgxafso6bc577q"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "contract-metadata-0.0.21.jar",
          "url": "contract-metadata-0.0.21.jar",
          "size": 7209,
          "sha512": "1e635fb970006304b98ab62961ad51b5b9f9d51f8850986b32bd4239ed41ab0fcdb018dfcaaa42e85f44dedb5ea36a5d8d825770ae66c04979771c0afe79fef4",
          "sha256": "9d84bfb72e8845c83a00df1820c138ced15f3aadc9acdeea385f99e75a405c00",
          "sha1": "83fb836bed29738a956fd0105ecae93416d71ae6",
          "md5": "807e6ce30871d37e992d85634284e893"
        }
      ]
    }
  ]
}
