{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha26.jar",
          "url": "generator-1.0.0-alpha26.jar",
          "size": 202615,
          "sha512": "c9e7f9475455b8d313a81066173d8766a97c7ee9bfd39c8f06bc937fa61b3e689e2a6a3ca6dae903864880dce235986c43f569fc1cbb6cabfb783b8bafc8eeb0",
          "sha256": "bb36cbf2bf5ad03b0e3778723397780525e743b793e85ad9a00418f8eac977ea",
          "sha1": "1a7ddeac1f33e86785c31e965aee336e0a4febd0",
          "md5": "08f5ed3c9d2e7c980d81abab19aa5484"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha26"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha26.jar",
          "url": "generator-1.0.0-alpha26.jar",
          "size": 202615,
          "sha512": "c9e7f9475455b8d313a81066173d8766a97c7ee9bfd39c8f06bc937fa61b3e689e2a6a3ca6dae903864880dce235986c43f569fc1cbb6cabfb783b8bafc8eeb0",
          "sha256": "bb36cbf2bf5ad03b0e3778723397780525e743b793e85ad9a00418f8eac977ea",
          "sha1": "1a7ddeac1f33e86785c31e965aee336e0a4febd0",
          "md5": "08f5ed3c9d2e7c980d81abab19aa5484"
        }
      ]
    }
  ]
}
