{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha26.jar",
          "url": "generator-1.0.0-alpha26.jar",
          "size": 194056,
          "sha512": "3d4936ebba5c401553bfb93b0627043645584c00da462c27d9bcbbdb5d5dd0ed777b5df9820b9d26ca050bd832b79184894a36bbf90b744dfbef1c243320b1b2",
          "sha256": "a803af5d2808b3353c122f6230353e2d1e3aa2478f142e52ee8d6843716f951b",
          "sha1": "60dc9b69997c80259cac8a112d2b2e0b38c4b8eb",
          "md5": "07b2849a7fbbc59f8c25cc9f79ce45a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha26"
          }
        },
        {
          "group": "tech.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha26"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha26.jar",
          "url": "generator-1.0.0-alpha26.jar",
          "size": 194056,
          "sha512": "3d4936ebba5c401553bfb93b0627043645584c00da462c27d9bcbbdb5d5dd0ed777b5df9820b9d26ca050bd832b79184894a36bbf90b744dfbef1c243320b1b2",
          "sha256": "a803af5d2808b3353c122f6230353e2d1e3aa2478f142e52ee8d6843716f951b",
          "sha1": "60dc9b69997c80259cac8a112d2b2e0b38c4b8eb",
          "md5": "07b2849a7fbbc59f8c25cc9f79ce45a7"
        }
      ]
    }
  ]
}
