{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.5/viewmodel-0.0.5.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "nju6gt2f4nfplmunyax325fmbu"
    }
  },
  "variants": [
    {
      "name": "android-debugApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.5-debug.aar",
          "size": 46677,
          "sha512": "e64708f56d968306e250bcf470e205f64d67790db4503e608fd0972e309f91987a1cccd50f40d392942137b6d1d3fe67fc4b6a942e0a60e502cd9ce826ba48dd",
          "sha256": "fd6b73ed9dacb8cb7a05475fc14e3c183aca9f549c5291ed61f45c45b61ab9ca",
          "sha1": "fd080d5dcdd089865c5e69907af1bfd9f97086cb",
          "md5": "a82729b6c0e1567dffbacfdf03bd80a5"
        }
      ]
    },
    {
      "name": "android-debugRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.VariantAttr": "debug",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-debug.aar",
          "url": "viewmodel-android-0.0.5-debug.aar",
          "size": 46677,
          "sha512": "e64708f56d968306e250bcf470e205f64d67790db4503e608fd0972e309f91987a1cccd50f40d392942137b6d1d3fe67fc4b6a942e0a60e502cd9ce826ba48dd",
          "sha256": "fd6b73ed9dacb8cb7a05475fc14e3c183aca9f549c5291ed61f45c45b61ab9ca",
          "sha1": "fd080d5dcdd089865c5e69907af1bfd9f97086cb",
          "md5": "a82729b6c0e1567dffbacfdf03bd80a5"
        }
      ]
    },
    {
      "name": "android-releaseApiElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.5.aar",
          "size": 45299,
          "sha512": "9ee2b0973d26674631eab9407441b23e8e6b8a83125e3470e8c8d6017e3739470109ed65d866855fc5e40fa03bcc4042162123e92d55d2d9f1e2b992aed75a4b",
          "sha256": "72f1153ba58cf74f30597add532725ad34975c7639fc41366531b524df3b3570",
          "sha1": "2f47975e4de39bdad95b87bdb1558f91b7098dba",
          "md5": "1f30e2b7fa0f9ef04b33d0e64a34671c"
        }
      ]
    },
    {
      "name": "android-releaseRuntimeElements",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.api.attributes.VariantAttr": "release",
        "com.android.build.gradle.internal.dependency.AndroidTypeAttr": "Aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-release.aar",
          "url": "viewmodel-android-0.0.5.aar",
          "size": 45299,
          "sha512": "9ee2b0973d26674631eab9407441b23e8e6b8a83125e3470e8c8d6017e3739470109ed65d866855fc5e40fa03bcc4042162123e92d55d2d9f1e2b992aed75a4b",
          "sha256": "72f1153ba58cf74f30597add532725ad34975c7639fc41366531b524df3b3570",
          "sha1": "2f47975e4de39bdad95b87bdb1558f91b7098dba",
          "md5": "1f30e2b7fa0f9ef04b33d0e64a34671c"
        }
      ]
    }
  ]
}
