{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "1.0.0-alpha6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "zljbyqy3nbb2zhpwyxxxugh5ly"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha6.jar",
          "url": "generator-1.0.0-alpha6.jar",
          "size": 130187,
          "sha512": "b4906767f164031cf98caf87e496411f110fbe9ad4f9bd26b65306e5a1c7f8875d844ca257ceb9da1abaa6a38746056e3cf213ef6f5e27cf61a999c351314941",
          "sha256": "c67e06c88768a1a416617c19bc0b16078608ef6819035038dcbbd136e61caab0",
          "sha1": "d743ca316a504be775db7b5c31e68aecde8544cf",
          "md5": "6e36b42131c65a37e9c4028e5ff25b20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "tech.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha6"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha6.jar",
          "url": "generator-1.0.0-alpha6.jar",
          "size": 130187,
          "sha512": "b4906767f164031cf98caf87e496411f110fbe9ad4f9bd26b65306e5a1c7f8875d844ca257ceb9da1abaa6a38746056e3cf213ef6f5e27cf61a999c351314941",
          "sha256": "c67e06c88768a1a416617c19bc0b16078608ef6819035038dcbbd136e61caab0",
          "sha1": "d743ca316a504be775db7b5c31e68aecde8544cf",
          "md5": "6e36b42131c65a37e9c4028e5ff25b20"
        }
      ]
    }
  ]
}
