{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.15/androidTests-0.0.15.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "gqpemdskoneufiyethujbxdcv4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.15.jar",
          "url": "androidTests-metadata-0.0.15.jar",
          "size": 261,
          "sha512": "e5f5427a5e7d556f7ea7be62c7bc6cf739a59e51ecf2bb6a2d937172f0c54b8f0b33f3795ac775eb4e7ecdf712e0c9ac048ac0388b0fce40f425efb163224b63",
          "sha256": "54879c60367a268bddea57b83f047add3e9eff810427916b67cb2e3fa58cd73e",
          "sha1": "4e67f59507279e8100faa32afbe715afaa1ab91a",
          "md5": "3d8006d704ea6c73d1b8aa0beb876fd5"
        }
      ]
    }
  ]
}
