{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/0.0.11/viewmodel-0.0.11.module",
    "group": "tech.skot",
    "module": "viewmodel",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "54rgzgyyazhrrpcl4ramv75y3e"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.soywiz.korlibs.klock",
          "module": "klock",
          "version": {
            "requires": "1.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel-metadata-0.0.11.jar",
          "url": "viewmodel-metadata-0.0.11.jar",
          "size": 5558,
          "sha512": "bc8557fd9435f4d107360ac398e4e9243b8abb0ee0c65f28aca64edd41d600674ca6c8325e4b78cc48cb1246ed18c3c5d02d8ccf03d60a8ef0ee8f08ed22960d",
          "sha256": "428173ad189ed9dfe7cf97fce5c36162580ab086d130cb84b5726a3e326e3bc7",
          "sha1": "95c3f70227e6dabb766160de7c0af80817e4a853",
          "md5": "d2b95d5b2bca564441bf77a19dc5236b"
        }
      ]
    }
  ]
}
