{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha24/viewcontract-1.0.0-alpha24.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract.klib",
          "url": "viewcontract-iosarm64-1.0.0-alpha24.klib",
          "size": 39439,
          "sha512": "35cf4955a6c6d4053e496679f342a8da247e022f058d47ebc8e809f21387178b76f1f1f737177e64a1b87040625451ad3b9ff119c157eb410f2ce6aca9ce4379",
          "sha256": "59174e91007a9ad09ff652df1058e72a9556c0d1b15c7c02454b3a96190d6721",
          "sha1": "ff3c833cc13edeabd78556f3b03e3a0941170f3c",
          "md5": "648f76edf0a3e9f24aebbb4e884d97aa"
        }
      ]
    }
  ]
}
