{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha11/modelcontract-1.0.0-alpha11.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "hi5k4zmxxffn3jdfvdfn25oce4"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0-RC-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract.klib",
          "url": "modelcontract-iosarm64-1.0.0-alpha11.klib",
          "size": 15039,
          "sha512": "72c45b8c8f7e9e86501194eb1e24bc5aa8bdbf8ad3263843cf82edf10c7908cfb03b4c5a550c225204691fd97bf7433a612ce8e06d606c1c0f627c6371094819",
          "sha256": "634dbac5328672814509e70393f261f039adddca9d1f75229a66fdc0428beda1",
          "sha1": "ed526b9236cbafa2089799f28ccdfac86003950a",
          "md5": "cfd02efc0ce85ffb12866019263ce49b"
        }
      ]
    }
  ]
}
