{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewmodel/1.0.0-iosalpha62/viewmodel-1.0.0-iosalpha62.module",
    "group": "com.github.skot-framework.skot",
    "module": "viewmodel",
    "version": "1.0.0-iosalpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.skot",
          "module": "core",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-iosalpha62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewmodel.klib",
          "url": "viewmodel-iosarm64-1.0.0-iosalpha62.klib",
          "size": 69344,
          "sha512": "28b9b47fa5d3d198d61433514d89429721cf60876c5ffe32859f18857e547c57d04f905a388fda94961c2a8926e7fc01bb8999fb47d94e08e4ea4949debcb87f",
          "sha256": "cbb51c99c11482580f61361008393978f116ca876519a9285a44403b01d88500",
          "sha1": "6c95c0c692b4d84552aaefde62d7db38666054d2",
          "md5": "d5c1a1afdfbff14a178f8724ab936837"
        }
      ]
    }
  ]
}
