{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "plugin",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha20.jar",
          "url": "plugin-1.0.0-alpha20.jar",
          "size": 218598,
          "sha512": "e718b1643c68a3fd927b72b321ded4313474cad7292e3d2d540850129605285581ed50b099c3fc95308edd7840d4252b84873aadf31617e04aae0684854a4864",
          "sha256": "5949817e0ac9a148492b168d16f7233d17765f667014e0a925fffbd11dfd7bcb",
          "sha1": "faa448608cd254512dbdc948e1c8854d974dc863",
          "md5": "1bf80468c3d79b2499562ddc1272315d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-serialization",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0-alpha20.jar",
          "url": "plugin-1.0.0-alpha20.jar",
          "size": 218598,
          "sha512": "e718b1643c68a3fd927b72b321ded4313474cad7292e3d2d540850129605285581ed50b099c3fc95308edd7840d4252b84873aadf31617e04aae0684854a4864",
          "sha256": "5949817e0ac9a148492b168d16f7233d17765f667014e0a925fffbd11dfd7bcb",
          "sha1": "faa448608cd254512dbdc948e1c8854d974dc863",
          "md5": "1bf80468c3d79b2499562ddc1272315d"
        }
      ]
    }
  ]
}
