{
  "formatVersion": "1.1",
  "component": {
    "url": "../../model/0.0.23/model-0.0.23.module",
    "group": "tech.skot",
    "module": "model",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "h626lwyzk5cqpjrywyt6pslmqm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "tech.skot",
          "module": "core",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-runtime-common",
          "version": {
            "requires": "0.20.0"
          }
        }
      ],
      "files": [
        {
          "name": "model-metadata-0.0.23.jar",
          "url": "model-metadata-0.0.23.jar",
          "size": 13118,
          "sha512": "3f51d31cfbba2d091f4ca123e89c79e121be09169f6a4ce641e4dd63aee14a9cc047feebc7ea8ab8fb9dc9800eb6ebace985c05f1ac1e534508810fe8402139b",
          "sha256": "7a126e0c4f2237740b16dc7b7482de9dd05a71fd9114f2d3179823752758051c",
          "sha1": "f7367ca9f591a11bd3af1161ee97c28a4176adca",
          "md5": "eef247a00156c8f356ba83386cfc0b15"
        }
      ]
    }
  ]
}
