{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-alpha14/core-1.0.0-alpha14.module",
    "group": "tech.skot",
    "module": "core",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "r323g3eu6re6rhuxjhc3etletm"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.0",
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "core.klib",
          "url": "core-iosx64-1.0.0-alpha14.klib",
          "size": 22489,
          "sha512": "d7917ec101197541409565bc3ca7b16fc468d2f34fe5436a6c9a2117adf020b5e42492a4453623ec3586364a8c6968d7b43d2c385f6208df5b1303b26108ad09",
          "sha256": "6828f48f5ce12eecb3cd00dd7844b5dc45a6e35ed2398a4416508f92c7643305",
          "sha1": "14410215660e4cfb7e7005cc3099f96fb57d599d",
          "md5": "24abc5f01d459e4001c8479a8140324b"
        }
      ]
    }
  ]
}
