{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha25.jar",
          "url": "androidTests-1.0.0-alpha25.jar",
          "size": 261,
          "sha512": "7900a866f3aaa318db531df552eb192b72d31b6faec504b14f951f70a1d3a3a0092232f1bda4800596579612e0119c93e44a90503be302f07a933c96b58e925b",
          "sha256": "3fef78d8d5d0469911025215538c9ee51d9fc72278696b34d03b56e7c84379f5",
          "sha1": "2bd35c6505150e7176165180afc356a3b793f4df",
          "md5": "ae4a9d42c098c80ff3ce4a9caf9226b7"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha25/androidTests-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha25/androidTests-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha25/androidTests-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha25"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha25/androidTests-android-1.0.0-alpha25.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha25"
      }
    }
  ]
}
