{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-metadata-1.0.0-alpha19.jar",
          "url": "viewcontract-1.0.0-alpha19.jar",
          "size": 17665,
          "sha512": "9a16d3bc15ef43d14b06816500dfb30e10e44d1a89ebd76783985cfc2bbd10b6e8374e3f9dae554808640e71d91f77531db683fb752f8e43e986d07b93e40f8f",
          "sha256": "11f4cedeae3848a27c2bd3686475ff3dde0cc4a86110338f0cd8434b98beb847",
          "sha1": "9c83a50e017b38195e4e174ee77a7039a2c5e4de",
          "md5": "37f36b238cb571d745711b08a482d477"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosarm64/1.0.0-alpha19/viewcontract-iosarm64-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewcontract-iosarm64",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../viewcontract-iosx64/1.0.0-alpha19/viewcontract-iosx64-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewcontract-iosx64",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha19/viewcontract-jvm-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha19"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../viewcontract-jvm/1.0.0-alpha19/viewcontract-jvm-1.0.0-alpha19.module",
        "group": "tech.skot",
        "module": "viewcontract-jvm",
        "version": "1.0.0-alpha19"
      }
    }
  ]
}
