{
  "formatVersion": "1.1",
  "component": {
    "url": "../../modelcontract/1.0.0-alpha25/modelcontract-1.0.0-alpha25.module",
    "group": "tech.skot",
    "module": "modelcontract",
    "version": "1.0.0-alpha25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha25.jar",
          "url": "modelcontract-jvm-1.0.0-alpha25.jar",
          "size": 79211,
          "sha512": "c223f72dd6fdd300c5cb2f13bf221c3d54c3b0abea7ec69ba91f4cef09668ee50c7c1ee2af8a40c0497dacc8dd218d4921a6b2737fa86a5393ed05025a9136d1",
          "sha256": "19252910ae91f8405276526a1bbcd91a8d54456d8a695868f8fcd800e6185969",
          "sha1": "a626f715f4fe00d0addde4f8e8d7a9906e0ef9a1",
          "md5": "9570a1ade677aeecc26ea52ead4f113b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "strictly": "1.5.1",
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "modelcontract-jvm-1.0.0-alpha25.jar",
          "url": "modelcontract-jvm-1.0.0-alpha25.jar",
          "size": 79211,
          "sha512": "c223f72dd6fdd300c5cb2f13bf221c3d54c3b0abea7ec69ba91f4cef09668ee50c7c1ee2af8a40c0497dacc8dd218d4921a6b2737fa86a5393ed05025a9136d1",
          "sha256": "19252910ae91f8405276526a1bbcd91a8d54456d8a695868f8fcd800e6185969",
          "sha1": "a626f715f4fe00d0addde4f8e8d7a9906e0ef9a1",
          "md5": "9570a1ade677aeecc26ea52ead4f113b"
        }
      ]
    }
  ]
}
