{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/1.0.0-iosalpha62/core-1.0.0-iosalpha62.module",
    "group": "com.github.skot-framework.skot",
    "module": "core",
    "version": "1.0.0-iosalpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-1.0.0-iosalpha62-debug.aar",
          "size": 28616,
          "sha512": "4b944afe84debc95cfe5942d561a1c49189c9acf010ab4c9e5ca6b82723f8a461d6f4a49263efa8a071daa5bb139433afcf11ecbd2981e69cf19671557ec233c",
          "sha256": "7beaec3667cdb535c8bc2cf80eee8f5dcc0b6d9fe3415926a72da624b378811a",
          "sha1": "a2e8feefde7990ddb84726494616d8a46957e407",
          "md5": "83c0d9a7ff7e93029c1725fcd7a9b59d"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2-native-mt"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-debug.aar",
          "url": "core-android-1.0.0-iosalpha62-debug.aar",
          "size": 28616,
          "sha512": "4b944afe84debc95cfe5942d561a1c49189c9acf010ab4c9e5ca6b82723f8a461d6f4a49263efa8a071daa5bb139433afcf11ecbd2981e69cf19671557ec233c",
          "sha256": "7beaec3667cdb535c8bc2cf80eee8f5dcc0b6d9fe3415926a72da624b378811a",
          "sha1": "a2e8feefde7990ddb84726494616d8a46957e407",
          "md5": "83c0d9a7ff7e93029c1725fcd7a9b59d"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-1.0.0-iosalpha62.aar",
          "size": 27618,
          "sha512": "289e86d65cdc01f9a0937da99604ee38c365664505360ed1921ff3a641d81886cfcc55497f08fc33501b301bd9303000e1697fa4df32817cdf35260cb4764ff5",
          "sha256": "7af642be8162b4d7478db58958f02b9ce71ddbbd9941560a4896f69e790650dd",
          "sha1": "37b4a409fb8e84e842779a62ef14b315b025bb44",
          "md5": "56e68aac5ef96f08edd78d22c6fcd940"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "4.7.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2-native-mt"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2-native-mt"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.2.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "core-release.aar",
          "url": "core-android-1.0.0-iosalpha62.aar",
          "size": 27618,
          "sha512": "289e86d65cdc01f9a0937da99604ee38c365664505360ed1921ff3a641d81886cfcc55497f08fc33501b301bd9303000e1697fa4df32817cdf35260cb4764ff5",
          "sha256": "7af642be8162b4d7478db58958f02b9ce71ddbbd9941560a4896f69e790650dd",
          "sha1": "37b4a409fb8e84e842779a62ef14b315b025bb44",
          "md5": "56e68aac5ef96f08edd78d22c6fcd940"
        }
      ]
    }
  ]
}
