{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.14/androidTests-0.0.14.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "rze23afjkfa6nkiqth44ynahsm"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.14.jar",
          "url": "androidTests-metadata-0.0.14.jar",
          "size": 261,
          "sha512": "81ba382c7561295aeec744350ef5e4b384c360203acc229d32cb10660dec3f4e2acef2285b30d354b8fb7d8dddd32421d63467e36f286c48b50e55095f142ccb",
          "sha256": "cd28273138d568eaf8c096f1a2832a47d8e9f5a0fdf1c1e2a430d2bbbd69cdad",
          "sha1": "86c62c90c3f99a80082459220cbbfc612a2dec0c",
          "md5": "6a7ffaec1ce8ad5afabbb18d56f60098"
        }
      ]
    }
  ]
}
