{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.14/androidTests-0.0.14.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "3dorn7aqgzbq3owi6pxgrw7ncy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.14.jar",
          "url": "androidTests-metadata-0.0.14.jar",
          "size": 261,
          "sha512": "da08867fdc3aa94cab55b00c239bb4641db34071de05253102a2af94d6c9866f1716be429ef2827ff48b756a8a86a8a5a505e44da71b5ebfa71f8a9b547129a4",
          "sha256": "492a9890a94f0da77742fba991e3b3ecff79b4f4e9aff46f9ad96102ac08817d",
          "sha1": "3460b6ac0930e465071abe0ad891679c7a21a9bd",
          "md5": "bfaef2a2e1481407c6614f5eaed7e018"
        }
      ]
    }
  ]
}
