{
  "formatVersion": "1.1",
  "component": {
    "url": "../../androidTests/0.0.16/androidTests-0.0.16.module",
    "group": "tech.skot",
    "module": "androidTests",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "xduo2x3rkbaepe3emobddesovq"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-common",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-0.0.16.jar",
          "url": "androidTests-metadata-0.0.16.jar",
          "size": 261,
          "sha512": "aa9d8bb41581fab630e5397f4d4d407913aa7da07b9fb12655609eeb09f93b851018eca99694caf0735626a0c7ce2d2d752c2b4cef7403b7c46ed9c4a16607cb",
          "sha256": "2c51ccb23cc2844f34508adcb2387c6646b001ad63f35cd1d3aedc1029f9cf53",
          "sha1": "16c2a51843c6d95cf28a8552eafb29f907517141",
          "md5": "504c7c616250c7f4b836a2b1adc10db2"
        }
      ]
    }
  ]
}
