{
  "formatVersion": "1.1",
  "component": {
    "url": "../../contract/0.0.32/contract-0.0.32.module",
    "group": "tech.skot",
    "module": "contract",
    "version": "0.0.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "6qssia3r7rbwpb5cs5jxxg4cpy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.32.jar",
          "url": "contract-jvm-0.0.32.jar",
          "size": 17939,
          "sha512": "d8656374b0fe41821dcd304db0439755e557fc603bd8f44f0f4b5e309c7494093f37bece13eba9634a0888f83a249da5c4ce6dc2594f308ac6cdece385cbcb73",
          "sha256": "f74bb87cd1a1651ef8123ec510e786598d457398111aa2fc035b40b24e6d4fd2",
          "sha1": "cb9922ae85079c0944836433eb6ade9169e987eb",
          "md5": "a60a4be76c5abcc1a3f5173f3f723910"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "contract-jvm-0.0.32.jar",
          "url": "contract-jvm-0.0.32.jar",
          "size": 17939,
          "sha512": "d8656374b0fe41821dcd304db0439755e557fc603bd8f44f0f4b5e309c7494093f37bece13eba9634a0888f83a249da5c4ce6dc2594f308ac6cdece385cbcb73",
          "sha256": "f74bb87cd1a1651ef8123ec510e786598d457398111aa2fc035b40b24e6d4fd2",
          "sha1": "cb9922ae85079c0944836433eb6ade9169e987eb",
          "md5": "a60a4be76c5abcc1a3f5173f3f723910"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../contract-metadata/0.0.32/contract-metadata-0.0.32.module",
        "group": "tech.skot",
        "module": "contract-metadata",
        "version": "0.0.32"
      }
    }
  ]
}
