{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "tenhzqz6yrgi7kuzn7zyg6tdie"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.10.jar",
          "url": "generator-0.0.10.jar",
          "size": 92123,
          "sha512": "b474d65957445ddb33aa034f4104a968484e748ed6e834a2378d81ffe09c0b65e0ed720eeaf3691c568c59c69214cac7c65ddf02855f26e08bc99ee40504db2b",
          "sha256": "33eebf12414b0068f6578bd2751e1e24cbee8e1f992f25720c385b27a953dae2",
          "sha1": "f20f59760710f877fa84f046987f0f62d82198d3",
          "md5": "033bb215260dba989d98adbf63120079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.10.jar",
          "url": "generator-0.0.10.jar",
          "size": 92123,
          "sha512": "b474d65957445ddb33aa034f4104a968484e748ed6e834a2378d81ffe09c0b65e0ed720eeaf3691c568c59c69214cac7c65ddf02855f26e08bc99ee40504db2b",
          "sha256": "33eebf12414b0068f6578bd2751e1e24cbee8e1f992f25720c385b27a953dae2",
          "sha1": "f20f59760710f877fa84f046987f0f62d82198d3",
          "md5": "033bb215260dba989d98adbf63120079"
        }
      ]
    }
  ]
}
