{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "androidTests",
    "version": "1.0.0-alpha23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "androidTests-metadata-1.0.0-alpha23.jar",
          "url": "androidTests-1.0.0-alpha23.jar",
          "size": 261,
          "sha512": "1d4e128fa6b6f6f3c5349e2389787a761e3b2a29e996568984102fa5c35c1c4ee8738caed5867daa6cc6a81b4e258daa08acc46851cbee47b1cfb74e8fc738e0",
          "sha256": "9396e10fc8f093064a48389600c0ebd571a28798553bbf9350a108f505cbe226",
          "sha1": "bc70360ccb2b9dea0c744194986f5da043ae70ab",
          "md5": "ec960f612f24615b4a6493da03489f5f"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha23/androidTests-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha23"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.gradle.internal.attributes.VariantAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha23/androidTests-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha23"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha23/androidTests-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha23"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "com.android.build.gradle.internal.attributes.VariantAttr": "release",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../androidTests-android/1.0.0-alpha23/androidTests-android-1.0.0-alpha23.module",
        "group": "tech.skot",
        "module": "androidTests-android",
        "version": "1.0.0-alpha23"
      }
    }
  ]
}
