{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.skot",
    "module": "generator",
    "version": "0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.1",
      "buildId": "giu2xg36zfb4vbk5yuetpxzity"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.35.jar",
          "url": "generator-0.0.35.jar",
          "size": 94266,
          "sha512": "dfd8d29bfe4749d1c017ee4c9b0979f9eff02948118a5459ec82f0bcd61854a99aeee24bd62431f140976145c804192f7c8c9f13b8cc9641642b4060f0b65249",
          "sha256": "b4fac5ecf2eeecfde4f7fe423b5107f0dcaeaac2fcb5781f2453999d1f9b3b95",
          "sha1": "c8485dac52579d56075ad14f9b3dd9c6030cb4c1",
          "md5": "2961cd751bca5fdfcbfb50a435776c92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "tech.skot",
          "module": "contract",
          "version": {
            "requires": "0.0.35"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "generator-0.0.35.jar",
          "url": "generator-0.0.35.jar",
          "size": 94266,
          "sha512": "dfd8d29bfe4749d1c017ee4c9b0979f9eff02948118a5459ec82f0bcd61854a99aeee24bd62431f140976145c804192f7c8c9f13b8cc9641642b4060f0b65249",
          "sha256": "b4fac5ecf2eeecfde4f7fe423b5107f0dcaeaac2fcb5781f2453999d1f9b3b95",
          "sha1": "c8485dac52579d56075ad14f9b3dd9c6030cb4c1",
          "md5": "2961cd751bca5fdfcbfb50a435776c92"
        }
      ]
    }
  ]
}
