{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.skot-framework.skot",
    "module": "generator",
    "version": "1.0.0-alpha62",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha62.jar",
          "url": "generator-1.0.0-alpha62.jar",
          "size": 219771,
          "sha512": "39506832ad51fd19831b33bb91314668224452786a194053dfcb4ea4128336286c22abac0d2be43ebe7c62eeb8b4564c0bd67b224e96c12b860ea9e91f879fb0",
          "sha256": "14a1b11ece10f63ae8250e4b58ab413f79fc233d1e91ddd476feec6a95d3895d",
          "sha1": "cdedf3ba044943eca96e96b2240b788dea71ce0f",
          "md5": "394db3b43b46042a093d34f53876d3a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "modelcontract",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.skot-framework.skot",
          "module": "viewcontract",
          "version": {
            "requires": "1.0.0-alpha62"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "generator-1.0.0-alpha62.jar",
          "url": "generator-1.0.0-alpha62.jar",
          "size": 219771,
          "sha512": "39506832ad51fd19831b33bb91314668224452786a194053dfcb4ea4128336286c22abac0d2be43ebe7c62eeb8b4564c0bd67b224e96c12b860ea9e91f879fb0",
          "sha256": "14a1b11ece10f63ae8250e4b58ab413f79fc233d1e91ddd476feec6a95d3895d",
          "sha1": "cdedf3ba044943eca96e96b2240b788dea71ce0f",
          "md5": "394db3b43b46042a093d34f53876d3a1"
        }
      ]
    }
  ]
}
