{
  "formatVersion": "1.1",
  "component": {
    "url": "../../viewcontract/1.0.0-alpha9/viewcontract-1.0.0-alpha9.module",
    "group": "tech.skot",
    "module": "viewcontract",
    "version": "1.0.0-alpha9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h2ihyef5ird4dpcb6ziswov2gq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha9.jar",
          "url": "viewcontract-jvm-1.0.0-alpha9.jar",
          "size": 33799,
          "sha512": "96ed18f892617724f010107a576e9cc4b2e7359d612706728b5f6d81776d311528eea1ac2e2e5097386dce8bab292764805b6ef4e6bdde4e6a397d9e046d1a7d",
          "sha256": "fcee1bfd8a4b960072f6c2747d89f6d76126157d01103d8ead46ce4439942d6e",
          "sha1": "a669482169a2174317d55d48a363607c450d716a",
          "md5": "6f81fef0b445835777e32feb96b4dde6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcontract-jvm-1.0.0-alpha9.jar",
          "url": "viewcontract-jvm-1.0.0-alpha9.jar",
          "size": 33799,
          "sha512": "96ed18f892617724f010107a576e9cc4b2e7359d612706728b5f6d81776d311528eea1ac2e2e5097386dce8bab292764805b6ef4e6bdde4e6a397d9e046d1a7d",
          "sha256": "fcee1bfd8a4b960072f6c2747d89f6d76126157d01103d8ead46ce4439942d6e",
          "sha1": "a669482169a2174317d55d48a363607c450d716a",
          "md5": "6f81fef0b445835777e32feb96b4dde6"
        }
      ]
    }
  ]
}
